### ISSUE TITLE
IT-runner DLC not functioning properly

### ISSUE THREAD

**Issue by PatrickWende** [Courseplay/courseplay#759] opened 2014-12-13 11:56 UTC
Hi all,

I have bought the new IT-runner DLC and I am running into some problems. It looks like Courseplay does not recognize the silo trigger for loading (it just drives through). It does recognize and unloads the combine when using combi-mode. 

With forward unloading it recognizes the unloadingtrigger and it stops to unload. When going backwards however, it looks like Courseplay does not recognize the trailer and it tries to steer the tractor towards the unloadingtrigger instead of the trailer.

 I am using the standard Deutz tractor, the IT-runner trailer and the green container. I am using Courseplay version 0201, log contains no errors. I know it is a brand new DLC, but I hope you guys can find a solution to the problems. If there is anything I can do to help please let me know.

Thanks in advance,

Patrck

**Comment by Satissis** [comment] 2015-01-02 16:55
Try out v0012. It should work in that one now :)

**Comment by PatrickWende** [comment] 2015-01-02 18:48
Hello Satissis,

First of all Happy New Year to you guys:) I hope you all can make 2015 your best year so far.

I tested version 0012 and loading from the farmsilos works, as well as reverse onloading, so no problems there. 

I also tried the Bergmann silagecontainer, but this one refuses to unload at the BGA-silo. It just drives trough the silo without unloading. The "Tip trigger has been reached"- text does not show up. Do you want me to open a new issue for this?

Regards,

Patrick

**Comment by Satissis** [comment] 2015-01-02 19:24
Nop, since it still related to the same DLC :) I'll have a look at it.

**Comment by Satissis** [comment] 2015-01-02 20:08
I just tested it with the Bergmann and I can't reproduce it.
Could you try test it one more time, but this time let it run through the silage bin once and let it return to the field and then it should start returning to the silage bin again and see if it will unload in the silage bin on the second run.
I have seen this before and letting it run it twice, the second run works fine and it will work fine after that.
I haven't found out why it does that yet, but at least it will confirm if that is the case.

**Comment by PatrickWende** [comment] 2015-01-02 22:58
Hi there Satissis,

I did some more tests and it seems there is a problem with the map (Papenburg) that was using. I tried the same route with the origininal Bergmann HTW65 and this did not unload as well. So I tried a different map and here the IT-runner / Bergmann combination works flawless. So problem solved :) 

Thanks for all your help,

Patrick

**Comment by Satissis** [comment] 2015-01-03 02:07
Hmm this sounds a bit like the map is using the "UniversalProcessKit" from issue #889, could you add a link for the mod map and what silage bin you are using.

**Comment by PatrickWende** [comment] 2015-01-03 10:39
I am using Papenburger V 3.9 and FahrsiloExtension V 2.0, both mods are from Modhoster. I don't this map uses the UniversalProcessKit, but I might be wrong.
 I was trying to unload at one of the silos on the main farm, next to the cowshed. I put these mods in a folder on my Google Drive, so you don't have to download the map from Uploaded. You can find them here : https://drive.google.com/folderview?id=0B3cDP5m0CMxJZFhmaVV4UHQzbW8&usp=sharing (how do I insert a link here? :)

**Comment by Satissis** [comment] 2015-01-03 12:54
I'll have a look at it.
About the inserting a link, you just past it in. You can also find the Markdown that is used in here from this site: https://guides.github.com/features/mastering-markdown/

**Comment by Satissis** [comment] 2015-01-03 23:16
So I had a look at the map and yeah there is defiantly something wrong with the silage bins on that map.
First of, not all the bins accepts chaft but grass instead and those for chaft I can get it to unload in it, but it don't unload at the last 1 or 2 sections of the silage bin even that I still have something in the trailer, so it's clearly an map fault.
I don't have that much of map making experience so I'm not totally clear on how this needs to be done.
Can we close this now ?

**Comment by PatrickWende** [comment] 2015-01-03 23:38
As it is a map-problem and the IT-runner is working flawless on other maps please close this issue. Thanks for all the help Satissis.

**Closed** 2015-01-04 00:11 UTC
Labels: enhancement
