### ISSUE TITLE
Fill Level Detection 

### ISSUE THREAD

**Issue by o0Kyoshou0o** [Courseplay/courseplay#2193] opened 2017-07-23 18:35 UTC
Hi everyone
firstly, thank you for this courseplay tool, it 's so useful !!
so,
I have compare two version of courseplay the 5.01..00160.dev and the 5.01.00169.dev
In the second the transborder fill level is sometimes not detected. For the test, i wait the bug appear and i relaunch one or two times the save games  with the .00169, but not any detection of transborder fill level target and so the transborder "wait the combine fill level" (the full fill level run).  therefore, i relaunch the game with .00160  and this time the transborder fill level is detected and the transborder go to unload into the truck trailer.

the "transborder trailer" used is Coolamon 30T (official mod: FS17_Coolamon_Chaser_Bins_30T_36T.zip) . perhaps, it is the reason ?
i dont think that pb comes from tractors 

thanks,
best regards
Kyoshou

**Comment by pops64** [comment] 2017-07-23 22:25
https://github.com/Courseplay/courseplay/wiki Follow. What is a transborder? Which mode? Etc.

**Comment by o0Kyoshou0o** [comment] 2017-07-26 17:47
hi,
i  published my post with more informations.
have you need log? if so, what debug touch are used (1,2,3,...) ?
thanks,
best regards
Kyoshou

**Comment by pops64** [comment] 2017-07-26 23:23
Follow http://courseplay.github.io/courseplay/en/manual/index.html#hud_mode2settings for probably setting up your settings. The Start at will wait until the combine fill percent is x amount. The drive on will wait until the trailer/overloader is filled to y amount. If you are using auto detect make sure you are completely on the field and then some and that there is a straight line a 100% on the field to combine or just use manual mode and select the combine itself.

**Comment by o0Kyoshou0o** [comment] 2017-07-27 17:13
hi, 
thx for your answer.
i have played with CP for more 500 hours. i read your link for setting and all parameter are correct.
i don't think that problem comes of its because CP transborder run correctly with 5.01..00160.dev but not with 5.01.00169.dev. today i play with the first version in order to have not this problem. 

>  If you are using auto detect make sure you are completely on the field and then some and that there is a straight line a 100% on the field to combine or just use manual mode and select the combine itself.

i don't use the auto detect because my vehicle is not into the field area. so i choice manually the combined harvester, in my case an lexion of pack FS17_Claas_Lexion_700_Stage_IV.zip.
Kyoshou

**Comment by pops64** [comment] 2017-07-27 21:35
Try turning off pathfinding.

**Comment by o0Kyoshou0o** [comment] 2017-07-29 12:46
ok i try it.
i see there have been a new version of CP 5.01.00173.dev , i test it too
Kyoshou

**Comment by o0Kyoshou0o** [comment] 2017-07-30 18:15
hi,
i test today CP 5.01.00173.dev and i have the same problem see the picture (sorry this is in french language)
In the red square, it's writed " wait the target fill level". the tractor don't want to go to unload crop into truck trailer. 
![2017-07-30_20-05-29](https://user-images.githubusercontent.com/30392058/28755813-fc1c5328-7562-11e7-9760-30139dcee792.png)

Kyoshou

**Comment by pops64** [comment] 2017-07-30 19:13
If you leave pathfinding off it will work fine. The problem I think is it can't find a path to unload course and so it does nothing.

**Comment by pops64** [comment] 2017-07-30 19:21
Try with the latest push version 176. It will now drive over fruit if it can't find a path back to the beginning of the course even with pathfinding on.

**Comment by o0Kyoshou0o** [comment] 2017-07-30 22:56
> If you leave pathfinding off it will work fine. The problem I think is it can't find a path to unload course and so it does nothing.

Yes but the transborder sometimes parks on the harvest line, so i switch between pathfinding on/off (see the following figure)
![2017-07-31_00-49-46](https://user-images.githubusercontent.com/30392058/28757767-5e391d12-758a-11e7-938f-8b17d592932e.png)

> Try with the latest push version 176. It will now drive over fruit if it can't find a path back to the beginning of the unloading course even with pathfinding on.

Ok, tomorrow, i try with version 176 :+1: 
Thx far all

**Comment by pops64** [comment] 2017-07-30 23:19
Yea your second picture is a separate issue that seems to pop up every once in a while. Can't seem to figure out what is causing it because it is hard to reproduce.

**Comment by o0Kyoshou0o** [comment] 2017-07-31 19:01
hi,

> Try with the latest push version 176. It will now drive over fruit if it can't find a path back to the beginning of the unloading course even with pathfinding on.

i just test the version 176, and i think that bug is fixed. the transborder go to unload at the target fill level.
thx for all

> Yea your second picture is a separate issue that seems to pop up every once in a while. Can't seem to figure out what is causing it because it is hard to reproduce.

yes, i think that we will have to wait more information. it's possible that fixed too with the version 176

wait and see :-)
i appreciate your time and wish you continued success in your challenges. 
best regards
Kyoshou

**Comment by pops64** [comment] 2017-07-31 23:08
We will close this out then. The other issue is on our todo list to fix.

**Closed by pops64** 2017-07-31 23:08 UTC
Labels: bug
