### ISSUE TITLE
Problem AIDriver.lua

### ISSUE THREAD

**Issue by jareklyson** [Courseplay/courseplay#4267] opened 2019-09-18 21:17 UTC
Hello 
when I wanted to make silage from oats, the courseplay panel disappear, including speedometer, 
and when its traied to work tractor don't following silageharwester
/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/AIDriver.lua:679: attempt to index field 'course' (a nil value)
2019-09-18 22:34 Error: Running LUA method 'draw'.

**Comment by Tensuko** [comment] 2019-09-19 05:00
Duplicate of #4217
Closed.

**Closed by Tensuko** 2019-09-19 05:00 UTC
