### ISSUE TITLE
Collision avoidance

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#1994] opened 2017-04-19 19:11 UTC
In Courseplay for FS15 when working trailers in Combi mode, if 2 tractors travelling to or from the harvester were about to collide they would both change course to avoid hitting each other.  With FS17 they don't do this, they just keep driving in a straight line until they hit each other.  Was this a feature that was removed intentionally?  I'm using CP v5.01.00125
![fsscreen_2017_04_19_20_06_58](https://cloud.githubusercontent.com/assets/18528850/25197499/3868e49e-253c-11e7-90e7-cfea2ad4b5ab.jpg)

**Comment by realm174** [comment] 2017-04-24 16:09
In addition to this (I'm guessing it's related to the same issue) when having multiple vehicles assigned to the same route, they rear end each other. For example, in combi mode, when one semi is at the waiting point (waiting for combine to call it), if another semi is coming to the same route after unloading, it will rear end the one waiting to be called, and literally push it out of the way.

**Comment by pops64** [comment] 2017-04-24 16:18
@realm174 Your issue is completely different. Check your log to see if it says that if you're missing a traffic collision for that tractor. Also try straightening out your approach sharp Thurs will sometimes throw off the traffic system

**Comment by Blackmankot** [comment] 2017-04-29 01:13
@pops64 What is the status of this issue?

**Comment by pops64** [comment] 2017-05-09 02:18
Can't Reproduce. Closed to keep issues area clean

**Closed by pops64** 2017-05-09 02:18 UTC
