### ISSUE TITLE
Computer freeze after trying to create a new Course with Multitool

### ISSUE THREAD

**Issue by burbon1985** [Courseplay/courseplay#5019] opened 2020-03-07 13:15 UTC
Computer freeze after trying to create a new Course with Multitool

**Comment by burbon1985** [comment] 2020-03-07 13:15
Computer freeze after trying to create a new Course with Multitool

**Comment by burbon1985** [comment] 2020-03-07 13:25
Multitool bedeutet einen Kurs für mehrere Geräte, z.B. 2 oder 3 Grubber auf einem Feld/Kurs. problem

**Comment by burbon1985** [comment] 2020-03-07 13:31
hello, the problem is in that when a create a new course in Multitool the computer is freeze. but when i create the course with one tool it's working ok. the problem is appearing when i create a course with multitools.

**Comment by Tensuko** [comment] 2020-03-07 13:38
Duplicate of #4994 (continue there)
and that is becouse the course for the offsettools is generated when start the driver.

Closed.

**Closed by Tensuko** 2020-03-07 13:38 UTC
