### ISSUE TITLE
Mode 1, starting at field edge, driver does not wait or waits at wrong point

### ISSUE THREAD

**Issue by Brzzl** [Courseplay/courseplay#2051] opened 2017-05-09 18:08 UTC
Hi guys!
Am I missing something or is it a feature of mode 1, that the driver does not wait an the starting point on a fields edge until he gets filled by a combine, which is selfunloading (mode 7). On the first round everything is going fine, in round 2 the driver doesn't stop at the starting point of the course, drives slowly (think it is turning speed) to waypoint 19 and stops there, waiting to get its load.

Thanks for your help!

(Picture shows the combine waiting at its overloading point and the drivers starting point, driver waits at WP 19 for its load)
![fsscreen_2017_05_09_19_59_08](https://cloud.githubusercontent.com/assets/3459971/25865444/33a882f4-34f3-11e7-9a80-39913d404d21.png)

**Comment by pops64** [comment] 2017-05-09 18:33
see #1976. try with a giants tipper. The wait point you have in your courses where is that located?

**Comment by Brzzl** [comment] 2017-05-09 18:54
Hi pops.
Combine, tractor and tipper are stock (Farmtech TDK 1600).
Waitpoint is WP 2 next to starting point, because the issue confused me already yesterday and I wanted to find a workaround to stop the driver passing by.

In this picture there is no waitingpoint but the driver passes the starting point, too.

![fsscreen_2017_05_09_20_53_25](https://cloud.githubusercontent.com/assets/3459971/25867353/9e084c78-34f9-11e7-8ca7-4747abfe6957.png)

**Comment by Brzzl** [comment] 2017-05-09 19:04
Tested it with another trailer combination and it works (now Fendt Vario 939 and Joskin Trans-SPACE 8000, both stock).
driver stops at starting point w/o waiting point and waits for its load.

![fsscreen_2017_05_09_21_03_25](https://cloud.githubusercontent.com/assets/3459971/25867789/fc1a100c-34fa-11e7-9d77-521765164b7e.png)

**Comment by pops64** [comment] 2017-05-23 16:29
Are you using current way point or nearest way point when you start the course?

**Comment by Brzzl** [comment] 2017-05-23 17:10
I've tried it with first waypoint and nearest waypoint.

**Comment by Blackmankot** [comment] 2017-08-05 01:12
@pops64 And I propose to close this issue for cleaning.

**Comment by Andreas28003** [comment] 2017-10-09 14:06
Hallo,
Ich habe festgestellt, dass wenn der Kurs am Feldrand beginnt - also "Beladen am Startpunkt" - und dann der Kurs zum Abladetrigger führt ist alles ok, sollte aber ein Beladetrigger auf diesem Kurs kommen, fährt CP am Startpunkt mit Wendegeschwindigkeit weiter. Getestet auf der Cornbelt Map. Hier sind die Trigger auf dem selben Platz - wenn ich den Ladetrigger verschiebe, so dass der Kurs nur noch über denn Abladetrigger führt, ist wieder alles Gut. Auch der Text das das"Silo Leer"ist kommt hier nicht. 
Ich hoffe, dass ihr das Problem beheben könnt da, die Abfahrer-Funktion sehr wichtig (für mich) ist.

**Comment by pops64** [comment] 2017-10-09 16:29
Please post in English

**Comment by Andreas28003** [comment] 2017-10-10 00:42
Hello,
I have noticed that if the course begins at the edge of the field - "loading at the starting point" - and then the course leads to the unloading trigger, everything is ok, but a loading triggers should come on this course. Tested on the Cornbelt card. Here are the triggers in the same place - if I move the load triggers so that the course only leads over the unload trigger, everything is all right again. Also the text "Das Silo Leer" is not here.
I hope the problem can be solved, the downhill function is very important (for me).

**Comment by pops64** [comment] 2017-10-12 02:52
Please run this again with the latest push of CP with debug channel 2. Thanks

**Comment by Brzzl** [comment] 2017-10-12 07:41
Now it works like a charm! thanks for your work! :) 👍 

https://www.youtube.com/watch?v=TAIBVw2KOvo&feature=youtu.be


[log.txt](https://github.com/Courseplay/courseplay/files/1378450/log.txt)

**Comment by Andreas28003** [comment] 2017-10-12 10:33
die übersetzung ist fürchtbar

**Comment by Andreas28003** [comment] 2017-10-12 11:45
Unfortunately, he still travels further I have my log with the debugger 2 attached and apologize my english
`[log.txt](https://github.com/Courseplay/courseplay/files/1379148/log.txt)`
[log.txt](https://github.com/Courseplay/courseplay/files/1379159/log.txt)

**Comment by pops64** [comment] 2017-10-12 12:52
On that course are you crossing a silo fill trigger?
```
[dbg2 lp46932 895.452 s] HKD: SiloTrigger Added! (onEnter)
[dbg2 lp46980 896.326 s] HKD: SiloTrigger Added! (onEnter)
[dbg2 lp48109 917.683 s] S Series (#1): Silo Trigger unloadDistance = 132.04 vehicle.cp.trailerFillDistance = -6.0
```

There should be an onLeave associated with that. Because the problem is when it returns to way point one it still thinks your trying to load at a silo and not on a field

**Comment by Andreas28003** [comment] 2017-10-12 13:29
Of course I can make over again with Debug canal 1 and 2 if you also want with all ^^

**Comment by Andreas28003** [comment] 2017-10-12 13:42
Interesting from line in 6334 before it only the old one allowed to then remove the same course only with 1 and 2, drivers CP opposed and then on "remove immediately" resounded ones, the driver stops with the road point 8.

**Comment by Andreas28003** [comment] 2017-10-12 13:43
and here it lied file
[log.txt](https://github.com/Courseplay/courseplay/files/1379498/log.txt)

**Comment by pops64** [comment] 2017-10-12 14:39
I don't see any1 debug channel 1 active. Could you recored your whole course via video? Or upload savegame courses, and give use the name and a clean download link for the map

**Comment by Andreas28003** [comment] 2017-10-12 15:22
http://ul.to/xzt16eus 
you will not like this these are the 16-fold Map of Castor the Corbelt I will try to make a video. but too only I will restart the play and because run course anew and then to you it lied smart alternatively I could place on the standard Map a silo and an on-line play start

**Comment by Andreas28003** [comment] 2017-10-12 15:51
so here now with debug 2 and then with debug 1 video has not clapped
[log.txt](https://github.com/Courseplay/courseplay/files/1379880/log.txt)

**Comment by Mithories** [comment] 2017-10-12 17:03
I was having this same issue.
I re-recorded the course with debug channels 1 and 2, and it seems to be fine now.  The tractor doesn't stop right exactly under the start point, but it is plenty close to work.

**Comment by Andreas28003** [comment] 2017-10-12 17:08
Unfortunately, this not always is in such a way, I have immediately run then course three times and every time true he occur give

**Comment by Andreas28003** [comment] 2017-10-12 17:10
look better more translated. Proposals?

**Comment by Mithories** [comment] 2017-10-12 17:26
Well, that didn't last very long.  
I re-recorded the overloader path to match my new transport path, and all of a sudden I started having issues with my overloader not stopping to unload again (previous issue)...So I turned off the bug channels thinking that was messing it up, and it wasn't.  So I turned them back on, but now the grain transport isn't stopping again.  Even with the bug channels.



[log.txt](https://github.com/Courseplay/courseplay/files/1380104/log.txt)

**Comment by Andreas28003** [comment] 2017-10-12 17:28
The problem lies with the silo trigger for loading of the CP he does not know this Trigger must not ignore there the start point in the silo is sonder in the field edge, otherwise the announcement "Siio could also not come blank. ", I have tested it also on another MAP "Morris land" and here the Trigger lie behind each other and not like with the Cornbelt into each other also here it is not thus of the Abfahrer then a course properly takes over with the Cornbelt I have moved at court and an outside camp the Trigger and with these courses gives it no problems only can and wants to I not always Map alter if new version comes. 
But I would like to thank here also over again for the Really work of you, without Coursplay I could never probably have played big cards. If I am right used I CP since Ls 13 with joy and a solution will also find here again. 
Thank you very much 
I hope this the translation is so good.

**Comment by pops64** [comment] 2017-10-13 01:26
Yea if you are having issue with this bug try re recording your courses has to not drive through a silo Trigger(The thing you fill your tipper with when not on a field) The debug channels have no impact what so ever on gameplay(with the exception of causing lag when they are on)

**Comment by Andreas28003** [comment] 2017-10-13 14:18
Unfortunately, most Modder obstruct the silo thus this the Be and Unloading trigger in a line are. Thus is one do not drive possibly. I will alter these Silo's for myself, however, with every update map I must alter this again. 
It lasts just quite well if to her could change this and I would also find out this. 
A lot of thanks in prerau

**Comment by pops64** [comment] 2017-10-13 15:19
The problem is why isn't it deleting the trigger after leaving it. Like it should.

**Comment by Andreas28003** [comment] 2017-10-13 17:37
Nevertheless, really then this is certainly quite simply zuändern ^^

**Comment by Andreas28003** [comment] 2017-10-13 17:57
here a better translation
Really, then, nevertheless, this is quite easy certainly to change ^^

**Comment by A-Rimmer** [comment] 2017-10-14 14:17
I'm having this same issue, is it because there is a fill trigger on top of the dump trigger that you want to unload at?

**Comment by Andreas28003** [comment] 2017-10-14 18:01
For a course " Loading at the start point ", there must only be the unloading trigger.
If the course is guided by a loading trigger, it is taken as a reference point and the downhill driver tries to load at this point. My approach is to change the triggers on a map so that the course only passes one trigger at a time. 
Start point at the edge of the field for unloading triggers and back to the edge of the field, and CP is happy and so am I. ^^

**Comment by Phantom742** [comment] 2017-11-27 18:44
There are maps like Cornbelt when you often have to load and unload trigger on the same route. Is it possible to check the distance to the next trigger so the tipper stay and waits to be loaded at the beginning on the course?

Thx in advance!

**Comment by ThomasGaertner** [comment] 2018-03-10 23:31
try again with v.0062 or higher and report ....

**Comment by pops64** [comment] 2018-06-11 20:46
inactivity

**Comment by pops64** [comment] 2018-06-11 20:47
Is this problem still around?

**Comment by Natasmi** [comment] 2018-06-20 04:55
i have had this problem many times on both single player download of CP and on the developers ver of CP there is an easy fix that has worked everytime for me and you dont have to create a new course.

what i do and it fixes the problem for me everytime this happens is

    open CP window and unload current course on effected vehicle
    make sure trailer is empty(you will lose product if not)
    reset both the trailer and the tractor
    4.re attach trailer to tractor and drive back to field open CP and reload recorded course
    5.sit back and enjoy

i found you must reset both the tractor and trailer to fix it and it has worked for me everytime.
i also found that if a tractor and trailer are having a problem restarting the game will not fix it but resetting them will, not sure why it may be a hook from CP to the trailer that resetting it reloads but with the process i listed above it works for me every time.

i usually ran into this issue after a few hrs of playing as my fields can take 3-4 hours to harvest with 2 combines and the course will run fine for a few hours and all the sudden it just stops working i just reset trailer and tractor and reload course and boom fixed.

**Closed** 2018-07-11 15:49 UTC
Labels: bug, waitingForUserAnswer

**Comment by pops64** [comment] 2018-07-11 15:53
You may now drive through silo triggers to your hearts content and this should no longer affect stooping at way point one

**Comment by DreamsOfAnarchy** [comment] 2018-07-25 15:59
Just reinstalled v5.3.0 through the ingame menu and I am still getting this.  Previous fix:

     1.open CP window and unload current course on effected vehicle
     2.make sure trailer is empty(you will lose product if not)
     3.reset both the trailer and the tractor
    4.re attach trailer to tractor and drive back to field open CP and reload recorded course
     5.sit back and enjoy

works, but only for a short amount of time and then you have to reset them all again.  You have to reset and reconnect and move back to the course multiple trucks and trailers several times per field.  Resetting also puts the vehicles at the end of the sort cycle every time as well so that is another annoyance caused by the short term fix.

**Comment by pops64** [comment] 2018-07-25 17:05
Please alwys check the latest dev version before posting problems with CP. This didnt make it to 5.3 release and got fixed just 2 weeks ago

**Comment by Andreas28003** [comment] 2018-07-27 09:14
Super, I have today 27.07.18 CP reloaded and tested the same. Field edge loaded and off to a silo where the triggers are in one place, and it works without the driver even batting an eye.
And I also think it's great because you also care about LS 19 that can hope that the CP is quite early for LS 19 is available.
Thank you for your great work
Greetings Andreas
