### ISSUE TITLE
Straw or grass picking with loader wagons

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3083] opened 2019-02-02 13:59 UTC
Hello I have the problem with the collection car. and although the first he makes it full, but still does something (bsp: 23000 liters, the loader but 22901 he just loads.) and at the second discharge he writes loading point is reached but not even near the unloading point.

MFG Mannie313

**Comment by Knowen** [comment] 2019-02-02 15:12
This issue allready exists: #3025

**Comment by Mannie313** [comment] 2019-02-02 15:16
![fehlerbild](https://user-images.githubusercontent.com/3021040/52165808-a8b0f580-2705-11e9-88b6-98b524df999c.png)

What else I forgot. He does not turn off the loader when he is full, but just lifts the pickup up and lets it run.

Should be the same but I have found another problem.

The red rimmed.

MFG Mannie313

**Comment by Satissis** [comment] 2019-02-02 17:18
True but still a duplicate of #3025 
I'll close this one but do add your issues to #3025 so we get it all in 1 place and easier to look into instead of us having to run around it 10 different issues to see if we fixed it all ;)

**Closed by Satissis** 2019-02-02 17:18 UTC
