### ISSUE TITLE
Courseplay not unloading to silo

### ISSUE THREAD

**Issue by cronuss64** [Courseplay/courseplay#2078] opened 2017-05-18 13:51 UTC
I am using the GTX Mods Road Train Pack and courseplay does not unload to silo. I have tried with in game trailers aswell and with more than 1 it does not unload. It works fine with a single trailer. Tried with different types of crops with same result. I have also tried various sell points and different maps, including Goldcrest Valley and it is the same. Tried with and without other mods installed.

[log.txt](https://github.com/Courseplay/courseplay/files/1011083/log.txt)

Video: https://youtu.be/nkdwzg0LMA4

**Comment by pops64** [comment] 2017-05-19 02:54
Try with version 143 or higher and report back

**Comment by cronuss64** [comment] 2017-05-19 11:21
Courseplay 143
It now works on my mod map but it does not work properly on Goldcrest. As you can see in the video 1st run does not unload 2nd trailer, but 2nd run in debug mode 2 does.

[log.txt](https://github.com/Courseplay/courseplay/files/1013976/log.txt)

Video: https://youtu.be/q0bHDupXlW8

**Comment by pops64** [comment] 2017-05-19 12:37
This is now a mod issue because it appears from the log that 143 worked. Your modded trailer didn't respond to the unload command

**Comment by cronuss64** [comment] 2017-05-19 13:22
I don't understand either, but as i stated it works on my mod map properly, but not on the Giants map. When i used debug 2 on Giants map it worked so i cannot send you a debug when it is not working. If you check the video you will see what i mean.

**Comment by pops64** [comment] 2017-05-19 18:18
You have to be doing something different between turning the debug channel on and off. Because the debug channel has zero impact on the code. So unless you can reproduce this with the debug channel on. It is going to be a can't fix. Can we close here?

**Comment by cronuss64** [comment] 2017-05-19 18:59
I did not do anything different, i just left on loop and on second pass turned on debug. If i leave the 1st trailer empty and fill the 2nd it empties. But if it can't be fixed then close. Thanks for trying anyway. I have uploaded the log file.

[log.txt](https://github.com/Courseplay/courseplay/files/1015265/log.txt)

**Comment by pops64** [comment] 2017-05-19 19:23
Yea I was hoping there was a nil error cause you can get weird behavior like this but your log is clean. It should make a difference if it is empty or not. The bug was I was only accounting for the vehicle unloading distance not each tipper. In the push I made it accounts for each tipper. Only thing the debug does is print out the distance and has no impact on. And if it works on the 2nd passe that probably is what the difference is try running the debug the very first unload of the loop. But I doubt it will change anything. Will close this out. Thanks for the response

**Closed by pops64** 2017-05-19 19:23 UTC
Labels: bug, can't fix, fixed, waitingForUserAnswer

**Comment by rogeriodec** [comment] 2019-10-18 17:37
[log.txt](https://github.com/Courseplay/courseplay/files/3745063/log.txt)
I have already created a route to unload the beet into the silo twice, which is automatically loaded during harvest, the truck goes through the silo but does not stop and does not unload.
