### ISSUE TITLE
Grain Transport and trailer moving at start point.

### ISSUE THREAD

**Issue by benjoglove** [Courseplay/courseplay#1036] opened 2015-02-06 06:32 UTC
Just wondering if anyone else has had this issue?

Have a truck and two trailers on a "grain transport" mode that awaits at a start point to have the over loader load the trailers and then empties at silos then returns. I am finding that the truck waits at the start point however the trailers will start shifting and moving around. Therefore when the over loader comes back it cant unload due to the trailers being all over the place. Have tried numerous trailers and appears on all of them.

**Comment by Maxcdr** [comment] 2015-02-06 08:11
Just tried with this trailer: http://www.modhoster.com/mods/krampesb3060-mit-kupplung

Works fine (v.4.01.0071dev)

![fsscreen_2015_02_06_09_09_30](https://cloud.githubusercontent.com/assets/10348839/6076197/13f0ef2e-ade0-11e4-9b44-ee6caaed55b7.png)

**Comment by benjoglove** [comment] 2015-02-06 08:14
How l long did you leave it there for? Usually takes a small while. I find it occurs more on hills even slight ones. Map I'm using has numerous hills and some paddocks dont have a flat are to work.

**Comment by Maxcdr** [comment] 2015-02-06 08:57
I tried on field 11 of Westbridge Hills and here what I get:

![fsscreen_2015_02_06_09_51_15](https://cloud.githubusercontent.com/assets/10348839/6076613/3b6b75be-ade6-11e4-97ae-3e9c011fc59b.png)

I guess this is what you get as well, correct? This is linked to this issue: https://github.com/Courseplay/courseplay/issues/895

**Comment by benjoglove** [comment] 2015-02-06 09:45
The truck stays okay its the trailers that end up like a worm behind it. I guess every time the truck slides then back up the trailers hit each other and slide? Guessing there's no fix for it from what I can read?

**Comment by JakobTischler** [comment] 2015-02-06 11:13
It's not only linked to the mentioned issue, it's basically a duplicate of it. 

I've tried some "hammer down" methods, but nothing all too reliable. So please go complain to Giants to get their heads out of their asses, get their shit together and fix their damn physics system.

**Closed by JakobTischler** 2015-02-06 11:13 UTC

**Comment by benjoglove** [comment] 2015-08-01 09:14
Now fixed with latest patch!!!
