### ISSUE TITLE
"Stop at last point or at next trigger"  different settings?

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#4448] opened 2019-10-26 18:38 UTC
So when I go into a harvester make a course etc, and i look at the settings and "Stop at last point or at next trigger" is different when you start the harvester and when before its started. Like before I click "Drive course" it shows the setting as Deactivated, but when I click "Drive course" It changes to Activated???? Is this a bug or normal?? And I still dont understand what is means
https://gyazo.com/1777cb51d85e88f91602d2e0c5dee706
https://gyazo.com/30695b627e73b408923d6c5bd892b1aa

**Comment by Tensuko** [comment] 2019-10-26 18:44
There is a little bug, some works some doesn't.
Whats actual working is under Advanced Settings.
Duplicate of #4437
Closed.

**Closed by Tensuko** 2019-10-26 18:44 UTC

**Comment by NumseBacon** [comment] 2019-10-26 18:47
what does the lower implements and raise implements mean then?

**Comment by Tensuko** [comment] 2019-10-26 18:51
at the end of a row, raise the tool early or later
and the start of a row, lower the tool early or later

That way you can adjust the lowering and raising of a tool.
The sprayer stops to early ? make it raise later
The sprayer starts to early ? make it lower later
And so on.... for all tools....

**Comment by Gibbanator** [comment] 2019-10-26 22:43
so when I am setting my course up I do not see these areas in advance settings? nothing to set anything to early or later.

**Comment by Tensuko** [comment] 2019-10-26 22:50
![fsScreen_2019_10_27_00_48_23](https://user-images.githubusercontent.com/27344744/67626954-a70afd00-f853-11e9-81ea-d87792f2a73f.png)
there is...

**Comment by Gibbanator** [comment] 2019-10-26 22:57
Thanks Tensuko..
