### ISSUE TITLE
Overloader mode: field borders, waiting position, ignoring "start at" setting.

### ISSUE THREAD

**Issue by MartinGrisotto** [Courseplay/courseplay#902] opened 2015-01-04 21:26 UTC
As you can see below, tractor with grain cart tries to find the shortest way to the waypoint. Since the file  has a shape different than rectangle (letter "L" in this case), it leaves the field bordes of the field. In this situation, it fells of a cliff, and tries to climb it back. It applies to other obstacles, as fences, trees etc. It would be good, to implement field border detection to prevent such issue.

![fsscreen_2015_01_04_20_22_32](https://cloud.githubusercontent.com/assets/10392883/5607485/34e6b8e4-945e-11e4-97d3-c7ada42be268.png)

Another thing is, that after emptying harvesters storage, tractor turns in other direction than it was going during driving side-by-side with harvester. For some reason, it drives a little bit to deep into the fruit. The tractor should stop ca 1,5-2,0m earlier. Otherwise, situation from below happens: harvster makes naother turn, and there you have it, tractor in the way. Interestingly, it doesn't happen every time, so it's hard to reproduce specific situation to narrow it down.

![fsscreen_2015_01_04_21_54_35](https://cloud.githubusercontent.com/assets/10392883/5607517/3bac4120-945f-11e4-9ca8-e07e734aaf2a.png)

I can't post the log, since there is none in my folder. Also, those situations happens if i use other tractors, and simple unloading mode "Combi".

Other issue i'm facing, but i can't reproduce it easly as well: sometimes, for no apparent reason, tractor is ignoring "start at" setting. It waits until harvester is full. It doesn't matter, if i use automatic search for harvester, or i pick one from the list. For now, it looks like it will happen when the tractor is faced in another direction than combine: ie tractor is facing north, harvester goes south, so they kinda don't see each other, as if tractor have had blind spot at 6 o'clock.

Mods that are on during the game and are related to vehicles: AutoCombine 3.2.
Courseplay ver: 4.01.0013

**Comment by gui7545** [comment] 2015-01-04 22:12
For your third issue, it is maybe because the path finding is activate : [http://courseplay.github.io/courseplay/en/manual/index.html#hud_generalSettings](manual)

**Comment by MartinGrisotto** [comment] 2015-01-05 07:42
Oh yes, I might give it a go, probably that's the cause.

**Comment by MartinGrisotto** [comment] 2015-01-06 15:46
Updating: issue 3 was caused by my incopentence ;) 

Issue 1 and 2 is still valid though.

**Comment by JakobTischler** [comment] 2015-01-06 15:48
Issue 1: "driving around the fruit" is deactivated, as described in the [manual](http://courseplay.github.io/courseplay/en/manual/index.html#hud_generalSettings).

**Comment by MartinGrisotto** [comment] 2015-01-06 21:10
I'm not sure what do you mean. Pathfinding refers to the possibility to avoid driving thru the fruits, and it was the couse to ignore "start at" setting. And this was issue nr 3 ;) Leaving the field boundaries or hitting not moving object is nr 1.

As to the second case, it's quite reproduceable, tractors tend to drive into the fruit shortly after they unload the harvester. No matter what map, tractor, harvester.

![fsscreen_2015_01_06_22_07_33](https://cloud.githubusercontent.com/assets/10392883/5636226/7b885706-95f0-11e4-813c-a401709e5c92.png)

**Comment by JakobTischler** [comment] 2015-01-06 21:12
> Leaving the field boundaries or hitting not moving object is nr 1.

And that is what I referenced when I talked about the deactivated "driving around fruit". It basically means "path finding": driving at the fruit border, or the field border, and not cutting field corners.

**Comment by MartinGrisotto** [comment] 2015-01-06 21:25
OK, roger that.

And as to the tractor cutting into the fruit after unloading the combine? It's all managed by pathfinding?

**Comment by MartinGrisotto** [comment] 2015-01-07 19:56
At first, i thought that it matters, wether the tractor was previously on the fruit side or not. 

It looks like the tractor final position is dictated by harvester. It occured to me, that tractor NEVER goes into the fuit, if harvester drives in the straight line. Driving into the fruit happens always,using AutoCombine and when the harvester was just unloaded at the and of the field (fruit, to be precise). Before tractor finishes its manouver to face the other direction, harvester is still showing a waypoint that lies on the harvesters longitudinal axis, and in the fruit at the same time. It happens because AutoCombine tends to make a little turn into the fruit BEFORE it finishes threshing. And if we choose turn mode: driving, it will make the case even worse, because the tractor will drive into the fruit just in front of the harvester. 

Solution: use AutoCombine in "circle" mode and/or avoid unloading if harvester is making a turn, whether or not shredding.

**Comment by JakobTischler** [comment] 2015-01-09 18:04
Can you please try again with debug channel 4 active? Then post the log.

**Comment by MartinGrisotto** [comment] 2015-01-09 19:23
BTW, i found a workaround to avoid going into the fruit after unloading at the end of the field. Simply add positive turn offset in AutoCombine, say, 10m, especially if youre using wide combine such as Case 9320. AutoCombine does not take into account how wide the combine is, and it makes the turnaround way to short. So it drives back into the fruit making a slight turn, making a "crooked cut". When the combine gets back to this point next time, it's actually making a turn (going in curve line), hence poiting position in the fruit, while waiting for the tractor to go away. Setting a positive offset helps to avoid "crooked cut" effect, and at the same time combine is poiting a position that is away from the fruit. 

But it still doesn't work for unloading while going in curve line, abviously.

LOG:
http://pastebin.com/JBEixJRH

**Comment by JakobTischler** [comment] 2015-01-09 19:26
Uhm, you do realise that many of your mods are just filled with errors, right? You should either fix or remove those first before testing Courseplay. Best to test a certain CP behaviour without any mods, but rather standard equipment.

**Comment by MartinGrisotto** [comment] 2015-01-09 19:49
I'm sorry, you are right. Nevertheless, same happened.

![fsscreen_2015_01_09_20_45_39](https://cloud.githubusercontent.com/assets/10392883/5686154/cb23dd42-9840-11e4-8798-04a6aaf537c9.png)
![fsscreen_2015_01_09_20_45_57](https://cloud.githubusercontent.com/assets/10392883/5686155/cb275a80-9840-11e4-833a-d30a604a4314.png)

LOG:
http://pastebin.com/AhtfcGWi

**Comment by ThomasGaertner** [comment] 2015-01-16 19:46
so, lets take the issues apart: for the last screenshot I have an explanation , but no solution yet. For the pictures before, I have no explanation. would you tell me the situation, was it on a field edge and the tractor turned or was it on straight way on the field . can you post the links to the mods u used ?

**Comment by MartinGrisotto** [comment] 2015-01-16 20:04
Like i said before, it is with close connection with harvester behavior being under AutoCombine control. What happens is this: while unloading, combine reaches end of field (or fruit) and makes a slight turn BEFORE full stop. Then, combine is waiting, still stoped, while tractor is getting behind the combine and makes full stop.

Now 2 things can happen:
1) If combine makes a slight turn towards the fruit, tractor will go bit more away from the fruit than it would normally go while harvester was driving the straight line. Sometimes, if this is the first pass on the field, it makes the tractor to go off the field, thus making autodetection of harvester impossible
2) if combine makes a slight turn away from the fruit,  tractor will go bit more towards the fruit than it would normally go while harvester was driving the straight line. In 99% of cases, it will make the tractor to drive into the fruit/path of the next pass.

Conclusion: harvester must stay parallel in relation to fruit border (line); otherwise, it is quite highly probable that tractor will NOT be in neutral area in realation to harvester.

**Comment by ThomasGaertner** [comment] 2015-01-17 09:38
please try again with v0043 or higher and report . please note that there is no solution for the last picture you sent but for turning at field edges....

**Comment by Muaddib-1** [comment] 2015-01-17 15:42
Sorry if this is not related to this issue but it seemed likely. ![2015-01-17_00002](https://cloud.githubusercontent.com/assets/5287689/5789357/f8f4f52a-9e2c-11e4-8aca-47984f3126cb.jpg) Would you like a debug channel?

**Comment by MartinGrisotto** [comment] 2015-01-17 17:24
I'm testin v0043 and it looks much better now. Further testing needed tough, will report later.

**Comment by ThomasGaertner** [comment] 2015-01-17 18:18
@Muaddib-1 : please post the log with debug channel 4 active . sounds like the tractor doesn't get all waypoints...Thanks

**Comment by Muaddib-1** [comment] 2015-01-17 20:21
It happened 2-3 times before I took that screenshot but I am unable to reproduce it now.

**Comment by Otterbear** [comment] 2015-01-20 13:26
I'm using CP version 4.01 and am getting the same result as problem #2 Tractor-trailer, when emptying at the end of the lane, turn and park in the "fruit" right in the lane the combine is turning into. Various mods installed, will post with clean mod folder. Just wanted to say it happens. 
![7b885706-95f0-11e4-813c-a401709e5c92](https://cloud.githubusercontent.com/assets/10614613/5817845/051a4690-a07e-11e4-88a2-43eca0f8605f.png)

**Comment by MartinGrisotto** [comment] 2015-01-20 13:37
Try with v0043 and report. ThomasGaertner made some changes to the code and it looks beeter now.

BUT (yeah, i know...), the roblem still exists when using Grimme sugar beet harvester. But i'm still testing, so i'll report when ready.

**Comment by AndyK70** [comment] 2015-01-20 20:39
Don't know if that is the same category of issue, thought I might post it here than in a new one.

When sending driver home via Button driver crashes into combine.
[See video at 17:30](https://www.youtube.com/watch?v=R8wfpigFwWs&17m30s)

Combine is under control of AutoCombine, Driver is called and they begin to fill the trailer. Meanwhile they are getting to the end of actual lane and both stop continuing to fill the trailer.
After that, the driver should drive into waiting position, but AC "is telling me to stop"...
[see video at 5:45](https://www.youtube.com/watch?v=jUvsp5cow8c&t=4m45s)
[At 11:00 it works](https://www.youtube.com/watch?v=jUvsp5cow8c&t11m0s), well it would work if there wasn't a tree holding back the truck.

[At 18:00](https://www.youtube.com/watch?v=jUvsp5cow8c&t18m0s) same crashing into combine when sending driver home.

**Comment by Otterbear** [comment] 2015-01-21 05:56
How to get v0043?

**Comment by Satissis** [comment] 2015-01-21 13:02
http://lmgtfy.com/?q=Downloading+and+installing+Courseplay

**Comment by ThomasGaertner** [comment] 2015-01-21 15:34
@AndyK70 : issue form 5:45 is not an issue , its when the auto combine is in traffic with the MAN and cant turn, if it cant turn , the turn stage will not be set and CP will not recognise the turn.
18:00 has been fixed in the past, but appeared now again and has been fixed again in v0051. please test and report. 
because of the mix of issues in this threat I will close it now....

**Comment by AndyK70** [comment] 2015-01-21 17:45
tested with 0051 and it was a bit strange...
made a video again, but it'll take some time to upload.
Now I have a logfile: [FS15 logfile (2015-01-21 18:25)](https://gist.github.com/AndyK70/35bf32ab09a1e9bc3477#file-fs15-logfile-2015-01-21-18-25)

trying to describe it:
Combine was under AC control, has finished and stopped. Manually I requested the driver which was under CP control.
After unloading the combine I clicked "Send driver home". The driver made his turn to a waiting point. But instead driving on to his unload course he stopped there and signed "waiting until fill level is reached".
I switched to the combine again, requested the driver again and he was circling counter clockwise the combine and at the end he was "In traffic" with the combine.
I switched to the driver, stopped him, drove the MAN a bit down, behind the combine and startet the driver again in hope, now he has free sight to the pipe of the combine if he wants to get some more grain (which in fact wasn't there), or to his right side a free driveway to his unloading course.
Again he said "waiting until fill level is reached".
Switched to the combine and requested the driver once more.
The driver then made a turn (into waiting position?) sliding a bit and took off to his unloading course.

Video will be available around 7:00pm at [LS15 Sending driver home with CP0051dev](https://www.youtube.com/watch?v=yuW7GfVyPTQ)

should we transfer this issue in a new one?

**Comment by ThomasGaertner** [comment] 2015-01-21 19:12
yea that's because the fill level of the combine was 0 at this moment. try again and send the driver home when the combine has still grain in the tank....

**Comment by AndyK70** [comment] 2015-01-21 23:54
hmm maybe I didn't point out what I think the problem was?
1. the combine had stopped and had grain loaded
2. I requested the driver, driver came alongside and unloaded the combine.
3. I clicked "Send driver home"
4. The MAN made a turn to his waiting point. (until now everything was fine)
5. now the problem: the driver sits there and waits for the combine to reach fill level, instead of driving the unload course as I told him clicking on "Send driver home"
6. the rest of the story arose from not driving the unload course.

**Comment by ThomasGaertner** [comment] 2015-01-23 16:14
@AndyK70 : try with v53 or higher, should work now....

**Comment by AndyK70** [comment] 2015-01-24 10:10
was testing it with 0055.

it worked ... somehow a bit strange.
Driver first seemed to go wild after sending him home, but at least found it's way to the unload course.
Will upload the corresponding video later this evening. Have to go to bed again and nurse my cold.

**Comment by AndyK70** [comment] 2015-01-24 18:48
Ok, here is the video of it. [https://www.youtube.com/watch?v=9fGup1j3xj4](CP0055 Sending driver home)

should I try another one with some debug channel activated?

**Comment by ThomasGaertner** [comment] 2015-01-25 07:47
please try intensely v0060 or higher and report...

**Comment by AndyK70** [comment] 2015-01-25 18:28
used 0063 for test.

looks very good.
Driver was making his turn to waitpoint and went straight forward to his unloading course.
very nice

**Comment by Otterbear** [comment] 2015-01-28 01:28
Not quite ready for prime time. Using suggested version 4.01 00063 dev file.

Truck will not not respond to "start at" level, First pass he did manage to approach once my combine reached the end of the row...at around 99% full. ("Start at" was 80%). 
Second, pass, refused to move...period. Had great difficulty driving the route...with an EMPTY trailer. Got stuck momentarily in places that I the player drive, (and must drive) regularly, and require little power, and that are easily navigated by the player. :( I did record the route, and its set to use the speed used during the recording, but still could not manage a turn after just leaving the silo. -With an empty trailer.

The one time he did manage to at least show up, the truck/trailer did move to a more logical waiting point.

**Comment by ThomasGaertner** [comment] 2015-01-28 06:47
@Otterbear : im pretty sure that the start at issue is concerning the path finding setting to active. 
For your other issues I unfortunately don't understand what you want to say.
since this issue has many mixed cases, II will close it for the last time. 
Please open a new issue with an more clear and detailed description of your problem 
Thanks

**Closed by ThomasGaertner** 2015-01-28 06:47 UTC
Labels: bug
