### ISSUE TITLE
Silage trailers (mods) not completely full

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#1716] opened 2017-01-30 20:38 UTC
I noticed when in mode 2 and using mods of silage trailers that they won't completely fill up. The harvester, a Krone Big X1000, keeps chopping but the trailer won't completely fill up or very slowly. It always happens at the latest percentage before it's completely full. 
No errors in log. 

Some trailers I noticed: 
[Krone 460D](http://forbidden-mods.phpbb8.de/anhanger-f1930/krone-460d-t30284.html
)
[ITRunner](http://forbidden-mods.phpbb8.de/anhanger-f1930/itrunner-container-t29668.html)

**Comment by ThomasGaertner** [comment] 2017-02-03 14:21
sorry I don't want to load mods from Uploaded.net , do you have alternative links ?

**Comment by SnoopBok** [comment] 2017-02-03 15:26
Unfortunately, I have no alternative links.

**Comment by pops64** [comment] 2017-02-07 04:57
Copied from my issue. Has I think this is the cause of your problem

So here is a new one. So it seems if the Mex5 is attached to too large a trailer when that said trailer closes in on capacity the Mex5 pipe is no longer able to reach some parts of the trailer but Mode 6 doesn't know to abort and keeps driving :O . This may also explaing when I have seen a few people mention the chaff harvesters are driving off with out waiting for the tipper. [Video](https://youtu.be/J1ddt5Q_AvA)

**Comment by pops64** [comment] 2017-08-12 20:20
Closing this out. Not a bug but a problem with the way Giants changed fill up trailers. The pipe has to be in range of 100% of the trailer otherwise you get this issue. It is on our list of enhancements that will fix this issue.

**Closed by pops64** 2017-08-12 20:20 UTC
Labels: Mod Issue, postponed
