### ISSUE TITLE
Transportation of liquids.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#1968] opened 2017-04-11 02:36 UTC
Good afternoon. Since version 5.01.00101 at start-up at the rate of transport for transportation of liquids in some tanks the point "to remember position of a pipe" began to appear. Because of this item, transportation is not possible. Thank you for your great contribution to Farming. Sincerely, Alexander. Translation Google.

![2017-04-11_10-20-54](https://cloud.githubusercontent.com/assets/26131714/24890471/aac10fee-1ea2-11e7-9613-d3b63edf5b5d.jpg)

![2017-04-11_10-24-14](https://cloud.githubusercontent.com/assets/26131714/24890478/b20d6d56-1ea2-11e7-975f-75bd5c347098.jpg)

**Comment by pops64** [comment] 2017-04-11 03:14
Mode 8 is the only mode you should be using to transport liquids. Has for this bug I will look into it

**Comment by Zoochase** [comment] 2017-04-11 04:24
Can you add the count down or number of runs to Mode 8 like Mode 1?

**Comment by Blackmankot** [comment] 2017-04-11 09:25
@pops64  Thank you! Unloading was done with a waiting point. But the loading does not work, not according to the old scheme and not according to the new scheme. How now to write down the rate for loading?
![2017-04-11_16-44-40](https://cloud.githubusercontent.com/assets/26131714/24902126/c9787d94-1edb-11e7-816c-7429c82b1022.jpg)

![2017-04-11_17-23-35](https://cloud.githubusercontent.com/assets/26131714/24902134/d02c2172-1edb-11e7-934b-010136b864ae.jpg)

![2017-04-11_17-24-32](https://cloud.githubusercontent.com/assets/26131714/24902141/d5766e80-1edb-11e7-9d82-a554c8d57370.jpg)

**Comment by Blackmankot** [comment] 2017-04-11 09:34
@Zoochase  No, I can not, this parameter is not in 8 point. In the window before starting the course is empty ... 

![2017-04-11_17-29-10](https://cloud.githubusercontent.com/assets/26131714/24902551/1d219c72-1edd-11e7-9f40-4ce86795ec41.jpg)

**Comment by Zoochase** [comment] 2017-04-11 12:11
That question was for the Developers asking if they could add that in, sorry

**Comment by Blackmankot** [comment] 2017-04-11 13:39
@pops64 A question, could add to the 8 point the number of flights, as in the first paragraph? Thank you and success!

**Comment by pops64** [comment] 2017-04-11 15:14
Yea. I will look into adding that into mode8

**Comment by Blackmankot** [comment] 2017-04-13 05:15
@pops64 Good afternoon. As practice has shown, transporting all liquids at 8 points complicates the process and increases the number of courses. Here is an example: a cannery accepts potatoes, onions, carrots, corn, sunflower oil. The old scheme allowed to record only one course for the transport of all goods. It's comfortable. The new scheme requires the creation of several courses for the transport of goods. Can you go back to the old transportation scheme? 

![2017-04-13_12-22-07](https://cloud.githubusercontent.com/assets/26131714/24990832/3e92ece0-2049-11e7-81e2-379f5d833dc4.jpg)

Another example. The bakery, accepts: rye flour, corn flour, wheat flour, sunflower oil, sugar, milk. I could transport all the goods in one course. The new scheme does not allow it to be done ... Please return the old transportation scheme. Thank you for attention.

![2017-04-13_13-10-25](https://cloud.githubusercontent.com/assets/26131714/24991134/436ebe5e-204b-11e7-9f64-afcf6c807c2d.jpg)

**Comment by pops64** [comment] 2017-04-13 14:41
CP has never been designed to transport more than one thing at a time. And the way it is setup is it will only look for the trigger that accepts the current fill type in the trailer when in mode 1. Mode8 can't support this behavior and relies on placement of the waitpoint and is only designed for liquid fill types of giants and some mods

**Comment by Zoochase** [comment] 2017-04-13 23:53
@Blackmankot What map are you playing?  Link?

**Comment by Blackmankot** [comment] 2017-04-14 02:42
@Zoochase Map of "Gifts of the Caucasus"
https://modsgaming.ru/load/farming_simulator_2017/maps/farming_simulator_2017_skachat_mod_karta_dary_kavkaza_v_2_0_3/160-1-0-7837

**Comment by Blackmankot** [comment] 2017-04-14 03:18
@pops64  Then I have the following sentence. Add items to the menu: 1 unloading of solid goods; 2 unloading of liquid goods. When recording a course at the unloading point, stop the transport and specify the type of unloading of the goods and continue recording. In this version, you do not need 8 items.

![2017-04-14_11-04-56](https://cloud.githubusercontent.com/assets/26131714/25032089/03aff242-2104-11e7-93d3-9fc4690bae5b.jpg)

**Comment by Blackmankot** [comment] 2017-04-14 05:07
@pops64 When you combine several courses, the load courses can be different, and the unloading course is one.  Here is an example. 
![2017-04-14_13-03-58](https://cloud.githubusercontent.com/assets/26131714/25033742/2207d8ea-2113-11e7-8ed1-0ff8548990f7.jpg)

![2017-04-14_13-00-47](https://cloud.githubusercontent.com/assets/26131714/25033744/27ce8698-2113-11e7-94e5-75bb6c3d802f.jpg)

**Comment by Blackmankot** [comment] 2017-04-14 05:17
@pops64 Then I have the following sentence. Add items to the menu: 1 unloading of solid goods;2 unloading of liquid goods. When recording a course at the unloading point, stop the transport and specify the type of unloading of the goods and continue recording. In this version, you do not need 8 items. In this case, only one course will be needed to unload all types of goods in production.

![2017-04-14_11-04-56](https://cloud.githubusercontent.com/assets/26131714/25033897/b706e71e-2114-11e7-8ead-fed124b580e4.jpg)

**Comment by pops64** [comment] 2017-04-14 14:03
That would be redundant  has mode1 will automatically unload at first trigger that accepts the fill type it is currently loaded with. And mode 8 uses the wait point for where to unload. The problem is and why you have to use mode 8 for liquids mode 1 for solids is how Giants handles loading and unloading. For tanks they load by refilling and unloading changes by which trigger it is in. For tippers I believe loading is handled by the trigger and unloading is the same for all triggers. Plus it would be a lot of rewriting of core CP code which we don't have the time to do

**Comment by Blackmankot** [comment] 2017-04-15 06:10
@pops64 All right! Thank you.  I close the question.

**Comment by pops64** [comment] 2017-04-15 15:04
I am going to reopen this until I add the run counter to mode 8 has that is possible

**Comment by Blackmankot** [comment] 2017-04-15 18:24
@pops64 Excellent!

**Comment by pops64** [comment] 2017-04-15 20:17
Try with v0118 or higher and report back for the runcounter in mode8

**Comment by Blackmankot** [comment] 2017-04-16 15:15
@pops64 The result of the test. Everything works fine - when the download is started from the departing course. Transport starts from any point of the course. Foto.
![2017-04-16_16-35-56](https://cloud.githubusercontent.com/assets/26131714/25071968/70f3509e-22f6-11e7-809b-c6c3d698d537.jpg)
![2017-04-16_16-36-11](https://cloud.githubusercontent.com/assets/26131714/25071972/8053e274-22f6-11e7-9e22-4686e40e1f15.jpg)
![2017-04-16_19-09-58](https://cloud.githubusercontent.com/assets/26131714/25071976/90522410-22f6-11e7-95cf-1a69914c97a1.jpg)

If you start the course - where the loading rate is arriving, then after the first loading and commencement of the movement along the departing course, the counter shows that one flight has already been completed. And after the completion of a given number of flights, the third loading (superfluous) begins.

![2017-04-16_16-36-11](https://cloud.githubusercontent.com/assets/26131714/25072078/27ebe886-22f9-11e7-877b-f1088480939d.jpg)
![2017-04-16_16-36-11](https://cloud.githubusercontent.com/assets/26131714/25072092/6b1f7398-22f9-11e7-86d6-c73a7f1d058d.jpg)
![2017-04-16_16-49-56](https://cloud.githubusercontent.com/assets/26131714/25072096/7ad03732-22f9-11e7-94bb-f62676d6cd8d.jpg)
![2017-04-16_16-50-25](https://cloud.githubusercontent.com/assets/26131714/25072097/7d0f0dfc-22f9-11e7-9994-bec15281ea4a.jpg)
I suggest that you transfer the course counter to the incoming rate. With such a scheme it will not matter which course the download starts from, departing or arriving. Thank you for attention.

**Comment by 3lronMcBong** [comment] 2017-04-16 15:19
Very nice thanks for this :-)
runcounter in mode8  works good.
Is it possible to drive after a certain time?
timecounter?

**Comment by pops64** [comment] 2017-04-16 16:01
@3lronMcBong Already should occur you would have to better describe when you want it to drive after a certain time. Unless your talking the runcounter which case it doesn't I don't think I would every add that in.

@Blackmankot I would avoid that situation for now. I am working on a fix for it.

**Comment by Blackmankot** [comment] 2017-04-16 16:43
@pops64 And if you count flights for unloading !? Number of unloads = number of flights.

**Comment by Blackmankot** [comment] 2017-04-16 16:49
@pops64  If you think that everything is only getting more complicated, then let's leave the current version.

**Comment by 3lronMcBong** [comment] 2017-04-16 17:50
@pops64 I mean that he drives after a certain time.
For example, which he always starts after 60 minutes.

**Comment by pops64** [comment] 2017-04-16 19:10
@3lronMcBong O your asking if CP will run the loaded course after waiting a certain amount of time

@Blackmankot It is not going to get much more complicated it is just question of how to code it.

**Comment by 3lronMcBong** [comment] 2017-04-16 22:22
@pops64 Yes, that is exactly what I mean 👍

**Comment by Blackmankot** [comment] 2017-04-17 03:32
@pops64 I will be happy if you solve this question.

@3lronMcBong I do not quite understand the need for delayed start of transport for a while on the course? I can certainly be mistaken, but this function is not advisable.

**Comment by 3lronMcBong** [comment] 2017-04-17 10:50
@Blackmankot I mean for example for the feeding of the animals.
If water or food is empty after 6 days, CP will automatically start and fill up.

**Comment by Blackmankot** [comment] 2017-04-17 17:14
@3lronMcBong  I think it will be difficult to do, we still need to count the days.

**Comment by Blackmankot** [comment] 2017-04-17 17:17
@pops64 I can close the question !?

**Comment by pops64** [comment] 2017-04-17 19:15
Yea you can if your satisfied with the way it currently is setup. I know I forgot to do a few things that will create bugs that I will push once I think of a good way to handle this

**Comment by Blackmankot** [comment] 2017-04-18 04:11
@pops64 Thank you! I'm sure you will succeed.

**Comment by Blackmankot** [comment] 2017-04-18 07:50
@pops64 Found a question that is logical to close.
Dump truck is not unloaded Mod Issue
#1912 opened 28 days ago by fckorolev

**Comment by pops64** [comment] 2017-04-18 16:54
Test again v01.0123 and report back. Thanks

**Comment by Blackmankot** [comment] 2017-04-19 04:42
Version 5.01.00124. 
1 . TSA 30000 - Does not work on the course.
![2017-04-19_10-34-08](https://cloud.githubusercontent.com/assets/26131714/25162486/aa9bae58-24f5-11e7-8346-766ba4527569.jpg)
![2017-04-19_10-34-29](https://cloud.githubusercontent.com/assets/26131714/25162488/ae2c0fc2-24f5-11e7-89bd-c26db089634b.jpg)

2 . FS17_kotteUniversalPack - At the rate of unloads perfectly. But he stopped turning off the engine on unloading. On loading, the engine switches off. Fuel economy is active. In previous versions of the course, this problem was not.
![2017-04-19_10-01-49](https://cloud.githubusercontent.com/assets/26131714/25162840/45412e72-24f8-11e7-96a3-7787af1e5f6a.jpg)

3 .  The flight counter does not work. With any loading organization.
![2017-04-19_10-43-16](https://cloud.githubusercontent.com/assets/26131714/25162996/69270b62-24f9-11e7-9575-659472dcad8d.jpg)
![2017-04-19_10-44-16](https://cloud.githubusercontent.com/assets/26131714/25163156/c666359a-24fa-11e7-890e-0a1d0fe32b83.jpg)
One flight is completed. But the movement continues and loading begins.
![2017-04-19_10-56-46](https://cloud.githubusercontent.com/assets/26131714/25163288/a91a7bd0-24fb-11e7-83fa-2f9742596091.jpg)
![2017-04-19_10-57-04](https://cloud.githubusercontent.com/assets/26131714/25163303/c4009b6e-24fb-11e7-9db3-cdb90272f1e2.jpg)
![2017-04-19_10-58-09](https://cloud.githubusercontent.com/assets/26131714/25163374/6e9ebfb0-24fc-11e7-85b3-264f7e60e106.jpg)

The situation is the same.
![2017-04-19_10-54-45](https://cloud.githubusercontent.com/assets/26131714/25163450/180f1c5c-24fd-11e7-925a-59c21fce2fb6.jpg)
![2017-04-19_10-55-36](https://cloud.githubusercontent.com/assets/26131714/25163510/7d114738-24fd-11e7-9d0e-a40177e836a1.jpg)

**Comment by pops64** [comment] 2017-04-19 16:58
Try again with version 125 or higher. Thanks.

**Comment by Blackmankot** [comment] 2017-04-20 06:58
Alas, nothing has changed. For both loading schemes.
![2017-04-20_09-51-44](https://cloud.githubusercontent.com/assets/26131714/25217486/bc12afda-25d9-11e7-97c6-f712f1e04068.jpg)
![2017-04-20_09-52-33](https://cloud.githubusercontent.com/assets/26131714/25217489/bf455a90-25d9-11e7-8877-2f9e8433f966.jpg)
![2017-04-20_13-52-13](https://cloud.githubusercontent.com/assets/26131714/25217493/c214faa0-25d9-11e7-914c-c978d9ffbf21.jpg)
![2017-04-20_13-52-29](https://cloud.githubusercontent.com/assets/26131714/25217496/c3e977ca-25d9-11e7-9616-67bd186e9ecc.jpg)
![2017-04-20_13-53-20](https://cloud.githubusercontent.com/assets/26131714/25217498/c5779f36-25d9-11e7-8d71-b93168dc2e3c.jpg)
![2017-04-20_14-47-16](https://cloud.githubusercontent.com/assets/26131714/25217499/c71651b6-25d9-11e7-96bb-70c874a62737.jpg)

**Comment by pops64** [comment] 2017-04-20 16:16
I have tried every way I can think of to produce what is occurring. There was a bug in 125 that might have caused this(Nil error which prohibited stopping in mode8). Try again with v126 and if it still doesn't work run again with debug channel 12 active and post that log. Here is link of what is suppose to look like [viedo](https://www.dropbox.com/s/e4u4ygc8w8knhzl/FarmingSimulator2017%2064bit%204_20_2017%2012_00_11%20PM.mp4?dl=0) Sorry for the crap quality

**Comment by Blackmankot** [comment] 2017-04-22 03:54
Alas, nothing has changed. 
![2017-04-22_11-34-55](https://cloud.githubusercontent.com/assets/26131714/25301184/681e7b78-2752-11e7-9aea-68159ba9e880.jpg)
![2017-04-22_11-48-33](https://cloud.githubusercontent.com/assets/26131714/25301185/6becdcb8-2752-11e7-8970-96bf0482c22e.jpg)
![2017-04-22_11-49-09](https://cloud.githubusercontent.com/assets/26131714/25301186/702754d4-2752-11e7-836c-fe6ef7698dba.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/948698/log.txt)

**Comment by pops64** [comment] 2017-04-22 05:25
I just don't understand how you are creating this behavior. Has shown in this [video](https://www.dropbox.com/s/e4u4ygc8w8knhzl/FarmingSimulator2017%2064bit%204_20_2017%2012_00_11%20PM.mp4?dl=0 )is my attempt at recreating your courses and as you can see it is working. Is there anything your doing different that I am not? I will push some more debug prints because what I see from you log is what should be occurring.

**Comment by Blackmankot** [comment] 2017-04-23 13:09
Nothing changed. The trigger does not interfere. In version 5.01.00119, everything worked, if the flight started with a boot rate. In the screenshots above, I showed.
![90522410-22f6-11e7-95cf-1a69914c97a1](https://cloud.githubusercontent.com/assets/26131714/25313787/506ec1b0-2868-11e7-9433-baeb71126e27.jpg)
Quote - Everything works fine - when the download is started from the departing course. Transport starts from any point of the course.
I suggest to return to this working variant.

**Comment by pops64** [comment] 2017-04-23 17:17
I just can't figure out how you are getting this behavior. I was only able to produce it by driving into the fill trigger at 85 kph but even then it still attempted to stop. Because the way it is coded it has to try to stop if it is able to count and the is no wait point within 3 waypoints and there is a filltrigger present. Then it can only count if there is a fill trigger present. I can add in a error protection that if the count ever goes higher than the total number to just stop.

**Comment by pops64** [comment] 2017-04-23 21:24
try with version 01.00128 or higher. This won't change anything but if the current run exceeds the total number of runs allowed it will just straight up stop. When you do try this run with only debug 12.

**Comment by Blackmankot** [comment] 2017-04-24 04:05
![2017-04-24_11-21-13](https://cloud.githubusercontent.com/assets/26131714/25322061/04e63790-28e6-11e7-8551-e50aba397353.jpg)
I understood the difference. If you use a default tank, everything works fine. If you use FS17_kotteUniversalPack (Version: 1.0.0.3). The screenshots show everything. :)
![2017-04-24_11-10-24](https://cloud.githubusercontent.com/assets/26131714/25321870/881baaca-28e4-11e7-8c6e-81b745104098.jpg)
. The screenshots show everything. :)) 
![2017-04-24_11-23-49](https://cloud.githubusercontent.com/assets/26131714/25321694/2ef027d8-28e3-11e7-9272-03e44ab7d432.jpg)
![2017-04-24_11-07-09](https://cloud.githubusercontent.com/assets/26131714/25321697/32999950-28e3-11e7-9c44-4d39cc82032f.jpg)
![2017-04-24_11-08-13](https://cloud.githubusercontent.com/assets/26131714/25321741/8f820d96-28e3-11e7-9ef2-c46c95569a6a.jpg)
![2017-04-24_11-09-01](https://cloud.githubusercontent.com/assets/26131714/25321786/09bb93d4-28e4-11e7-984b-ab802e16aab4.jpg)
![2017-04-24_11-11-21](https://cloud.githubusercontent.com/assets/26131714/25321872/8ee9d44e-28e4-11e7-97ed-fb1c10405cd3.jpg)
![2017-04-24_11-12-08](https://cloud.githubusercontent.com/assets/26131714/25321915/d373087e-28e4-11e7-91c3-e439642ada84.jpg)
This is a tank from Kote.
![2017-04-24_11-14-07](https://cloud.githubusercontent.com/assets/26131714/25321973/261ffa96-28e5-11e7-8be7-09aa29da56e1.jpg)
![2017-04-24_11-14-56](https://cloud.githubusercontent.com/assets/26131714/25322006/72821734-28e5-11e7-9d88-974bbad00877.jpg)
![2017-04-24_11-16-12](https://cloud.githubusercontent.com/assets/26131714/25322013/85d0e3d8-28e5-11e7-90ae-84a888caa8f1.jpg)
![2017-04-24_11-17-04](https://cloud.githubusercontent.com/assets/26131714/25322021/9873511a-28e5-11e7-85ae-04606f0796a1.jpg)
![2017-04-24_11-17-53](https://cloud.githubusercontent.com/assets/26131714/25322031/b1b9454e-28e5-11e7-9831-4cf66e18a500.jpg)
![2017-04-24_11-18-19](https://cloud.githubusercontent.com/assets/26131714/25322037/c38d3208-28e5-11e7-8dc5-823bc06888ec.jpg)
![2017-04-24_11-19-33](https://cloud.githubusercontent.com/assets/26131714/25322045/e3b3b0ca-28e5-11e7-9c24-eee02d7c48e5.jpg)
![2017-04-24_11-20-22](https://cloud.githubusercontent.com/assets/26131714/25322049/f44b35e8-28e5-11e7-88d8-2e78b745885e.jpg)
![2017-04-24_11-21-13](https://cloud.githubusercontent.com/assets/26131714/25322073/2ad6b678-28e6-11e7-98e0-1c58a56267a4.jpg)
![2017-04-24_11-21-31](https://cloud.githubusercontent.com/assets/26131714/25322082/445a11c6-28e6-11e7-9c91-e82f6a4fafac.jpg)
![2017-04-24_11-23-06](https://cloud.githubusercontent.com/assets/26131714/25322091/4f722544-28e6-11e7-8f4f-5d5b25145318.jpg)

**Comment by Blackmankot** [comment] 2017-04-24 05:17
Update: The course version is 5.01.00129. Excess loading produces and does not attempt to perform an extra flight. Everything has become, as in version 5.01.00119. This is much better! :))
![2017-04-24_13-03-15](https://cloud.githubusercontent.com/assets/26131714/25323200/5a44eec0-28f0-11e7-9a61-602ab23edc66.jpg)
![2017-04-24_13-04-11](https://cloud.githubusercontent.com/assets/26131714/25323204/5f8df5b6-28f0-11e7-8a2f-8d0feeefd356.jpg)

**Comment by pops64** [comment] 2017-04-24 06:05
Yea I think I know what the problem is with the kote. Something I forgot to tank into account. It is both a water and slurry tank. Glad my error protection is working for you. See if I can fix the kotte mod and push something a little later

**Comment by Blackmankot** [comment] 2017-04-24 07:40
@pops64 My last two posts have seen?

**Comment by pops64** [comment] 2017-04-24 16:21
Yea. I a fix for this but when I tested I got some werid behavior. I will push it later today once I work out the kinks

**Comment by pops64** [comment] 2017-04-25 02:37
@Blackmankot I have a question I am over hauling the changing the total number of runs. What would you think would be better to increase the run count at the end of loading(This is the way it currently is setup). Or at the beginning of loading

**Comment by pops64** [comment] 2017-04-25 03:14
Ok v01.0130 or higher should fix any remaining issues as well putting in some prevention measures to changing the total number of runs during loading.

**Comment by Blackmankot** [comment] 2017-04-25 03:26
Ok, I'll check.

**Comment by Blackmankot** [comment] 2017-04-26 10:58
All perfectly! Thank you!
![2017-04-26_18-56-46](https://cloud.githubusercontent.com/assets/26131714/25431247/5e4034d0-2ab2-11e7-9061-a9c861a078c6.jpg)

**Comment by pops64** [comment] 2017-04-26 13:50
I will close this out then has I am not going to do anymore improvement to the run counter

**Closed by pops64** 2017-04-26 13:50 UTC
Labels: enhancement, waitingForUserAnswer

**Comment by Blackmankot** [comment] 2017-04-26 14:15
Of course!

**Comment by Blackmankot** [comment] 2018-03-10 08:26
@pops64  Hello! Transportation digestat again does not work unfortunately. If you use the FS17_kotteUniversalPack pkg 1.2.0.0. That loading and unloading does not work at all. If you use a similar tank from the game itself, the boot works, and the unloading does not work. Transportation mode 8.
https://fs17.lt/kotte-universal-pack-v-1-2/
Video - https://yadi.sk/i/vRGUWDLt3TCo7M
And of course, thanks for the work!

**Comment by pops64** [comment] 2018-03-10 12:36
Please start a new issuse and post a log with debug channel 23 active thx
