### ISSUE TITLE
.037 Turn Fixes: Lemken Titan 11 wont turn

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#1561] opened 2016-12-28 17:01 UTC
Lemken Titan 11 is lifted on Headland, but attacherVehicle goes straigt forward,instead of doing the "ohm-turn".

**Comment by krookoo** [comment] 2016-12-28 17:02
Download v0.36

**Comment by RedOhne** [comment] 2016-12-29 07:45
I have the same issue with any implement when I choose turn outside field. It goes straight forward on any turn. Everything works fine when I choose turn on field. 

Where can I download the v036, if a fix takes some more time. Any logs or debugs needed for this? I can upload some in the afternoon. 

Best regards 
Tim

**Comment by pops64** [comment] 2016-12-30 02:14
https://github.com/Courseplay/courseplay/tree/55457d9fdf49785247716c1a40f037d0319aac51

**Comment by Satissis** [comment] 2017-01-04 20:46
Try 01.0009 or later and report back

**Comment by frm274** [comment] 2017-01-05 09:13
Ohm Turn seems to work, but bugs in the other ones. See pic.
<a href="http://www.pic-upload.de/view-32425668/cpissue2.jpg.html"><img src="http://www2.pic-upload.de/thumb/32425668/cpissue2.jpg" alt="Bild hochladen" /></a>

**Comment by Satissis** [comment] 2017-01-05 16:09
Typical.... once fixing one thing another thing breaks :P
I'll have an look at those.

**Comment by RedOhne** [comment] 2017-01-06 13:01
Hi, I've just checked the turning outside field with version 1.00018 with an N Series Tractor and Amazone Plough on the standard map. It's still running straight forward reaching end of the field.

**Comment by Satissis** [comment] 2017-01-08 22:59
Try 01.0023 or later and report back

**Comment by Satissis** [comment] 2017-01-09 20:37
@frm274 v01.0025 should fix your problems with the Q-Mark turn. Am still going to look into the chopper stuff :)

**Comment by RedOhne** [comment] 2017-01-09 21:08
Hi, The turns work fine now. At least for me. Thanks for the fixes. Best regards Tim

**Comment by frm274** [comment] 2017-01-11 18:14
Except the "chopper-problem",They seem to turn fone now ;)

**Comment by Satissis** [comment] 2017-01-11 19:25
@frm274 could you try reproduce this on a default map and send me the savegame and courses, so I have something to test it with? 
I have just made my own test, but could not reproduce it :S

**Comment by pops64** [comment] 2017-01-15 21:27
Maybe its related to this. [Log](http://pastebin.com/LcpJQuxW). Would like the save game to?
![farming simulator 17 1_15_2017 4_19_27 pm](https://cloud.githubusercontent.com/assets/10678220/21966273/a6af1d6c-db3e-11e6-99c8-1cc06af9e389.png)

**Comment by Satissis** [comment] 2017-01-21 18:03
Alright, I think I found the problem.
It have something to do with turning outside the field or if it's an combine/chopper (which overwrite the turn inside field to not allowing that)

I forgot to add an check in the wide turn for combines/choppers or if you disabled the turn inside field, which made it move the starting point further back than intended.

I have it fixed on my end right now, but I want to make some small optimizations as well + adding an option as @pops64 and me was talking about in #1634.

**Comment by Satissis** [comment] 2017-01-21 22:29
@frm274 and @pops64 try out v01.0042 or newer.
I have only tested it with the fertilizer, but they are the same turn maneuver and I believe they are related, so I think it will work for the chopper now as well :)

**Comment by MartinGrisotto** [comment] 2017-01-22 12:14
Sorry to bother, but it seems that your latest changes broke turning when using 2 harvesters. With turning on the field enabled, harvester goes straight instead of turning, if harvester is supposed to take the next second lane (regular lane change). With tourning on the field deactivated, everything works fine. Course without headlands.

**Comment by Satissis** [comment] 2017-01-22 12:18
@MartinGrisotto could you post an picture of this with debug 12 and 14 active

**Comment by MartinGrisotto** [comment] 2017-01-22 14:55
[https://www.youtube.com/watch?v=eMaXxYHaGOA](url)

I recorded 4mins video when i test all the possibilities

**Comment by frm274** [comment] 2017-01-23 15:50
Single Harvester on selfmade Course works now!

**Comment by Satissis** [comment] 2017-01-23 19:35
@MartinGrisotto it should be fixed in v01.0050.
Try it out and report back.

**Comment by pops64** [comment] 2017-01-24 22:23
The Grimme Tectron 415 does not drive forward just turns where it stops at the edge of field so it leaves a meter of fruit behind because the cutting head is about a meter ahead of the turning point of the vehicle get you a picture in a bit

**Comment by Satissis** [comment] 2017-01-28 14:32
@pops64 it should be fixed in v01.0054.
Try it out and report back.

Also any new problems with turn, that's not related to this issue, please make an new one for them.

**Comment by pops64** [comment] 2017-02-04 02:22
Can we close here have all issues in this issue been resolved?

**Comment by MartinGrisotto** [comment] 2017-02-04 09:00
I guess it's all in order at the moment :)

**Comment by pops64** [comment] 2017-02-04 16:58
I am going to close here. Has @Satissis said any new problems with the turn make an new issuse

**Closed by pops64** 2017-02-04 16:58 UTC
Labels: bug, waitingForUserAnswer
