### ISSUE TITLE
No recognition of placeable silo triggers

### ISSUE THREAD

**Issue by Banone** [Courseplay/courseplay#3295] opened 2019-02-24 11:29 UTC
When a courseplay driver arrives at a tipping point on a placeable silo it tips like when filling a fermenting silo for chaff and nothing comes in the silo.

**Comment by sootysax** [comment] 2019-02-24 17:16
why does no one post a log?  

https://github.com/Courseplay/courseplay/wiki

![download 1](https://user-images.githubusercontent.com/6591048/53302612-f5cc4700-382d-11e9-90e1-90a5194cbe61.jpeg)

**Comment by Banone** [comment] 2019-02-24 18:13
Here it is: https://gist.github.com/Banone/888674690bd24754961f320cf7ed4b9f

**Comment by ThomasGaertner** [comment] 2019-02-24 18:21
could you give me the save game and courses, did you try with v.94 ?

**Comment by Banone** [comment] 2019-02-24 18:30
I used the newest version like 30 minutes ago to reproduce the bug. Give me some minutes to give you the savegame.

**Comment by Banone** [comment] 2019-02-24 19:23
-I could not upload the savegame zip to gist so i uploaded it to google drive: 
 https://drive.google.com/open?id=1O829TXFDAtofSK5wVP3Xl9VQ25RV2rcZ
-The course name is 16_haeckseln_silo and i used the massey ferguson with the fendt tigo. The map is 
 volksbrunn v2.0 by biface: https://www.modhoster.de/mods/volksbrunn 
-Other mods you need for reproducing it like me: https://www.modhoster.de/mods/grosses-multi- 
 silo#description and the big x580 from giants(you can use any other too): https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=120415&title=fs2019

**Comment by jeremy3112** [comment] 2019-02-24 21:47
Same problem for me.
The coursplayer just pass on the placeable grain silo on mode 2.

**Comment by Hmmvee** [comment] 2019-02-25 20:32
I tried this with 2 different silos because I had the same problem.
I seems to depend on the silo.

Courseplay doesn't unload in this silo and only stops in front of it when you activate stop at end of course but the course doesn't end there.
![fsscreen_2019_02_25_20_40_55](https://user-images.githubusercontent.com/46241969/53366381-b7c14700-3943-11e9-926b-1f9acb9f40ca.png)

As you can see here sometimes it unloads the 2nd trailer but never the first one.
Also you can see at this picture that the tractor is not waiting long enough to go on so the tipper hooks into the wall and the weels are spinning until it is low enough to fit through the door.
![fsscreen_2019_02_25_20_28_08](https://user-images.githubusercontent.com/46241969/53366586-403fe780-3944-11e9-9311-c44401c7edee.png)

But it unloads at this silo.

![fsscreen_2019_02_25_21_22_02](https://user-images.githubusercontent.com/46241969/53366448-e9d2a900-3943-11e9-90bd-bb170a48a27c.png)

This first silo has a switch inside to activate the tipper trigger or the loading trigger.
Maybe that is an issue?

**Comment by Innallas** [comment] 2019-02-25 23:19
Mmmh i added a version for loading to work at husbandries & biogaz in issues.

For this one i'm trying to find a fix, for now nothing but with what you say it look like to be a trouble with distance to move forward at silos. So without touching the code >> try to put your silo-loading-waypoint JUST UNDER the pipe (the driver's cabin under the pipe), so he will move forward and be recognized i hope (also try to force a backward distance at loading in CP setting on path). I just finish a 6-8 hours modding i will try later a modification i did and all this.

**Comment by Innallas** [comment] 2019-02-26 14:38
It's really an obscur bug but i'm at 80% sure the problem comes from Triggers, i tried in order (save & reload game between tries):
- with felsbrun original silo and its working then when i add other silos > nothing work anymore !
- reload with both > nothing work > deleting the 2nd silo added (i even took the original silo and turn into mod).
- After reloading the 1st silo rework !! 
-Deleting all silos > adding a Stock silo > don't work anymore even after reload !

So the problem clearely look to come from triggers, they are probably saved somewhere else into game engine, i added all g_currentMission.storageSystem.loadingStations[table].loadTriggers as forcing driver to wait but nothing work.

**Comment by Innallas** [comment] 2019-02-26 16:34
Oh i got it ! IT'S WORKING ! But i also have very weird things, like an old saved route of CP don't work for loading, but all new routes are loading at my custom/placeable silos (the unloading work too but was never a trouble or it was for somes of you ? ).
For now i'm not yet sure of what is making it working , wait a bit i'm looking code and i'll publish the Fix.

**Comment by Banone** [comment] 2019-02-26 18:53
@Innallas 
This issue is about unloading... The courseplay driver doesn´t get the trigger and drives over it like when unloading in a fermenting silo and the whole load of the trailer is on the ground.

**Comment by Hmmvee** [comment] 2019-02-26 19:07
In my case he doesn't unload an passes the silo with full trailers.

![fsscreen_2019_02_25_20_46_32](https://user-images.githubusercontent.com/46241969/53439115-9faffd00-3a01-11e9-88a0-5d846de3b97c.png)

**Comment by evybart** [comment] 2019-02-26 20:46
Try to use a silo with the unloading point and loading not at the same spot

**Comment by Innallas** [comment] 2019-02-27 11:12
Ha , he was also talking about loading so i thought it was both. Anyway after lot of tries i'm pretty sure the problem is in "getexactloadorunloadtriggernode" because there are lot of similar troubles for loading.
But also unloading > i got a problem at an husbandry and i had to remake the route with an unloading waypoint with a better place.

**Comment by panther5** [comment] 2019-02-27 14:29
never had this problem with the placeable Grain Silo, but .94 solved my Hay Silo problem.

**Comment by Innallas** [comment] 2019-02-27 19:30
It's a problem with **distance** ! Calculation are made from tippers but we put the waypoint with the tractor ! So now after adding load/unload places i modified the calculation to remove some of the distance (you can't with a "shift" on route for this one). But i don't use 2 tippers but i think when i'll have a working version and give it to you it could work (or if you want modify in toolsManager.lua , near line 1162 you have an unloadDistance, i modify the trailerX & Z to be more close).

Do you see your tippers starting to unload > then the driver move on ?

**Comment by Innallas** [comment] 2019-02-27 22:17
Okay i got a working version when i disabled an AIDrive during unload (which should not be here), and also i think there s a 2nd problem : The tipper is a bit too long to start to unload (animation of movement of the tipper) so CP run too fast and say him to move forward because he s not tipping anymore for him (like he think it's finish but you didn't started). So after modifying this portion and reduced a bit the unloading distance it look to work all time for now, i keep testing and i will post tomorrow.

**Comment by Hmmvee** [comment] 2019-02-27 22:40
I have to check but it can be that the first trailer start to lift but stops immediately without unloading something.
To clarify the think with the 2 silos.
The trailers are filled by the combine and then the route to unload is passing the small silo with the unload issue and after that he is passing the bigger silo in the upper pictures where unloading works.

**Comment by Innallas** [comment] 2019-02-28 20:38
I think i got it, i bet you have a not so fast tipping opening animation ? I removed a condition about that who make them to leave like they believe they had finish the unload.

try to replace your "toolManager.lua" with this one to see ? i removed the condition and for now for me its working , just some problems on some custom MoDs because of models mismade.

**Comment by Innallas** [comment] 2019-03-01 12:00
Did you tried ? is it working now ? for me it's good, other problems comes from custom mod like a truck in 1 piece (without tipper > considered as a combine i think so he don't unload)

**Comment by Hmmvee** [comment] 2019-03-01 18:41
Sorry for the late answer I had no time to play.

I tested now your new file with fresh downloaded courseplay and your file added.
I see 2 effects at the moment.

At the bigger silo he is now tipping the first trailer and when it's finished the 2nd one.
I my eyes a more realistic work style. :-)

![fsscreen_2019_03_01_19_24_50](https://user-images.githubusercontent.com/46241969/53658374-de8bc000-3c58-11e9-97ad-6b98fe12c828.png)

![fsscreen_2019_03_01_19_25_02](https://user-images.githubusercontent.com/46241969/53658390-eba8af00-3c58-11e9-974a-b731ddf34a38.png)

At the first silo the 2nd trailer now gets unloaded but the first one only shortly is oppening the door directly closing the small gap again and is driving forward to unload the 2nd trailer.

Minimal open door:

![fsscreen_2019_03_01_19_31_09](https://user-images.githubusercontent.com/46241969/53658471-2d395a00-3c59-11e9-89a5-365e8c79b319.png)

2nd trailer unloading:

![fsscreen_2019_03_01_19_31_16](https://user-images.githubusercontent.com/46241969/53658503-3d513980-3c59-11e9-915a-9e8dddd93255.png)

I think you are on a good way but there is still an issue that stops the first trailer immediately after starting to lift before some material is going out.

**Comment by Innallas** [comment] 2019-03-02 02:46
Mmmh it look like to be a distance problem between tipper & unloading trigger, but the problem is that is dependant of your 2 tipper model & also the silo... 
Best thing to do 1st because modifying course play may cause other silo/tipper to dont work  > save the mod of your silo & rename with "_original" at end , then edit with giant editor the mod that you use > then make a bigger unload trigger (just need to rescale it to be more longer/larger, not too much height). Then try again ^^ if it work with 1 silo the problem with the other trigger is distance OR the tractor arrive too fast (so he get bad distance in fact XD).

**Comment by Hmmvee** [comment] 2019-03-02 14:59
Ok when I unstand you correctly it seems to be an issue with to small trigger areas in the mod silo in combination with the mod trailer?
I will try to use different trailers and test that.

**Comment by Hmmvee** [comment] 2019-03-03 11:25
Could it be that courseplay wants to bring both trailers at the same time on the silo trigger?
Is there a chance to tell courseplay to unload one trailer after the next?

In the 1st video both trailers a filled, the first starts to unload and stops directly.
In the 2nd video the first trailer is filled and the 2nd one empty. Now he unloads the first trailer correctly.

So i think this is a double trailer and to short trigger issue.
Is there a chance that courseplay recognises that and handles this like we would do in real.
Unload the first trailer, lower it to the end, drive forward and unload the 2nd trailer and lower this one while slowly drive forward?

https://www.dropbox.com/sh/h119u0xfiagtik1/AAANyohRV5SyEkOf3nC9vlYra?dl=0

**Comment by ThomasGaertner** [comment] 2019-03-03 16:51
please try v.112 or higher I reworked the tipping system. be aware that mode2 still uses the old dying code.
next step will be to transfer the street part of mode2 to this new system...

**Comment by Hmmvee** [comment] 2019-03-05 19:15
With todays version it seems that both trailer are lifting longer and the small vanilla ones in the video are starting to unload but stop again.

https://www.dropbox.com/sh/h119u0xfiagtik1/AAANyohRV5SyEkOf3nC9vlYra?dl=0

**Comment by Hmmvee** [comment] 2019-03-08 18:36
Short additional information:

1 full trailer works.
2 trailers with one empty and one full works.
2 full trailers see video above.

**Comment by ThomasGaertner** [comment] 2019-03-08 22:16
the problem is, that we have to brake as soon as we reach the unloading trigger , but till we stop completely, the trailer missed the trigger again. hmm no idea at the moment. stopping the tractor immediately looks horrible ...

**Comment by ThomasGaertner** [comment] 2019-03-08 22:19
you could try to record the course slower than 10km\h in this area, maybe that helps

**Comment by Hmmvee** [comment] 2019-03-12 19:55
I tried it today to record it with 2km/h in the silo area.
Courseplay automatically is increasing the speed back to the 10km/h after it's recognising the silo area.

Then i reduced the speed in the courseplay menue to 3km/h and it works now.
But I think this is not the best solution because you also have to reduce other areas where courseplay is using this parameter (Wendemanöver).

Is there a chance to split that to an extra parameter for unloading areas?

You can see that also at the attached video at the 2nd half of the video.

WIll be added when uploaded.

**Closed** 2019-04-17 20:14 UTC
Labels: postponed
