### ISSUE TITLE
Make proximity sensor to ignore his own vehicle to not block himself

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#5530] opened 2020-05-31 16:53 UTC
![image](https://user-images.githubusercontent.com/50051834/83357890-f149e480-a334-11ea-8887-02faf93e6288.png)

I'm not sure what debug channels you need.  This may be a map issue as it's my first time playing on this map and the first time seeing this issue.    It's the edited Felsbrunn from https://www.yesmods.com/fs19-mods/maps/european-maps/felsbrunn-edit-by-mc/

The harvester gets to the end row and reverses very slow, 1mph.  Then freezes for a long time before cutting the next row.  If you "tap" the harvester with another tractor to kind of knock him off course, he continues as normal and cuts the next row.  
[log.txt](https://github.com/Courseplay/courseplay/files/4708033/log.txt)

**Comment by Tensuko** [comment] 2020-05-31 19:44
Clean Mods Folder.
Many Errors, and a LUA Error from another Mod.
2020-05-31 11:42 Error: Running LUA method 'update'.
2020-05-31 11:42 C:/Users/Andrew/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleExplorer/VehicleSort.lua:1907: attempt to index a nil value

**Comment by enderwiggin07** [comment] 2020-05-31 21:26
[log.txt](https://github.com/Courseplay/courseplay/files/4708519/log.txt)

I see something is complaining about key bindings to the game pad a lot but I don't think it's related

**Comment by Tensuko** [comment] 2020-06-01 06:04
Load mod: FS15_JDDB120 (Version: 1.2.1.0 beta) (Hash: 0593b68f096ccc9ef93cab112fa0b82f)
Error: Unsupported mod description version in mod FS15_JDDB120

ForgottenPlants also does not belong into mods Folder.

No Errors from CP. What about Turn speed in CP HUD ?

**Comment by Tensuko** [comment] 2020-06-01 07:45
Also can't reproduce this, guess a Modissue somewhere.

**Comment by Tensuko** [comment] 2020-06-11 10:32
Closed due to inactivity, I am sure this is some kind of Mod Conflict.

**Comment by Tensuko** [comment] 2020-06-18 18:34
Found the Problem:
![fsScreen_2020_06_18_20_31_37](https://user-images.githubusercontent.com/27344744/85058713-c835aa80-b1a2-11ea-8e59-bdd9a56da745.png)
Log say this while reverse with this Harvester:
2020-06-18 20:33 :54 [dbg14 lp221600] 330 (#1): proximity: d = 1.2 (13 %), speed = 2.5

**Comment by Tensuko** [comment] 2020-12-01 05:57
Should be fixed.

**Closed by Tensuko** 2020-12-01 05:57 UTC
Labels: enhancement
