### ISSUE TITLE
Q: Will CP survive?

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#6038] opened 2020-09-06 20:06 UTC
CP was and is my all time favourite FS mod but with 219 issues: will it survive?
Maybe it is time for a status talk.

**Comment by leo32128fs** [comment] 2020-09-06 21:08
it can even survive, the problem is that almost all players who use CP want it to do all the farm work, that is, they don’t play farmig watch CP play, with me it was just a problem I found and even so it doesn’t affect the game because the problem is small and appears only in mp and does not interfere in the gameplay of the game

**Comment by Tensuko** [comment] 2020-09-07 04:43
What is this kind of stupid question ?
What keeps CP alive ? Simple, the mood of the dev...
We don't need a status talk here, we do what we want to do and thats it....

**Comment by pvaiko** [comment] 2020-09-10 12:11
@AgroWillem let's restart this conversation: what exactly do you mean by a 'status talk'?

**Comment by Mike1977** [comment] 2020-09-10 17:04
> players who use CP want to make CP do all the work on the farm, that is, they don’t play farmig watching CP play

Yes, that is actually true... CP makes it possible to almost automate all the things you can do in the game. And as you can see, thos "automation games" ala factorio satisfactory ect have a lot of fans. Without CP and Autodrive, i wouldnt even play FarmingSimulator. Because its a dull game after a while. With all the automation you completely shift your focus away from farming to micromanaging all your vehicles and stuff. You still do farming, but its more about managing everything, instead of driving around the field for 40 minutes and falling asleep all the time. 
I know its not just me, because i personally know 4 people who play this game and all of them won't play it, if CP and Autodrive wouln't be around.

So this mod better does survive, or FS will loose a pretty large part of the playerbase... 

@devs: its a shame Giants doesnt compensate you for your work. I would have stopped playing long ago, and would have never bought a new game or dlc if courseplay would not have been available. They owe you quite a bit and i'm sure they even know it.

**Comment by AgroWillem** [comment] 2020-09-10 17:22
Hi Peter,

Thanks for your reply.
I was a kind of disappointed after the reaction of the post you removed. But leave that.
I always admired the work op the devs of CP and my post was morely of commitment because the lot of work the devs of CP do.
I was not offending anyone but as seen the list of issues, i wondered if CP will be done at last?
The status i asked of was merely a question about were are we now, what are the bottlenecks, is there enough support from Giants?

And i quote Mike1997 all. I agree all. No CP, no FS for me. So make it 5.

**Comment by pvaiko** [comment] 2020-09-10 19:12
@Mike1977 if Giants approves a mod for their website and for in-game downloading, devs get some compensation based on the downloads (last time CP was official we had over 500,000 downloads) but the amount of that compensation compared to my paycheck from my day job was negligible (We haven't attempted to put CP6 on ModHub yet as we did not get to the level of stability we wanted to)

@AgroWillem Giant support is working much better now, they are responsive and help us out, they even published a debugger earlier this year which makes our life a lot easier. The main bottleneck is, as always is the developer's time, especially that there's now only two active devs and we have families and jobs to take care of.

We could use a lot of help, not just development but also documentation. Much user frustration is caused by complex functions not documented sufficiently, from time to time someone shows up and offers working on the manual but then we never hear from them again...

As to where CP is going, we don't know :) I was planning to launch a survey to find out what the community thinks are the worst pain points, but was too busy IRL. At some point we were also considering releasing a Courseplay Light with only the stable functions enabled, that may still be an option.

**Comment by Misamangame** [comment] 2020-09-11 15:24
I think more crucial question is will FS survive without CP? I personally bought FS 19 after Seasons and CP mods were released and only for ability to harvest cotton and sugar cane which I haven't tested yet:). Otherwise FS is totally unfinished game (like unfortunately most of the games in 21st century) and depends on modders who keep it in playable state. I think many issues here is because people just don't know how to setup courses properly and using modded vehicles which are crap. Which goes back to @pvaiko point about manual. Personally I found one guy on YT and he made great videos about using CP and AD especially after Mode 2 release, which helped me a lot even when I later saw "How it looked on our testing server" from Tensuko, but that channel has only few views so now wonder almost everyday here is an issue which is about not knowing properly CP functions. But if I compare CP 5 when I ran 15 combines on my 1100ha field with 20+ unloading auger tractors it was a nightmare, CP 6 did a massive step forward since then and when @pvaiko will solve his selfraised issues with traffic control it will be almost job done as more unloaders will be usable :). Basically I like to watch machines at work and more of them in motion which works without faults, better:) And it is possible only because of CP and guys standing behind it.  So back to main question Will CP survive? DEFINITELY even in current state which is far from finished it is better then nothing and there is no replacement.  So is that DONATE button still works? Just move him on top of the page :) Keep up the good work guys

**Comment by Mike1977** [comment] 2020-09-11 18:25
> What does CP have to survive ?

I can't speak for the OP, but i'm a little concerned about the survival of the mod, because usually around this time the next version of FS would be released and for fs 19 there isnt even a full release of courseplay yet. The Mod is still under heavy reconstruction and if a new FS would be released, you could already start all over again.
If i where a dev, i'd probably given up already. 
I was once working on a popular "Mod" for PHPBB 10 years ago. And even though i am not a scripter, i was working on the style implementation for this mod, and wrote config files and the documentation for users on how to convert specific styles to work with this mod. It was like a full time job without getting paid. It took away my whole free time, and i even answered support questions during my launchbreak on my regular job. 
So i completely understand how time and energy consuming this is and i can't even imagine what i would do if i where in your shoes.

Having that said, i really have an issue with me having to use two mods with two guis and different keybindings for the same job.
Autodrive is way supperior on the streets and in my view even on the whole track managing point, while doing little to no fieldwork, wich is the strength of courseplay. So i always have to use both mods together, wich is a pain in the ass and a clutter on the screen. 
Im always dreaming of you guys merging your projects wich would be great both on the field and outside of them. 
You would have less work (per team), less support, more devs working on the same project and we would have a seamlessly working mod

**Comment by pvaiko** [comment] 2020-09-11 19:52
> if a new FS would be released, you could already start all over again.

Let me clarify this, 80% of the refactoring we are doing on CP is **not** due to FS19, it was our decision as CP evolved over so many years the code base became an unmaintainable collection of bad programming practices, including some of my contributions :). 

As for AutoDrive, we've worked together in the past and there sure is room for more collaboration, all I can do is encourage all CP and AD users to come up with ideas on how the two mods could work together more seamlessly.

**Comment by Mike1977** [comment] 2020-09-11 21:50
But if i remember correctly, it took you quite a while because of the changes in the new version of the game, to make courseplay barely work again. Now since probably noone knows what comes next, maybe most of what you've done to improve the mod, will need to be redone when the next fs comes around. Lets hope not, and i don't want to sound too negative, but i know that i would never buy the next version of the game if you would anounce eol for this mod. Im glad you said you won't though ;)

**Comment by pvaiko** [comment] 2020-09-11 21:56
@Mike1977 sure, FS19 broke a lot of things and for quite a while Giants did not publish the new API documentation, so in the beginning it was a struggle. And this of course can happen with the next FS version too. But I believe CP is a better shape now and we can handle that more efficiently.

**Comment by Misamangame** [comment] 2020-09-11 22:26
If new version of FS will be released and will not have mods like CP or Seasons built-in in base game it will be crushed by C&C, which is for realism far more superior game then FS. Yes they lack number of vehicles/implements but it is only advantage FS have now. So if developers are not blind (and they are) they should offer permamenent job to guys doing these mods which making their game playable for masses.

**Comment by Tensuko** [comment] 2020-09-12 06:03
C&C is far away of being good.
The Graphics doesnt even look nice.
It looks more like a technical demo for the ground and pathfinder and some ozher smal stuff.

**Comment by rohne83** [comment] 2020-09-13 10:07
> I can't speak for the OP, but i'm a little concerned about the survival of the mod, because usually around this time the next version of FS would be released and for fs 19 there isnt even a full release of courseplay yet. The Mod is still under heavy reconstruction and if a new FS would be released, you could already start all over again.

That raises a question for me: once the next FS is released, which shouldn't be too far from now, what are the plans for the older versions, especially v6? Will there still come updates from time to time (for sure not as frequently as currently, but maybe development on v7 sometimes brings some changes which can easily be merged into older versions as well), or are you going to put all your effort just on v7?

**Comment by pvaiko** [comment] 2020-09-13 12:24
@rohne83 can't tell, we'll see what changes in FS. And, as always, how many active developers will CP have a that time. Maybe someone who needs it, creates a fork for v6. Remember, we are open source under GPL, anyone can use the entire CP code for whatever purpose they want.

**Comment by rohne83** [comment] 2020-09-13 21:13
Well, true. Atm it's not really relevant since the next FS has got postponed. So seems there will still have to be at least a year to go with v6.
Would say, the biggest topic might be the pathfinder avoiding (or maybe self-resolving) crashes on the field, at least those with combines involved. Several open issues seem to be related to just that. Apart from that I'd say it's running really stable already, at least for me.

**Comment by pvaiko** [comment] 2020-09-17 12:12
>  the biggest topic might be the pathfinder avoiding (or maybe self-resolving) crashes on the field, at least those with combines involved

I know, have those on my taskboard.

**Closed** 2020-11-25 10:42 UTC
