### ISSUE TITLE
No loading on farmsilo with courseplay

### ISSUE THREAD

**Issue by FreelancerTrent** [Courseplay/courseplay#5156] opened 2020-04-08 20:16 UTC
Hello togehter,

I play on the NF Marsch 4fach oG and I use the Fed-Mods-Multifruit-silo. When I try to fill my trailer on the starting point, the vehicle with the trailer drives to the start point and waits and waits and no filling is started.

When I jump into the traktor or truck then the filling begins and the saved course will be driven.

For the first I don't know wich information you need. Please let me know this and I will send yo the information are needed.

Thanks for your support.

Daniel

**Comment by FreelancerTrent** [comment] 2020-04-08 20:24
The log contains one error.

[log.txt](https://github.com/Courseplay/courseplay/files/4452636/log.txt)

**Comment by Tensuko** [comment] 2020-04-09 05:59
There seems to be something wrong with your saved course...
2020-04-08 21:44 Error: Sharing violation on file 'C:/Users/danie/Documents/My Games/FarmingSimulator2019/CoursePlay_Courses/FS19_NF_Marsch_4fach_oG.SampleModMap/courseManager.xml' ... perhaps open in another program?

Is this SP or MP ?

I could also need a Screenshot of how your Course look like at the Silo and logfile with debugchannel 1 and 2 active, then let the tractor start at any waypoint before the silo and let it get to the silo.

**Comment by FreelancerTrent** [comment] 2020-04-09 19:40
I share the courses via dropbox with my koop-partner. Maybe the course was uploaded at the same time when I used it.

This was in MP, but also tested in SP. Logs from MP.

If you need any further information, let me know.

![fsScreen_2020_04_09_21_23_06](https://user-images.githubusercontent.com/18641585/78932770-66710a00-7aa8-11ea-9cfe-a42a5b47eb53.png)

[log_standing outside.txt](https://github.com/Courseplay/courseplay/files/4458236/log_standing.outside.txt)
![fsScreen_2020_04_09_21_36_24](https://user-images.githubusercontent.com/18641585/78933840-3591d480-7aaa-11ea-88d5-4610166cc546.png)
[log_sitting in the tractor.txt](https://github.com/Courseplay/courseplay/files/4458259/log_sitting.in.the.tractor.txt)

**Comment by Tensuko** [comment] 2020-04-09 21:47
Duplicate of #4943
MP related ... Closed...

**Closed by Tensuko** 2020-04-09 21:47 UTC
Labels: More Information Required, waiting for logfile

**Comment by FreelancerTrent** [comment] 2020-04-10 15:29
When I removed the mods "manure system"(and the mods  and "fillLevelLimiter" courseplay works.
