### ISSUE TITLE
Warning (script): Unknown entity id 354411 in method 'getName'. (triggers.lua:486)

### ISSUE THREAD

**Issue by Ntone107** [Courseplay/courseplay#3315] opened 2019-02-26 21:20 UTC
Have 2 separate combinaties (Combine + tractor and trailer - Silage harvester + tractor and trailer) both with same issue. Both combinations run in "Combi" mode, but after planning the course and activiting it, there is a large orange arrow that appears, and nothing happens. Tractor is blocked, doesn't move. I have to fire the helper (using key H) to get tractor "unstuck". 

My first Combi-course works fine. Problem exists with course 2 & 3.

Snippet from logfile: 
2019-02-26 22:03 Warning (script): Unknown entity id 354411 in method 'getName'.
2019-02-26 22:03 LUA call stack:
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/triggers.lua (486) : getName
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/start_stop.lua (398) : updateAllTriggers
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/input.lua (277) : start
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/input.lua (208) : executeFunction
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/input.lua (194) : setCourseplayFunc
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/input.lua (70) : handleMouseClick
2019-02-26 22:03   =C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/CpManager.lua (351) : onMouseEvent
2019-02-26 22:03   dataS/scripts/BaseMission.lua (1413) : mouseEvent
2019-02-26 22:03   dataS/scripts/FSBaseMission.lua (1940) : mouseEvent
2019-02-26 22:03   dataS/scripts/main.lua (1732) : mouseEvent
2019-02-26 22:03 Error: Running LUA method 'mouseEvent'.
2019-02-26 22:03 C:/Users/ntone/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/triggers.lua:486: bad argument #1 to 'tostring' (value expected)

**Comment by pvaiko** [comment] 2019-02-26 23:35
duplicate of #3297

**Comment by donnti** [comment] 2019-02-27 04:20
I had to revert back to *92 because all of these errors started after that. The first version I tried after 92 was 94. (06.01.00093:tip trigger raycast direction is now related to the surface) Might be the culprit as 94 was a fix for the wages (06.01.00094:fixed wages).

**Comment by ThomasGaertner** [comment] 2019-02-27 22:56
@donnti : this part of the script is 2 years old so no change has been done since then . it must be a map issue : the trigger of the bunkersilo doesnt have a name
@Ntone107 . would be nice if you would have written, on which map you have this issue

I close here because of duplicate

**Closed by ThomasGaertner** 2019-02-27 22:56 UTC
Labels: duplicate
