### ISSUE TITLE
Course Generator - un-necessary tracks

### ISSUE THREAD

**Issue by abehnke** [Courseplay/courseplay#2571] opened 2018-02-08 19:51 UTC
The Course Generator from vehicle position seems to generate un-necessary tracks when transitioning from the headers to the up/down rows.  I have an edge path defined over field 22 on Sosnovka.  I want 2 headers.  The generated course after the inner header lane drives west over the already done header, makes a very sharp turn and goes east close to the row it just did.  I have seen this on quite a few generated courses and some waste time and material spraying over already done parts.  Why does it not go straight from the end of the inner header into the up/down rows? That would seem to be simplier. 

Using CP5 v5.02.00056 on Sosnovka map.

![fsscreen_2018_02_07_17_32_15](https://user-images.githubusercontent.com/3346683/35994778-763d2ef2-0cdf-11e8-99bc-22821177c7ba.png)

**Comment by pvajko** [comment] 2018-02-08 21:20
We have several different topics here.

First of all it can't just go straight to the up/down rows as then it would miss a part of the first row, in your example the first few meters on the the north east. It could theoretically back up instead of continuing straight on the headland but that's more difficult to implement.

It should however turn off everything while driving up on the headland to the end of the row, if it does not than it is a bug.

Now, in this example, the first (northernmost) row is really close to the headland and I understand that it is a waste of material and time, but the problem is that without that row you would not cover the field, there'd be an uncovered gap between the headland and the last row. This is most noticeable with very wide implements. This should however happen only on one side of the field, the other (last) row should be width/2 from the headland. It is hard to see on this screenshot if that's the case.

Anyway, if you think there's bug, could you post the cpFields.xml as described here: https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions

**Comment by abehnke** [comment] 2018-02-09 19:36
Thanks for looking into this. Yes, the tool is raised while driving one of the rows.  I understand there will be overlap when the field width is not a multiple of the tool width.

I decided to show the problem possibly more clearly.  I started a new game using Goldcrest with only Courseplay mod enabled.  I went to field 12 and generated a course with 2 headland for a 9m tool.  

My first image shows the view from the start point.  The course switches from the outer header to the innner header and when the inner header completes - the tool is lifted as the sower passes over the inner header to the far (east) end.

The 2nd image shows the east end action, the tool will be lowered around the sharp turn, sowing will overlay 1/2 of the prior inner header.

The 3rd image shows the north side, note that the inner header overlaps the final up/down row. 

The result is two overlaps when only one was expected. (Either at the start of the up/down or at the end of the up/down.)

Note: in my images the tractor is not actually driving the course, I just positioned it to get images.  I did drive parts of the course earlier to test what was happening.

Tell me if you need any more info.  Thanks for working on the course generation.  I really like that the turns for the up/down are now indented away from center of the headland course. 

![one](https://user-images.githubusercontent.com/3346683/36046268-5625e70e-0da6-11e8-9f08-a5e0818bde30.png)

![two](https://user-images.githubusercontent.com/3346683/36046277-601a561e-0da6-11e8-98d5-0c915fc8c897.png)

![three](https://user-images.githubusercontent.com/3346683/36046287-69efafe0-0da6-11e8-8f2d-0a2aef452e77.png)

[log.txt](https://github.com/Courseplay/courseplay/files/1712195/log.txt)



[cpFields.xml.txt](https://github.com/Courseplay/courseplay/files/1712196/cpFields.xml.txt)

**Comment by pvajko** [comment] 2018-02-09 20:11
Yes, you are right, that's a bug, there shouldn't be an overlap on both sides. I'll fix it.

**Comment by pvajko** [comment] 2018-02-11 13:25
This should now be fixed in 5.02.00057, please reopen if that's not the case.

**Closed by pvajko** 2018-02-11 13:25 UTC
Labels: bug
