### ISSUE TITLE
Mode 2 tractor not following chopper

### ISSUE THREAD

**Issue by Sparky5237** [Courseplay/courseplay#7396] opened 2021-08-03 12:41 UTC
The issue im having is the tractor, no matter its start location, will pull up to the exact rear of the chopper, but not within range to collect chaff, tried manually adjusting offset and nothing seemed to help or change its target follow point.

![20210802212417_1](https://user-images.githubusercontent.com/88356566/128015987-c4a71182-069a-47cd-a892-41e20f326fd9.jpg)

it worked for a very short time until it reached a turn and completely stopped again, nothing was changed it just randomly started and randomly stopped

![20210802213322_1](https://user-images.githubusercontent.com/88356566/128015993-b8f60c66-b103-44ec-a959-292705f4a10b.jpg)

Im very new here so if i missed anything please let me know and ill be sure to give more info.

and heres my log

https://gist.github.com/Sparky5237/af62592c0118352c6773a1be804636fb

**Comment by envikowaty** [comment] 2021-08-03 12:54
The problem is in chopper, the range of the pipe is to small, try with class

**Comment by Tensuko** [comment] 2021-08-03 12:58
> 
> 
> The problem is in chopper, the range of the pipe is to small, try with class

We do extend the range of the chopper, but that works only for the smal pipe.

@Sparky5237 
change the pipe to the smal one and try it again.

It is in the GIANTS Code, there are some axes that got limits and we change those values, but as I said, only for smal pipe, else we would need to take more different combinations into account.

**Comment by Sparky5237** [comment] 2021-08-03 19:04
Now that is working, however. Now the reason that caused me to update from 6.4.0, it still doesnt seem to be enough. I didnt try it with the claas harvester but rather the shorter pipe. If its this harvester thats bugged i have no problem trying a different one, just need to add some funds to do so.

![20210803145907_1](https://user-images.githubusercontent.com/88356566/128071062-da3e1f9d-c98a-4107-94e4-445b1e98f058.jpg)

The tractor hangs in a turn maneuver. It will either, Run into the back of the chopper, getting stuck on the bumper until it stops at the end of the row, or be too far away to engage the chopper at the beginning of the row, i had both happen in the span of one row. Its almost like it wont go back far enough to swing to be back in line of the chopper when it turns around.

**Comment by Bobster82** [comment] 2021-08-04 07:37
I know the new holland chopper works perfect with john deere's 7R/krone trailer ... maybe its a mod thing. As tensuko already said, they modify the gians choppers (so I dont know if that mod works the same)
So just for your info that the standard machines work ;)

**Comment by Tensuko** [comment] 2021-08-04 11:03
If this is the JD Chopper from Ifkos JD Pack, it should work just fine.
Also there might be a tweak on the way in PR #7343
But I don't know how far @MddMBorg is if he can get it working.

For now, try another tractor.
I would need more debug informations (channel 2 and 11 and screenshot with F5 active maybe). For that, update to 6.4.0.5 from our release side.

**Comment by Sparky5237** [comment] 2021-08-05 03:50
With the Claas Jaguar 960, it appears everything is working as expected. Odd that the JD cutter is throwing issues, I turned channel 2, 11 and F5 on and it looks like its pathing how its supposed to, even backing up when it needs too, with the occasional tap i did notice as it gets into position next to the cutter, but nonetheless it does work.. Thank you guys so much for your quick responses.

**Comment by garo73** [comment] 2021-08-09 08:38
The problem is the "trailer trigger" on JD i3d... it is too short and does not "hear" the trailer on the back of the forage harvester... i've change it with GEeditor and some xml value for the long pipe and now it work!

**Comment by Tensuko** [comment] 2021-08-09 15:01
2 Values are responsible for the throw distance:
`<dischargeNode node="pipeRaycastNode" emptySpeed="1000" fillUnitIndex="1" **maxDistance="40"** stopDischargeOnEmpty="false">`

and

`maxRotationLimits`

Wich I don't find in my example Chopper, but that values does exist for the animations axes if the pipe.
Since we only modify one position, the smal pipe is the better choice.
GIANTS know that and I don't know if they find a better way to increase the discharge, since this is not only a CP Error.
In Reallive, Choppers are easy able to throw far enough into a trailer when the tractor with trailer is driving behind and that is not possible without CP...

**Comment by garo73** [comment] 2021-08-10 08:08
> 
> 
> 2 Values are responsible for the throw distance:
> `<dischargeNode node="pipeRaycastNode" emptySpeed="1000" fillUnitIndex="1" **maxDistance="40"** stopDischargeOnEmpty="false">`
> 
> and
> 
> `maxRotationLimits`

I'm sorry to correct you but touching those values ​​in the xml does not correct the error, I tried it too, you have to modify the area of ​​the trailer trigger with GEeditor otherwise the forage harvester does not hear the wagon and, in the xml of the long tube, change:

< pipeNode node = "pipeArm02L" rotationSpeeds = "80 0 0" autoAimXRotation = "true" minRotationLimits = "45 - -" maxRotationLimits = "80 - -" bendingRegulation = "0.15">
                        <state1 rotation = "80 0 0" />
                        <state2 rotation = "80 0 0" />

to

<pipeNode node = "pipeArm02L" rotationSpeeds = "80 0 0" autoAimXRotation = "true" minRotationLimits = "45 - -" maxRotationLimits = "80 - -" bendingRegulation = " 0.15 ">
                        <state1 rotation = "90 0 0" />
                        <state2 rotation = "105 0 0" />

**Comment by garo73** [comment] 2021-08-10 08:16
I'm sorry to correct you but touching those values ​​in the xml does not correct the error, I tried it too, you have to modify the area of ​​the trailer trigger (in forage harvester i3d!) with GEeditor otherwise the forage harvester does not hear the wagon and, in the xml of the long tube, change: < pipeNode node = "pipeArm02L" rotationSpeeds = "80 0 0" autoAimXRotation = "true" minRotationLimits = "45 - -" maxRotationLimits = "80 - -" bendingRegulation = "0.15"><state1 rotation = "80 0 0" /><state2 rotation = "80 0 0" /> to <pipeNode node = "pipeArm02L" rotationSpeeds = "80 0 0" autoAimXRotation = "true" minRotationLimits = "45 - -" maxRotationLimits = "80 - -" bendingRegulation = " 0.15 "><state1 rotation = "90 0 0" /><state2 rotation = "105 0 0" />

**Comment by garo73** [comment] 2021-08-10 08:18
> 

> 
> 
> 2 Values are responsible for the throw distance:
> `<dischargeNode node="pipeRaycastNode" emptySpeed="1000" fillUnitIndex="1" **maxDistance="40"** stopDischargeOnEmpty="false">`
> 
> and
> 
> `maxRotationLimits`

I'm sorry to correct you but touching those values ​​in the xml does not correct the error, I tried it too, you have to modify the area of ​​the trailer trigger (in forage harvester i3d!) with GEeditor otherwise the forage harvester does not hear the wagon and, in the xml of the long tube, change:

**Comment by garo73** [comment] 2021-08-10 08:19
< pipeNode node = "pipeArm02L" rotationSpeeds = "80 0 0" autoAimXRotation = "true" minRotationLimits = "45 - -" maxRotationLimits = "80 - -" bendingRegulation = "0.15"><state1 rotation = "80 0 0" /><state2 rotation = "80 0 0" />

to

**Comment by garo73** [comment] 2021-08-10 08:19
<pipeNode node = "pipeArm02L" rotationSpeeds = "80 0 0" autoAimXRotation = "true" minRotationLimits = "45 - -" maxRotationLimits = "80 - -" bendingRegulation = " 0.15 "><state1 rotation = "90 0 0" /><state2 rotation = "105 0 0" />

**Comment by garo73** [comment] 2021-08-10 08:33
1

**Comment by Tensuko** [comment] 2021-08-10 12:47
We have our informations from GIANTS, so we do it like that and it works fine for Vanilla and DLC Chopper.
I also got it to work with the JD from Ifkos pack, so its fine for us.

We change the `maxRotationLimits = "80 - -"` to `maxRotationLimits = "- - -"` with the maxDistance of 40 and its fine.

**Comment by Tensuko** [comment] 2021-08-10 12:48
In the end, not a CP problem, so closing this.

**Closed by Tensuko** 2021-08-10 12:48 UTC
Labels: waitingForUserAnswer
