### ISSUE TITLE
FS crash

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3169] opened 2019-02-08 21:31 UTC
These setting caused Fs to crash (#49)

![image](https://user-images.githubusercontent.com/30005040/52507226-cd670a80-2be8-11e9-824e-11f0148565bc.png)

**Comment by sootysax** [comment] 2019-02-08 21:51
what version of FS19 are you running?

**Comment by alpha117** [comment] 2019-02-08 22:27
latest BETA released today V1.3

Also tried it the 'old way' and FS crashed here

![image](https://user-images.githubusercontent.com/30005040/52509615-c04e1980-2bf0-11e9-8e13-7618fda82766.png)

**Comment by alpha117** [comment] 2019-02-08 22:30
oops

**Comment by alpha117** [comment] 2019-02-08 22:39
just went back to #45 and still no go; so Giants must have changed something in this latest BETA that has 'broken' CP currently. I'm sure you guys will get it sorted very quickly

Thanks

**Comment by pvajko** [comment] 2019-02-08 23:02
@alpha117 do you think it would help if you described what you were doing when it crashed and (God forbid) attached a log?

**Comment by alpha117** [comment] 2019-02-08 23:14
[log.txt](https://github.com/Courseplay/courseplay/files/2847226/log.txt)

**Comment by alpha117** [comment] 2019-02-08 23:15
Sorry,
Just generated a course, then press drive course and then that's it..CP stops responding and FS hangs
[log.txt](https://github.com/Courseplay/courseplay/files/2847228/log.txt)

**Comment by alpha117** [comment] 2019-02-08 23:31
Just tried #49 on a map that is NOT from MOD hub (Fenton Forest) and CP works just fine, no issues

**Comment by pvajko** [comment] 2019-02-08 23:52
Duplicate of #3165

**Closed** 2019-02-09 07:38 UTC
