### ISSUE TITLE
Grain transport mode gives warning text "farm silo dosen't have the selected fill type".

### ISSUE THREAD

**Issue by antonfallman** [Courseplay/courseplay#5017] opened 2020-03-06 22:18 UTC
I have tried setting up a sell grain course and when i start the course the tractor stopps under the load pipe from the silo it pops up a text were it says the "farm silo dosen't have the selected fill type" when i selected soy beans on the tractor. 
![soybeans for tractor](https://user-images.githubusercontent.com/61890031/76126759-45784d80-6000-11ea-982b-4e6690c0563c.png)

Even thoe the silo has soybeans in it. 
![soybeans](https://user-images.githubusercontent.com/61890031/76126763-490bd480-6000-11ea-88db-61a8b7599800.png)

The text goes away if i set it to forage, straw, hay, chaff, wood chips, silage, grass, 
![forage for tractor](https://user-images.githubusercontent.com/61890031/76126753-41e4c680-6000-11ea-90b2-e26983b51251.png)

Can anybody help?

**Comment by Tensuko** [comment] 2020-03-06 22:49
logfile with debugchannel 1 and 2 active.

**Comment by Tensuko** [comment] 2020-03-06 22:57
Can't reproduce.
![fsScreen_2020_03_06_23_56_27](https://user-images.githubusercontent.com/27344744/76128962-2d0b3180-6006-11ea-9bdb-9f475431a19a.png)

Also when make screenshots pls turn on the waypoints and not the debugpoints (only when we ask for this).

**Comment by antonfallman** [comment] 2020-03-06 22:59
can't reproduce? what do you mean?

**Comment by Tensuko** [comment] 2020-03-06 23:01
That I can't reproduce this Error, it does work.
And I need a logfile from you to see if there is any Error msg or Information from debugchannel 1 and 2.

**Comment by antonfallman** [comment] 2020-03-06 23:08
alright how do i get the logfiles? i am renting a server so is this it? 
![logfiles](https://user-images.githubusercontent.com/61890031/76129436-b4a57000-6007-11ea-915a-b161e518bcf7.png)

**Comment by antonfallman** [comment] 2020-03-06 23:10
i can give you screenshots of the whole logfile, i first just need to know where to get them.

**Comment by Tensuko** [comment] 2020-03-06 23:11
And there we got the missing information: MP Dediserver.
Duplicate of #4943

Closed.

**Closed by Tensuko** 2020-03-06 23:11 UTC
Labels: can't reproduce, waiting for logfile
