### ISSUE TITLE
unloader starts to swerve the target combine, when turn radius is to smal

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6612] opened 2021-01-03 19:06 UTC
![20210103125852_1](https://user-images.githubusercontent.com/5993529/103486522-1b302180-4dc4-11eb-86d6-62657e63515c.jpg)
![20210103125854_1](https://user-images.githubusercontent.com/5993529/103486525-1c614e80-4dc4-11eb-9c00-41cb388ec9f2.jpg)
![20210103125855_1](https://user-images.githubusercontent.com/5993529/103486526-1cf9e500-4dc4-11eb-8d14-19b8fdd3ccc1.jpg)
![20210103125855_2](https://user-images.githubusercontent.com/5993529/103486527-1d927b80-4dc4-11eb-831b-16c01503f7b4.jpg)
![20210103125858_1](https://user-images.githubusercontent.com/5993529/103486528-1e2b1200-4dc4-11eb-8882-242a0e8cd7bb.jpg)
![20210103125902_1](https://user-images.githubusercontent.com/5993529/103486530-1ec3a880-4dc4-11eb-90c1-16882497b6b0.jpg)
![20210103125905_1](https://user-images.githubusercontent.com/5993529/103486534-1f5c3f00-4dc4-11eb-84d2-150182b89b15.jpg)
![20210103125910_1](https://user-images.githubusercontent.com/5993529/103486536-1ff4d580-4dc4-11eb-87e2-c60b8295f2cf.jpg)

so, essentially, as the photos show, the pathfinder initially puts it under the pipe... but then the pathfinder moves and expands the course to where the overloader trys to run into the combine.

[log.txt](https://github.com/Courseplay/courseplay/files/5762096/log.txt)

**Comment by NicholasSoares** [comment] 2021-01-03 21:42
same happened here a fell days ago only fixed when i sell and buy the tractor again (same everything in matters of configuration) 
![fsScreen_2020_12_29_21_21_07](https://user-images.githubusercontent.com/42093631/103489442-585fd800-4df3-11eb-92ae-7a7700f7f6f3.png)

**Comment by Tensuko** [comment] 2021-01-04 00:51
Thats a rare case when drive like this behind the combine, hopefully with .00020 it should work better and this is not a overloader problem.

**Comment by Commissar0617** [comment] 2021-01-04 02:19
right. i figured it was some sort of occasional issue with path-finding. ill see about reproducing on my next harvest. the funny thing is, i even tried increasing the turn radius in the settings and it had no apparent effect.

**Comment by Tensuko** [comment] 2021-01-04 10:10
It must be big enough.
I know exactly whats happening here and why it is happening.
Anyway, Try Version .00020

**Comment by Commissar0617** [comment] 2021-01-09 06:31
nope no fix. 
![20210109003009_1](https://user-images.githubusercontent.com/5993529/104085032-f5ff4100-5211-11eb-84ac-b93840e3d409.jpg)

**Comment by Commissar0617** [comment] 2021-01-09 06:49
[log.txt](https://github.com/Courseplay/courseplay/files/5790258/log.txt)
here's the latest log. i didn't ahve debug on the whole time, but ill get more tommorow

**Comment by NicholasSoares** [comment] 2021-01-09 07:01
![fsScreen_2021_01_09_01_00_02](https://user-images.githubusercontent.com/42093631/104085433-29e85f80-522e-11eb-9498-83a7cd8ac29f.png)
Happening here in special if i set max loading below 100% on combine, also i do notice that a lot of my issues happens inside of the route temporary turn section waypoints, last images just for ilustration of what i talking about 
![fsScreen_2021_01_08_03_09_33](https://user-images.githubusercontent.com/42093631/104085491-a3804d80-522e-11eb-8523-ef0b9c86af59.png)
![fsScreen_2021_01_08_03_05_47](https://user-images.githubusercontent.com/42093631/104085502-c14db280-522e-11eb-9497-65bed347870a.png)

**Comment by Tensuko** [comment] 2021-01-09 15:39
@NicholasSoares 
same for your:
logfile ?!
Also it looks like you have avoid fruit off and no headland.

**Comment by NicholasSoares** [comment] 2021-01-09 17:14
@Tensuko i need to create the save again to generate any log infortune, just posted to give more detais of the problem, avoid fruit is always set on it just dont work any good when off, and headland in this fields usually are not necessary (plenty of room and way too short) i can try to use some (3m header) if it corrects the issue for some reason

**Comment by Commissar0617** [comment] 2021-01-09 18:53
[log.txt](https://github.com/Courseplay/courseplay/files/5791624/log.txt)
i've observed it a couple times today, along with another issue i'll be filing another report about

**Comment by Commissar0617** [comment] 2021-01-10 02:29
https://mega.nz/file/fK4zEIZA#Y0QbucmpfOJmo6iyyrnff_-4sQvObK8VNXbgrN14948
(log too big for github)


![20210109192528_1](https://user-images.githubusercontent.com/5993529/104112841-51d0d500-52b9-11eb-9f16-fa1b4941ca85.jpg)
![20210109192528_2](https://user-images.githubusercontent.com/5993529/104112842-53020200-52b9-11eb-89eb-9ae6520620bd.jpg)
![20210109192529_1](https://user-images.githubusercontent.com/5993529/104112844-539a9880-52b9-11eb-8c55-ee0617a6808a.jpg)
![20210109192529_2](https://user-images.githubusercontent.com/5993529/104112845-54332f00-52b9-11eb-89d3-758ea2ff0124.jpg)
![20210109192529_3](https://user-images.githubusercontent.com/5993529/104112846-54332f00-52b9-11eb-87f4-2cb8bb4e4b89.jpg)
![20210109192530_1](https://user-images.githubusercontent.com/5993529/104112847-54cbc580-52b9-11eb-8915-d8e91204b847.jpg)
![20210109192530_2](https://user-images.githubusercontent.com/5993529/104112848-55645c00-52b9-11eb-9177-287699236ad6.jpg)
![20210109192530_3](https://user-images.githubusercontent.com/5993529/104112849-55fcf280-52b9-11eb-932c-da4269edbf56.jpg)
![20210109192531_1](https://user-images.githubusercontent.com/5993529/104112850-56958900-52b9-11eb-9449-59cccaa58a1f.jpg)
![20210109192531_2](https://user-images.githubusercontent.com/5993529/104112851-572e1f80-52b9-11eb-9576-f868e0798ee2.jpg)
![20210109192532_1](https://user-images.githubusercontent.com/5993529/104112852-57c6b600-52b9-11eb-8a51-d88d901106d9.jpg)
![20210109192532_2](https://user-images.githubusercontent.com/5993529/104112853-585f4c80-52b9-11eb-9021-f6594615e6c3.jpg)
![20210109200218_1](https://user-images.githubusercontent.com/5993529/104112855-58f7e300-52b9-11eb-830c-d07a364d0af6.jpg)

**Comment by pvaiko** [comment] 2021-02-10 14:51
@Commissar0617 is this still happening? 

Since version 20 we are deactivating the swerving for the combine when the current waypoint is within 20 meters of the end of the course, which in your screenshots above would be when the tractor is somewhere around waypoint 114. Looks like it gets somehow enabled again towards the end of the course, but I'm not able to reproduce this at all.

Would you able to use a test branch where I'd add some debug info to help resolving this?

**Comment by Commissar0617** [comment] 2021-02-11 03:25
lemme check. i know it was last time i played, but idk if i've playued ont he latest version of cp. as far as a test branch, sure.

**Comment by Commissar0617** [comment] 2021-02-11 03:56
![20210210215516_1](https://user-images.githubusercontent.com/5993529/107600918-c9608f80-6bea-11eb-87a6-598f82e5f3c8.jpg)

yep, still happening

**Closed** 2021-02-11 18:35 UTC
