### ISSUE TITLE
Strange behavior using "Stop while unloading"

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#3476] opened 2019-03-25 06:28 UTC
Yesterday in the morning I downloaded the version .144 (I guess).
Since that update, my combines and harvesters behave very strange when I avtivate "Stop while unloading". (I don't know how it is called in the english version because I use the german translation). 

Problem:
The driver comes next to the combine or sugar beet harvester. The combine puts out the pipe. When the pipe is completely put out, the unloading process starts for at least half a second and than stops. The pipe stays out but the combine starts to drive backwards in a quarter of a circle. Than it drives forward again next to the trailer and than it is caught in this procedure.

I saw this behavior with different combines and the Ropa Tiger 6XL sugar beet harvester.

This function is very important in my view because unloading while making a turn seems not to be possible.

Another problem with the same function:
The Grimme Novacat potato harvester does not accept the function "Stop while unloading" at all. To activate the function has no effect. The harvester always continues driving while unloading.

Don't get me wrong, CP is the only reason for me to keep playing FS19! :)

EDIT:
Ok, after reading the Issue #3282 I understand what the problem is. I think, there must be a command for the tractor not to drive next to the combine, until it drove out of the crop.

But it leads to another problem. I play on Nordfriesische Marsch. At least 90% of the fields have water or fences surrounding them. This is why I start the combine always with the pipe in the fruit and deactivate "Fruchtumfahrung". There is just no space next to the first headland for the unloading tractor (and even not for the combine to pull out of the fruit. So in this case, in my view, it is necessary to enable the unrealistic unloading while the pipe and the tractor stand in the fruit.

What's your opinion on that?

**Comment by pvaiko** [comment] 2019-03-25 11:28
Duplicate of #3474

**Comment by pvaiko** [comment] 2019-03-25 11:42
Check https://github.com/Courseplay/courseplay/releases/tag/6.01.00148, if you now deactivate pathfinding the combine won't pull back when the pipe is in the fruit.

**Comment by Th301** [comment] 2019-03-25 18:01
Thanks for your answer. The difference between the two posts was the amount of combines used.
I will check out the new version! 
At the end I hope, that pathfinding will be that good, that I can use it on NF :)

**Comment by pvaiko** [comment] 2019-03-25 18:56
Pathfinding is good enough, it's the cooperation between the combine and the unload tractor which is not ready yet for the pathfinding.

**Comment by Th301** [comment] 2019-03-26 07:31
Hey again,
ah ok, I see.
yesterday I tested with version .150. It seems to be still the same behavior. Independent if "Fruchtumfahrung" is activated or deactivated, the unload tractor drives straight into the fruit next to the harvester. That is absolutely ok for me because of the narrow fields. As soon as I activate "Stop while unloading" the procedure starts lile I described in my initial post. The tractor arrives next to the harvester and than the harvester starts backing up to get the pipe out of the fruit. But the tractor will not move anymore cause it is waiting to be loaded.
Is there perhaps a signal necessary from the harvester, telling the tractor that it will drive out of the lane?

**Comment by pvaiko** [comment] 2019-03-26 11:15
@Th301 you have deactived pathfinding on the combine, right? If yes and it still does not work then you have to give me very specific instructions because I can't reproduce this now.

**Comment by Th301** [comment] 2019-03-26 11:21
I will start a new test in the evening and try out all possible combinations of the pathfinding and "stop while unloading" and than give you another feedback!
Since sometimes the options go back to default (I think when there was a version update), it is possible, that the pathfinding at the combine was activated during the tests yesterday.
Sorry for the confusion. As a test engineer I normally should know how to fix the parameters of tests! ^^

**Comment by Th301** [comment] 2019-03-27 05:52
@pvaiko , you were right. Deactivating pathfinding on both, the combine and the unloading tractor, makes it work fine with "stop while unloading" ! 👍

**Closed** 2019-03-27 11:04 UTC
