### ISSUE TITLE
Courseplay bug with hiered helper

### ISSUE THREAD

**Issue by ZZenon** [Courseplay/courseplay#1536] opened 2016-12-19 10:38 UTC
When I use Helper (H) on a harvester, the assigned courseplay tractor does not stop when the harvester unloadet. Tractor keeps following the harvester forever. But if I put the harvester on a fieldwork course then everything works fine

**Comment by ThomasGaertner** [comment] 2017-01-06 08:20
I couldn't replicate it, can you give me some more detailed description and a screenshot of the situation ?

**Comment by lcc1211** [comment] 2017-01-15 17:20
I've tried to replicate this so I could capture a video, but haven't been able to so far.  I have seen it under this situation:  The combine is at the fill level trigger I've set, the tractor has pulled up along at the end of a lane, and I deliver the partial load (combine is not at 100%), and I manually take control of the harvester.  The tractor has followed me under these circumstances.

**Comment by SquareCloud506** [comment] 2017-01-15 21:17
So, if I understand the specific situation. A CP harvester has called a tipper, then before the harvester has told the harvester to stop, you take over for CP in the harvester? Maybe because the tipper was called by a CP harvester it will stay until a CP harvester tells it to stop?  I don't know how a CP harvester works with a CP tipper, but I've noticed in FS15 that a CP tipper reacts differently to a CP harvester than to a Player harvester.

**Comment by lcc1211** [comment] 2017-01-16 13:09
Yes. In the situation I described (related to a bug I reported earlier). The harvester is also near the end of the lane with a few meters of fruit left on the field.  I stop CP to manually get that since the harvester will skip it and go to the next lane.

**Comment by SquareCloud506** [comment] 2017-01-16 23:22
I'm not one of the CP programmers, but my guess is, if a CP tipper is called by a CP harvester, it will stay there until the CP harvester tells it to stop, instead of sensing when the harvester is empty. Because you've removed the CP harvester worker after the tipper gets called, the tipper never gets the 'stop' signal, so it just keeps following.

**Comment by lcc1211** [comment] 2017-01-17 02:00
I would say fixing the bug with the harvester ignoring the last few meters of fruit would be a good place to start looking and then the need to manually take over the job would not be needed.  Alternatively, what I have started doing is stopping CP and reversing the harvester roughly 5 meters back and restarting with the "nearest waypoint" option.

**Comment by pops64** [comment] 2017-02-04 01:53
Is this still an issue? Can we close here?

**Comment by lcc1211** [comment] 2017-02-04 12:17
I'll have to test it later today and see if I can duplicate. I think I have the game saved where I can reproduce it easily.

**Comment by lcc1211** [comment] 2017-02-06 21:05
Looks fine to me now.

**Comment by pops64** [comment] 2017-02-06 23:03
Close this out to keep the issues area clean

**Closed by pops64** 2017-02-06 23:03 UTC
Labels: waitingForUserAnswer
