### ISSUE TITLE
All AI vehicles stop anywhere near a CP driven vehicle

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3200] opened 2019-02-10 23:19 UTC
Regardless of Debug #3 setting, any car on the road will stop if there is any Courseplay vehicle anywhere near them.   That means that cars on the road in front of the CP vehicle will stop as it approaches from the rear..  either trapping it in traffic or having the CP vehicle smash into the back of it

v00059

**Comment by pvajko** [comment] 2019-02-11 02:38
duplicate of #3015

**Closed by pvajko** 2019-02-11 02:38 UTC
