### ISSUE TITLE
Lua Error Waypoint.lua:820

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#4829] opened 2020-01-16 20:27 UTC
Hello,

with the newest version of CP i get this lua error:
`2020-01-16 20:32 D:/LS19 Mods/FS19_CoursePlay6/Waypoint.lua:820: attempt to get length of local 'waypoints' (a nil value)
2020-01-16 20:32 Error: Running LUA method 'update'.`

This occurs in the fieldwork mode but I haven't tested a different mode so I can't say anything about that. If you need a report with a debug channel active just let me know.

Here is the log: 
[log.txt](https://github.com/Courseplay/courseplay/files/4073642/log.txt)

Greetings,
Knowen

**Comment by pvaiko** [comment] 2020-01-16 22:35
Duplicate of #4827

**Comment by pvaiko** [comment] 2020-01-16 22:44
Log with channel 14 and 7

(looks like no one really tested this while it was on beta:)

**Comment by pvaiko** [comment] 2020-01-16 22:51
Actually, this was just another stupid merging issue, should be working with 366.

**Closed by pvaiko** 2020-01-16 22:51 UTC

**Comment by GeorgeEarslight** [comment] 2020-01-17 05:57
> Log with channel 14 and 7
> 
> (looks like no one really tested this while it was on beta:)

Apologies if I missed it, but it didn't happen on beta.
I tried the same course late yesterday and only happened then.
Thanks for the quick fix :)

**Comment by pvaiko** [comment] 2020-01-17 20:22
@GeorgeEarslight No need to apologize, I screwed it up.
