### ISSUE TITLE
Turn problem with Horsch Sowing Machine

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3723] opened 2019-05-01 21:24 UTC
[log.txt](https://github.com/Courseplay/courseplay/files/3136044/log.txt)
![Screenshot (2357)](https://user-images.githubusercontent.com/47073128/57043478-ee7b4c80-6c67-11e9-84f3-5208283c58c7.png)
![Screenshot (2358)](https://user-images.githubusercontent.com/47073128/57043481-ee7b4c80-6c67-11e9-97f1-881cf5a56909.png)
![Screenshot (2359)](https://user-images.githubusercontent.com/47073128/57043483-ee7b4c80-6c67-11e9-9e68-b2e5af7c7def.png)
![Screenshot (2360)](https://user-images.githubusercontent.com/47073128/57043484-ee7b4c80-6c67-11e9-84dd-0c0a1def5988.png)
![Screenshot (2361)](https://user-images.githubusercontent.com/47073128/57043485-ef13e300-6c67-11e9-82da-039c83f8c926.png)

Hello!
I downloaded teh Horsch Pack and i used the 18 Meter "Single-Corn" Seeding Machine. I believe that there somethign is wrong with the turn maneuver...
In headland corner after turning correctly driver drives a circle without reason. In up/down rows afterwards the trailer is becoming wedged a bit for unknown reason, it equals unworked patches.

**Comment by StefanBraun2001** [comment] 2019-05-05 15:50
I recognized that this happens to almost all tools (at least in sharp headland corners) which are wheeled.

**Comment by pvaiko** [comment] 2019-05-11 12:18
This is a duplicate of #3748 and fixed in 211.

**Closed by pvaiko** 2019-05-11 12:18 UTC
