### ISSUE TITLE
Lely Juno Mod Hired worker costs money

### ISSUE THREAD

**Issue by HardRooster** [Courseplay/courseplay#2135] opened 2017-06-26 23:52 UTC
Normally the hired worker is free, since it's a robot.  Now it appears to cost twice as much as a normal hired worker.  Probably something in the script for the Juno, any ideas on how to modify/correct it?

**Comment by HardRooster** [comment] 2017-06-27 00:02
I'm not a coder, so I don't completely know what I'm looking at, but I've been able to manipulate vehicle prices, daily upkeep and things like that. Is this the script that sets the worker price?  Could I make it a negative number to work with courseplay?  And if so, what would the number be?

<ai>
        <conveyorBelt minAngle="500" maxAngle="6000" stepSize="250" speed="4" centerWheelIndex="1" backWheelIndex="2"/>
        <didNotMoveTimeout deactivated="true"/>
        <pricePerHour>0</pricePerHour>
    </ai>

**Comment by sootysax** [comment] 2017-06-29 17:57
when you buy the charger, it offsets the cost of hiring

**Comment by pops64** [comment] 2017-06-29 18:11
Also there is a mod that you can change the rate of pay globally for hired workers called Game Extension mod I believe.  I am going to close this out. Since this is not a CP issue.

**Closed by pops64** 2017-06-29 18:11 UTC

**Comment by dclay1983** [comment] 2018-04-08 23:11
I can confirm that this is a courseplay issue, though it doesn't cause double payment. I realized after running the lely only for almost an hour having a wage payment of 1,035. I have Game Extension, but have AI worker fees disabled in that mod. The Lely Juno has a 0 on wage payment in it's config file. After going into the courseplay config in my save game and turning off wages there, I no longer was charged a wage for running the Lely Juno.

**Comment by dclay1983** [comment] 2018-04-08 23:12
I think instead of setting a constant wage based on difficulty, using a multiplier instead as that would not affect a piece of equipment that has a wage of 0.
