### ISSUE TITLE
Loading Save Courses Not Loading Correctly

### ISSUE THREAD

**Issue by majora15** [Courseplay/courseplay#6287] opened 2020-11-05 01:47 UTC
Playing Wild West x16, multi player.  We are creating courses then after some unknown time we will call that course again and it is not displaying the correct path.  For example.  Course that goes from Point A to Point B, and confirms working, 15 minutes after that if you load that same course it may go from Point A to Point C.

If we reset the vehicle everything starts working as normal.

Running Version 6.02.00075

https://gist.github.com/majora15/6180f3c35786b10d59117a10da1b7247

It appears that the issue is when you create folders to organize your courses.  For Example:

-Field 6
--Mowing
---Mow S Field 6
--Transport
---Transport Field 6 S to Farm

-Mow N Field 6
-Mow E Field 6

When we move "Mow N Field 6" and/or "Mow E Field 6" it messes up all courses and when you select any courses after the move it doesn't load the correct course.

Logging out and logging back in does not fix the issue, it causes more problems.  More problems like, if you have a worker working while you log out, when you log back in and dismiss the worker it still shows the worker in the vehicle.  If you reset the vehicle it then removes the field numbers, the hud where season time / weather / funds amounts are at.  To fix the hud issue you have to log out and log back in.

**Comment by Tensuko** [comment] 2020-11-05 05:54
All the Course Management in MP need to be investigated more and you also have to make sure, saveing and deleting course should not be done while other ppl deleting and saveing course.
It is still very messy and need to be refactored soon or later, just try it get it working somehow for now...

**Comment by majora15** [comment] 2020-11-06 04:02
Playing tonight added 5-8, once getting to the 6-8 courses we started noticing the courses not loading right.  a course on field 10, directs the vehicle to field 16.  Seems as new course are added it changes the order and causes issues.

**Comment by Ericd22b** [comment] 2020-11-18 17:45
Hi is there any news on this problem we have been using courseplay on our server for weeks and it worked great then lately we have encountered this problem

**Comment by majora15** [comment] 2020-11-19 02:36
Had another issue tonight... Went to search for a course set it and noticed it didn't display the course, told it to run course and it seemed to pick a different course to run.

**Comment by Ericd22b** [comment] 2020-11-19 20:18
majora15 thats what ours has started doing

**Comment by PioneerX** [comment] 2020-11-24 07:41
We are experiancing the very same issue. When moving folders or moving courses to/between folders the server throws the following errors......

2020-11-24 06:53 Error: Running LUA method 'packetReceived'.
2020-11-24 06:53 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
2020-11-24 06:53 Error: Running LUA method 'packetReceived'.
2020-11-24 06:53 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:800: attempt to index local 'f' (a nil value)
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value
2020-11-24 06:57 Error: Running LUA method 'packetReceived'.
2020-11-24 06:57 game/mods/FS19_Courseplay/settings.lua:800: attempt to index local 'f' (a nil value)

....once the errors are thrown the folder order appears to be miss matched between GUI (correct order) and the actual structure. This is confirmed by logging off and loggin back in. Once you log back in the folder structure can be redicaly different to the one shown by the GUI prior to logging off. It appears this miss match is the cause of incorrect route loading. I observed the following.....

- Login
- Load route
- Load successful
- Move route/folder (move shows correct on GUI)
- Load route - wrong route loaded

....This appeared to be working correctly post v6.0.2.00076 but broke in one of the more recent updates. Unforutantly I do not have the logs available to determine which of the subsquent updates it broke in.

**Comment by Tensuko** [comment] 2020-11-24 07:58
@PioneerX looks like a different Error.
00076 just fixed the course and folder problem.
If you created folders before (.00075) your coursemanager might be corrupted.
Download it with ftp access and change the parent value to 0 and sort everything new.

**Comment by PioneerX** [comment] 2020-11-24 11:46
> @PioneerX looks like a different Error.
> 00076 just fixed the course and folder problem.
> If you created folders before (.00075) your coursemanager might be corrupted.
> Download it with ftp access and change the parent value to 0 and sort everything new.

Tensuko, that solution seems to have done the trick on our case. Courses now load as they should. I redid the folders and moved all 118 courses to the folder without issue and courses still load ofter the move. We did see the same symptoms as described in this ticket but the reset of all coursed to 'parent="0"' and redo of the folder seems to have solved it for us.

We do still get the occational error in the logs...

2020-11-24 09:41 Error: Running LUA method 'packetReceived'.
2020-11-24 09:41 game/mods/FS19_Courseplay/settings.lua:698: attempt to index a nil value

...but no longer timed with the move of courses between folders.

Thanks

**Comment by majora15** [comment] 2020-11-25 18:10
Updated to v6.03.00001 in MP, that now when you click on "Drive Course" on the BSM 850 its strobe bar comes up but doesn't drive the course.  Created even a new course and same thing.

020-11-25 11:42 	### CourseplayMultiplayer: writing 107 courses 
2020-11-25 11:42 	### CourseplayMultiplayer: writing 7 folders 
2020-11-25 11:42 	### CourseplayMultiplayer: writing 0 custom fields 
2020-11-25 11:59 data/shared/ai/trafficCollision.i3d (33.18 ms)
2020-11-25 11:59 :04 [info lp63346] 850 (#1): AI driver in mode 1 starting at 430/436 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 11:59 :22 [info lp64422] 850 (#1): AI driver in mode 1 starting at 430/436 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:00 dataS2/character/humans/player/player02.i3d (429.97 ms)
2020-11-25 12:00 :23 [info lp68029] 850 (#1): AI driver in mode 1 starting at 23/436 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:00 :26 [info lp68263] 850 (#1): AI driver in mode 1 starting at 24/436 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:00 :45 [info lp69393] 850 (#1): AI driver in mode 1 starting at 422/429 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:01 :18 [info lp71368] 850 (#1): AI driver in mode 1 starting at 254/254 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:01 :34 [info lp72309] 850 (#1): AI driver in mode 5 starting at 254/254 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:01 :50 [info lp73273] 850 (#1): AI driver in mode 5 starting at 422/429 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:02 :08 [info lp74325] 850 (#1): AI driver in mode 5 starting at 420/429 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:05 :55 [info lp87946] 850 (#1): AI driver in mode 5 starting at 458/458 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 12:09 :10 [info lp96154] 850 (#1): AI driver in mode 5 starting at 458/458 waypoints (COURSEPLAY_NEAREST_POINT)

**Comment by Tensuko** [comment] 2020-11-25 18:16
uhm okay... also not on a new created course ?

**Comment by majora15** [comment] 2020-11-25 21:38
That is correct, if I create a brand new course and tell it drive course it does the same thing.  Revert back to 6.02.00075 and it works.

**Comment by Tensuko** [comment] 2020-11-25 22:35
Must be something on your server then, no Issue with driving CP on Server.
![fsScreen_2020_11_25_23_34_47](https://user-images.githubusercontent.com/27344744/100288381-d91af100-2f76-11eb-9f40-71045aa87896.png)

**Comment by majora15** [comment] 2020-11-26 02:42
The issue seems to be with a specific truck and not a tractor.  I have done some additional troubleshooting.  First I can reproduce this on a second server.  We have a hosted server, and I built a private server.    The common theme is the following mods:
-FS19_Courseplay.zip (latest version)
-Maps_FS19_WildWest_16x.zip (latest version)
-FS19_850_Legende_Truck.zip (latest version)

I've tried the following:
-Removed all other mods except the ones noted above, issue still persists with these trucks.
-Started a new save, and the issue still persists with these trucks
-Created a new course going from one field back to a farm and tried driving it, issue still persists with these trucks.
-Created a short course that just goes around in circles and tried driving it, issue still persists with these trucks.

I turned on all debugging mod then clicked start driving and this is what I received from the server:

2020-11-25 18:28 :02 [dbg5 lp6020] setCourseplayFunc: function: startStop value: 1 noEventSend: true page: 1
2020-11-25 18:28 :02 [dbg5 lp6020] executeFunction: function: startStop value: 1 page: 1
2020-11-25 18:28 ##################################################
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): updateWorkTools(850, "850 (#1)", isImplement=false) (mode=5)
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): askForSpecialSettings(..., "850 (#1)")
2020-11-25 18:28 :02 [dbg3 lp6020] 850 (#1): adding "850 (#1)" ("850.xml") to cpTrafficCollisionIgnoreList
2020-11-25 18:28 :02 [dbg3 lp6020] 850 (#1): adding "850 (#1)" ("850.xml") components to cpTrafficCollisionIgnoreList
2020-11-25 18:28 --------------------------------------------------
2020-11-25 18:28 :02 [dbg3 lp6020] 850 (#1) cpTrafficCollisionIgnoreList
2020-11-25 18:28 :02 [dbg3 lp6020] \___ [429336] = 850 ("850_main_component1")
2020-11-25 18:28 ##################################################
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): Set turnDiameterAuto to 14.68m (2 x vehicleTurnRadius)
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): turnDiameterAutoMode is active: turnDiameter set to 14.68m
2020-11-25 18:28 --------------------------------------------------
2020-11-25 18:28 --------------------------------------------------
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): no workTools set
2020-11-25 18:28 ##################################################
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): getting working width...
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): has NO work area
2020-11-25 18:28 :02 [dbg6 lp6020] 850 (#1): working width is 0.0
2020-11-25 18:28 :02 [dbg5 lp6020] setCpVar: distanceCheck: true -> send Event
2020-11-25 18:28 :02 [dbg12 lp6020] 850 (#1): numWaitPoints=0, waitPoints[1]=nil, numCrossingPoints=0
2020-11-25 18:28 :02 [dbg1 lp6020] updateAllTriggers()
2020-11-25 18:28 :02 [dbg1 lp6020]    check itemsToSave
2020-11-25 18:28 :02 [dbg1 lp6020]     add Mill Station 1(424545) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Wood chips(424931) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Ranch(424976) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]    found a BGA
2020-11-25 18:28 :02 [dbg1 lp6020]      add 45(MANURE) from slot1 to acceptedFilltypes
2020-11-25 18:28 :02 [dbg1 lp6020]      add 28(GRASS_WINDROW) from slot1 to acceptedFilltypes
2020-11-25 18:28 :02 [dbg1 lp6020]      add 30(DRYGRASS_WINDROW) from slot1 to acceptedFilltypes
2020-11-25 18:28 :02 [dbg1 lp6020]      add 24(SILAGE) from slot1 to acceptedFilltypes
2020-11-25 18:28 :02 [dbg1 lp6020]      add 46(LIQUIDMANURE) from slot2 to acceptedFilltypes
2020-11-25 18:28 :02 [dbg1 lp6020]     add Biogas Plant(424723) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Biogas Plant(424722) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]    BGA End -------------
2020-11-25 18:28 :02 [dbg1 lp6020]     add Western Port(425101) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Diesel Sales(425075) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Spinnery(425053) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Mill Station 2(424567) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Dairy(424643) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Bales sales(425030) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Restaurant(424607) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Mill Station(424523) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Manure Sales(424840) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Garden Centre(424808) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Saw Mill(424880) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Granny's Super Market(424665) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]   23 in list
2020-11-25 18:28 :02 [dbg1 lp6020]    check placeables
2020-11-25 18:28 :02 [dbg1 lp6020]     add Mill Station(424522) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Mill Station 1(424544) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Mill Station 2(424566) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Restaurant(424606) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Dairy(424642) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Granny's Super Market(424664) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Garden Centre(424807) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Manure Sales(424839) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Saw Mill(424879) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Wood chips(424930) to tipTriggers
2020-11-25 18:28 :02 [dbg1 lp6020]     add Gas Station(424952) to fillTriggers (buyingStation)
2020-11-25 18:28 :02 [dbg1 lp6020]     add Ranch(424975) to tipTriggers
2020-11-25 18:28 :03 [dbg1 lp6020]     add Bales sales(425029) to tipTriggers
2020-11-25 18:28 :03 [dbg1 lp6020]     add Spinnery(425052) to tipTriggers
2020-11-25 18:28 :03 [dbg1 lp6020]     add Diesel Sales(425074) to tipTriggers
2020-11-25 18:28 :03 [dbg1 lp6020]     add Western Port(425100) to tipTriggers
2020-11-25 18:28 :03 [dbg1 lp6020]     add Farm Silo(425156) to tipTriggers
2020-11-25 18:28 :03 [dbg1 lp6020]     add Liquids(425160) to fillTriggers (loadingStation)
2020-11-25 18:28 :03 [dbg1 lp6020]     add waterFillTrigger(425198) to fillTriggers (buyingStation)
2020-11-25 18:28 :03 [dbg1 lp6020]    23 found
2020-11-25 18:28 :03 [dbg1 lp6020]    check fillTriggerVehicles
2020-11-25 18:28 :03 [dbg1 lp6020]    0 found
2020-11-25 18:28 :03 [dbg1 lp6020]    check nodeToObject
2020-11-25 18:28 :03 [dbg1 lp6020]     add (424739) to fillTriggers (nodeToObject->triggerNode )
2020-11-25 18:28 :03 [dbg5 lp6020] setCpVar: distanceCheck: false -> send Event
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): getTotalLengthOnWheels()
2020-11-25 18:28 --------------------------------------------------
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): frontWheelToDirectionNodeOffset=-1.34, frontWheelToRearWheel=7.39
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): frontWheelToRearTrailerAttacherJoints[7]=6.60
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): frontWheelToRearTrailerAttacherJoints[2]=8.37
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): frontWheelToRearTrailerAttacherJoints[3]=8.37
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): frontWheelToRearTrailerAttacherJoints[18]=6.36
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): frontWheelToRearTrailerAttacherJoints[16]=5.23
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): turningNodeToRearTrailerAttacherJoints[7]=0.57
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): turningNodeToRearTrailerAttacherJoints[2]=2.34
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): turningNodeToRearTrailerAttacherJoints[3]=2.34
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): turningNodeToRearTrailerAttacherJoints[18]=0.33
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): turningNodeToRearTrailerAttacherJoints[16]=-0.79
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): Using frontWheelToRearWheel=7.39
2020-11-25 18:28 --------------------------------------------------
2020-11-25 18:28 :03 [dbg6 lp6020] 850 (#1): totalLength=7.39, totalLengthOffset=-1.34
2020-11-25 18:28 --------------------------------------------------
2020-11-25 18:28 :03 [dbg5 lp6020] setCpVar: canSwitchMode: false -> send Event
2020-11-25 18:28 :03 [dbg12 lp6020] 850 (#1): validateCanSwitchMode(): isDriving=true, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=false
2020-11-25 18:28 dataS2/character/humans/player/player02.i3d (938.08 ms)
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): CollisionDetector:init()
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): will ignore collisions with "850 (#1)" ("850.xml")
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): -- "aiCollisionTrigger"
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): will ignore collisions with "850 (#1)" ("850.xml") components
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): -- "850_main_component1"
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): Making sure cars won't stop around us
2020-11-25 18:28 :04 [dbg2 lp6020] 850 (#1): new TriggerHandler state = NOTHING!
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): CollisionDetector:init()
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): will ignore collisions with "850 (#1)" ("850.xml")
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): -- "aiCollisionTrigger"
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): will ignore collisions with "850 (#1)" ("850.xml") components
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): -- "850_main_component1"
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): TrafficConflictDetector:init()
2020-11-25 18:28 :04 [dbg3 lp6020] 850 (#1): Collision detection enabled
2020-11-25 18:28 :04 [dbg12 lp6020] Course with 41 waypoints created/updated, 109.1 meters, 0 turns
2020-11-25 18:28 :04 [info lp6020] 850 (#1): AI driver in mode 5 starting at 41/41 waypoints (COURSEPLAY_NEAREST_POINT)
2020-11-25 18:28 :04 [dbg12 lp6020] 850 (#1): PPC: 850-relevantWpNode waypoint index 41
2020-11-25 18:28 :04 [dbg12 lp6020] 850 (#1): PPC: 850-nextWpNode waypoint index 41
2020-11-25 18:28 :04 [dbg12 lp6020] 850 (#1): PPC: 850-currentWpNode waypoint index 41
2020-11-25 18:28 :04 [dbg12 lp6020] 850 (#1): PPC: initialized to waypoint 41 of 41
2020-11-25 18:28 :04 [dbg12 lp6021] 850 (#1): PPC: waypoint 41 passed, dz: 0.0  
2020-11-25 18:28 :04 [dbg12 lp6021] 850 (#1): PPC: 850-relevantWpNode waypoint index 1
2020-11-25 18:28 :04 [dbg12 lp6021] 850 (#1): PPC: 850-nextWpNode waypoint index 1
2020-11-25 18:28 :04 [dbg12 lp6021] 850 (#1): PPC: 850-currentWpNode waypoint index 1
2020-11-25 18:28 :04 [dbg12 lp6021] 850 (#1): PPC: initialized to waypoint 1 of 41
2020-11-25 18:28 :04 [dbg3 lp6021] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :04 [dbg3 lp6021] 850 (#1): collision trigger cpAiCollisionTrigger 1 entered: cpAiCollisionTrigger 2, 1 colliding objects.
2020-11-25 18:28 :04 [dbg3 lp6021] 850 (#1): collision trigger cpAiCollisionTrigger 2 entered: cpAiCollisionTrigger 1, 2 colliding objects.
2020-11-25 18:28 :04 [dbg3 lp6021] 850 (#1): collision trigger cpAiCollisionTrigger 2 entered: cpAiCollisionTrigger 3, 3 colliding objects.
2020-11-25 18:28 :04 [dbg3 lp6021] 850 (#1): collision trigger cpAiCollisionTrigger 3 entered: cpAiCollisionTrigger 4, 4 colliding objects.
2020-11-25 18:28 :04 [dbg12 lp6022] 850 (#1): PPC: common case, ix=4, q1=7.8, q2=9.1 la=7.9
2020-11-25 18:28 :04 [dbg12 lp6022] 850 (#1): PPC: 850-currentWpNode waypoint index 5
2020-11-25 18:28 :05 [dbg3 lp6042] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :06 [dbg3 lp6066] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :07 [dbg3 lp6089] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :08 [dbg3 lp6100] 850 (#1): has 4 colliding object(s)
2020-11-25 18:28 :08 [dbg3 lp6113] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :09 [dbg3 lp6135] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :10 [dbg3 lp6158] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :11 [dbg3 lp6177] 850 (#1): updating collision boxes at waypoint 1, have 20 positions
2020-11-25 18:28 :12 [dbg5 lp6196] setCourseplayFunc: function: startStop value: 1 noEventSend: true page: 1
2020-11-25 18:28 :12 [dbg5 lp6196] executeFunction: function: startStop value: 1 page: 1
2020-11-25 18:28 :12 [dbg3 lp6196] 850 (#1): reset CollisionDetector triggers
2020-11-25 18:28 :12 [dbg3 lp6196] 850 (#1): deleting CollisionDetector
2020-11-25 18:28 :12 [dbg3 lp6196] 850 (#1): deleting CollisionDetector
2020-11-25 18:28 :12 [dbg2 lp6196] 850 (#1): new TriggerHandler state = STOPPED!
2020-11-25 18:28 :12 [dbg3 lp6196] 850 (#1): Removing all traffic conflicts
2020-11-25 18:28 :12 [dbg3 lp6196] 850 (#1): deleting CollisionDetector
2020-11-25 18:28 :12 [dbg5 lp6196] setCpVar: canSwitchMode: true -> send Event
2020-11-25 18:28 :12 [dbg12 lp6196] 850 (#1): validateCanSwitchMode(): isDriving=false, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=true
2020-11-25 18:28 Warning: Send called with unknown target address.
2020-11-25 18:28 :17 [dbg8 lp6279] 850 (#1): Setting visibility for 41 waypoints, start/end=nil all=nil, xing=nil

I understand that your team doesn't support this truck mod, however when I revert back to the older version everything works as normal.

It appears it is being attached to the truck, attaching current game.log file if this helps.

[game.log](https://github.com/Courseplay/courseplay/files/5600152/game.log)

**Comment by Tensuko** [comment] 2020-12-01 05:41
I guess the truck blocks itself due to fked up traffic box.
Got a similar Issue ( #6313 ) but that got nothing to do with the original title.
Will close this one here.

**Closed by Tensuko** 2020-12-01 05:41 UTC
Labels: MP Coursemanager, try to reproduce
