### ISSUE TITLE
Saved games won't load with version > v6.03.00026

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/courseplay#6719] opened 2021-01-24 03:32 UTC
I'm not sure what was changed in 27 and 28, but none of my saved games will load. I haven't added any new mods in over (6) months, once I find good vehicles and implements I stick with them. Apparently some type of mod conflict. But before you ask, not one single error in the log file for CP, game won't load, little circle of dots for the upper left loading just spins forever. Put v6.03.00026 back into mods folder, and all my maps load.
On top of that, while using my pickup wagon in the transport mode, the vehicle under v6.03.00026 is now stuck at its field speedLimit, even when on any road.
Overload problems persist, and under v6.03.00026, headlands are barely working for any courses using 2 - 3 vehicles, either only the left vehicle works, and the right skips its headland, and does a 180 U-turn at the end of the first pass, or both the left and right course skip the headland, and do a U-turn after the first pass.

**Comment by Tensuko** [comment] 2021-01-24 08:18
And not a single logfile.......

**Comment by Tensuko** [comment] 2021-01-24 08:19
Pickup wagon limited to field speed is nothing new...

**Comment by Tensuko** [comment] 2021-01-24 08:25
Overloading no Idea what you mean by this.

Multitool course the problem is you started the course in a corner, also nothing new.

**Comment by pvaiko** [comment] 2021-01-24 12:23
We'll only deal here with the save game loading issue.

**Comment by HC1Gunner** [comment] 2021-01-24 16:57
Again, what the heck is wrong with starting a course from the corner? I can
send you tons of "real" framers on you tube with GPS / auto-steer starting
on the field from its "edge" (the corner).

Overload = Overloading = OL, 3rd mode in from the left.

If you have suggestions for using CP 6 (FS19) I'm all ears, but right from
your own website and manual, Field work, Fertilizing and Seeding modes, the
diagram shows courses starting and ending in the "corner".
[image: CP manual corner start.jpg]

**Comment by HC1Gunner** [comment] 2021-01-24 17:05
No, the Sim won't load with v6.03.00027 or v6.03.00028, the last version
the game loads with for me "is v6.03.00026". If I'm not mistaken, v6.03.00027
and forward was where you made some changes to CP.

It was after your below statement of changes starting with 027 that FS
would not load with all my saved games running and saved with v6.03.00026.
"Special tools (or vehicle) configuration should be configurable and

not hard coded, therefore, moved everything still in use from
specialTools.lua to a configuration file.

Created a config folder for the new file (and moved ValidModeSetup.xml
there too).

Courseplay now loads configurations from config/VehicleConfigurations.xml
and it will also look under the modsSettings folder for a user created
configuration in Courseplay/vehicleConfigurations.xml, where users
can add or override config parameters".

**Comment by Tensuko** [comment] 2021-01-24 17:26
Game launches just fine with .00028
The not start from corner is becosue of multitool right now, there is no other way for now!

And again, no logfile of 'game not starting' ...

**Comment by pvaiko** [comment] 2021-01-24 18:12
@HC1Gunner take it easy. We know exactly what we changed an when, no need to paste in the release description in here for me since I was the one who wrote it in the first place.

What we still don't know though is why you are not posting a log file here.

**Comment by pvaiko** [comment] 2021-01-24 18:14
As for starting the course in the corner, nothing is wrong with that, but the transition between headlands and between the headland can be difficult in those cases. Remember, this is a community project and if you can improve the code generator code you are more than welcome to open a pull request.

**Comment by pvaiko** [comment] 2021-01-25 19:53
Duplicate of #6728, it does at least have a log.

**Closed by pvaiko** 2021-01-25 19:53 UTC
Labels: waiting for logfile
