### ISSUE TITLE
Error: Running LUA method 'draw'. - AIDriver.lua:614: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#4086] opened 2019-08-15 10:52 UTC
Error: Running LUA method 'draw'.
version 6.01.00277 - 79
FS19_CoursePlay6/hud.lua:466: attempt to index a nil value

[log.txt](https://github.com/Courseplay/courseplay/files/3505271/log.txt)

**Comment by Tensuko** [comment] 2019-08-15 11:23
Duplicate of #4074
Closed.

**Closed by Tensuko** 2019-08-15 11:23 UTC
