### ISSUE TITLE
Suggestion: Add Continue into Headlands for all work modes

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#2399] opened 2017-10-22 11:11 UTC
Hey,
I'd be nice, if you could add the continue into headlands options for plowing into all work courses.
especially with the new course generator, vehicles often leave a gap between headlands and the rest of the field.

**Comment by pvajko** [comment] 2017-10-22 12:50
I'd rather figure out what the root cause of this behavior is instead of band-aiding it. Do you have a savegame and courses for a standard or official mod map?

**Comment by JDTiger** [comment] 2017-10-22 16:10
take any non- rectangular field, and it will happen on the slanted side, because the implement will be turned off/lifted, when the middle of the implement hits the outside of the headland

**Comment by pops64** [comment] 2017-10-22 18:07
@JDTiger use the plough past field edge option in order for this to be achieved. It should work for fields with headlands just fine

**Comment by JDTiger** [comment] 2017-10-22 18:33
Yip, problem is, it seems to only appear when a plow is attached...

**Comment by pvajko** [comment] 2017-10-22 20:32
So this should actually be fixed in the course generator, it should extend the up/down lanes depending on the headland angle and work width. Let me check how difficult that would be.

Everything else is just band aid.

**Comment by pvajko** [comment] 2017-10-23 16:32
I think this is an easy fix in the course gen.

**Comment by pvajko** [comment] 2017-10-29 00:16
Closed due to inactivity. I think this works fine now, please reopen if not.

**Closed by pvajko** 2017-10-29 00:16 UTC
