### ISSUE TITLE
'silo empty' after fulfilling a previous grain transport course

### ISSUE THREAD

**Issue by Haiya-Dragon** [Courseplay/courseplay#2026] opened 2017-04-30 13:40 UTC
After fulfilling a grain transport course where the input silo is completely emptied, starting a different grain transport course with the same vehicle will result in the 'silo empty waiting for more' message near the start of the course. This means the course will never really start. A reload of the savegame 'fixes' the issue, so it seems some internal value isn't properly cleared after removing the first course from the vehicle.

Running v131

**Comment by pops64** [comment] 2017-04-30 17:15
Shouldn't be having this issue. The variables that used are updated when you change the fill type for mode 1. I would start by turning off mods that effect silos or give us a video of how you are producing this error

**Comment by Haiya-Dragon** [comment] 2017-05-09 15:56
So far I haven't been able to reliably reproduce the issue, but it does show up during my longer play sessions. Last night for example I did a large logging operation with two trucks hauling the woodchips back to a silo. I updated the course a few times because the site for chipping moved. This all worked flawlessly. Next I had another hauling course (which worked fine in other sessions), and it gave me the issue again.

For all these actions I never set a filltype because it just waits at the start of the course until it's filled by a conveyor until that stops and the level is over the percentage set in the options. You mentioned the variables are updated when you change the filltype, so perhaps this is the cause of my issues. I will investigate further..

**Comment by pops64** [comment] 2017-05-09 18:31
Yea if you get this message try toggling the selected fill type. This will clear the variables.

**Comment by sootysax** [comment] 2017-05-10 00:01
i also have this problem..  the tractor will also not stop at the silo and drive completely past the loading point, driving until it reaches the unload trigger, where it stops to try and be loaded..   the only way to fix the issue is to quit and restart the savegame

**Comment by pops64** [comment] 2017-05-10 19:07
@sootysax your issue sounds completely different it sound like #2051

**Comment by sootysax** [comment] 2017-05-12 02:04
but the "silo does not have selected fill type" is also displayed when this happens

**Comment by pops64** [comment] 2017-05-12 02:12
either way it is a completely different issue. Mostly likely the one I referenced you are just are getting a different outcome either way mode1 isn't stopping at the first waypoint. This issues sounds like it stops at the first way point but CP isn't agreeing with the selected fill type and what CP is collecting from the trigger. So with your issue and the one we referenced we have to figure out why CP doesn't want to stop at the first waypoint and once that is fixed we will go from there

**Comment by sootysax** [comment] 2017-05-13 14:49
I'm not sure which issue mine is more associated with, but I will post here, because issue #2051 is dealing with offloading combines, and this issue is happening with forage silos and conveyor belts.

both of these courses were previously working with the same vehicle and the same save game..   I ran one course, then switched to the other... after a few starts/stops on the second course, both of these courses resulted in the demonstrated behavoir..    the only way to get either course to work again is to quit the save game and restart it.   this scenario is reproducible.   eventually, if I run enough courses, they will break and fail like this..  i do not know what is triggering it to start.. but sooner or later it will.

https://www.dropbox.com/s/1lmtd6szki8osvh/2017-05-13_103743286.mp4?dl=0

https://www.dropbox.com/s/8ta5pec7c0zidoo/2017-05-13_103550289.mp4?dl=0

**Comment by pops64** [comment] 2017-05-13 19:31
Both the videos you are showing is only a guess with out F5 active is actually related to. #1918. So you first and second video it is running over that unloading trigger first which is probably what is causing the hang up. I honestly don't know how CP would handle a unload trigger first than a fill trigger. I think it is trying to do both things at the same time and CP isn't designed to handle that.  Your picture is also probably the same cause.  I honestly would edit the map and separate those trigger enough that you don't have that conflict.

**Comment by Faelandaea** [comment] 2017-06-08 03:18
I am not new to Courseplay but never had any reason to post before now.  I am also encountering this issue as of tonight.  Attached are the debug lines from the log.  For me, using mode 1, the truck will drive the route once, not stopping at all at the start even though there was a motherbin there full trying to pour into it.  Having a little bit in it from the motherbin, it would stop at the tip point and unload.   Then it would return to the start point.

Once back at the start point, it would keep on trucking, but this time throw up an error that "the silo doesn't have the selected fill type"  What?  I'm not emtying a Silo.  The truck shouldn;t give a rat's a__ what's in my farm's silo.  The thing needs to just sit there and wait to be filled by whatever stuff it's face.

Anyway, after finding this thread, I ran a debug 2 and copied the lines to a file.  I hope the information helps.  For me, since older versions are unavailable for download, I cannot revert back to an older version.  The current version completely breaks CP for me because my soul purpose for using it is to help me harvest fields, and my job as the player is to auger between the harvesters and the truck (since augering is the least successful facet of CP and has never ever worked right for me).

Hopefully this issue does get resolved so I can start streaming this wonderful mod again.  And I hope the text file helps.

[log.txt](https://github.com/Courseplay/courseplay/files/1059848/log.txt)

**Comment by dkfiremann** [comment] 2017-06-08 20:31
Let me try to understand what you ar doing. You want to fill the truck in a overload position and transport the harvest to a silo or sellingpoint? 
And you fill the truck using a Auger wagon, that is emptying the combine? 

The error message that you see is a standard message for mode 1, no matter if to fill it from a silo or not. 
Would it be possible for you to attach/add pictures of you setup?

**Comment by pops64** [comment] 2017-06-08 23:38
Yea we would need more information with pictures or video. Has well has your combi settings page. Refill pct etc. I know some people have been having issues with mode 1 not stop at the start point. Since you said this just started and CP hasn't been updated in a while. Have you installed a new mod? Has for mode 3 not working right what is your problem there? I know it is a little on the sensitive side when approaching the parking spot but you can adjust the pipe position and save that new one. Also you can try adjusting the horizontal wait point offset in the driving settings page.

**Comment by Blackmankot** [comment] 2017-08-05 01:30
@pops64 And I propose to close this issue for cleaning.

**Comment by pops64** [comment] 2017-08-12 20:29
Closing this out has not reproducible. If you can reliably reproduce this please post steps here and we will review this again.

**Closed by pops64** 2017-08-12 20:29 UTC
Labels: waitingForUserAnswer
