### ISSUE TITLE
Courseplay_6_01_00350/vehicles.lua:897: attempt to index field 'attacherJoint' (a nil value) 2019-12-30 17:01 Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by thadeausmaximus** [Courseplay/courseplay#4741] opened 2019-12-31 00:29 UTC
[savegame3.zip](https://github.com/Courseplay/courseplay/files/4011545/savegame3.zip)

tried to make this as simple as possible. FS19 with only courseplay and syntrac mods loaded. When I use the syntrac tractor with a universal adapter connected and connect to a sugarcane hopper mf 3012 it works fine until I set a course. Once a course is set if I attempt to connect to the hopper the game gets stuck with the hopper in an in between connection to the hopper not quite connected but it follows me around and I can't release it either. Lots of these lines show up in the log:

2019-12-30 17:01 C:/Users/thad/Documents/my games/FarmingSimulator2019/mods/Courseplay_6_01_00350/vehicles.lua:897: attempt to index field 'attacherJoint' (a nil value)
2019-12-30 17:01 Error: Running LUA method 'update'.
2019-12-30 17:01 C:/Users/thad/Documents/my games/FarmingSimulator2019/mods/Courseplay_6_01_00350/vehicles.lua:897: attempt to index field 'attacherJoint' (a nil value)
2019-12-30 17:01 Error: Running LUA method 'update'.
2019-12-30 17:01 C:/Users/thad/Documents/my games/FarmingSimulator2019/mods/Courseplay_6_01_00350/vehicles.lua:897: attempt to index field 'attacherJoint' (a nil value)
2019-12-30 17:01 Error: Running LUA method 'update'.

To reproduce on this save: tab to the syn trac tractor, open courseplay and create a course, backup to the mf 3012 trailer and attempt to attach.

**Comment by thadeausmaximus** [comment] 2019-12-31 01:18
it is a duplicate of 3968 with more information so hopefully it can be fixed now. It only occurs with certain objects. The mf 3012 sugarcane trailer is the first thing I bumped into the bug with. It seems to have more to do with what is attached and how the standard adapter interacts because it doesn't happen when I use the 3 axle tractor configuration that has the hitch built in to the tractor instead of connecting through the adapter. Interestingly it doesn't occur when using the 3 axle version of the syn trac even when using the standard adapter on the front and connecting to the mf 3012 through it. Could it be due to multiple possible attachment points?

**Comment by pvaiko** [comment] 2019-12-31 17:56
Duplicate of #3968

**Comment by pvaiko** [comment] 2019-12-31 17:57
Not sure if we'll ever have the time to fix this. Just out of curiosity, does it work with the in game helper?

**Comment by thadeausmaximus** [comment] 2020-01-02 06:07
No problem with the in game helper. Is there something that scans the attachers on the tractor and there are too many of a single type available with this mod?

**Comment by Petje81** [comment] 2020-01-28 22:11
Exact same problem with the [Adapter](https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=146352&title=fs2019) that got released today on v377, vehicles.lua:897: attempt to index field 'attacherJoint' (a nil value).

Connect the adapter to the 3-point link, connect something like a seeder to the adapter, set course, press start and all is stuck.
After loading that savegame the screen is dimmed and the save is stuck..

**Comment by Tensuko** [comment] 2020-03-09 08:58
Related Issues are closed and also got a fix so I would guess this is fixed, if not make new Issue with log pls.

**Closed by Tensuko** 2020-03-09 08:58 UTC
Labels: Mod Issue
