### ISSUE TITLE
Combines don't lower the head after the rain stopped

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#5231] opened 2020-04-24 10:42 UTC
Hello all,
as title said I experinced the issue with headers not lowering when the rain stops during the harvest. Combines stopped and rise headers when rain started and when the crops were dry again they start their course but did not lower their heads. I had 5 combines na same field 1 of them actually left header lowered all the rain I think it was probably because he was unloading when rain started. Log is here, not sure if there will be something usefull. I saved the game after I restarted all combines again. Gonna say I use Seasons on the map which is not supported, but don't think it has any impact on this.
[log.txt](https://github.com/Courseplay/courseplay/files/4528369/log.txt)

**Comment by Tensuko** [comment] 2020-04-24 11:19
Duplicate of #5039

**Closed by Tensuko** 2020-04-24 11:19 UTC
