### ISSUE TITLE
whats wrong with the Veenhuis W400 from modhub

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2076] opened 2017-05-17 05:13 UTC
hello guys,
i use the Veenhuis W400 from modhub
http://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=75622&title=fs2017
i love this trailer and he is useful for me to unload in low buildings, while this is not a tipper who needs highroom above when tipping.
but yesterday i note, i cant use this trailer to push back ???
i cant drive in a curse with push back but the trailer only push back straight in a line, he dont follow the course if the course is a curved line.
what is wrong with this trailer?
is there a missing thing in the i3d or the xml ?
btw what must i change in the trailer to get the full push back funktion?

lg
andreas

**Comment by tatti14** [comment] 2017-05-17 09:36
I have the same prob with this trailer after the Veenhuis has been updated.
Probs while pushing back into a BGA-Silo and also while pushing back near a harvester (didn't stop and pushes back into other fields).

LG
Karsten

**Comment by Blackmankot** [comment] 2017-05-17 15:52
Good afternoon! Sorry, but to write about one mod, which suddenly stopped working correctly - it's not rational! Authors need to be notified when the problem is global, when all mods do not work correctly! Look at how many open questions that the authors need to correct! Think of it!

**Comment by pops64** [comment] 2017-05-17 23:26
Yea. That's why we label mods issue so we know what needs to be prioritized. Could we get a video with debug channel 13 and the log from that video. Thanks. I would 
 also contact the author about this seeing how you said he did a update which broke this mod with CP. Mostly likely changed something CP needs to reverse correctly

**Comment by andreasthu** [comment] 2017-05-18 11:19
Hello guys
here is the log:
[log.txt](https://github.com/Courseplay/courseplay/files/1010648/log.txt)

and the video:
http://www.filehosting.at/file/details/666380/FarmingSimulator2017Game%202017-05-18%2012-58-51-48.avi
(1,2GB)

lg
andreas

**Comment by andreasthu** [comment] 2017-05-18 11:25
@Blackmankot,
sorry for your attitude
i know that its an mod, i write this, for eeryone to see, also in the title.
i dont call for an fix for this tipper.
i ask only whats wrong with this tipper.
maybee the modder from the veenhuis has forgotten to make a needet index-entry or so.
onla the cp-guys know what indexe the vehikles need for this.
maybe i am able to make this entry in the i3d or the xml as self but i dont know which is missing
so i hope the cp-guys tell me the answer
lg
andreas

**Comment by pops64** [comment] 2017-05-21 21:58
Everything looks fine in the log. Need a video on a clean link ex, you tube, drop box, google drive etc. or a picture of debug channel 13 when the lines pop up with all the waypoints on.

**Comment by andreasthu** [comment] 2017-05-22 06:23
Video is to download from filehost.at
The link in my post.
Or what you mean with "clean link" ?
Can't you download the video from filehost?
I will see that i make a screenshot wit channel 13 and the lines and try to load the video up to you tube, drop box, google drive but i didnt this before. 
Lg
Andreas

**Comment by andreasthu** [comment] 2017-05-22 10:36
ok,
here is the youtube link

https://youtu.be/3W_aPgEjl6I

**Comment by theSeb1979** [comment] 2017-05-22 23:28
There is something wrong with this particular trailer. Not much that CP can do, in my opinion. I have seen this problem on youtube videos (rdallen for example) and experienced them myself.

**Comment by pops64** [comment] 2017-05-22 23:47
Ok. The problem for not possible to fix at the moment. For what ever reason CP thinks your trailer is like the agroliner hdk 302

**Comment by andreasthu** [comment] 2017-05-24 06:28
Thanks for use your time.
Then will i look for another lowtip trailer until the problem is open.
Lg
Andreas

**Comment by Blackmankot** [comment] 2017-08-05 01:09
@pops64 And I propose to close this issue for cleaning.

**Comment by pops64** [comment] 2017-08-12 19:49
Collapsing mod issues into one thread. #2231

**Closed by pops64** 2017-08-12 19:49 UTC
Labels: Mod Issue
