### ISSUE TITLE
Realistic Seed Storage won't work with CP

### ISSUE THREAD

**Issue by breadje** [Courseplay/courseplay#7233] opened 2021-06-02 18:29 UTC
You can't place the realistic Seed Storage (mod from modhub) when courseplay is also loaded as mod in the game. You get the error 'to many objects of this type' error when you try to place it. This did not happen with the precious official CP release. 
[log.txt](https://github.com/Courseplay/courseplay/files/6586685/log.txt)

**Comment by Tensuko** [comment] 2021-06-02 19:14
Link to that mod ?

**Comment by leo32128fs** [comment] 2021-06-03 00:44
I also noticed this when we used the global Company

**Comment by Tensuko** [comment] 2021-06-03 05:16
> 
> 
> I also noticed this when we used the global Company

I can tell you for 100% that GC and CP works very well together.
Or did you mean Global Company + Real Seed Storage ?

**Comment by leo32128fs** [comment] 2021-06-03 13:59
no , only global company I don't use this other mod ai Real Seed Storage , but it's giving this problem without the courseplay-release-creator version released this 11 days ago

**Comment by leo32128fs** [comment] 2021-06-03 14:04
but I don't see a problem with that as I always use the latest officially released version

**Comment by leo32128fs** [comment] 2021-06-03 14:05
this one works without problems perfectly

**Comment by Tensuko** [comment] 2021-06-03 17:22
Can you test the latest push and report if it does work now ?

**Comment by leo32128fs** [comment] 2021-06-03 18:03
yes i can do it now

**Comment by breadje** [comment] 2021-06-03 18:23
That was very quick, but it did fix the problem, Thanks!

**Comment by leo32128fs** [comment] 2021-06-03 18:23
The GC seems to be working fine now, only the bunker silo is not being recognized by the CP

**Comment by leo32128fs** [comment] 2021-06-03 18:26
[Uploading log.txt…]()

**Comment by leo32128fs** [comment] 2021-06-03 18:26
[log.txt](https://github.com/Courseplay/courseplay/files/6593582/log.txt)

**Comment by Tensuko** [comment] 2021-06-04 05:17
> 
> 
> The GC seems to be working fine now, only the bunker silo is not being recognized by the CP

Since I don't know what Bunker Silo and how you made your course with the Bunker silo I can't tell you if it is a User or CP Error!

**Comment by leo32128fs** [comment] 2021-06-04 12:06
[https://drive.google.com/file/d/1krIwt-_6EfIYGt4aoJRRitZ5N6vDJ10-/view?usp=sharing](url)

**Comment by leo32128fs** [comment] 2021-06-04 12:07
> > O GC parece estar funcionando bem agora, apenas o silo bunker não está sendo reconhecido pelo CP
> 
> Já que eu não sei o que Bunker Silo e como você fez o seu curso com o silo Bunker eu não posso dizer se é um Erro de Usuário ou CP!

I sent a video showing the problem ok

**Comment by leo32128fs** [comment] 2021-06-04 12:10
https://drive.google.com/file/d/1krIwt-_6EfIYGt4aoJRRitZ5N6vDJ10-/view?usp=sharing

**Comment by Tensuko** [comment] 2021-06-04 13:50
So it is unloading.
The course has totaly changed, give me some time I will explain that in a Video later.

**Comment by leo32128fs** [comment] 2021-06-04 13:54
> So it is unloading (or better say empty with Mode9)
> The course has totaly changed, give me some time I will explain that in a Video later.

Ok, friend, thank you

**Comment by Tensuko** [comment] 2021-06-07 15:33
Problem of the Issue is solved at the Branch.
Mode9 is other Issue. Closing.

**Closed by Tensuko** 2021-06-07 15:33 UTC
Labels: waitingForUserAnswer
