### ISSUE TITLE
Version .00326 tractor turns off and wage issue again

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4512] opened 2019-11-03 18:24 UTC
Worker was doing fine, then suddenly stopped working.
When i try to start course, it just stand and do nothing, it tries to turn on tractor, but fails
Workers still take wage even if its deactivated in options. I think it was working perfect in 324 or 325 build.

https://www.youtube.com/watch?v=6nbIz8MeZqg&
https://youtu.be/HXtwj5xvo3I

**Comment by pvaiko** [comment] 2019-11-04 01:47
turning off is most likely a duplicate of #4510 

The wages: honestly I don't understand how it works.

**Comment by Tensuko** [comment] 2019-11-04 06:03
The strange hing about wage is, that it only appears if you hired a normal helper once, even if you just hit H by accident and FS says Helper has finished the work (like instantly) then CP Helpers take wage.... Not sure if we are even able to do something about it or if it is problem of the game...

**Comment by bojanh66** [comment] 2019-11-04 07:50
I didnt hire normal worker, i dont even use them since CP is doing 99% of the jobs.
That bug appears randomly :/, but i think, although not 100% sure, that worker wage was doing perfect in 1-2 release earlier

**Comment by pvaiko** [comment] 2019-11-04 11:52
No idea how it could have worked before. As of now, when you turn it off in CP (or even if I remove the entire code doing it), the Giants AIVehicle spec pays wages, not always, but definitely after the helper is first invoked. Will ask Giants, or maybe @Stephan-S knows, I see he is actually adding money in AD to compensate for this.

**Comment by pvaiko** [comment] 2019-11-04 14:56
This should now really work with 328.

**Comment by Tensuko** [comment] 2019-11-04 16:46
Looks like it works the same way as in AD, the money is flickering, but cause no Error, so this is fixed.
Closed.

**Closed by Tensuko** 2019-11-04 16:46 UTC
Labels: try to reproduce

**Comment by ontot** [comment] 2019-11-04 23:25
it's normale. the cp had always problems with autodrive... in the fs17 too.

**Comment by Tensuko** [comment] 2019-11-05 05:58
FS17 is FS17.
This is FS19 and CP doesn't have problems with AD.
Stop shout untrue stuff arround!

**Comment by bojanh66** [comment] 2019-11-05 06:17
Yes, wage works now perfect.
And CP didnt had any problems with AD, because i always tested wage issue with and without AD to see if there's any conflict and problem was the same, but thankful to the CP team, its fixed now.

**Comment by Stephan-S** [comment] 2019-11-05 07:26
Yeah, no one should have any problems with AD :-)
CP and AD work together like a charm!
