### ISSUE TITLE
6.1.00103: Cannot open HUD when right-click to open is disabled and CP is driving a different vehicle

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#3329] opened 2019-03-02 01:16 UTC
- When I switch the "open hud with" to Ctrl+Delete (and thus disable right-click to open) I can no longer open the HUD for that vehicle as long as CP is driving a different vehicle. In the vehicle CP is driving, it is still possible to open the HUD this way.
- When pressing Ctrl+Del in an attempt at open the HUD (in the vehicles where it's now inaccessible), it plays the click-sound for the HUD opening the first time the keys are pressed, but the actual HUD is never drawn, and following key-presses do nothing.
- In any vehicle where the right-click to open the HUD is still enabled, the HUD will open no matter if any CP drivers are active or not.
- When all CP drivers are dismissed it again becomes possible to open the HUD with either method in all vehicles.

CP 6.1.00103 dev / FS 19 1.0.3 beta

**Comment by Hubcap-1** [comment] 2019-03-02 12:25
I'm having a similar issues If someone was to tell me the debug channels to run for the ui  I will  recreate the issue and submit video and GIST info.

**Comment by Innallas** [comment] 2019-03-02 12:32
I got the same trouble, wait a bit i'll take a look in HuD :) never saw this file :D 
Edit : i think i foud something i'll test with other stuffs.

**Comment by sootysax** [comment] 2019-03-02 13:55
#3101 duplicate

**Comment by Innallas** [comment] 2019-03-02 14:16
It's DONE ! :) It's working, i will submit new modification here, until you can download this "hud.lua" then open your zip > move it into and replace the original.

You will be able to always open HUD with your Keyboard-Key, then if you disable the right click (for big vehicle who use lot of function) it work :) (it may need a little adaptation time (seconds) for the hud to be refreshed but it work nicely)

**Comment by sootysax** [comment] 2019-03-02 15:59
@Innallas - you need to read Thomas' comment #3326

**Comment by knarffenfarmer** [comment] 2019-03-03 09:58
I tried using his med HUD_XML dosnt work for me with the reload or reassign button.
I still cant open the the CoursplayHUD when I go from right mouse button to the standard LeftCtrl + Delete.

**Comment by Meliandah** [comment] 2019-03-03 12:56
It was not so easy, in fact the Settings are not reloaded during the game (only after loading a savegame)
I proposed the solution : https://github.com/Courseplay/courseplay/pull/3347
I tried it and it's working nice :)

**Comment by sootysax** [comment] 2019-03-03 13:24
@ThomasGaertner: @Innallas just opened a new account as @Meliandah to get around the ban..   I saw both names on the blocked profile yesterday.

**Comment by ThomasGaertner** [comment] 2019-03-03 13:27
@sootysax : allready done

**Comment by sootysax** [comment] 2019-03-03 13:31
@ThomasGaertner Unbelievable..  possible to block IP address?

**Comment by OmgBrother** [comment] 2019-03-03 13:59
Oh my god it was my little brother !!! By the way it's working what i did !! 
Also your function "onActionBindingChanged" is never called (this is why we have this bug now)

And you just need to recall a load at the end of "execute" function in "inputs.lua" with this :

if vehicle ~= nil then
        courseplay.loadVehicleCPSettings(vehicle, courseplay.savegame_custom.xmlFile, courseplay.savegame_custom.key, courseplay.savegame_custom.resetVehicles);
end;

My pull request is working well now... but well i see why it s never moving here and why there are more and more bug.... my brother was right you do lot of shit, i bet no one of you have degree in computing.

OMG you re stupid its awesome, i see why there are so few people trying to help when we see your childish behavior. 

-"Only truth hurt"

**Comment by sootysax** [comment] 2019-03-03 14:01
@ThomasGaertner And another one.. this guy is a sociopath.  I'm going to keep reporting new accounts as abusive to Github Support, and hopefully they block his IP Address

**Comment by OmgBrother** [comment] 2019-03-03 14:02
Yeah you are really a poor dumb guy @sootysax  :D as i said IT WAS MY BROTHER, do you read english ?

**Comment by OmgBrother** [comment] 2019-03-03 14:02
While waiting this bug is corrected if you follow or try what i showed

**Comment by sootysax** [comment] 2019-03-03 14:04
Noone should use any code that this guy posted, I have to assume it is malicious

**Comment by corrado33** [comment] 2019-03-07 04:22
I had the same issue. It's worth noting that "resetting" the vehicle will reset the CP button to be the default (right mouse.) 

I even tried changing the keys when this was happening to no effect.

**Comment by Anonymous-any** [comment] 2019-03-07 19:17
It's worth noting that "resetting" the vehicle will reset the CP button to be the default (right mouse.)
Good to know !
for complete this, if some ppl don't know and want to reset them, then search for `openHudWithMouse="false"` value into vehicle.xml savegame file then switch "true" the concerned vehicle name.

**Comment by Hubcap-1** [comment] 2019-03-07 23:47
@ Anonymous-any "openHudWithMouse="false" value into vehicle.xml savegame file then switch "true" the concerned vehicle name."
* And there in is the root of the whole problem* Dev should make this a universal command incorporated into the UI itself. It should have nothing to do with the " Tractor" I'm in.  They need to simplify this command. Give the two options, and then it applies to ALL vehicles.

**Comment by Hubcap-1** [comment] 2019-03-08 09:17
Can we please change the Hud  " open / close" to one choice for all vehicles rather than making it Dependant on which vehicle your in. If this does not solve it it will surely make identifying the problem much easier. I have one vehicle that is doing this in a particular save game when all other vehicles are working fine.

**Comment by sootysax** [comment] 2019-03-09 15:02
> Can we please change the Hud " open / close" to one choice for all vehicles rather than making it Dependant on which vehicle your in. If this does not solve it it will surely make identifying the problem much easier. I have one vehicle that is doing this in a particular save game when all other vehicles are working fine.

@Hubcap-1 No, thats a terrible idea.   I would rather not have vehicles that I am never going to use CP with, that have right mouse click controls open up with the right mouse click (wheel loaders, skid steers etc).   I would rather have them set to Left Ctrl + Delete, and most other vehicles to Right Click.

**Comment by Hubcap-1** [comment] 2019-03-09 22:55
My Point exactly...I never use right click as it interferes with other options / mods I suspect Right click interferes with the game as well

**Comment by sootysax** [comment] 2019-03-12 12:49
> My Point exactly...I never use right click as it interferes with other options / mods I suspect Right click interferes with the game as well So I will add to my request that they remove right click as an option all together

I think they have to get the key bindings working first..  because they only work on a fraction of my vehicles

**Comment by Hubcap-1** [comment] 2019-03-12 12:53
Well it certainly is first and foremost if you can't even start the course
play or it doesn't work simply because the HUD. thisI think they need to
make this the first priority somehow it's on the back burner

**Comment by sootysax** [comment] 2019-03-12 13:25
they changed how key bindings work in FS19 and its giving alot of modders problems..  be patient

**Comment by StreelRodent** [comment] 2019-03-15 22:58
Not sure if the last few builds has aggravated the problem or if there's more to it than I noticed at first. When the HUD is open I can't control CP with the shortcut keys at all (at least not once CP is driving, which is when I need it), and when a vehicle reaches its endpoint, just pressing Ctrl by itself makes CP restart the course without hitting any other keys. Bit of an issue when CP misbehaves and I need to emergency stop the drivers. It's still workable nonetheless.

**Comment by Hubcap-1** [comment] 2019-03-15 23:12
I agree that the past few builds have aggravated the Problem.

**Comment by Hubcap-1** [comment] 2019-03-17 05:48
How do you “ Emergency stop” the driver. I have to restart the game to regain control.

Sent from Mail for Windows 10

**Comment by ThomasGaertner** [comment] 2019-03-17 07:04
write 'cpStopAll' to the console

**Comment by Hubcap-1** [comment] 2019-03-17 07:12
Cool...thanks

**Comment by StreelRodent** [comment] 2019-04-05 15:23
You're supposed to be able to hit Ctrl+Num 7 to stop any driver you're riding with, but alas it's a bit up and down if it works atm.

There are still some cases where CP seems to break completely and the drivers go completely nuts that require restarting the game, but I trust that it will be fixed eventually once everything else works as intended. Will report it properly once I figure out how to replicate these cases.

**Comment by Tensuko** [comment] 2019-04-17 20:10
Should be fixed, if any more trouble, let me know and we reopen it.
Closed.

**Closed by Tensuko** 2019-04-17 20:10 UTC
