### ISSUE TITLE
CoursePlay and AI traffic (Maybe old Mode2 related)

### ISSUE THREAD

**Issue by dexus92** [Courseplay/courseplay#4219] opened 2019-09-10 16:17 UTC
Hey.

I noticed a problem with AI traffic and CoursePlay courses, e.g. transport etc.
You can see ii watching video: https://youtu.be/NEV5uJMsvag

**Comment by Tensuko** [comment] 2019-09-10 16:33
Screenshot or Video with F5 active.

**Comment by dexus92** [comment] 2019-09-10 16:49
I try and try reproduct it and I can't but if I can see it again tell me what option F5? First? Second or third?

**Comment by Tensuko** [comment] 2019-09-10 17:40
1st, you will see some orange Arrows, if not, the Vehicle has no collision detection.

**Comment by dexus92** [comment] 2019-09-10 18:09
Ok. I do it. You can see it there: https://youtu.be/WpLWkenZQaQ

**Comment by Tensuko** [comment] 2019-09-11 07:27
@Axel32019 do you know what the Problem is here ?

**Comment by Axel32019** [comment] 2019-09-11 16:23
Hello,
The problem is the big orange box, which stops the AI traffic.
I suggest  the following:
1. @pvaiko In the next release please remove the 4x "if ....getAINeedsTrafficCollisionBox... then" completely
    To be found in AIDriver.lua and start_stop.lua
2. For Users:
    - If you observe this problem stop the CP driver
    - Select mode1 and start the CP driver
    - If the vehicle starts to move stop the CP driver
    - Select the Mode you want to operate and start the CP driver
    Now the big orange box should not to be seen and all vehicles should move.

**Comment by Tensuko** [comment] 2019-09-11 16:34
Thx @Axel32019 
Can you (or did you already) test that ?

**Comment by Slick001** [comment] 2019-09-14 01:21
Axel's work around didn't work for me. the problem is at the AI traffic is stopping once the CP vehicle gets within a certain range of the AI traffic. So If your on the roadway and come up behind an AI car. it throws on the breaks and you slam into it. I stop the CP driver and restart and then it happens again unless i either slow it down or allow AI traffic to get enough lead that it the CP driver wont catch back up.

**Comment by Slick001** [comment] 2019-09-14 01:29
Here is a screen shot of the AI traffic stopping on the road as they drive by the potato harvester. They stop and block the harvester as a result. I failed to open the field up with a couple header rows, that would solve this problem. But the AI are still stopping when any CP vehicle gets close.
![fsScreen_2019_09_13_20_26_11](https://user-images.githubusercontent.com/54826978/64901956-f0690980-d664-11e9-9f97-2ca3cf94a125.png)

**Comment by Axel32019** [comment] 2019-09-14 16:13
@Tensuko Now I observed it again. **Correction for the workaround: Start Mode2 for a short time, not Mode1.**
@Slick001 This is as mentioned due to the big orange box, which stops the AI traffic. You may enable to see it with F5 key if your game.xml contain this:
```
    <development>
        <controls>true</controls>
    </development>
```

**Comment by Slick001** [comment] 2019-09-27 19:10
ok thank you, I ended up just turning off the traffic for now until its fixed. The Mode 2 thing on and off briefly doesnt seem to be working for me.

**Comment by Tensuko** [comment] 2020-03-09 07:38
#3311 and Refernce Information.

**Comment by Tensuko** [comment] 2020-07-15 07:45
Might be fixed. Closing this one.

**Closed by Tensuko** 2020-07-15 07:45 UTC
Labels: postponed
