### ISSUE TITLE
courseplay using money when its not supposed to

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#3929] opened 2019-06-25 15:55 UTC
courseplay helpers use money if you use them after you use ingame helper "H" key. reloading the game fixes until h is pressed again.  the money in the config is set to false and 0.

**Comment by Tensuko** [comment] 2019-06-25 17:47
How about seed and fertilizer ? Set to not buy in option ?

**Comment by shadow250** [comment] 2019-06-25 18:20
in game options its set not to buy anything i didnt see anything in the config file for that. and also i was plowing with nothing else going when i noticed it.

**Comment by Tensuko** [comment] 2019-06-25 19:49
Ok I will take a look at that when I got time.

**Comment by sootysax** [comment] 2019-06-25 23:45
i beleive this is a Follow Me conflict..

**Comment by Tensuko** [comment] 2019-06-26 05:02
Did you try it with only CP and CP+Follow Me ? Without any other Mods ?

**Comment by Dylan-z-Thompson** [comment] 2019-06-26 11:44
i have this issue as well.  further details:
money is spent paying CP helpers as normal until in-game helper is invoked.  from that point, until restart, any time CP helper is used, regardless of whether or not there is an in-game helper running, both are paid.
this can be determined by watching the money tick down.  for in-game helpers it ticks down constantly in 1 unit decrements.  for CP helpers, it ticks down every 4 or five seconds, in large decrements depending on the amount you have configured for CP helpers to be paid .  when the issue is present, the constant ticking down occurs, as well as the 4-5 second larger decrements.  again, regardless of whether or not there is currently an in-game helper running.
i can confirm this is occurs without Follow Me.

**Comment by shadow250** [comment] 2019-06-26 12:55
i do not have the follow me mod eithier.

**Comment by iljarogoff** [comment] 2019-06-26 15:18
Having this issue too from time to time and have no idea how to reproduce it.

**Comment by Tensuko** [comment] 2019-06-27 17:43
Happens in Vanilla + CP
Is a bug.

**Comment by sootysax** [comment] 2019-07-26 12:52
My issue is that even when you do want the CP helpers to get paid, they continue to get paid after they are finished with the course... and will draw pay until you manually stop the course..

Is there any way to have the course stop automatically when it is finished?

**Comment by Tensuko** [comment] 2019-07-26 12:54
I think that would be possuble with something like end CP Driver whrn finished. But then you dont have that msg anymore... Would have to discuss this... Maybe there is another way

**Comment by iljarogoff** [comment] 2019-10-23 03:51
> 
> 
> Happens in Vanilla + CP
> Is a bug.

Anything new about it? Still having that issue

**Comment by Tensuko** [comment] 2019-10-23 05:14
No Idea since I don't have this Issue.
But I put AD wage down to 0% in AD Settings.
I will reference this here and close this, as it is very similar #4345
Closed.

**Closed by Tensuko** 2019-10-23 05:14 UTC
Labels: bug
