### ISSUE TITLE
mode1 trailer unload in bga bunker but don't close before driving away

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#4618] opened 2019-12-01 14:45 UTC
if it drives backward into the BGA bunker it dumps and drives a few times forward for unloading further. then it drives away out of the bunker, but don't close the trailer. its the latest version.

**Comment by Tensuko** [comment] 2019-12-01 15:52
That also happens when you tip manualy, not sure if can do anything about it.
Duplicate of #4534

**Closed by Tensuko** 2019-12-01 15:52 UTC

**Comment by candymant** [comment] 2019-12-01 16:01
if I tip manually with ctrl+i then it closes after its empty

**Comment by Tensuko** [comment] 2019-12-01 16:28
From personal test and other ppl try out as well I can tell you, that it will happen when you tip manually.
We think, that this happens when the hill starts to grow and you slowly advance while unloading.
When reach close to 0% or even are at 0% and advance, it will stuck and even it shows 0% you can still drip out a tiny bit... thats rly a Problem from the game, I already have Ideas in mind, that we could repair this with CP, but not sure about what we can rly do in the end. sry.
