### ISSUE TITLE
Why does Courseplay not work with Mods with IC? It did in the FS17, didnt it?

### ISSUE THREAD

**Issue by NIGE2057** [Courseplay/courseplay#4679] opened 2019-12-22 06:46 UTC
I really like to play with courseplay but it doesnt work with IC anymore like it did in the FS17... Why? Or is it an issue of the mods?

**Comment by Tensuko** [comment] 2019-12-22 11:36
Why is FS19 different then FS17 ?
Why does everyone make the mods different then FS17 ?
......
Duplicate of #4185
Closed.

**Closed by Tensuko** 2019-12-22 11:36 UTC
