### ISSUE TITLE
mode3.lua:24: attempt to perform arithmetic on a nil value Running LUA method 'update'.

### ISSUE THREAD

**Issue by Dilligaf1981** [Courseplay/courseplay#4462] opened 2019-10-28 18:53 UTC
I'm getting an mode3.lua:24 error when i try to use an auger wagon to off load a harvester. The thing i noticed is I can't select the option to offload the harvester to trailer option. I just have the load/unload and combine offload. After loading the course the game just locks up and if i turn off the course fast enough I don't have to force shutdown the game. I've tried the same course with a trailer and it works just fine. I'm just using a stock auger and trailer. I've removed all my mods but CP and Autodrive with the same outcome.

https://pastebin.com/6dFJYLWU

**Comment by Tensuko** [comment] 2019-10-28 19:13
Duplicate of #3996
Closed.

**Closed by Tensuko** 2019-10-28 19:13 UTC
