### ISSUE TITLE
duplicate tractor in overview

### ISSUE THREAD

**Issue by zed636** [Courseplay/courseplay#2109] opened 2017-06-07 22:37 UTC
I want to send you this issie when using CP: 
the tractor is duplicated in overview like these images
[log.txt](https://github.com/Courseplay/courseplay/files/1059491/log.txt)
![fsscreen_2017_06_08_00_32_43](https://user-images.githubusercontent.com/19471664/26904443-3d18f7e6-4be2-11e7-9fb2-8d595ce41db1.png)
![fsscreen_2017_06_08_00_32_34](https://user-images.githubusercontent.com/19471664/26904439-37a363fa-4be2-11e7-9612-bdbb01b98c9b.png)
after stop the course:
![fsscreen_2017_06_08_00_33_00](https://user-images.githubusercontent.com/19471664/26904454-49739870-4be2-11e7-9cd1-906d3eb26f23.png)
vanilla game (mod folder empty)  version 1.4.4.0 1.4.4RC8
CP  version 5.01.00145

Thanks for your work!

**Comment by pops64** [comment] 2017-06-08 23:41
Other than the duplicate is this causing any other issues. Other wise this is going to be postponed until CP is out of beta

**Comment by zed636** [comment] 2017-06-09 07:09
No other issue detected

**Comment by pvajko** [comment] 2017-08-28 17:14
This is a duplicate of #1676

**Closed by pvajko** 2017-08-28 17:14 UTC
Labels: bug, postponed
