### ISSUE TITLE
Fertilizing with Kuhn and Hardi components

### ISSUE THREAD

**Issue by tuzlo** [Courseplay/courseplay#2959] opened 2019-01-27 22:14 UTC
When fertilizing a field with  Hardi mega 2200 or Kuhn Deltis 1302 MTA3 CP did recognize the fertilizer in the Kuhn PF 1500 attached to the front end of the tractor.

**Comment by pvajko** [comment] 2019-02-10 21:46
Fixed, duplicate of #3034.

**Closed by pvajko** 2019-02-10 21:46 UTC
