### ISSUE TITLE
CP don't brake at end of Track by using "COURSEPLAY_STOP_AT_LAST_POINT" in some modes

### ISSUE THREAD

**Issue by AlterSack1966** [Courseplay/courseplay#877] opened 2014-12-30 11:44 UTC
Hi 
When i activate COURSEPLAY_STOP_AT_LAST_POINT the vehicle roll out over the desired Stop Position. Can  you reinstall that CP the vehicle at the end of the route stops. It has done so in the previous CP version (V3.x).
Affected are the fertilize / seeding mode and the field work mode. In the other modes stops the vehicle on the right place (except shovel mode, i can not test it).

Best wishes for 2015.

![fsscreen_2014_12_30_12_09_38](https://cloud.githubusercontent.com/assets/10278670/5578127/771359de-9021-11e4-858a-3a201484ce45.png)

**Comment by ThomasGaertner** [comment] 2015-01-01 15:27
please post your courseplay.xml to gist and post the link and tell me which couses/fields/tools you used...

**Comment by AlterSack1966** [comment] 2015-01-02 07:45
Map:
Westbridge Hill (Original)

Courseplay.xml:
https://gist.github.com/AlterSack1966/6a47fbd512037d6c9a54

1th Sample:
Bührer 6135A / Suer SB 700 / Krone Swadro 2000 in mode 6 on Track-Combo "AbfahrtParkplatz(5)Hof" & "FeldarbeitHof-16" & "16 18m 1xVorgew. danach" & "Feldarbeit16-Hof(W)" & "AnfahrtParkplatz(6)Hof(W)"

2nd Sample:
Deutz AgroStar 6.61 / Suer SB 1000 / Pöttinger Vitasem 302A (100%) in mode 4 on Track-Combo "AbfahrtSaatgutHof" & "FeldarbeitHof-16" & "16 18m 1xVorgew. danach" & "Feldarbeit16-Hof(W)" & "AnfahrtSaatgutHof(W)"

**Comment by AlterSack1966** [comment] 2015-01-02 07:47
Sorry for this mistake

**Comment by ThomasGaertner** [comment] 2015-01-02 09:37
hmm , could you test it again with debug channel 12 active and post the log ?
how do you connect the courses: with the folder icon or the folder icon with the + sign in it ?
I can not get it, works fine for me...

**Comment by Satissis** [comment] 2015-01-02 10:01
Could you post your log as well

**Comment by AlterSack1966** [comment] 2015-01-02 15:12
OK, I've tested it twice:
1th 
 Bührer 6135A / Suer SB 700 / Krone Swadro 2000 in mode 6 on Track-Combo "AbfahrtParkplatz(5)Hof" & "FeldarbeitHof-10" & "10 18m 1xVorgew. danach" & "Feldarbeit16-Hof(W)" & "AnfahrtParkplatz(5)Hof(W)"
Result: :+1: Worked fine :+1: 

2nd
 Deutz AgroStar 6.61 / Suer SB 750 / Pöttinger Vitasem 302A (100%) in mode 4 on Track-Combo "AbfahrtSaatgutHof" & "FeldarbeitHof-10" & "10 03m 1xVorgew. danach" & "Feldarbeit10-Hof(W)" & "AnfahrtSaatgutHof(W)"
Result: :-1: Worked wrong :-1: 
![fsscreen_2015_01_02_15_47_37](https://cloud.githubusercontent.com/assets/10278670/5596875/90f9cb16-9298-11e4-9e48-aa30c2ef0b8c.png)

The courses are combinatet with the folder icon with the + sign in it. Is there a difference if there is no cross points within the used Tracks?

Here is the Log:
GIANTS Engine Runtime 6.0.2 64bit (Build Date: Dec  8 2014)
Copyright (c) 2008-2014, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2014, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Memory: 8152 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: F430 Force Feedback
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software Compatibility Mode
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: GeForce GTX 660 Ti/PCIe/SSE2
  Version: 4.5.0 NVIDIA 347.09
  Shader Version: 4.50 NVIDIA
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: High (auto)
  View Distance Factor: 1.100000
  Shadow Quality: 1.000000
  Skip Mipmaps: 0
  LOD Distance Factor: 1.100000
  Terrain LOD Distance Factor: 1.500000
  Foliage View Distance Factor: 1.400000
  Volume Mesh Tessellation Factor: 0.850000
  Tyre Tracks Segments Factor: 2.000000
Farming Simulator 15
  Version: 1.2.0.0 1.2 RC6
  Available Languages: de
  Language: de
Game vehicle types loaded
Mod directory: \\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/mods/
Load mod: ZZZ_Courseplay
### Courseplay: initialized 38/38 files (v4.01.0010)
    ******************************************* WARNING *******************************************
    * You are using a development version of Courseplay, which may and will contain errors, bugs, *
    * mistakes and unfinished code. Chances are your computer will explode when using it. Twice.  *
    * If you have no idea what "beta", "alpha", or "developer" means and entails, remove this     *
    * version of Courseplay immediately. The Courseplay team will not take any responsibility for *
    * crop destroyed, savegames deleted or baby pandas killed.                                    *
    ***********************************************************************************************
### Courseplay: installed into 20 vehicles
data/sky/sky_day_night.i3d (6.91 ms)
data/sky/rain.i3d (0.79 ms)
data/sky/hail.i3d (0.63 ms)
data/sky/dust.i3d (0.49 ms)
data/maps/map02.i3d (5368.36 ms)
## Courseplay: setting up signs
\\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/mods//ZZZ_Courseplay/img/signs/normal.i3d (0.39 ms)
\\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/mods//ZZZ_Courseplay/img/signs/cross.i3d (0.57 ms)
\\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/mods//ZZZ_Courseplay/img/signs/wait.i3d (0.74 ms)
\\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/mods//ZZZ_Courseplay/img/signs/start.i3d (0.72 ms)
\\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/mods//ZZZ_Courseplay/img/signs/stop.i3d (0.68 ms)
## Courseplay: setting up fields (basic)
## Courseplay: loading settings from "courseplay.xml"
## Courseplay: setting up hud
## Courseplay: setting up debug channels
## Courseplay: setting up globalInfoText
## Courseplay: loading courses and folders from "courseplay.xml"
data/vehicles/steerable/deutz/deutzAgroStar661.i3d (106.32 ms)
dataS2/character/player/player.i3d (317.39 ms)
data/vehicles/steerable/huerlimann/huerlimannH488.i3d (31.81 ms)
data/vehicles/steerable/sampoRosenlew/sampoRosenlewC6.i3d (53.91 ms)
data/vehicles/steerable/buehrer/buehrer6135A.i3d (16.40 ms)
data/vehicles/tools/koeckerling/koeckerlingTrio300M.i3d (16.78 ms)
data/vehicles/particleAnimations/koeckerling/koeckerlingTrio300M.i3d (3.32 ms)
data/vehicles/tools/poettinger/poettingerVitasem302A.i3d (18.86 ms)
data/vehicles/particleAnimations/poettinger/poettingerVitasem302A.i3d (0.82 ms)
data/vehicles/trailers/brantner/brantnerE8041.i3d (7.17 ms)
data/vehicles/cutters/sampoRosenlew/sampoRosenlewC6.i3d (13.08 ms)
data/vehicles/tools/suer/suerSB700.i3d (2.70 ms)
data/vehicles/tools/amazone/amazoneZAM1501.i3d (11.76 ms)
data/vehicles/trailers/kroeger/kroegerHKD302.i3d (16.68 ms)
data/vehicles/balers/newHolland/newHollandBB1290.i3d (18.20 ms)
data/maps/models/objects/squarebales/baleStraw240.i3d (2.36 ms)
data/vehicles/tools/suer/suerSB1000.i3d (0.66 ms)
data/vehicles/tools/krone/kroneSwadro2000.i3d (24.10 ms)
data/vehicles/trailers/arcusin/arcusinAutostackFS63-72.i3d (17.71 ms)
dataS/character/player/playerCCT.i3d (7.52 ms)
[dbg12 lp26192] 6135 A (#1): numWaitPoints=2, waitPoints[1]=54, numCrossingPoints=10
[dbg12 lp26192] 6135 A (#1): maxnumber=675, stopWork=616, finishWork=611, hasUnloadingRefillingCourse=true, recordnumber=674
[dbg12 lp26192] 6135 A (#1): validateCanSwitchMode(): drive=true, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=false
[dbg12 lp31472] 6135 A (#1): validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp31966] 6135 A (#1): numWaitPoints=2, waitPoints[1]=54, numCrossingPoints=10
[dbg12 lp31966] 6135 A (#1): maxnumber=675, stopWork=616, finishWork=611, hasUnloadingRefillingCourse=true, recordnumber=617
[dbg12 lp31966] 6135 A (#1): validateCanSwitchMode(): drive=true, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=false
[dbg12 lp38058] 6135 A (#1): validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp41421] AgroStar 6.61: validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp43764] AgroStar 6.61: validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp44509] AgroStar 6.61: validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp45024] AgroStar 6.61: validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp45529] AgroStar 6.61: validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp48775] AgroStar 6.61: validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp50162] AgroStar 6.61 (#2): numWaitPoints=2, waitPoints[1]=54, numCrossingPoints=10
[dbg12 lp50162] AgroStar 6.61 (#2): maxnumber=2862, stopWork=2838, finishWork=2833, hasUnloadingRefillingCourse=true, recordnumber=1
[dbg12 lp50162] AgroStar 6.61 (#2): validateCanSwitchMode(): drive=true, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=false
[dbg12 lp50446] AgroStar 6.61 (#2): validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp51595] AgroStar 6.61 (#2): numWaitPoints=2, waitPoints[1]=54, numCrossingPoints=10
[dbg12 lp51595] AgroStar 6.61 (#2): maxnumber=2862, stopWork=2838, finishWork=2833, hasUnloadingRefillingCourse=true, recordnumber=1
[dbg12 lp51595] AgroStar 6.61 (#2): validateCanSwitchMode(): drive=true, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=false
[dbg12 lp55143] AgroStar 6.61 (#2): validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp55672] AgroStar 6.61 (#2): numWaitPoints=2, waitPoints[1]=54, numCrossingPoints=10
[dbg12 lp55672] AgroStar 6.61 (#2): maxnumber=2862, stopWork=2838, finishWork=2833, hasUnloadingRefillingCourse=true, recordnumber=2839
[dbg12 lp55672] AgroStar 6.61 (#2): validateCanSwitchMode(): drive=true, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=false
Saving screenshot: \\SBS2K11/RedirectedFolders/Klaus/Documents/My Games/FarmingSimulator2015/screenshots/fsScreen_2015_01_02_15_47_37.png
[dbg12 lp88996] AgroStar 6.61 (#2): validateCanSwitchMode(): drive=false, record=false, record_pause=false, customField.isCreated=false ==> canSwitchMode=true

Many Thx for your help

**Comment by JakobTischler** [comment] 2015-01-06 19:40
After looking at your courseplay.xml, I gotta ask: what did you do with it? There must have been some editing going on. Your courses have position and angle values that could never come from regular recording within the game.

**Comment by AlterSack1966** [comment] 2015-01-07 17:51
Correctly recognized, I'm a bad driver, but a good reader of the plan. So I measured the way and applied all courses (with the exception of field courses) by hand. Most are already in FS2013. Worked better for me. The coordinates and velocities are registered by hand, course play has angle values probably at the reading corrected. Do you see any errors?

**Comment by JakobTischler** [comment] 2015-01-07 18:23
No, I don't see any particular errors, but it was the only possible explanation that we had.

The problem is, we can neither reproduce this problem, nor can we provide a single possible reason for this behavior. Also, no other users have reported this.

**Comment by AlterSack1966** [comment] 2015-01-07 19:08
In mode 6, it seems to lie in an interaction with a different mod. Probably with "Inspector_V24", which interferes with probably the fuel triggers. I've tested it but still not seriously, I lack the desire at the moment. In mode 4, I have the problem even if I disable all MODs.

I would like to take your time does not have the mass but, if I'm the only one with the problem I need to find just an own workaround, E.g. the breakpoints enable or used to go by the gas pedal.

Thank you very much for your efforts

**Comment by JakobTischler** [comment] 2015-01-09 18:05
Sorry not to be able to help. As I said, there are no other reports, we can't reproduce it, so I'll close this.

**Closed by JakobTischler** 2015-01-09 18:05 UTC
Labels: waitingForUserAnswer
