### ISSUE TITLE
Save game

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#7222] opened 2021-05-24 19:01 UTC
Trying to save the route after modification, unfortunately it's not saving, please see attached log

https://gist.github.com/envikowaty/4c6430c18b5e4b7c8670a54d37b848f0

**Comment by Tensuko** [comment] 2021-05-24 19:06
Are your course on the new course system ?
I have no Issue on editing a course.
Remember you can only save edited course when they have been saved the normal way (not a temp course).

**Comment by envikowaty** [comment] 2021-05-24 19:11
Hmm I was editing the route like before:

First crest the route and save
Then during the time add modifications.

I will try with the new version of cp, I've just noticed that there is a new one from yesterday

**Comment by envikowaty** [comment] 2021-05-24 19:20
ok so:
1 picture, saved route -> open and ready for modifications = I moved the red point to the left
![Schowek01](https://user-images.githubusercontent.com/69640077/119396748-321cd500-bccd-11eb-81f9-c1e788458a96.jpg)

2 picture - route changed and saved:
![Schowek02](https://user-images.githubusercontent.com/69640077/119396828-4d87e000-bccd-11eb-838a-b11f3e9a77d1.jpg)

3 picture - route switch off, reloaded and open again -> you can see that is still not modified
![Schowek03](https://user-images.githubusercontent.com/69640077/119396917-685a5480-bccd-11eb-8551-4d0ac224cd9c.jpg)

**Comment by Tensuko** [comment] 2021-05-25 06:23
Don't have this Issue, can't reproduce it.

**Comment by Tensuko** [comment] 2021-05-25 13:45
Is it an old course ?
Created with an older Version ?

**Comment by envikowaty** [comment] 2021-05-25 18:18
Route made with one version down, on the last update the problem is still there but like I wrote in my last post I've found the way to go around it

**Comment by Tensuko** [comment] 2021-05-26 04:29
Well, it is strange that it doesn't work for you.
But sounds like I can close it...

**Closed by Tensuko** 2021-05-26 04:29 UTC
Labels: can't reproduce
