### ISSUE TITLE
Sprayer error finding attacherVehicle

### ISSUE THREAD

**Issue by JrbrownOverland** [Courseplay/courseplay#6211] opened 2020-10-12 10:11 UTC
[log.txt](https://github.com/Courseplay/courseplay/files/5364444/log.txt)

When running the Hardi Rubicon 9000, both base in game and a modded in game version (added Manure Mod and Sprayer Section Control) and after creating a course then starting the course, a few seconds after that, all controls stop working and in the log file get Lua call stack errors seen in the attached log file.

If you need me to do other testing on this let me know how you want me to setup the test.

**Comment by Tensuko** [comment] 2020-10-12 11:49
@pvaiko no Idea what that is....
Callstack:
LUA call stack:
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua (935) : printCallstack
2020-10-12 06:04   dataS/scripts/vehicles/specializations/Attachable.lua (1302) : __index
2020-10-12 06:04   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2020-10-12 06:04   dataS/scripts/vehicles/specializations/AIImplement.lua (586) : raiseEvent
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/FieldworkAIDriver.lua (936) : aiImplementStartLine
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/FieldworkAIDriver.lua (661) : lowerImplements
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/FieldworkAIDriver.lua (608) : startWork
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/PurePursuitController.lua (251)
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/PurePursuitController.lua (242) : notifyListeners
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/AIDriver.lua (394) : update
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/FieldworkAIDriver.lua (330) : drive
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/AIDriver.lua (374) : drive
2020-10-12 06:04   =[C] (4294967295)
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua (935) : xpcall
2020-10-12 06:04   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2020-10-12 06:04   dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
2020-10-12 06:04   dataS/scripts/network/NetworkNode.lua (98) : update
2020-10-12 06:04   dataS/scripts/network/Server.lua (58) : updateActiveObjects
2020-10-12 06:04   dataS/scripts/BaseMission.lua (1500) : update
2020-10-12 06:04   dataS/scripts/FSBaseMission.lua (1979) : update
2020-10-12 06:04   dataS/scripts/missions/mission00.lua (469) : update
2020-10-12 06:04   =C:/Users/brown/Documents/My Games/FarmingSimulator2019/mods/AAA_CommunityExtension/scripts/core/Master.lua (728) : superFunc
2020-10-12 06:04   dataS/scripts/main.lua (1927) : update
2020-10-12 06:04 :51 [info lp57842] Rubicon 9000 (#1): Exception, stopping Courseplay driver, [string "dataS/scripts/vehicles/specializations/Attachable.lua"]:1302: attempt to index field 'attacherVehicle' (a nil value)

None CP LUA Error:
2020-10-12 06:04 Error: Running LUA method 'update'.
2020-10-12 06:04 dataS/scripts/vehicles/specializations/Attachable.lua(1318) : attempt to index field 'attacherVehicle' (a nil value)

**Comment by JrbrownOverland** [comment] 2020-10-12 21:35
In the previous version of Courseplay, I believe v6.02.00065 or .00064 I did not have this issue

**Comment by GeorgeEarslight** [comment] 2020-10-14 07:18
@JrbrownOverland 
What's this `AAA_CommunityExtension`?

**Comment by JrbrownOverland** [comment] 2020-10-14 10:15
It was a mod conflict with:
AAA_CommunityExtension on ITS SynTrac (modhub)
FS19_TowBarWeight (modhub) [(https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=156390&title=fs2019)](url)
FS19_TowingChain (modhub) [https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=181546&title=fs2019](url)

AAA_CommunityExtension is a mod that is from ThundR on Discord and changes game elements, like being able to convert the Liters to Bushels or Gallons depending upon the filltype.

AAA_CommunityExtension has not been updated in a few months, but this error just started recently.  When I removed the three others, leaving CommunityExtension, it works.  Removing the TowBarWeight and TowingChain it works, but I get the error/conflict between CommunityExtension and the IT SynTrac, which has not happened before.

**Comment by GeorgeEarslight** [comment] 2020-10-14 10:37
Does CP work with all your ModHub sourced mods?

**Comment by JrbrownOverland** [comment] 2020-10-14 10:39
It did not work with the TowBarWeight or the TowingChain.  It would allow the course to start but that is where the attacher error is coming from in the previous logFile

**Comment by GeorgeEarslight** [comment] 2020-10-14 10:46
This is related to this #3883 I think. 
The issue title is wrong, took me some time to dig it up.

**Comment by Tensuko** [comment] 2020-10-14 14:28
So it is not sprayer, it is some Mod Issues, am I right ?
The TowBarWeight (if it is the one I am thinking about) dosn't make Problems to use, at least for manual use. Those things are never intended to work with CP, but I will try out what happens when you start a course (more then Mode5 won't be supported as it won't make any sence in any other mode).

**Comment by JrbrownOverland** [comment] 2020-10-14 14:31
The error in courseplay is with the Hardi Rubicon 9000. You can activate a course but due to the mod conflict it will freeze the external camera once it tries to slow down and will not let you stop the driver prior to that. When those mods above are removed it works again.

**Comment by Tensuko** [comment] 2020-10-19 05:48
Duplicate of #6219

**Closed by Tensuko** 2020-10-19 05:48 UTC
Labels: Mod Conflict
