### ISSUE TITLE
Mode 2: pathfinder issue

### ISSUE THREAD

**Issue by Walpe** [Courseplay/courseplay#2243] opened 2017-08-18 07:42 UTC
Hello,

I am currently performing a silage of several hours with the courseplay, which represents a rather long test, and I noticed some problems.

![pathfinder](https://user-images.githubusercontent.com/30939110/29449064-944b9222-83f9-11e7-8178-bb14bb3fff5d.png)

I put this image to illustrate the bugs encountered, the green dots being the tractors, the red dot for the forage harvester, the red arrows indicating the beginning and the end of the race for the tractors and two magnificent trees worthy of Picasso.

- Problem 1: collision between tractors.
On the picture above, we see that the tractors are waiting.
The first will go to the forage harvester and when it is filled to 35%, the second will go behind the first one by following the crops well.
The problem is that as the job progresses, there is not necessarily a tractor to follow the one that is being filled, because it is still on the road, so the tractor that is filled, leaves in Along the crops, the second one arrives and also runs along the crops to go to the ensilluse, but on the same trajectory, they end up colliding, instead of avoiding.

- Problem 2: tractor running in circles.
I do not know why, but from time to time the tractor, which is in the queue* and is called by the forage harvester, begins to move towards the latter and begins to turn round and at the end of a Some time, the game starts to freeze for a few seconds and all the other tractors with the courseplay, start to slide as if they were on ice, due to the freezing of the game.

Edit: * I just corrected the sentence that was erroneous.

- Problem 3: The tractors leave the field to go to the forage harvester.
On the picture, above, we see that the forage harvester almost finished working.
The problem is that when it calls a tractor that is waiting, and its position is farther south than that of the tractor, the tractor turns south towards it, and collides with the trees that are seen On the diagram.
I think it's better if the tractor goes north in the field and it runs along the edge of the field to the forage harvester.
I point out that the tractors are not waiting in the field but just at the edge of it, outside.

It's a long post, but I'd rather have as much information as possible through this long silage, before I write to you.
I also specify that my version of the courseplay is .00181 and my map is losshugeland, version 4.1

Thanks.

**Comment by pvajko** [comment] 2017-08-18 08:12
I know it's a long test and the picture helps a lot but there's not much we can do without the logs, debug channels 3, 4, 7, 9 turned on.

**Comment by pvajko** [comment] 2017-08-18 08:45
Problem 1 may be related to #2200

**Comment by Walpe** [comment] 2017-08-18 09:00
I suspected you needed logs but I did not know which channel. Here they are with channel 3, 4, 7, 9.
[log.txt](https://github.com/Courseplay/courseplay/files/1233855/log.txt)

In chronological order, the 724 got stuck in a tree (problem 3).
Then the 939 blocked the 724 (problem 1)
Then the 724 made circles (problem 2). So the game froze and I had to restart the race of the 927 which had slipped because of the freeze.
And finally the 828 blocked the 939 at the end of the field (problem 1).

I hope this will help you

**Comment by pvajko** [comment] 2017-08-19 06:07
I should probably know this but not sure what exactly those numbers like 724 or 939 mean or how to relate them to entries in the log.

As for Problem 3, I see at least 5 cases where the tractor was waiting just outside of the field and a path has been generated to the harvester successfully. At least in those cases, you should have seen the tractor moving to the field and then driving along the edge of the field to the harvester, right?

**Comment by Walpe** [comment] 2017-08-20 09:33
The numbers 727, 939, etc, correspond to the model of the tractors, I just look at the log file and they are noted as 900 vario for the 939, 800 vario for the 828 and 700 vario for the 724.

Yes, the tractor actually started from the queue in the direction of the forage harvester by the field and along the edge of the field while the logs were activated, the problem was mainly on the return, where the tractor was going directly to the point closest to the run and not to the starting point of the run along the field, causing the tractor to collide with the trees.

Did you find anything in relation to the tractor that went in circles after its departure in the direction of the forage harvester?

**Comment by pvajko** [comment] 2017-08-25 01:50
Not sure what you mean by "point closest to the run". Also, in the original report you said that problem 3 was tractors driving to the harvester, now you are saying the problem is on the return.

Also, I see the same error message as in #2236 for the traffic collision.

**Comment by pvajko** [comment] 2017-08-26 11:59
Please post your courses and savegame, see the last point in https://github.com/Courseplay/courseplay/wiki for instructions.

**Comment by pvajko** [comment] 2017-09-13 12:25
Front tractor unregisters from combine:

32201 [dbg4 lp395848 6474.340 s] 700 Vario (#4): activeCombine ~= nil, my position=2, frontTractor (positionWithCombine 1) = "800 Vario (#3)"
32202 [dbg4 lp395849 6474.359 s] 700 Vario (#4): activeCombine ~= nil, my position=2, frontTractor (positionWithCombine 1) = "800 Vario (#3)"
32203 [dbg4 lp395850 6474.375 s] 800 Vario (#3): unregistering from combine id(279)
32204 [dbg9 lp395850 6474.375 s] 800 Vario (#3): Switching state: 5 -> 1
32205 [dbg9 lp395850 6474.375 s] 800 Vario (#3): Switching state: 1 -> 0
32206 Error: Running LUA method 'update'.
32207 D:/Bibliotheque/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/distance.lua:31: attempt to index local 'object' (a nil value)

**Comment by Brzzl** [comment] 2017-09-26 16:09
Hi! :) here my 2 cents:
1. If you chosose starting and end point of your course on an edge which is reachable from ALL positions on the field (like north of the field 9), you can avoid the collision with the trees (made a video - ok, ok in german :D - on Loeshuegelland with starting point in the North, works like a charm: https://youtu.be/SsDLPcG_H9Y?t=8m55s)
2. If you still want to start your course where it is now at, then choose an alternate course for harvester (north to south f.e. or try AI Vehicle Extension, works great with CP!)

**Comment by pvajko** [comment] 2017-10-20 02:38
Closing due to no activity.

**Closed by pvajko** 2017-10-20 02:38 UTC
Labels: waitingForUserAnswer
