### ISSUE TITLE
Mode 2 AI Driver doesn't know when tipper truck is full

### ISSUE THREAD

**Issue by Silva-19** [Courseplay/courseplay#7074] opened 2021-04-07 18:01 UTC
I'm having problems getting mode 2 combine / chopper unload to work with tippers (trucks with their own dump bed), like the [MAN TGS 18.500 Kipper](https://www.farming-simulator.com/mod.php?lang=en&country=ie&mod_id=141156&title=fs2019) on the ModHub.
It seems that the driver doesn't recognize when the back is full and doesn't move to the unload course.
Tested this with several trucks from the ModHub and none of them work, and found issue #4003 with the same problem.
Should be easy to replicate with a forage harvester / combine and a truck with its own bed.

![image](https://user-images.githubusercontent.com/48566247/113912758-6b5bbd00-97d3-11eb-9608-83537c753b77.png)

**Comment by Tensuko** [comment] 2021-04-07 18:04
logfile.... https://github.com/Courseplay/courseplay/wiki

**Comment by Silva-19** [comment] 2021-04-07 19:31
Sorry my bad:
[log.txt](https://github.com/Courseplay/courseplay/files/6274017/log.txt)

>9190 - 2021-04-07 18:59 :27 [dbg2 lp149000] TGS 18.500 TURBO (#8): Can't find trailer target node

I'm using the latest version, 6.03.00052

**Comment by famfam2812** [comment] 2021-04-07 21:03
I have the same issue. Also with 6.03.00052 with the ingame krone forage harvester and ingame Drakkar  trailer. :(

**Comment by pvaiko** [comment] 2021-04-08 11:14
Is this something we broke lately? In which version was it working?

**Comment by Silva-19** [comment] 2021-04-08 11:57
I'm not sure if this has ever worked as I only started using Courseplay recently and never tried with this type of truck until now.
Might have to do with the fact the driver only checks trailer's fill levels and not the "tractor" itself, and as this type of truck has no trailer it gives the "Can't find trailer target node" message.
Does the self.vehicle.cp.workTools array not include the tractor itself at position 0? At least for combines and self-propelled sprayers they seem to work fine with reading their own contents.

**Comment by pvaiko** [comment] 2021-04-08 13:06
cp.workTools is legacy code which will go away. We'll use the existing fill state code currently in FieldworkAIDriver.lua

**Comment by rohne83** [comment] 2021-04-08 15:56
seems this issue is a duplicate of https://github.com/Courseplay/courseplay/issues/6329 which was reported last year already. So nothing which broke just lately ;)

**Comment by pvaiko** [comment] 2021-04-18 22:48
should be fixed by 53

**Closed by pvaiko** 2021-04-18 22:48 UTC
