### ISSUE TITLE
The problem of mode 9 and mode 10

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#7239] opened 2021-06-04 20:21 UTC
Finally, ome farm development has reached the silo pit.
And then I ran into two problems.

First (mode 9): During the arrival of the unloader, the rammer tries to return to the waiting point, but it does not do this on the specified route, but as it pleases. Then he goes into the fence, then in general in the other direction (there is enough room for maneuver), but most often he leaves the pit and tries to return to it from the outside, resting against the wall.

![1](https://user-images.githubusercontent.com/65189100/120858423-6fb21580-c58b-11eb-85a5-5bd59282d7c9.jpg)
![2](https://user-images.githubusercontent.com/65189100/120858425-704aac00-c58b-11eb-99f1-6c591b6bd92e.jpg)
![5](https://user-images.githubusercontent.com/65189100/120858948-329a5300-c58c-11eb-99cd-ff557a64a723.jpg)

Second (mode 10):the loader, after loading the parked car, goes to load its bucket again. Returning to the unloading point with a full bucket, he begins to circle around it, instead of standing and waiting for the truck to arrive for loading.

![3](https://user-images.githubusercontent.com/65189100/120858448-76d92380-c58b-11eb-9c7c-e2e47f344b87.jpg)
![4](https://user-images.githubusercontent.com/65189100/120858450-780a5080-c58b-11eb-8a3a-b6baa4c6f665.jpg)
[log — копия.zip](https://github.com/Courseplay/courseplay/files/6601080/log.zip)

P.S. maybe I have something wrong with the routes or settings, please help. CP - last version

**Comment by Tensuko** [comment] 2021-06-04 21:35
Your course both doesn't look very good and I can't see your waitpoints and stuff...
Do not use the eye, use the 3 dots in the settings HUD Page.

**Comment by Tensuko** [comment] 2021-06-04 21:36
BTW: GitHub or ModHub Version ?

**Comment by Tocik** [comment] 2021-06-05 04:17
Курс для FS19 v6.4.0.0

**Comment by Tocik** [comment] 2021-06-05 04:24
Your course both doesn't look very good and I can't see your waitpoints and stuff...
Do not use the eye, use the 3 dots in the settings HUD Page.

All 3 waiting points are standing
1) The beginning of the pit
2) Pit end
3)Place of unloading

**Comment by Crinouche** [comment] 2021-06-05 06:40
493 / 5000
Hello,
I think the problem reported here from mode 10 is the same as # 7202
For mode 9, I also have problems and these are very similar to those for mode 10. After loading, the bucket wants to return to the bunker.
Finally, in front of the trailer, he does not lift the bucket to empty. And I did recheck all my settings. I have been using Courseplay for 10 years now. So I think I know how to make the adjustments.
Here are some pictures taken in a row, one of the other.
thank you, 
![image](https://user-images.githubusercontent.com/36656729/120882362-81b9a580-c5d7-11eb-8350-aea69e41fc4a.png)
![image](https://user-images.githubusercontent.com/36656729/120882397-ea088700-c5d7-11eb-9ba2-ac346b752b4b.png)
![image](https://user-images.githubusercontent.com/36656729/120882436-410e5c00-c5d8-11eb-8e24-49210b2982c9.png)
![image](https://user-images.githubusercontent.com/36656729/120882415-12908100-c5d8-11eb-920d-a9f204637fee.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6602122/log.txt)

**Comment by Tensuko** [comment] 2021-06-05 09:31
Okay the way out of the Bunker is the same bug we had in Mode10.
For unloading into the Trailer, you need more distance between waitpoint and trailer.

**Comment by Tensuko** [comment] 2021-06-05 19:40
Can you guys try the current master Branch ?
You have to download the branch, unzip and rezip the files into FS19_Courseplay.zip (like in the past).

The Compacter (Mode10) got a rework, the course is the same but should work much better.

Mode9 got a new and more simple course:
Start in front of the Bunker, drive a bit into the Bunker and change to reverse recording.
The rest is the course is as usual (waitpoint in front of the traget and back infront of the bunker).

Our tests went very good.
About unload into trailer, like I said, a bit more distance, since we slowly approch our target now and so far it was successful.

**Comment by leo32128fs** [comment] 2021-06-05 20:28
I tested a variant that was performed yesterday , and it simply does not download to BGA , I will upload a video for you to see if I did something wrong ok

**Comment by leo32128fs** [comment] 2021-06-05 20:29
> Testei uma variante que foi realizada ontem, e simplesmente não baixa para bga, vou carregar um vídeo para você ver se eu fiz algo errado ok

https://drive.google.com/file/d/1xPo0ozCyzgpZ-fEEZBDrQMKjC9CP4Z9j/view?usp=sharing

**Comment by leo32128fs** [comment] 2021-06-05 20:56
I tested a variant that was performed yesterday, and it just doesn't download to bga, I'll upload a video for you to see if I did something wrong ok

https://drive.google.com/file/d/1xPo0ozCyzgpZ-fEEZBDrQMKjC9CP4Z9j/view?usp=sharing

**Comment by Tensuko** [comment] 2021-06-05 21:03
Your course is still wrong!



> Mode9 got a new and more simple course:
> Start in front of the Bunker, drive a bit into the Bunker and change to reverse recording.
> The rest is the course is as usual (waitpoint in front of the traget and back infront of the bunker).

**Comment by leo32128fs** [comment] 2021-06-05 22:51
> Seu curso ainda está errado!
> 
> > Mode9 tem um novo e  mais simples curso: Comece em frente ao Bunker, dirija um pouco para o Bunker e mude para reverter a gravação.  O resto é o curso é como de costume (ponto de espera em frente ao traget e de volta em frente ao bunker).

Ok I'll try, Thanks!

**Comment by leo32128fs** [comment] 2021-06-05 23:13
I traced the route as you teach, and now it's great!!! Thank you for your help

**Comment by leo32128fs** [comment] 2021-06-05 23:14
I did the route as you teach and now it's 100%, thanks for your help

**Comment by leo32128fs** [comment] 2021-06-05 23:24
I loved this new course mode , I uploaded a video for those who have problems , to see how I made my route , Ok

**Comment by leo32128fs** [comment] 2021-06-05 23:25
https://drive.google.com/file/d/1DqAcPhFDODYhTk_e30t902tQEK3R_bdB/view?usp=sharing

**Comment by Tocik** [comment] 2021-06-06 06:47
In the evening I will return to the city, I will test everything.
Then I'll write my comments

**Comment by Tocik** [comment] 2021-06-06 11:07
I apologize, it is difficult for me to understand the navigation of this site. Can you tell me where this branch is " master"

**Comment by Tensuko** [comment] 2021-06-06 12:22
![master](https://user-images.githubusercontent.com/27344744/120924163-99298900-c6d2-11eb-9cee-ca40bb8de7ac.png)

**Comment by Tocik** [comment] 2021-06-06 14:02
Yes, thank you. I already figured it out.
With mode 10, everything is much better, at least the tractor is no longer trying to return to the bunker.
Mode 10 has not yet been tested, because fermentation is underway.

**Comment by Tocik** [comment] 2021-06-07 18:02
Mode 9 did not start working correctly.
As soon as the truck left, the loader began to circle around the waiting point. I made a few laps and went on with my incomprehensible business.
![1](https://user-images.githubusercontent.com/65189100/121067428-b7c37900-c7d3-11eb-9b95-436e5b563386.jpg)
![2](https://user-images.githubusercontent.com/65189100/121067432-b8f4a600-c7d3-11eb-850d-a018d19292ac.jpg)

**Comment by Crinouche** [comment] 2021-06-07 18:05
Hello,

OK, I've done some mode 9 and 10 tests and both modes seem to be working, for now.
However, regarding mode 9, some improvements could be made:
- the "put the bucket in stationary position" function deactivated, does not work. The bucket must stop before going to load (photo 1)
- before unloading in the trailer, the loader stops to put itself in the "pre-unloading" position (photo 2) Is it possible that the loader does not stop and begins to put itself in "pre-unloading" position while driving to the trailer?
- when the loader has unloaded the trailer, is it possible that it goes back to the "transport" position when it returns to the 1st point? because for the moment, it leaves the bucket in the "pre-unloading" position and risks tipping in the bends.
- Finally, we cannot increase the forward and reverse speed when the loader is in the bunker (currently 10 km / h, maximum)

![image](https://user-images.githubusercontent.com/36656729/121066318-079d4280-c7ca-11eb-8c37-c19cf46130a4.png)
![image](https://user-images.githubusercontent.com/36656729/121066778-8eeab600-c7ca-11eb-9317-37bd44d87dbb.png)

**Comment by Tocik** [comment] 2021-06-07 18:14
Recorded a new route in an empty space where there is no trailer or trigger. After reaching the unloading point without finding the trailer or trigger, the loader returns back to the beginning of the route.
And so it goes around in circles.
![4](https://user-images.githubusercontent.com/65189100/121068694-44bb0200-c7d5-11eb-9cc3-1d7fda35b0b8.jpg)

**Comment by Tocik** [comment] 2021-06-07 18:59
It's funny, but I added a truck to this chain and it began to stop.

**Comment by Tocik** [comment] 2021-06-08 05:04
Here's what else I found.
The pit ran out of silage and the loader collected the rest-32%. But he did not go to unload, and continues to load the silo in an empty pit.
![1](https://user-images.githubusercontent.com/65189100/121126048-32ba7d00-c830-11eb-8127-c3d8e8562d05.jpg)

**Comment by Tensuko** [comment] 2021-06-08 05:08
Thank your for your feedback.
We will have a look at this :)

**Comment by Crinouche** [comment] 2021-06-08 07:40
retry with the latest version.
It does not work !

![image](https://user-images.githubusercontent.com/36656729/121143520-6cde4b80-c83d-11eb-9894-805ecb4bd273.png)

**Comment by Tocik** [comment] 2021-06-08 09:15
Thanks

**Comment by Tensuko** [comment] 2021-06-09 13:38
> 
> 
> retry with the latest version.
> It does not work !
> 
> ![image](https://user-images.githubusercontent.com/36656729/121143520-6cde4b80-c83d-11eb-9894-805ecb4bd273.png)

Your course looks wrong.
![Mode9new](https://user-images.githubusercontent.com/27344744/121365252-c7a89d80-c938-11eb-80ba-b604513f3c26.png)

**Comment by Crinouche** [comment] 2021-06-09 15:56
@Tensuko, my course is done exactly as you have drawn it. I think my image is misleading you once again and that it is an optical effect!

I emptied the 1st meters of the bunker manually and reactivated the CP afterwards and it works now. It is possible that if the shovel has to make a somewhat tight maneuver at the start, it will go around in circles or decide to go back into the bunker.
But I am not sure!
I continue my tests

**Comment by Tensuko** [comment] 2021-06-10 11:02
- your start is not in front of the bunker (distance to far)
- you have more waypoints between start and the 2nd WP (the one that should be inside the bunker to get the correct direction of the start WP).

That is not missleading at all.
And I did let the driver run for a while yesterday.
Could not reproduce this on current Master Branch.

**Comment by Tensuko** [comment] 2021-06-10 11:02
> It is possible that if the shovel has to make a somewhat tight maneuver at the start

For that, we drive reverse when the target is to close.

**Comment by schwiti6190** [comment] 2021-06-10 11:05
@Crinouche , @Tocik
Hi there, not sure if I figured out all the problems in this thread, but you can have a look here: https://github.com/Courseplay/courseplay/compare/issue-7239 . To test this you would have to download the branch: "issue-7239" similar to the download of the master branch. 
@Crinouche 
- `the "put the bucket in stationary position" function deactivated, does not work. The bucket must stop before going to load (photo 1)
before unloading in the trailer, the loader stops to put itself in the "pre-unloading" position (photo 2) Is it possible that the loader does not stop and begins to put itself in "pre-unloading" position while driving to the trailer?` these to are now combined into the old setting you mentioned above, there is currently no free space in the hud for seperate settings.

- `when the loader has unloaded the trailer, is it possible that it goes back to the "transport" position when it returns to the 1st point? because for the moment, it leaves the bucket in the "pre-unloading" position and risks tipping in the bends.`
Could explain this in more detail, maybe a picture ?

- the speed can now be adjusted in the mode 9 hud window, bunker silo speed. 

Thx for all your help :)

**Comment by Tensuko** [comment] 2021-06-12 17:09
@Crinouche , @Tocik
can you try the latest push of the Branch, that @schwiti6190 wrote.
I wonder how it does work on your situations.

**Comment by Crinouche** [comment] 2021-06-13 07:40
Hello,

I just downloaded version 7239, but unfortunately it's worse than the master version.
I have redone my CP lessons several times, I have tested with different chargers and in different bunkers, but it does not work.
Photos 1 & 2, before loading, the loader wants to go back to the bottom of the bunker.
If it does not block to climb, it goes to the back of the bunker, comes back to the starting point, puts itself in the loading position and does not move (photo 3 & 4) In photos 3 & 4, the loaders stay there, without moving. If I turn CP off and back on, the loaders will want to go to the back of the bunkers again.
![image](https://user-images.githubusercontent.com/36656729/121798828-e2c12900-cc28-11eb-9fc1-77b178f7d610.png)
![image](https://user-images.githubusercontent.com/36656729/121798992-cb367000-cc29-11eb-8c97-dd95deec3fb2.png)
![image](https://user-images.githubusercontent.com/36656729/121799027-020c8600-cc2a-11eb-9417-0dd9f94d075e.png)
![image](https://user-images.githubusercontent.com/36656729/121798883-18fea880-cc29-11eb-8a1e-7c016300f6d1.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6643464/log.txt)

**Comment by Crinouche** [comment] 2021-06-13 08:37
With the master version, it's not perfect but it still works. It is not fluid and the loader sometimes turns in circles, especially at the start of emptying the bunker (when it is full.)

Photo1 = pity that the work lights no longer work during work. At night, we no longer see anything
![image](https://user-images.githubusercontent.com/36656729/121800404-d2617c00-cc31-11eb-97e1-79f314e4b51c.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6643548/log.txt)

**Comment by Tensuko** [comment] 2021-06-13 11:20
Can you pls make pics not in complete darkness as we only see lines like that.

In what state did you get the branch ?
We added another commit 'enables alignment course for mode 9' wich at least should make sure, we start from the center and depending on the target, we drive reverse a few meters, then drive to our target and after that, we take the closest line to drive out in reverse. Somehow it looks like we drive to far ?
As I said can't see much on your last picture...

**Comment by DonBolli** [comment] 2021-06-13 11:46
Ich habe den Kurs so eingefahren wie ich es verstanden habe

![3](https://user-images.githubusercontent.com/43571844/121805901-989e6e80-cc4d-11eb-8b66-bdb45e821a06.png)
 
![4](https://user-images.githubusercontent.com/43571844/121805904-9dfbb900-cc4d-11eb-8fdb-a4255363eb0c.png)

Es funktioniert leider nicht, was habe ich falsch gemacht?

**Comment by Tocik** [comment] 2021-06-13 16:12
Plz use translate, bocouse don't use computer.

Предидущая версия работала не плохо, за исключением того, что погрузчик не выгружал последний последний ковш из ямы, т. к. Он был не полон, а пытался его наполнить в пустой яме...

**Comment by Crinouche** [comment] 2021-06-14 05:27
@Tensuko 
_Can you pls make pics not in complete darkness as we only see lines like that._
I took a picture in the dark, just to show that without the working lights, you can't see anything. It was not to show the course!

_In what state did you get the branch ?_
It seems to me that I had downloaded the very last version of N ° 7239
I will try again by downloading the update.

**Comment by Crinouche** [comment] 2021-06-14 06:11
Here are some photos taken during tests with version 7239.
I noticed a problem with loading when there is some silage left in the bucket. If I start CP and the bucket is not completely empty, the loader will do anything. See the pictures 2-3-5
Sometimes, before going to load, the loader will try to go up on the bunker in reverse, before returning to the starting point to start its cycle again. Pictures 1
![image](https://user-images.githubusercontent.com/36656729/121844564-7c99dc00-cce4-11eb-9038-12d232099c83.png)
![image](https://user-images.githubusercontent.com/36656729/121845022-22e5e180-cce5-11eb-8a34-65e7f2418184.png)
![image](https://user-images.githubusercontent.com/36656729/121845411-adc6dc00-cce5-11eb-8e5d-eefc0ff5442e.png)
![image](https://user-images.githubusercontent.com/36656729/121845934-7f95cc00-cce6-11eb-9d06-ba2184f91836.png)
![image](https://user-images.githubusercontent.com/36656729/121846214-f632c980-cce6-11eb-8721-8df8a4fa877c.png)

**Comment by Tensuko** [comment] 2021-06-14 07:36
> Sometimes, before going to load, the loader will try to go up on the bunker in reverse, before returning to the starting point to start its cycle again. Pictures 1

Start at wich starting point ?

**Comment by Crinouche** [comment] 2021-06-15 09:29
I think it's bug when I select "start at the first point"
If I select "start at nearest point", it looks like there are fewer problems
I will try with today's update

**Comment by Tensuko** [comment] 2021-06-15 11:23
6.4.0.2 should fix the most of your issues.

**Comment by Crinouche** [comment] 2021-06-15 16:53
I just did a lot of testing with the latest version. It works very well. Great job guys and thank you!
There is just a small problem when unloading the bucket into the trailer. If I deactivate "put the bucket in stationary position" the loader does not raise the bucket soon enough and runs into the trailer. The bucket should rise faster or a little more in advance. Is this possible, or am I doing some things wrong?
![image](https://user-images.githubusercontent.com/36656729/122091283-ef03dc80-ce08-11eb-93f3-09a84e1d8048.png)
![image](https://user-images.githubusercontent.com/36656729/122091426-1195f580-ce09-11eb-81c0-1e70a7457fb1.png)
![image](https://user-images.githubusercontent.com/36656729/122091828-86692f80-ce09-11eb-829a-3e3deab1b691.png)

**Comment by schwiti6190** [comment] 2021-06-16 11:02
@Crinouche I tried to implement fixes this here: https://github.com/Courseplay/courseplay/commit/85c6c82dfedbb5ad79711e38ead89a6dffbc28ae. 
If you would like to test this ? If possible with a few diffrent vehicles as mode 9 drivers :)

**Comment by Crinouche** [comment] 2021-06-16 18:37
@schwiti6190
i just tried the version 85c6c82 and it works perfectly. the loader lifts its bucket well enough early and no longer rushes into the trailers. Very good work !! :)
You also asked me:
__when the loader has unloaded the trailer, is it possible that it goes back to the "transport" position when it returns to the 1st point? because for the moment, it leaves the bucket in the "pre-unloading" position and risks tipping in the bends._
**_Could you explain this in more detail, maybe a photo?__**

I wanted to say:
In the pictures 1 and 2, we see that the loader has emptied his bucket into the trailer and is backing up to return to the starting point. It would be good if he started to lower his bucket during reverse gear and put himself in the "transport" position in order to be able to put himself in the "loading" position when he reached the start of the race.
Currently, he begins to lower his bucket only when he returns to forward and if the return trip is too short he must stop to lower his bucket.
![image](https://user-images.githubusercontent.com/36656729/122273130-6147f000-cee1-11eb-8d7e-bed8389a42dc.png)
![image](https://user-images.githubusercontent.com/36656729/122273411-b5eb6b00-cee1-11eb-8281-a0418bcb55dc.png)

**Comment by Crinouche** [comment] 2021-06-16 18:48
Ah! I forgot
I tested version 85c6c82 with the NH W190D, with the MF 5613 + charger and with the Class Scorpion 1033 and everything works perfectly. Even with very tall trailers !!

**Comment by schwiti6190** [comment] 2021-06-17 11:24
@Crinouche Perfect :)

I will close this issue then, if there are anymore problem please create a new issue, as this one is to big.
The fix will be implemented with the next version. This might take a while as their are other changes not yet finished :)

**Closed by schwiti6190** 2021-06-17 11:24 UTC
Labels: enhancement
