### ISSUE TITLE
Problem with 3rd combine headland

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#3285] opened 2019-02-22 22:03 UTC
Hi,

Im having a problem with my course. I have created a course for 3 combines to clear the field, combine1 and combine2 (left and middle) follow the course, combine3(right) follows the course till it needs to turn (headland, more then 90 degrees) then its wandering off and gets stuck in the trees.

Courseplay (v6.01.00082)
[log.txt](https://github.com/Courseplay/courseplay/files/2896008/log.txt)

![fs19 cp1](https://user-images.githubusercontent.com/47780758/53273924-bbf82500-36f5-11e9-9fb7-3752bc2e6c38.jpg)

**Comment by Bobster82** [comment] 2019-02-23 12:36
I tried and tried some more... Now I made some drawings too to help explaining. Picture#1 is how courseplay tries to follow the lines, as u can see combine1/line1 adds 13.5 to the outside and circles around the corner, combine2/line2 just follows the line..
The problem is with the 3rd combine/line3 that he is guided by the course line (combine/line2) so when going straight he goes 13,5 to far to the north and with his turn he cant find his line and wanders off (picture#2)
So courseplay needs to guide combine3 13,5m off to the right and 13,5off from distance to next wp, then u get something like in picture#3

So, outside the line courplay does it good, inside the line it goes wrong.. Hope i explained good enough

![fs19 cp track1](https://user-images.githubusercontent.com/47780758/53286431-c6a2d080-376e-11e9-8b02-f248c9671199.jpg)
![fs19 cp track2](https://user-images.githubusercontent.com/47780758/53286432-c86c9400-376e-11e9-8fc0-90252b303820.jpg)
![fs19 cp track3](https://user-images.githubusercontent.com/47780758/53286433-ca365780-376e-11e9-921d-5585f8ac57ac.jpg)

**Comment by Wadeeb** [comment] 2019-02-24 04:53
I have seen the same problem with acute angles like the course you showed. The 3rd combine is following the center line of the course as you said and when it tries to turn it loses the course and keeps gong straight at the last point it had and keeps going until it get stuck. This happened to me with 3 combines using 16.5m headers so there is a lot of overlap on sharp turns.

**Comment by Goof245** [comment] 2019-02-25 06:52
FWIW, you can work around this to an extent by using Round: Turn Radius in the course generation, though it doesn't always help in all cases.

Normally I try different start / end points until I get a course mostly free from tight turns in the up/down -> headland transitions, though if your field border has acute angles like that there's not much you can really do...

Acute angles, and in particular the inside turns when using multiple workers have been basically broken for months, same problems plagued FS17 as well :\ Hopefully what pablo has in mind to fix #3255 and #3290 finally fixes this and we can enjoy combine fleets / many large tool working together again...

**Comment by Bobster82** [comment] 2019-02-25 09:26
@Goof245 , I tried the option "round" but then a lot of the field outside gets skipped. I dont mind if a combine or a seeder/cult miss a little piece, but missing huge chunks is no option :P ... 
I also tried a lot of settings, but when the inside combine/tool needs to turn, he gets lost, so i need less machines on a course, but its taking time on huge fields hahaha

Thanks for pointing out more of the same problems. I wish i could program, then i could help out. I got the time, but not the experience haha

**Comment by Goof245** [comment] 2019-02-25 10:49
The missed chunks work out to nearly nothing with respect to the size of the field. If they do make up a significant portion of the field it might be a sign the machine is too big for it. Normally I'll roll the outer border of the field with grass, so I don't have corners filled with fruit after the harvests...

To elaborate on what I meant earlier:

This is kinda what machines seem to be doing; they'll try to follow every waypoint regardless of what lies ahead, and whether the machine can make the coming turn properly or not. 

![new](https://user-images.githubusercontent.com/3851003/53332073-8ac26380-3946-11e9-8e08-3674d04e174b.png)

All too often a waypoint ends up too far inside the turning circle and we get a machine making infinite circles. Another problem is that the longer the machine takes to make these turns, the greater the risk another machine turns up and they either crash or deadlock themselves in traffic facing each other.

I remember though, at one point, maybe multiple years ago, machines would do this:

![old](https://user-images.githubusercontent.com/3851003/53332142-b6454e00-3946-11e9-8662-1056788e9d1f.png)

The courses were infinitely more reliable, especially with larger or multiple machines. Only downside I remember was that the zones that a header or seeder missed were much larger. Perhaps people complained and this is why it was changed? Or maybe the behaviour changed at some point due to other refactors / rewrites in the code, I dunno...

**Comment by pvaiko** [comment] 2019-02-25 12:32
@Goof245 your first example is generated only when with the headland 'turn' option. But then it'll do a turn maneuver and not what you are showing. Can you describe how to reproduce that? Or send a course or savegame?

The 'round' option does exactly what your second drawing shows using the turn radius of the vehicle, and then yes, the corners will be missed especially when using multiple headlands. Finally you have the 'smooth' option which will result in curves too but the radius isn't limit to the vehicle's radius.

**Comment by Goof245** [comment] 2019-02-25 13:21
The second picture used to be default behaviour for most if not all waypoint following. Nothing to do with the course generation options at all.

If you had the waypoints visible, the machine would appear to literally cut off waypoints it knows were impossible under the current turning radius.

As far as reproducing, I can try and generate an example tomorrow; I think we're in very different timezones... Nearly any relatively acute angle does it though, curved fields with an up/down path pretty much have to have some of those to actually cover the field. Machine will happily work up until the green pause waypoint, raise the tool then do a wide circle and _maybe_ get back on track before it reaches the red waypoint to lower the tool again.

**Comment by pvaiko** [comment] 2019-02-25 13:45
> up until the green pause waypoint

That green waypoint is a turn start waypoint, the red is the turn end, and that is exactly I'm talking about, it is performing a **turn** maneuver, **not** normal driving. With no turn waypoints it'll behave like your second example (but there never was any intelligence built in like "knows were impossible under the current turning radius."

The problem with the turn maneuver is well known and being worked on.

**Comment by Goof245** [comment] 2019-02-25 14:14
>That green waypoint is a turn start waypoint, the red is the turn end, and that is exactly I'm talking about, it is performing a **turn** maneuver, **not** normal driving.

The behaviour appears much the same, it happens on both "turn maneuvers" and sharp corners on headland passes. In both cases, the worker drives right to the vertex of the path, or the green pause marker and makes a big circle, sometimes making it back on track, sometimes not.

>but there never was any intelligence built in like "knows were impossible under the current turning radius."

Might not have been deliberately accounted for, perhaps a side effect of clever pathing by you guys...

I get you guys have your hands full, and at least some of this isn't really a CP 6 thing. I used to be able to just set loose 4-5+ combines or seeders with corners much like the one in the OP and the ones on the very inside of the turn would have no trouble at all getting around. This is back when you had to work out offsets manually for different workers according to the number of machines / tool working width, before the easy GUI option to just choose what lane you wanted the worker in...

Sometime in the past year or more those inside workers no longer made that turn, or any tight turns and it seems to have gotten worse in CP 6. I'm sorry I can't be of more help at the moment :(

**Comment by pvaiko** [comment] 2019-02-28 01:08
For those who want and who know how to do it, you may give the improved headland turns a try. This is on the separate headlandturns branch (https://github.com/Courseplay/courseplay/tree/headlandturns)

**Comment by Bobster82** [comment] 2019-03-01 10:55
@pvaiko Thanks! I'm gonna try it today and let u know

**Comment by Bobster82** [comment] 2019-03-01 14:50
@pvaiko Im really happy with how u worked it out for sharp corners! Thanks!
But.... (yes, there is always a but ;) )
Sharp turns go great , but my problem still exists in sharp round corners where courseplay adds a lot of waypoinst in a small corner, you see it on the 2 pictures... the green lines go great now! the red lines still goes out of the field and get stuck.... the field on top and bottom has a small round edge, so no sharp "turn" , but sharp "corner"  

I hope u understand what Im telling, else let me know.

![fs19 1](https://user-images.githubusercontent.com/47780758/53645601-7da0bf80-3c39-11e9-8ba8-bef92e7926f1.jpg)
![fs19 2](https://user-images.githubusercontent.com/47780758/53645610-8396a080-3c39-11e9-92d6-f07f5e5b4025.jpg)

**Comment by Goof245** [comment] 2019-03-03 09:33
If this is in any way useful, I caught the moment this deviation happens. Whether or not this is actually the same scenario bobster encounters I'm not sure...
[https://youtu.be/EQg9HjfnpO4](url)

The tractor _seems_ to encounter a waypoint that exists behind the previous one as it tries to navigate the tighter turn on the inside of an offset path. Maybe something like this is happening?

![courseplay](https://user-images.githubusercontent.com/3851003/53693339-d499c680-3dea-11e9-8bc7-60c0385d75f1.png)

Trying to resume at current waypoint after the tractor wandered off caused it to try and drive back to where the problem occured.

I can't even begin to think about the maths that goes into trying to develop the paths these inside tractors need to navigate, you guys are wizards in what you do :)

**Comment by Bobster82** [comment] 2019-03-03 10:34
Looks interesting @Goof245 ... I hope cp guys can explain or translate this "problem"
Will wait for their answer, thx

**Comment by pvaiko** [comment] 2019-03-03 12:12
@Goof245 sorry, I should have updated this issue, yes that's what exactly is happening and I knew it from the beginning since I implemented the new course generator and this exact problem appears when you generate the headlands, that's why I have a 'grassfire' algorithm in there (offsetting in very small steps and clean up after each iteration).

And this is the reason this will remain unfixed for now as the multitool uses the naive implementation of just offsetting each waypoint on the fly and ends up with this little loops especially in case of wide implements and tight corners. 

The only 100% fix for this would be to generate a different headland course for each vehicle which is a little bigger effort and won't happen soon.

**Comment by Bobster82** [comment] 2019-03-03 13:06
If you dont gonna work more on this "problem" then this thread can be closed now ;) 

Thanks for all the effort! Its better then before! I hope this can be "fine tuned" later ;)

**Comment by Goof245** [comment] 2019-03-03 14:36
Good to know it's still on the radar... Guess for now we'll just have to stick to more up/down passes for these bigger fields.

**Comment by pvaiko** [comment] 2019-03-08 13:08
e16d8108dbbe578635e03ea92cf0528c32530555 may help with this too...

**Comment by Goof245** [comment] 2019-03-09 03:55
Behaviour's much the same in my case:

![20190309134050_1](https://user-images.githubusercontent.com/3851003/54065906-d5ab7780-4272-11e9-94fe-25530340c904.jpg)
Tractor gets to this waypoint, the very next one is way behind as the corner sharpens.
![20190309134112_1](https://user-images.githubusercontent.com/3851003/54065908-d7753b00-4272-11e9-8d57-4f5d2a53736b.jpg)
Tractor just wanders off in this direction practically forever...

**Comment by Bobster82** [comment] 2019-03-09 12:03
I tested it too. It was better for my combines, they now made a cirkel against the clock on the turningpoint and found his track back. Its working good until I go to 5 combines, then the inner cant find the track and wanders off. (I liked the way the combines behave with the cirkel ;) )

I also tried with a quadtrack and the 24m cultivator, 2 machines is not working when need to turn, it used the new method (go straight till turn point, then reverse and continue) it goes to turning backwards and not straight as a normal tractor would do.

I also tries with 2 times a challenger with 25.5m seedhawk, the outside is going good, the inside just as goof245 described, it wanders off.


If you need logs, pics or videos, let me know. Thanks!

**Comment by Tensuko** [comment] 2019-05-14 12:48
I add #3460 as a possible solution, if there are getting different turn options added for harvesters.
Like we already got, straight backwards or turn backwards (something like this...)

**Comment by pvaiko** [comment] 2019-05-26 16:22
With 225 vehicles should now stay on course.

**Closed by pvaiko** 2019-05-26 16:22 UTC
Labels: Fine Tuning, wontfix
