### ISSUE TITLE
Turn issue sprayer (NH SP400F)

### ISSUE THREAD

**Issue by SkiiBlock** [Courseplay/courseplay#1957] opened 2017-04-03 19:13 UTC
When the sprayer reach the end of the field, he is not turning fine and continue on a random way in the field. I don't see if this was reported before so I decide to do it. Maybe it's a bug or maybe it's my game, I don't know so I prefer post it :)

Here is the video : https://www.dropbox.com/s/7crioihgnrlpwdq/Farming%20Simulator%202017%2004.03.2017%20-%2021.08.57.41.mp4?dl=0

Here is the log : https://pastebin.com/KbJbp5tF

**Comment by Satissis** [comment] 2017-04-15 08:57
Looks like it missed an turn waypoint when it did that. I'll need to see if I can reproduce it, to be able to fix it

**Comment by Thomasovo** [comment] 2017-07-20 09:50
Same problem. CP 5.01.00089 is last version which works correctly.

**Comment by Blackmankot** [comment] 2017-08-05 02:27
@pops64 I suggest also close it for cleaning.

**Comment by pops64** [comment] 2018-11-07 20:09
Closed #2909

**Closed by pops64** 2018-11-07 20:09 UTC
Labels: Vehicle Ajustment
