### ISSUE TITLE
Tractor drove itself into water and became unrecoverable.

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#4294] opened 2019-09-24 20:30 UTC
I just had a tractor end-up driving itself off the course and into a lake. I noticed it on the map doing circles in the lake. As it is in the middle of the lake I am unable to enter the vehicle to stop the driver. As it is in-use, I can not reset the vehicle either.

Courseplay version 6.01.00300
John Deer 8400 R with a Merge Maxx 902
Using Mode 6 Fieldwork

**Comment by Tensuko** [comment] 2019-09-25 05:36
Console command: cpStopAll
Where does that Tractor come from ?

**Comment by Krahazik** [comment] 2019-09-25 17:46
It is a vanilla heavy tractor.

**Comment by Tensuko** [comment] 2019-09-25 18:00
logfile debugchannel 9 12 14 could be helpful.

**Comment by Krahazik** [comment] 2019-09-26 01:08
The Map was Felsbrunn, and the lake was the lake just south of field 22.

By now I have recovered the tractor. I finished other tasks and just saved the game and shutdown. 
When I later reloaded the game, both the tractor and the windrower were sitting in the store.
Not sure I could get it to do it again as im not sure how it ended up in the lake in the first place.
Think I did have a north-south up/down pattern generated for field 22.

**Comment by da4id** [comment] 2019-09-29 10:05
I observed that if you have a Fieldwork course loaded, but the mode of the verhicle is driving instead of fieldwork it will not start turning and drive just straight forward. Maybee this could be the reason why your tractor was ended up in the lake

**Comment by Krahazik** [comment] 2019-09-29 14:46
Not this time, as it was doing field work and completed the work. Looking at it, the only way I can think of how it might have happened is if the tractor tried to drive back to the start point and its return rout took it through the lake maybe.

**Comment by pvaiko** [comment] 2019-09-30 13:36
>  I noticed it on the map doing circles in the lake.

Too bad you don't have a video of that, would have entertaining...

I'm closing this here as we don't seem to be able to reproduce it. Open a new one if you can reproduce.

**Closed by pvaiko** 2019-09-30 13:36 UTC
Labels: waitingForUserAnswer

**Comment by Krahazik** [comment] 2019-09-30 17:49
If it ever happens again I'll see about getting pictures or a video.
