### ISSUE TITLE
limited speed on the road for CP driver

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3017] opened 2019-01-29 21:21 UTC
Hello!

I made a course combine a harvester. No problem! But CP driver ist limited to 15 km/h on the road, even though road-speed is set to max (53 km/h). Guess, it is not a problem on high priority, course is working fine.

![bildschirmfoto 2019-01-29 um 21 55 23](https://user-images.githubusercontent.com/24283753/51941134-1f9f7300-2414-11e9-8ce4-8e0d6bfe04d5.png)

**Comment by tjBerlin** [comment] 2019-01-29 21:22
oh.. using CP version .00014...

**Comment by ddewar** [comment] 2019-01-29 23:03
Changing the turn speed increases the speed too? I saw this too. Might be fixed by [this commit](https://github.com/Courseplay/courseplay/commit/c007d70694ebb61ca9271b52e38e469820fdcf7e)?

**Comment by tjBerlin** [comment] 2019-01-30 05:57
Just checked it with latest CP version .00015.

CP driver started on road, normal speed up to 53 km/h. 

After leaving the field and unloading the harvester, CP driver speeds up to a max of 15 km/h (turn speed). Increasing the turn speed, makes CP driver faster. [But he is losing control in the curves... ;)].

By dismissing the CP driver and hiring him again, CP driver uses max speed until he does a turn maneuver, then max speed on road 15 km/h (turn speed).

[log.txt](https://github.com/Courseplay/courseplay/files/2811046/log.txt)

**Comment by TinyCrocodile** [comment] 2019-01-30 05:57
I had the same problem. Cp somehow takes the Speed from cruise control of the tractor and does not modify it. If you manually increase the cruise control speed of the tractor it will go at full speed.

I think that cp is designed to use and modify cruisecontrol but 2nd part does not work yet.

**Comment by pvajko** [comment] 2019-02-06 01:31
Is this still an issue?

**Comment by tjBerlin** [comment] 2019-02-06 04:51
Hello! 

yes, it is. I just tested it with CP version .00044 on FELSBRUNN. 

![bildschirmfoto 2019-02-06 um 05 46 55](https://user-images.githubusercontent.com/24283753/52321038-cbc3f980-29d2-11e9-8ad4-d6b541efe3d9.png)

CP driver made the course from the field to farm with normal speed (53 km/h). After returning to the road max speed is set to 10 km/h, wich is the max of "Wendemanöver". 

Here is the log.txt with debug channel 12 and 14. 

[log.txt](https://github.com/Courseplay/courseplay/files/2834912/log.txt)

**Comment by pvajko** [comment] 2019-02-06 17:16
Oh, this is combi mode, then it goes to @ThomasGaertner.

**Comment by ThomasGaertner** [comment] 2019-02-06 17:48
can you give me the savegame and course, I cant reproduce it ...

**Comment by tjBerlin** [comment] 2019-02-06 21:15
I loaded the savegame and the courses to gist. 

savegame9
https://gist.github.com/tjBerlin/467f774f78605527f00ce206c331ecdb

courses, it should be #17 
https://gist.github.com/tjBerlin/ce042b2bbdfb1961c1a6ddc42cfaae5a

But bevor, I tried to reproduce the issue with CP version .00046. And there something happens: 

I tried the course with the combination JOHN DEERE and APERION 3401. And it worked! Very fine. I got a little bit confused. I remembered that on the other time I used FENDT, so I did a test: JOHN DEERE vs FENDT same trailer APERION 3401, starting point field 10, beginning at "first waypoint":

![bildschirmfoto 2019-02-06 um 21 48 28](https://user-images.githubusercontent.com/24283753/52373856-0de54d80-2a5c-11e9-8cfd-7450ec3c21ca.png)

The JOHN DEERE again made the course without problem. 

![bildschirmfoto 2019-02-06 um 21 49 30](https://user-images.githubusercontent.com/24283753/52373914-2f463980-2a5c-11e9-9ae2-f6435c2ae905.png)

But as the FENDT started max speed was reduced to 24 km/h. As you can see on the first screenshoot it was 63 km/h.

![bildschirmfoto 2019-02-06 um 21 51 28](https://user-images.githubusercontent.com/24283753/52374015-792f1f80-2a5c-11e9-8dbb-cd56887e1147.png)

The speed didn't increase the whole course. 

![bildschirmfoto 2019-02-06 um 21 53 13](https://user-images.githubusercontent.com/24283753/52374086-9f54bf80-2a5c-11e9-8dc0-bf97942a7d49.png)

Here is the log. 
[log.txt](https://github.com/Courseplay/courseplay/files/2838272/log.txt)

**Comment by tjBerlin** [comment] 2019-02-06 21:23
Because I saw on the last screenshoot the FENDT should use speed "wie beim einfahren", I tried it with max speed: 

![bildschirmfoto 2019-02-06 um 22 20 44](https://user-images.githubusercontent.com/24283753/52374428-88fb3380-2a5d-11e9-82e2-7018f314b35d.png)

Same issue, speed is reduced to 24 km/h.

**Closed** 2019-02-06 22:50 UTC
Labels: bug
