### ISSUE TITLE
Waiting for combine to call and unloading issues

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5580] opened 2020-06-07 19:24 UTC
Im using Ver027 and im having a few issues. Im having problems with combines and tractors not communicating.
![fsScreen_2020_06_07_20_03_25](https://user-images.githubusercontent.com/11178621/83977907-b24efc80-a8fb-11ea-9045-157c1f2725a3.png)
You can see the tractor hasnt picked up the combine despite the combine calling for it. It has a clear path between them. Ive tried turning the fruit option off but it makes no difference.
![fsScreen_2020_06_07_20_03_36](https://user-images.githubusercontent.com/11178621/83977942-f9d58880-a8fb-11ea-87d3-ee48d7a45c04.png)
Ive also been having issues where the tractor wil appraoch the moving combine and take off a small bit then stop. Then restart take off a bit more then stop. It will continue doing this. Its the 936 tractor in the pics
![fsScreen_2020_06_07_19_23_29](https://user-images.githubusercontent.com/11178621/83978006-5fc21000-a8fc-11ea-9271-5888864be458.png)
![fsScreen_2020_06_07_19_23_37](https://user-images.githubusercontent.com/11178621/83978014-74060d00-a8fc-11ea-93f3-05ba5c6ffca6.png)
![fsScreen_2020_06_07_19_23_53](https://user-images.githubusercontent.com/11178621/83978022-8718dd00-a8fc-11ea-9a93-4067931ea050.png)
You can see it drives to combine then stops and reverts back to waiting for combine to call before deiving back up to the combine and repeating the process
[log.txt](https://github.com/Courseplay/courseplay/files/4742751/log.txt)

**Comment by Tensuko** [comment] 2020-06-07 20:10
Closed Duplicate #5579

**Comment by pvaiko** [comment] 2020-06-08 15:52
@kwguk first of all, multiple unloaders per combine are not supported yet. 

If you had a savegame about your second problem (stopping/starting) that would be great.

**Comment by kwguk** [comment] 2020-06-09 06:56
By 'saved game' do you mean you want a copy of the game the incidents happen?
If so do I just drop said save game the way I drop my log? It's well over 100 hours if that makes a difference.

West Amesbury Farms

**Comment by kwguk** [comment] 2020-06-09 10:06
You gonna have to explain how i foreward my save game. Ive tried and its said you dont support that file type

**Comment by Tensuko** [comment] 2020-06-09 10:18
![savegame](https://user-images.githubusercontent.com/27344744/84136250-51363e80-aa4b-11ea-889d-4505d2f5b3f7.png)

**Comment by Bobster82** [comment] 2020-06-09 11:00
>You can see it drives to combine then stops and reverts back to waiting for combine to call before >deiving back up to the combine and repeating the process

I think the problem with the switch states can occur due the trailer mod.... I see when using that trailer, sometimes the back is a target, then it switch targets to the front or middle... I never seen that happen on a vanilla trailer ;)

>You can see the tractor hasnt picked up the combine despite the combine calling for it. It has a >clear path between them. Ive tried turning the fruit option off but it makes no difference.

The problem here is that as pvaiko said, no multiple unloaders are supported...
When combine unload is set at closest distance:
What is happening here is when  "unloader1" is assigned to a combine and the other "unloader2" is at closer distance, the combine still has assigned the unloader1, while asking for unloader2... thats why it doesnt switch to unload combine as unloader1 thinks unloader 2 goes to unload...

@pvaiko  and @Tensuko  ... this might help? I see this in most mode2 "problems"

**Comment by kwguk** [comment] 2020-06-09 11:06
Hopefully ive done this right
[savegame1.zip](https://github.com/Courseplay/courseplay/files/4751740/savegame1.zip)
I have been experimenting with 2 combines on lands courses with one unloader. The unloader with the 2 smaller JD combines was the one that was unloading with the other 939 on the combine cuttting oats.

**Comment by kwguk** [comment] 2020-06-09 12:27
I’ll try with another trailer when I get chance 
Thanks for the input 
Appreciated 

West Amesbury Farms

**Comment by kwguk** [comment] 2020-06-09 20:30
> > You can see it drives to combine then stops and reverts back to waiting for combine to call before >deiving back up to the combine and repeating the process
> 
> I think the problem with the switch states can occur due the trailer mod.... I see when using that trailer, sometimes the back is a target, then it switch targets to the front or middle... I never seen that happen on a vanilla trailer ;)
> 

That particular trailer is from Modhub. I was using the 800 version, which i think gave me no problems. I only switched as the 800 wasnt triggering autoload when using AD for sale runs from the silo whereas the 980 would trigger autoload. Bizzare.

**Comment by kwguk** [comment] 2020-06-09 20:36
> > You can see the tractor hasnt picked up the combine despite the combine calling for it. It has a >clear path between them. Ive tried turning the fruit option off but it makes no difference.
> 
> The problem here is that as pvaiko said, no multiple unloaders are supported...
> When combine unload is set at closest distance:
> What is happening here is when "unloader1" is assigned to a combine and the other "unloader2" is at closer distance, the combine still has assigned the unloader1, while asking for unloader2... thats why it doesnt switch to unload combine as unloader1 thinks unloader 2 goes to unload...
> 

Ive been using two unloaders all the time, otherwise the combine would be stopped for freakin' ages. Most of the time it works no problem. Wouldnt it be better if the combine could use 'fill level'? Then it would concentrate on a single trailer regardless of what else was in the field until it was full and had departed the field. I understand the whole 'only one unloader is supported' thing but im happy to make compromises in my gameplay to keep my combines moving!

**Comment by Bobster82** [comment] 2020-06-09 20:53
> That particular trailer is from Modhub. I was using the 800 version, which i think gave me no problems. I only switched as the 800 wasnt triggering autoload when using AD for sale runs from the silo whereas the 980 would trigger autoload. Bizzare.

So the problem isnt there when using a vanilla trailer? Then there is a problem with that mod... am I correct?



> Ive been using two unloaders all the time, otherwise the combine would be stopped for freakin' ages. Most of the time it works no problem. Wouldnt it be better if the combine could use 'fill level'? Then it would concentrate on a single trailer regardless of what else was in the field until it was full and had departed the field. I understand the whole 'only one unloader is supported' thing but im happy to make compromises in my gameplay to keep my combines moving!

As mode2 is still in development, some parts are not working (yet)
If im correctly, the search for highest fill can work, as there is no other unloader interfering. Didnt test this myself, but i can if needed... see if it works ;)

**Comment by pvaiko** [comment] 2020-06-10 11:44
Test with 28 and post the log here.

**Comment by Tensuko** [comment] 2020-09-28 13:30
I guess this one is solved then.

**Closed by Tensuko** 2020-09-28 13:30 UTC
Labels: Mode2/Mode3
