### ISSUE TITLE
Sugarcane Transporter

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#4316] opened 2019-10-01 01:02 UTC
Guys, I don't know if anyone has already answered or talked about, but I would like to know if you have an apossicao of how is working bazooka, because I try and not enabling the use of bazooka. I'm always in the last version of you.
A big hug

**Comment by Tensuko** [comment] 2019-10-01 05:02
bazooka is not rly helping us, as we don't play with weapons...
original language ?

**Comment by Tensuko** [comment] 2019-10-05 10:46
Closing this as I got no Idea what you are talking about. Post your original language part and I translate it on my own, then I will reopen this.

**Comment by erksartori** [comment] 2019-10-13 10:12
OK, ok

Vamos la, agora fica mais fácil eu escrever na minha língua.

Não sei se alguém já reportou, realmente por não entender varias línguas aqui, mas eu ainda não consegui fazer funcionar as bazucas, e os implementos de cana, a bazuca que eu falo seria aquelas carretinhas com cano  para poder descarregar no caminhão. é isso

abraços a todos

**Comment by Tensuko** [comment] 2019-10-13 10:40
Sugarcane Transporter I guess, when I use deepl translater.

**Comment by Tensuko** [comment] 2019-10-13 10:41
@pvaiko den habe ich dir nur gegeben, weil ich nicht weis wer die tools mit achsen zum abladen brauchbar macht....

**Comment by pvaiko** [comment] 2019-10-13 16:02
Still have no idea what the issue here is.

**Comment by Tensuko** [comment] 2019-10-13 17:53
@ThomasGaertner Die Zuckerrohr Anhänger werden nicht entladen, denke mal weil die nicht mit i sondern mit einer Achsen entladen werden.
z.B. der hier, habs probiert, geht nicht.
![fsScreen_2019_10_13_19_07_40](https://user-images.githubusercontent.com/27344744/66719650-149a4080-edf3-11e9-87a8-91dacd29f336.png)

**Comment by rgoe** [comment] 2019-10-14 15:00
Maybe the same as #4021?

**Comment by Tensuko** [comment] 2019-10-14 15:04
Thanks. Duplicate of #4021 closed.

**Closed by Tensuko** 2019-10-14 15:04 UTC
Labels: postponed
