### ISSUE TITLE
Wrong headland maneuver for multiple vehicles

### ISSUE THREAD

**Issue by raxtor** [Courseplay/courseplay#4068] opened 2019-08-11 11:37 UTC
I used 3 combines and 2 vehicles in mode 2.. I noticed too there is changed turning maneuver for combines in this version for sharp corner and doesnt work correctly... look at image <a href="https://ibb.co/hKS5Wqm"><img src="https://i.ibb.co/nDF2cWL/field.jpg" alt="field" border="0"></a>

Probably its connected somehow with changes for ploughing

**Comment by pvaiko** [comment] 2019-08-11 11:47
I can't reproduce the problem with the left (outermost) combine. That one seems to work fine for me. What working width are you using?

**Comment by pvaiko** [comment] 2019-08-11 11:47
Also, post a log with debug channels 12 and 14.

**Comment by raxtor** [comment] 2019-08-11 11:50
Its Case 9240 with 13,5m header and turn radius is set to 14m (default). Log file will try asap..

**Comment by aviator64** [comment] 2019-08-11 12:58
I am experiencing the same issue when using three harvesters in convoy. Here is my log and some screen shots.

![fsScreen_2019_08_11_13_49_15](https://user-images.githubusercontent.com/19857526/62834112-d7bd9c00-bc3f-11e9-83db-d241358be340.png)
![fsScreen_2019_08_11_13_49_26](https://user-images.githubusercontent.com/19857526/62834117-e015d700-bc3f-11e9-9db7-ef32b504aba4.png)
![fsScreen_2019_08_11_13_49_41](https://user-images.githubusercontent.com/19857526/62834119-e6a44e80-bc3f-11e9-962a-4e690b9a3091.png)
![fsScreen_2019_08_11_13_51_08](https://user-images.githubusercontent.com/19857526/62834122-f02db680-bc3f-11e9-952d-c094363c6cfc.png)
![fsScreen_2019_08_11_13_53_15](https://user-images.githubusercontent.com/19857526/62834123-f2901080-bc3f-11e9-980d-0710b94fbbd4.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3489972/log.txt)

**Comment by pvaiko** [comment] 2019-08-11 13:07
@aviator64 if you activate 'turn on field' it will be much better.

**Comment by raxtor** [comment] 2019-08-11 13:12
Well... logfile and screenshots + CP courses for field22 (County Line 2.0 map)
http://mysharegadget.com/335601657

I used 3x Case 9240 (course 22s) and 2x Krampe Bandit 750 (course 22o)
Mode 2 used 70% for coming to combine and 90% for silo unloding
You can try 1st headleand you will get a lot of troubles
- bad headland turning maneuvers
- conway distance fail whn turning maneuver
- a lot of crashes combine/tractor (over 10 conflicts during 1 headland) 

So all time you only fix tarcator and combine collisions.

**Comment by pvaiko** [comment] 2019-08-11 13:42
As the release notes say, 271 should work fine with multiple tools as long as 'turn on field' is activated. With multiple tools and 'turn on field' deactivated the inner combine will still not turn nice, I'll fix that in a later release.

Other than that, this issue is not something new in the recent releases, this has been a problem for quite a while, maybe since 230.

Also, don't mix things up here, collisions are an entirely different problem.

**Comment by raxtor** [comment] 2019-08-11 13:44
I know you are working on AI drivers yet, so I assume it will be solved in future. 
Anyway that conwoy distance? Should I open new issue?

**Comment by Tensuko** [comment] 2019-08-11 13:54
Whats wrong with the conwoy distance ?

**Comment by raxtor** [comment] 2019-08-11 13:58
in some turning maneuvers next combine doesnt respect conwoy distance and continues in course when vehicle ahead makes sharp corner turn.. see images, where 2 combines got to crash situation..
http://mysharegadget.com/335601657

**Comment by raxtor** [comment] 2019-08-11 14:09
I tested 271 and stil I see for inner combine wrong turn maneuver like describe image above...

**Comment by pvaiko** [comment] 2019-08-11 14:32
> I tested 271 and still I see for inner combine wrong turn maneuver like describes image above

That's what I said above, right? And I also said that it works with 'turn on field' activated.

**Comment by raxtor** [comment] 2019-08-11 14:34
"turn on field" ofc

**Comment by pvaiko** [comment] 2019-08-11 14:37
screenshot with debug channels 12 and 14.

**Comment by raxtor** [comment] 2019-08-11 14:39
<a href="https://ibb.co/5RDDrsd"><img src="https://i.ibb.co/5RDDrsd/fs-Screen-2019-08-11-16-38-46.png" alt="fs-Screen-2019-08-11-16-38-46" border="0"></a>

**Comment by Tensuko** [comment] 2019-08-11 14:55
For me it looks like he is doing it correctly....
3rd Combine in 2nd Headland (count the straw rows) and he turns that way....

**Comment by raxtor** [comment] 2019-08-11 15:01
Imho no, its should be done in the same way like 2nd harvester. Thats how course was generated. It means go to edge and than use reverse maneuver.. yes its second headland..

As I said, it worked perfectly in 266 version yet...

**Comment by pvaiko** [comment] 2019-08-11 18:33
Oh, two headlands with multiple tools, That won't work for the inner one, yes. 

> As I said, it worked perfectly in 266 version yet...
Yes, we all understand that. Isn't it awesome that you can download any previous version and use whichever works best for you?

**Comment by raxtor** [comment] 2019-08-11 19:02
Well.. tried to help you.. it seems you dont need it.

**Comment by pvaiko** [comment] 2019-08-12 01:05
Try with 272. And no, it does not work perfectly with 266.

**Comment by raxtor** [comment] 2019-08-12 12:32
You are right there is problem in earlier versions too.. but 273 still doing circle turn for inner harvester. What is problem? Maneuver is nice but when unloader is called usually it ends with crash between tractor and harvester. Thats why inner harvester should use reverse turn. Other possibility is send STOP signal to unloader when special turning maneuver is started.. Maybe I explained it in wrong way earlier but I hope you understand what I mean.
Also I made short video with about conwoy problem..
[![Watch the video](https://img.youtube.com/vi/rfTLj3sQa3k/maxresdefault.jpg)](https://youtu.be/rfTLj3sQa3k)

**Comment by pvaiko** [comment] 2019-08-12 13:33
Are you saying that with 273 it is still not working for the inner combine? 

Please note that this issue is for the headland turn only, please do not mix it with other problems 
(BTW, not sure what the problem with the convoy is, if you set the distance too short, it'll fail. With those big combines and wide headers 50 m will obviously not work, so set the distance higher.)

That with the unloader is a third topic which has a million issues open and is well known.

**Comment by raxtor** [comment] 2019-08-12 13:53
I have no idea what was fixed for inner combine. Can you say me what is awaited behaviour of your fix for inner combine? Now if corner has angle 90 and above, inner combine still do circle maneuver... Wasi it your intention?

Convoy problem is when combine start turn maneuver than next combine in convoy is not able detect real distance and continues in course instead of stop in safe distance and wait till turn manuever will be finished. It has nothing to do with header width or shouldnt imho.

..and after loaded savegame is original convoy distance forgotten. You have to set it again.. but its not big issue.

**Comment by Tensuko** [comment] 2019-08-12 13:53
If the only problem with this turn is, that the unloader will crash into Combine, it is #3311 
Becouse the Combine and Tractor not talk to each other right now.

**Comment by Tensuko** [comment] 2019-08-12 13:55
> Can you say me what is awaited behaviour of your fix for inner combine?

The question is, what is your expected behavior of the Combine ?
If you expect only a different turn becouse the unloader crash, well as I said, it will happen in any situation becouse of #3311

**Comment by pvaiko** [comment] 2019-08-12 13:57
The inner one should do exactly the same what the others do. (The combine I tested with works fine)

And one last time: this is for headland turns only. Find another issue to discuss the convoy problem.

**Comment by raxtor** [comment] 2019-08-12 14:00
Well, than close it... is there any theoretical idea of term when #3311 will be solve?
My original idea was using reverse turn instead of circle like do it single harvester when angle of turn is too sharp... and yes, I speak only about headlands.. maybe I dont know all scenarios how headland turns works and which maneuver is used for specific situation.

**Comment by Tensuko** [comment] 2019-08-12 14:01
Questions about 'when' won't get answered, as it is a hobby project and dev will work on it when there is time for it...
I will make my own test with that and then close this one...

**Comment by raxtor** [comment] 2019-08-12 14:05
ok, thx for your time..

**Comment by Tensuko** [comment] 2019-08-12 14:35
![fsScreen_2019_08_12_16_13_03](https://user-images.githubusercontent.com/27344744/62872963-cd260400-bd1e-11e9-9036-0f49bdf98055.png)
![fsScreen_2019_08_12_16_13_24](https://user-images.githubusercontent.com/27344744/62872966-cdbe9a80-bd1e-11e9-9324-73b3529758be.png)
![fsScreen_2019_08_12_16_13_38](https://user-images.githubusercontent.com/27344744/62872973-d2834e80-bd1e-11e9-919b-5ad2f6b29b0a.png)
Works fine.
Even on 2nd row of Headland.
About Convoy, we know the Issue, but you should take a bigger distance for such big Combine.
I use base setting of 100m and it works very good for me.

Closed.

**Closed by Tensuko** 2019-08-12 14:35 UTC
