### ISSUE TITLE
seed express 1260 cant save pipe position 

### ISSUE THREAD

**Issue by KAAG101** [Courseplay/courseplay#1987] opened 2017-04-17 13:02 UTC
Hey there
cp is the best mod for fs 17 :) 
i have a problem with the seed express it cant save pipe posistion is it somthing you can fix :) 
im use cp 5.01.00120
Thomas

**Comment by Blackmankot** [comment] 2017-04-18 04:37
Good afternoon. I already asked. Here is the answer to your question. :)

#1979 
![2017-04-18_12-34-40](https://cloud.githubusercontent.com/assets/26131714/25114729/6f78e600-2433-11e7-9cab-cee3bd1a7627.jpg)

**Comment by KAAG101** [comment] 2017-04-18 05:44
Good afternoon to you to. 
It might be that I did not understand your post but 
I see the line with the seed express. But I can't save the position. It is listet under augerwagon :)

**Comment by Blackmankot** [comment] 2017-04-18 07:32
@KAAG101  Show on screenshots. It will be easier to defuse the problem.

**Comment by KAAG101** [comment] 2017-04-18 11:47
![image](https://cloud.githubusercontent.com/assets/4026751/25129202/4ca0ea88-243d-11e7-87fa-dee55ca0c1d9.png)
when i try i cant save the pipe position :)

**Comment by Blackmankot** [comment] 2017-04-18 14:58
@KAAG101 The problem is in your fashion. I fix the pipe works in any position. The screenshot shows.
![2017-04-18_22-25-37](https://cloud.githubusercontent.com/assets/26131714/25137459/64815208-248a-11e7-9dbb-9479f19f02e3.jpg)
![2017-04-18_22-30-01](https://cloud.githubusercontent.com/assets/26131714/25137475/6e13f410-248a-11e7-8ef8-d3170ed6a9ba.jpg)
![2017-04-18_22-21-14](https://cloud.githubusercontent.com/assets/26131714/25137480/71f2a946-248a-11e7-9cd0-817bf254bd21.jpg)
![2017-04-18_22-21-49](https://cloud.githubusercontent.com/assets/26131714/25137483/7478259c-248a-11e7-87f0-d619e145c8c3.jpg)

**Comment by KAAG101** [comment] 2017-04-18 15:43
do you have any idea what i have to change to make it work :)

**Comment by KAAG101** [comment] 2017-04-18 15:49
the biggest difrent i cant see is that the seed express's pipe can move in 3d and the overloader trailers in the game only cant move in 2d

**Comment by Blackmankot** [comment] 2017-04-18 16:38
@KAAG101 I do not know how to solve your problem ... :)

**Comment by pops64** [comment] 2017-04-18 16:53
Can we get a clean link to your mod in question.

**Comment by KAAG101** [comment] 2017-04-19 06:53
here is the mod that i use https://www.modhoster.com/mods/seed-express-1260

**Comment by Blackmankot** [comment] 2017-08-05 02:21
@pops64 There is a problem of the mod itself, not the course. I suggest closing it for cleaning.

**Comment by KAAG101** [comment] 2017-08-09 00:36
tanks for looking at it :)

**Comment by pops64** [comment] 2017-08-12 20:08
Collapsing mod issues into one thread. #2231

**Closed by pops64** 2017-08-12 20:08 UTC
Labels: Mod Issue
