### ISSUE TITLE
Slurry not restarted after connecting track

### ISSUE THREAD

**Issue by abehnke** [Courseplay/courseplay#2584] opened 2018-02-16 13:40 UTC
Upon completing the connecting track on a generated course, the slurry tanker is not turned on. Instead, it does not restart until it reaches the turn at the end of the row.  Thus most of one row is left untreated.

I have included the course xml. Course is generated 12m wide with 2 headlands for field 14 of Goldcrest.

First image shows the tanker just after the connecting track ends and it should resume spraying. Note the wp is 222 which is after the last isconnectingtrack="true" wp which is at 213

Second image shows the tanker starting the spray just before the turn.

Using the standard Goldcrest map with default equipment. Only Courseplay5 (5.2.56) enabled.

![one](https://user-images.githubusercontent.com/3346683/36310038-c8cd320a-12f4-11e8-8774-e8cf5352cb39.png)

![two](https://user-images.githubusercontent.com/3346683/36310061-da18e66c-12f4-11e8-98ac-5e655f87514c.png)

[log.txt](https://github.com/Courseplay/courseplay/files/1731493/log.txt)

[courseStorage0116.xml.txt](https://github.com/Courseplay/courseplay/files/1731496/courseStorage0116.xml.txt)

**Comment by pvajko** [comment] 2018-02-18 01:28
@pops64 don't you want to look at this? The course is fine, I think the problem is that CP assumes there'll always be a turn maneuver which actually lowers the implements which isn't the case here.

**Comment by pops64** [comment] 2018-02-18 15:08
Yea I'll look at this. It has been a while so it may take some time

**Comment by pops64** [comment] 2018-07-27 22:09
Is this problem still occurring?

**Comment by abehnke** [comment] 2018-07-31 16:13
@pops64  Sorry - I don't know. I am not playing Farming Simulator at this time.  But thanks for looking into the problem.

**Comment by pops64** [comment] 2018-08-01 13:28
Alright, Ill close this out then. If I can reproduce the problem Ill open it back other wise just post here if you can reproduce the problem. Has I can't think of anything that would cause this problem

**Closed by pops64** 2018-08-01 13:28 UTC
Labels: bug
