### ISSUE TITLE
Defect: Cat-like rear-end shimmy in T4-40

### ISSUE THREAD

**Issue by realskudd** [Courseplay/courseplay#5282] opened 2020-05-04 04:23 UTC
Problem: Using any field pattern with the Terra Dos T4-40 in the Lazy Acres map, the harvester gets confused and does a shimmy before re-entering the field at the headlands, much like a cat getting ready to attack. Only in this case, the harvester doesn't pounce as a cat would, and instead burns a lot of fuel unless manually intervened. 

Example: [YouTube Video](https://youtu.be/41wdsCgfYM8) 
  [Cat-like example](https://media1.tenor.com/images/a7a35678afafec1a63dde6e5d6f4d1a8/tenor.gif?itemid=13009272)

Other mods?: Yes. Disabling them doesn't have any effect, though.

Updated to latest map?: Not yet. This seems to have only started in a recent build (from early 2020 onward). I haven't been able to track it down to one specific build though.

**Comment by realskudd** [comment] 2020-05-04 04:26
Failed to mention, but figure this would be best to throw down here: The version of the map, according to the modDesc.xml, is 1.1.1.0.

**Comment by Tensuko** [comment] 2020-05-04 08:21
And where is the logfile ?

**Comment by pvaiko** [comment] 2020-05-04 11:25
@Tensuko this has already been reported I just can't find it anymore.

@realskudd is  this happening only on this map? Need a log and video if possible with 12 and 14.

**Comment by Tensuko** [comment] 2020-05-04 11:41
@pvaiko this:  #5023

**Comment by realskudd** [comment] 2020-05-04 18:28
I turned on some of the debug channels to get some additional detail. 
[log.txt](https://github.com/Courseplay/courseplay/files/4576525/log.txt)

Also, here's a screenshot of the debug channel 14 overlay on the screen when this happened:
![fsScreen_2020_05_04_13_26_49](https://user-images.githubusercontent.com/4642150/80999968-24b75300-8e0b-11ea-972b-0470cbb5f336.png)

**Comment by realskudd** [comment] 2020-05-04 18:38
Sorry, I missed that you wanted debug 12 as well. Here's after another lap.
[log.txt](https://github.com/Courseplay/courseplay/files/4576597/log.txt)

**Comment by pvaiko** [comment] 2020-05-04 18:45
@realskudd thanks, in the meanwhile, if you enable AI turns it should stop dancing (as recommended in #5023).

**Comment by pvaiko** [comment] 2020-05-04 18:47
Ok, looks like the 3 point turn generator code overlaps two waypoints (39 and 40 on the screenshot), almost sure that is causing this cute behavior.

**Comment by realskudd** [comment] 2020-05-04 18:47
I just turned that on and I'm waiting to see if it helps. Another thing I have noticed in general is that the advanced settings don't persist between game restarts. Is that something y'all are aware of already, or should I open a separate defect for that?

**Comment by Tensuko** [comment] 2020-05-04 18:50
What do you mean with dont persists ?

**Comment by realskudd** [comment] 2020-05-04 18:51
I mean that now that I have enabled the AI in turns option, if I quit the game and start it up again that setting will not be enabled.

**Comment by Tensuko** [comment] 2020-05-04 19:20
Can't reproduce, all works fine on my side

**Comment by pvaiko** [comment] 2020-05-04 19:24
@realskudd definitely persisted. Sure you clicked Ok on the Advanced Settings screen after you changed it right?

**Comment by realskudd** [comment] 2020-05-04 19:45
Yep. I'll test it again now though. Stand by.

**Comment by realskudd** [comment] 2020-05-04 19:48
> Ok, looks like the 3 point turn generator code overlaps two waypoints (39 and 40 on the screenshot), almost sure that is causing this cute behavior.

So is it safe to assume that this (original issue) will be addressed via a fix?

**Comment by pvaiko** [comment] 2020-05-04 19:56
Yes, and if you'd like to play around with it you can change the 'true' to 'false' here to see it fixes it:
https://github.com/Courseplay/courseplay/blob/f656209f878537bf5e79f687b8c1be65b4038742/turn.lua#L992

**Comment by realskudd** [comment] 2020-05-04 21:33
That seems to have fixed it. I'll need to test for a while though to see if it has affected anything else. Would you like for me to submit a PR for it assuming it passes my tests?

**Comment by MicaelJarniac** [comment] 2020-05-04 22:09
This also happened to me a couple days ago, on Ravenport, doing a contract on one of the large fields. I don't remember which field exactly, but I had this happen like 3 times during the entire course, so I had to keep going back to it to make sure it wasn't dancing.

**Comment by pvaiko** [comment] 2020-05-04 22:22
@realskudd thanks for the offer, should be fixed now.

**Comment by Tensuko** [comment] 2020-05-05 17:56
For me it worked nice and smoothly.
Can someone pls confirm this ?

**Comment by realskudd** [comment] 2020-05-06 02:04
I'm playing with the change in my own deviated branch and it's working fine.

**Comment by MicaelJarniac** [comment] 2020-05-06 02:56
I've done a little bit of testing and couldn't get it to happen again, so it seems to be working fine for me too.

**Comment by Tensuko** [comment] 2020-05-06 03:24
Ok I take it as fixed then.

**Closed by Tensuko** 2020-05-06 03:24 UTC
Labels: waitingForUserAnswer

**Comment by realskudd** [comment] 2020-05-06 03:42
\o/
Thanks for the quick turnaround y'all.
