### ISSUE TITLE
Mode 2?

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#2039] opened 2017-05-06 09:24 UTC
Since I was away from FS now downloaded latest CP version. But now ingame I had unfinished field with forage harvester. Did everything as last time, but now driver's in mode 2 hit harvester every time they try to turn. My question is, is in mode 2 driver's turn around only inside the field? If so how I can disable it? Or I'm missing something?

**Comment by Raints** [comment] 2017-05-07 06:27
https://youtu.be/Ol60wJ6TPTc

Here is a video what im talking about.

**Comment by pops64** [comment] 2017-05-07 15:16
Yea the system wasn't designed to handle straw swaths. And in 17 you can't be default collect chaff from them.

**Comment by Raints** [comment] 2017-05-07 15:28
So before all worked well and now its not anymore? Will close it then.

**Comment by pops64** [comment] 2017-05-07 16:11
We will look into but when the current system was designed we didn't take into account straw swaths because by default you can't collect those with the chaff harvester any more.

**Comment by Raints** [comment] 2017-06-12 15:45
Sorry about posting here again, but what about grass swaths. I get same problem and grass swath's are in game by default. 
![fsscreen_2017_06_12_18_41_01](https://user-images.githubusercontent.com/3618060/27042318-39bf1a4c-4f9f-11e7-86ef-4d324429a150.png)

**Comment by pops64** [comment] 2017-06-21 01:47
How is this occurring exactly. CP does take into account the work width of the harvester when calculating how wide of a turn to make.

**Comment by Raints** [comment] 2017-06-21 18:04
Will make a new video about it.

**Comment by ThomasGaertner** [comment] 2017-07-01 09:35
pleas test again with .155 or higher and report.
Please consider, that you have to set the work width of the chopper to the width of the swaths manually

**Comment by willie2016** [comment] 2017-07-01 19:28
ThomasGaertner commented 10 hours ago
pleas test again with .155 or higher and report.
Please consider, that you have to set the work width of the chopper to the width of the swaths manually

so if my mower cuts the swaths at 8.4 i then have to set the harvester to go 8.4 ? because i normally save the course for the mower and load into fieldwork mode for forager , shouldnt that tell forager exactly that the swaths are 8.4  apart ?

**Comment by pops64** [comment] 2017-07-01 20:09
I don't believe that course work width is saved when you save a course(aka when you load in a saved course). You have to manually put in the work width for the harvester in order for it to read the work width setting to make the turn maneuver to work correctly for the following tipper

**Comment by willie2016** [comment] 2017-07-01 21:16
ok thanks i got that much to work , but now i have issue where iv selected the forager to tell the tipper go to the left each time , but at the end it goes to the right and when it starts to move on the swath the tractor and tipper attempts to go to the left and causes collision

**Comment by pops64** [comment] 2017-07-02 15:47
Could we get a video of this. I think I might now what is going but I would need a video to tell for sure. Or a log with debug channel 3 when the tipper is approaching the harvester.

**Comment by willie2016** [comment] 2017-07-02 16:16
ill try get a video but will be few hours ok , im trying to uninstall and reinstall my game , had to clear my laptop due to performance issues so need to install stuff again once done and ill get a video for you

**Comment by ollydoyle** [comment] 2017-07-02 20:44
> I don't believe that course work width is saved when you save a course(aka when you load in a saved course). You have to manually put in the work width for the harvester in order for it to read the work width setting to make the turn maneuver to work correctly for the following tipper

I've noticed that after each lane the work width resets to that of the harvester, say 3.1, rather than staying at that used to generate the course, in willie2016 case 8.5m. maybe this is causing the problem with turns?

**Comment by pops64** [comment] 2017-07-02 21:04
Hmmm. We will look into that

**Comment by ThomasGaertner** [comment] 2017-07-03 06:33
@ollydoyle , which version are U using ? it should have been changed since .155 ...

**Comment by ollydoyle** [comment] 2017-07-03 11:49
@ThomasGaertner, sorry my bad, you are correct, that is not happening in the latest versions

**Comment by pops64** [comment] 2017-08-12 20:53
Closing this out @willie2016 has been reported in a different thread.

**Closed by pops64** 2017-08-12 20:53 UTC
Labels: bug, waitingForUserAnswer
