### ISSUE TITLE
Combine Self-Unload mode not finding trailer

### ISSUE THREAD

**Issue by Petje81** [Courseplay/courseplay#4764] opened 2020-01-02 20:47 UTC
v.357
[log.txt](https://github.com/Courseplay/courseplay/files/4017276/log.txt)

#4745 was closed, but after some more testing a problem remained of the combine seemingly not always finding a trailer on the field. Sometimes it does, sometimes it doesn't while the trailers are not full and haven't been moved.

The combine just stands there with the speed at 0.

[edit]
Same log, while CP active i pressed "drive now" and that gave more info
[log.txt](https://github.com/Courseplay/courseplay/files/4017291/log.txt)

[edit]
After manually unloading a bit of it into an trailer and restarting CP back on course the combine found it's way again to a trailer when it was full.
Kinda weird for me...

**Comment by pvaiko** [comment] 2020-01-02 22:28
Well, it did find the trailer, it did not find a path to the trailer...

Do you have a savegame of this situation? Next time you see this make sure you post a savegame. It would be interesting to see this situation, there a way too many factors involved in pathfinding and it may need some tuning in certain situations.

**Comment by Petje81** [comment] 2020-01-02 23:13
Too bad i don't. 
I can post the savegame next time i see this and it is very certain i will have this problem again very soon. I just stopped playing for today and in the last 2 hours the problem kept coming back randomly and a lot, even with multiple trailers **on** the fields.

**Comment by Petje81** [comment] 2020-01-03 21:00
Well, this is certainly a challenge for CP and also for me to get a good savegame for you. Just before the save it stuttered trying to find a trailer.
[savegame2.zip](https://github.com/Courseplay/courseplay/files/4020883/savegame2.zip)

Hope it is of use to you, yesterdays problem in the above logs were on field 23. Now im on 166.

**Comment by pvaiko** [comment] 2020-01-03 21:41
Jeez, this has like 200 mods. If the map, combine, trailer and other vehicles around the field are mods but are not on modhub I won't be able to use the savegame unless you provide the mods or a clean link to them.

**Comment by Petje81** [comment] 2020-01-03 21:59
I was kind of expecting your response. 

I could try and replicate the problem with ingame machinery or modhub mods on a standard map but the chance of getting the same situation is very small.
The problem will eventually come back somewhere somehow because it was something not connected to "weird" mods.

The combine i'm using is a Custom Modding release (no "trailer" in the xml) with an extra bunker extension with a Midwest header with increased speed. The tractor is from CM, the HTS34.16 and the wilson trailers from modhub and the Pete from Expendables.
At the time there was nothing else near the field except a silo i don't own. The truck and auger were pretty much within a radius of 50 mtrs of the combine and it just crapped out.

I don't know why but after 4 more fields done i am getting a 9,8 out of 10 going like it should.

**Comment by pvaiko** [comment] 2020-01-03 22:07
I'm not saying the problem is caused by the mods, all I'm saying the time I can spend on Courseplay is limited and don't want to waste it on trying to figure out where to get all these mods (example: "Pete from Expendables", may be obvious to you but I have know idea what that even is, and just for fun, try to google that term and see what comes up...) 

That's why I said either upload them somewhere or provide me clean links otherwise we'll have to wait until someone else runs into these with a more modest setup.

**Comment by Petje81** [comment] 2020-01-03 22:35
My response was mainly intented to be understanding that this replication will be a lot of effort for you. Therefore i am not expecting you to go such a long way to get this all replicated and was hinting towards "close this topic and maybe hope someone will get a better situation created to tackle this issue".

The term "Pete" i used is short for the brand of truck i am using, not expecting you to do anything with that but i was sort of trying to describe the situation.

Sorry i have wasted your time with this as i am very happy with all the time and effort you put into this which also makes my gaming experience a lot more fun.

**Comment by pvaiko** [comment] 2020-01-05 16:16
All right, closing this now then.

**Closed by pvaiko** 2020-01-05 16:16 UTC
