### ISSUE TITLE
Can not use the buttons in the Courseplay

### ISSUE THREAD

**Issue by k4296** [Courseplay/courseplay#1470] opened 2016-12-08 08:00 UTC
Hello courseplay team. When I get to the CP menu, I get the opportunity to press the buttons, But nothing happens. As if CP is not activated properly. Hope that there is someone who can help, so that I will be able to use courseplay. Best regards Klaus  
![fsscreen_2016_12_08_08_30_30](https://cloud.githubusercontent.com/assets/24450817/21002177/baa27eaa-bd24-11e6-999b-d61368b667a5.png)
![fsscreen_2016_12_08_08_31_03](https://cloud.githubusercontent.com/assets/24450817/21002182/c37f9440-bd24-11e6-86c1-6c62579fe63a.png)

**Comment by ThomasGaertner** [comment] 2016-12-08 14:51
log ?

**Comment by k4296** [comment] 2016-12-08 16:29
Hello Thomas. There was no errors in the log. And I have also tried CP with out other mods. Thats the same.

**Comment by SquareCloud506** [comment] 2016-12-08 16:37
The CP in the pictures is in Drive mode (bottom center button). You need to change to Fieldwork mode with a combine (bottom row of buttons) for the field generating button in top row to become active.

**Comment by k4296** [comment] 2016-12-08 16:51
SquareCloud506. My problem is that I can`t use any of the buttons. When I use the mause curser, nothing happend. Its change nothing. But I cann opload my log, and perhaps is there something that I haven`t seen. 
[log.txt](https://github.com/Courseplay/courseplay/files/640050/log.txt)

**Comment by SquareCloud506** [comment] 2016-12-08 20:44
I've managed to download the map you're using. I'll start installing the mods you show in the log file and see if I can pinpoint one that causes CP to not function anymore. I'm attempting to recreate the problem, unless somebody else knows of a direct conflict with CP and any of the other mods you've got showing in your log. :)

**Comment by hsiverts** [comment] 2016-12-08 23:30
Does it work with the standard maps?

**Comment by SquareCloud506** [comment] 2016-12-08 23:53
So far the HUD interaction works fine for me, both in standard maps and the mod map that k4296 is using here. I suspect a mod conflict as his log shows a lot of mods being loaded into his game. The one thing I've noticed so far from his screen shots is the Fuel consumption mod display is lower than it should be, for me it sits correctly next to the fuel icon in the vehicle info section, lower right corner. another possible mod conflict. At this point, I don't see this as being a bug specifically with CP.

**Comment by SquareCloud506** [comment] 2016-12-09 01:04
I'm unable to duplicate the problem you've described here, I'm also unable to find EVERY mod listed in your log. I installed the same map, and EVERY mod in ModHub (available in game under mods) both tested and beta, and CP still works fine for me. Sorry I couldn't be of further help.

**Comment by k4296** [comment] 2016-12-09 05:28
Thanks for the answer SquareCloud506. I cann hope, that the next version of CP works for me. Have a nice weekend. Best regards Klaus

**Comment by Satissis** [comment] 2016-12-09 12:37
Hi Klaus.
The only way to really figure out it this is an mod conflict, is to only have the mod map and courseplay active.
If that works, then slowly add more mods until it breaks again and you can narrow it down to what mod is conflicting with CP.
If it's an mod conflict, then please tell us what mod is doing this and where you got it from.

well we do still not support mods yet, but once we do, we have something to look into ;)

**Comment by k4296** [comment] 2016-12-09 14:01
Hi Satissis. When I have only the " Old stream map " and no more mods in my folder, it dont still. I think perhaps, that is my mause making the problem. Sometimes the mause do some strange thing. Thanks Satissis ( Klaus ) for your answar

**Comment by Satissis** [comment] 2016-12-10 01:51
can we close this then ? Since we are not able to reproduce it at all :S

**Comment by k4296** [comment] 2016-12-11 09:44
Yes you cann close it. Thanks for the answer all. Best regards Klaus

**Closed** 2016-12-11 15:07 UTC
Labels: waitingForUserAnswer
