### ISSUE TITLE
Turning Circle -9223372036854775808m

### ISSUE THREAD

**Issue by RicolaRules** [Courseplay/courseplay#1348] opened 2016-09-18 20:35 UTC
No matter the tractor used, with [http://www.farmingmods2015.com/case-ih-cart-air-seeder-32m-fixed-v1-1-fs-15/](THIS) seeder, the tractor finishes a row, and turns circles until the game crashes, or I stop it manually.
![turning circle issue](https://cloud.githubusercontent.com/assets/22281432/18618887/7fa68778-7db5-11e6-9c73-4a73f64c271b.jpg)

**Comment by Satissis** [comment] 2016-09-19 14:25
Well I have seen this before, but dont know what the problem is, other than it's the way the seeder is made and CP don't know about that type and returns an faulty value.

Also please read this: #1346

When that's said, then I am actually working on CP again, not working on bug fixes, but finishing stuff I want to finish before FS17 is released. The thing I'm working on right now is the new turn system and I have made some changes on how it calculates the turning circle, so it might already be fixed on that branch I'm working on, but I'll try get the seeder my self and test it out, to see what the problem could be.

I wont promise that I'll work on it right away though.

**Comment by RicolaRules** [comment] 2016-09-19 14:40
I'd much rather see continuing work for 2017 personally. Haha, already bought that and can't wait for release. If it's not a quick fix ill use something else as a seeder for now. I appreciate the quick response. Looking forward to things to come. (Hopefully alternate lane changes. E.g.; do lane one, then lane three, then lane 2, then 4, etc. Would cut back on missed corners with bigger machines) thanks again!

**Comment by Satissis** [comment] 2016-09-20 14:12
After a little chat with Thommas, we decided not to add this one, due to the way it's constructed and that it's way bigger than any of the real life versions of it :)

I'll close this for now,

**Closed by Satissis** 2016-09-20 14:12 UTC
Labels: bug, FS15

**Comment by pops64** [comment] 2016-11-21 19:40
Don't want to open old wounds but I was running FS15 and came across it. It appears the issue is in the calculateTurnRadius function in vehicles.lua. I added in 
`if rotMax == rad(90) then`
		`rotMax = rad(89);`
	`elseif rotMax < rad(1) then`
		`rotMax = rad(5);`
`end;`

To prevent divide by 0 and multi by 0 calculations in this function. And it went from the above value to 40m. So my guess is the function is being passed a 0 angle rotmax valve which is causing this behavior. My setup was the the deutz fahr 7250 ttv and Vaderstad carrier 820 in mode 6. I did not get this weird behavior in mode 4. I can report back any bug caused by this addition or if I find how a value < 1 is getting passed into the function.  Thanks for reading cause I know your busy with FS17 conversion. And sorry for opening closed bugs
