### ISSUE TITLE
Profihopper cant use anymore #MOD#

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2499] opened 2017-12-12 11:50 UTC
Hey guys,
since, i think, v02.0038 i have a proplem with cp, that i cant use the amazone profihoppern since this.
https://www.modhoster.de/mods/amazone-profihopper-2017-edition
i have generatet a fieldworkcourse, mode6, and a drive away course mode1, than i load the fieldcourse and combined them with the driveaway course:
[courseStorage0003.zip](https://github.com/Courseplay/courseplay/files/1551389/courseStorage0003.zip)
in earlyer version it works fine, i stastet the course on anway point, the profihopper drive to the first point, lower the mower, turn it on and cut and collect the gras, when he was full, he drivet to the first point to the driveaway course - unload at the gras-dry-hay station (fabricscript building) and drive to the first point and go to the point 10 points before he was full lower the mower turn it on, and mowe so the whole grass field.
but now:
al the same but cp dont lower the mower and cp dont turn on the mower.
he drive the way further but dont work.
when i stop the cp driver, start the mower manually and let the cp driver drive , he works fine, when the profikopper is full, he drive to the unload course unload drive to the first point, drive to the point he leave work and drive normaly , means, he dont turn on the mower. when i start it also manually the same als above.

as example, the big brother, case IH L32000 mower,
http://www.modhub.us/farming-simulator-2017-mods/case-ih-l32000-mower-for-farming-simulator-2017-v2/
work fine, also with v 02.0040. there are no such  problems.

lg
andreas

**Comment by pvajko** [comment] 2017-12-12 16:49
Andreas, not clear from your description if v 02.0040 has the problem with the Profihopper? And can you confirm that other tools work ok with 40?
Also we don't know which map is this.

**Comment by andreasthu** [comment] 2017-12-12 18:54
ok, map is the gorzkowa multifruit
https://www.modhoster.de/mods/gorzkowa_v3_2k17
i had make a little changes

my problem i, that the profihopper drive the course but he dit not cut the grass.
he dont work. when i start the mower deck manually ant then hire the cp helper, the helper cut and when full, he start the unloading course, come back and go to the rigt point but me dont turn on the mower. so he still drives the course in normal driving, not in cutting grass.
it funktions not with 0038, 009, and 0040.
in earlyer versions the profihopper works prfekt

i have an bigger mower, the case l3200mower, this machine makes it fine, cut grass, went to unloading, come back to field and cut grass.

also, in old cp versions, both machines work perfect, since 0038 the profihopper does no cutting.

lg
andreas

**Comment by andreasthu** [comment] 2017-12-12 20:10
ok, no plan which version this was.
the file generated at 24.november.
i use norml always the newest dev version from here.
but i have tried it with the v02.0040, i generated a fielwork course, save them as 1
then i generated a driveaway course, save as2
then i switch to mode 6 load the course 1, combine it with course 2 andtried it.
no works. the mower dont turn on the mowerdeck and so he dont cut grass

it is for me not so a big problem. used the profihopper only to cut grass for the sheeps.
can to the same work with the big case L32000 mower.

would only say that there are problems.

lg
andreas

**Comment by pvajko** [comment] 2017-12-27 17:31
Andreas,

can you get me a savegame and your courses folder as described under 9 in the wiki (https://github.com/Courseplay/courseplay/wiki) to make my life easier?

**Comment by andreasthu** [comment] 2017-12-27 19:46
ok, i load the map and the mods you need up to filehorst.de
can i send you the links at pm or should i post it here?
you cant use the original gorzkowa map while i build many things new and addet remove and change some
lg
andreas

**Comment by pvajko** [comment] 2017-12-27 19:59
I have downloaded the Profihopper and the Gorzkowa map, is the problem reproducible with those or only with your modified map? Honestly, I only want to spend time on this if it is potentially a problem affecting others too.

And sure, you can pm me.

**Comment by andreasthu** [comment] 2017-12-27 20:25
hello pvajko
sry, cant find the pm function here,
send you a email to github@vajko.name from your profile
no the things are on eachmap.
i rebuild the fences, so on normal map the mower cant follow the course
or i placed a gras to hay dry-fabricscript where the profihopper unlaods
or plac the haygrasloft from FS-modhub, but mine isable to stor more, also grass, where the case mower unloads,.. such things 
btw, with version 020047 i had seen that the profihopper turn on the mowerdeck when he find a turnstart or turnend, also in the up and down driving.
but not in the first 5 rounds before
in the smaler zip is also a *.ddswith infos to the field and the fieldcourse
i also have no permission from the mapper for the map so i cant offer here the map link for all people, sorry

lg
andreas

**Comment by andreasthu** [comment] 2017-12-27 20:31
you need only my courses, open na new game, cheat mone and buy the profihopper course Wiese33mä or to have an comparison use the case mower for Wiese31mä, to Wiese3mä
lg
andreas

**Comment by pvajko** [comment] 2017-12-28 07:07
Andreas, I know I can start a new game, cheat money and buy tools and drive them to the field from the shop, etc. but that all takes a lot of time. As you know, we all have jobs, families and we'd like to spend the little time we have with fixing bugs and adding new features and not setting up scenarios. That's why we ask for those files because then we only need to copy those and everything is set up for test.

**Comment by andreasthu** [comment] 2017-12-28 07:38
Ok.
No problem.
Send you later the day a savegame, ready for use and with machines in position.
Lg
Andreas

**Comment by andreasthu** [comment] 2017-12-28 13:26
so, here is the savegame.
Mower are in position and ready to cut grass
grass is growing full

[savegame7.zip](https://github.com/Courseplay/courseplay/files/1591264/savegame7.zip)

lg
andreas

**Comment by andreasthu** [comment] 2017-12-28 13:48
ok, sorry
save your time, i loadet a few minutes ago the v 020050 from the dev version down and testet it with this version. now it works.
i tried it only with the mods i have send you and i tried it with all mods in my modordner active
now the profihopper works correctly as he should.
dont know, last time is used it and he fail was with the  020047dev and there he works so i descriped above
in v0038, 009, and 0040 he dont worked, with 0037 it was also ok
other versions not testet
but thank you very much, you guys spend a lot of time to make us happy with cp and the game

hope you had a beautiful christmas and good luck in 2018

lg
andreas

**Comment by pvajko** [comment] 2017-12-28 18:05
Thanks for testing Andreas, I guess I can close this then, please reopen if you have any issues.

**Comment by andreasthu** [comment] 2018-03-13 08:45
Hy Guys
i have now the same problem with the v 02.00063.
the profihopper dont turn on the mower when he come back from unloading
with v 02.00060 he works perfekt.
lg
andreas

**Comment by andreasthu** [comment] 2018-03-15 06:03
ok, really silly,
now he doesnotwork with any cp-versioni testet
i sell the profihopper any rebuy it
now he works perfekt
is this a entry i nthe vehicles.xml?
here are both:
`
this is the old profihopper:

    <vehicle id="36" modName="FS17_Profihopper_BIG" filename="$moddir$FS17_Profihopper_BIG/Profihopper.xml" isAbsolute="true" age="118" price="12700" propertyState="1" operatingTime="71950.341820904"  fuelFillLevel="145.12883760798"  vsid="10" cruiseControl="18"  foldAnimTime="0.54705226421356" fillTypes="grass_windrow" fillLevels="3554.995"  preferedTipReferencePointIndex="1" isCoverOpen="true" dirtAmount="0.59498711922273" GPSstoreInv=""  ssLastRepairDay="120" ssYesterdayOperatingTime="54978360" ssCumulativeDirt="11736899.831768" ssYears="4.9166660308838" >
        <component1 position="-301.6618347168 81.26212310791 -104.86715698242" rotation="0.01190532464534 -0.00010588274744805 -0.003058890113607" />
        <configuration name="motor" id="1" />
        <boughtConfiguration name="motor" id="1" />
        <courseplay aiMode="6" courses="68" openHudWithMouse="true" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="grass_windrow" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="12" turn="12" field="24" max="43" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="70" fillDriveOn="95" turnDiameter="2" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0;0" abortWork="0" refillUntilPct="100" turnOnField="false" oppositeTurnMode="true" manualWorkWidth="0.0" ploughFieldEdge="false" lastValidTipDistance="0.0" hasSavedPosition="false" savedPositionX="0.000000" savedPositionZ="0.000000" savedFieldNum="0" fertilizerOption="true" convoyActive="false" /> 
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0" drivingThroughtLoading="false" />
        </courseplay>
        <followMe backDist="20" sideOffs="0.0" />
        <wheelDirt wheel1="0.600000" wheel2="0.600000" wheel3="0.600000" wheel4="0.600000"/>
    </vehicle>
	
--------------------------------

and here is the new one, who works:

    <vehicle id="92" modName="FS17_Profihopper_BIG" filename="$moddir$FS17_Profihopper_BIG/Profihopper.xml" isAbsolute="true" age="0" price="12700" propertyState="1" operatingTime="1505.9723658314"  fuelFillLevel="160.3579913781"  vsid="19" cruiseControl="18"  foldAnimTime="1" fillTypes="grass_windrow" fillLevels="1114.35"  preferedTipReferencePointIndex="1" isCoverOpen="true" dirtAmount="0.46006433688503" GPSstoreInv=""  ssLastRepairDay="137" ssYesterdayOperatingTime="33.233015060425" ssCumulativeDirt="425351.66620115" ssYears="0" >
        <component1 position="-331.66021728516 81.274696350098 -42.301494598389" rotation="-0.0091638574376702 0.00018253491725773 0.0098541490733624" />
        <configuration name="motor" id="1" />
        <boughtConfiguration name="motor" id="1" />
        <courseplay aiMode="6" courses="68" openHudWithMouse="true" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="grass_windrow" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="12" turn="12" field="24" max="43" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="70" fillDriveOn="95" turnDiameter="1" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0;0" abortWork="0" refillUntilPct="100" turnOnField="false" oppositeTurnMode="true" manualWorkWidth="0.0" ploughFieldEdge="false" lastValidTipDistance="0.0" hasSavedPosition="false" savedPositionX="0.000000" savedPositionZ="0.000000" savedFieldNum="0" fertilizerOption="true" convoyActive="false" /> 
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0" drivingThroughtLoading="false" />
        </courseplay>
        <followMe backDist="20" sideOffs="0.0" />
        <wheelDirt wheel1="0.600000" wheel2="0.600000" wheel3="0.600000" wheel4="0.600000"/>
    </vehicle>
	`
no plan what is wrong, but it is ok for me, it cost less and sometimes a new machine is ok

lg
andreas

**Comment by pops64** [comment] 2018-06-11 20:38
added to the list

**Closed by pops64** 2018-06-11 20:38 UTC

**Comment by andreasthu** [comment] 2018-07-20 08:00
Give you a feedback:
Profihopper works fine with the new cp 5.03.
Problems from before never exist.
No reason why but he works fine now.
Actually i have 5.03.010.
But works with all 5.03 versions there was online.

Lg
Andreas
