### ISSUE TITLE
problem mode 10

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#7207] opened 2021-05-17 18:16 UTC
Hello,

I have a problem with mode 10.
The tractor sometimes tries to return to forward at the first point. It does not reverse and therefore hangs against the walls. This problem is not systematic, but happens very often. I have tried several blades, several width settings, in different bunkers ..., but nothing corrects the problem
[log.txt](https://github.com/Courseplay/courseplay/files/6495988/log.txt)

**Comment by Tensuko** [comment] 2021-05-17 18:24
Screenshots ?

**Comment by Tensuko** [comment] 2021-05-17 18:33
Works just fine.
![fsScreen_2021_05_17_20_33_20](https://user-images.githubusercontent.com/27344744/118538977-2706f980-b74f-11eb-8ff5-27ee8a9fe333.png)

**Comment by Crinouche** [comment] 2021-05-18 07:23
![image](https://user-images.githubusercontent.com/36656729/118608647-35d6c600-b7ba-11eb-8d96-84cc294921ae.png)
Like I said, it doesn't always do it, but very often anyway
Map Eirsholt
[log.txt](https://github.com/Courseplay/courseplay/files/6499164/log.txt)

**Comment by Tensuko** [comment] 2021-05-18 08:02
Why your course is placed in the middle of both silos ?!
That doesn't make any sence.

**Comment by Tensuko** [comment] 2021-05-18 08:24
I did run this a few minutes, no Issue.
Where on the map are those silos ? I can't find them.
![fsScreen_2021_05_18_10_23_42](https://user-images.githubusercontent.com/27344744/118617703-2c9e2700-b7c3-11eb-8c0f-825bf76d5c5a.png)

**Comment by schwiti6190** [comment] 2021-05-18 08:24
@Crinouche Could you check the silo map with debug channel 10 and make a picture =, as Tensuko said it might be a problem with the silo.

**Comment by Crinouche** [comment] 2021-05-18 12:52
@tensuko: my course is not placed between the 2 bunkers? he is in the center of the 1st bunker.

@schwiti6190: everything was working fine before the last updates. I have this problem in all the bunkers on the Eirsholt map. Whether those from the farm or those from the bga.
I will remake photos and use your version with debug channel 10 active

**Comment by Tensuko** [comment] 2021-05-18 12:56
> 
> 
> @Tensuko: my course is not placed between the 2 bunkers? he is in the center of the 1st bunker.

Well, that was some optical illusion then.
Mostly it is not from interest how your tractor looks like when made the accident, but the stuff arround.
Course, Bunker, etc

**Comment by Crinouche** [comment] 2021-05-18 13:12
@Tensuko : OK, i understand, but I'm trying to take pictures where we can see the whole course.

@schwiti6190 : here are the requested elements
[log.txt](https://github.com/Courseplay/courseplay/files/6501505/log.txt)
![image](https://user-images.githubusercontent.com/36656729/118656593-f70d3400-b7ea-11eb-9a6d-74dfa651ba2d.png)
![image](https://user-images.githubusercontent.com/36656729/118656349-bc0b0080-b7ea-11eb-8358-fd71c883da3e.png)
![image](https://user-images.githubusercontent.com/36656729/118656386-c3caa500-b7ea-11eb-8319-9202515b1fde.png)
![image](https://user-images.githubusercontent.com/36656729/118656422-cd540d00-b7ea-11eb-9afd-345721d8f59b.png)

**Comment by Tensuko** [comment] 2021-05-18 13:58
Images are very smal...
but is the 4th pic directly after the 3rd ?
If so, it is very strange, why we the way back out of the silo in another row.
But I guess he try to reach a specific point and drive up the chaff ?

A video with the debugchannel would be awesome.

**Comment by Crinouche** [comment] 2021-05-18 14:18
yes the photos are a bit small. I will do more (but I have to go there!)
Photo 4 was taken 4 minutes after photo 3
Sorry, I don't know how to make FS video.

**Comment by Tensuko** [comment] 2021-05-18 14:22
> Photo 4 was taken 4 minutes after photo 3

This will make a difference.
Is it just a wrong line that we generated there to drive out of the silo, or is it more a problem of driving but the row is correct!

So a video will show this much better.

You can try it with OBS (free software and used by a lot of streamer) it is not very hard to get a Video recorded.

Or upload your savegame here as a .zip so I can try it on my own.

**Comment by leo32128fs** [comment] 2021-05-18 16:20
> > Foto 4 foi tirada 4 minutos após foto 3
> 
> Isso vai fazer a diferença.
> É apenas uma linha errada que nós geramos lá para dirigir para fora do silo, ou é mais um problema de condução, mas a linha está correta!
> 
> Então, um vídeo vai mostrar isso muito melhor.
> 
> Você pode experimentá-lo com OBS (software livre e usado por um monte de streamer) não é muito difícil obter um Vídeo gravado.
> 
> Ou carregue seu savegame aqui como um .zip para que eu possa experimentá-lo por conta própria.

https://drive.google.com/file/d/1nbv3-yQYcbyE6TLcyzL19fhAwAiOBtr3/view?usp=sharing

I made a video with the problem happening is not frequent happens at intervals of discharge from the unloader

**Comment by leo32128fs** [comment] 2021-05-18 16:24
As you can see the tractor also descends very fast from the silo 20 km / h, I don't know if this could be the cause, in v6.03.00060 it goes down more slowly and everything works fine

**Comment by leo32128fs** [comment] 2021-05-18 16:25
If you need more information I will be available to help, thanks for the excellent work with the mod

**Comment by Tensuko** [comment] 2021-05-18 17:22
What is happening there.
Thats some strange stuff, we never had that during the test.
Basically he tries to get out of the silo twice...

Well it is nice to see that the basic Idea behind this change is working very nice, but what was that random action of getting a way out of the bunker a 2nd time in the total wrong row....

Do you have a logfile of this ?

**Comment by leo32128fs** [comment] 2021-05-18 17:40
> O que está acontecendo lá.
> Isso é uma coisa estranha, nós nunca tivemos isso durante o teste.
> Basicamente ele tenta sair do silo duas vezes...
> 
> Bem, é bom ver que a ideia básica por trás dessa mudança está funcionando muito bem, mas o que foi aquela ação aleatória de conseguir uma saída do bunker pela segunda vez na fila errada.
> 
> Você tem um arquivo de registro disso?

[log.txt](https://github.com/Courseplay/courseplay/files/6503234/log.txt
I have this one

**Comment by Crinouche** [comment] 2021-05-21 17:21
[savegame5.zip](https://github.com/Courseplay/courseplay/files/6524124/savegame5.zip)
If you want to test my backup

**Comment by Tensuko** [comment] 2021-06-08 05:09
Mode10 seems to be fixed on the current Branch state. Will close here for now.

**Closed by Tensuko** 2021-06-08 05:09 UTC
Labels: More Information Required
