### ISSUE TITLE
Grain transport start from field issue

### ISSUE THREAD

**Issue by bubbatron04** [Courseplay/courseplay#1976] opened 2017-04-13 01:32 UTC
Running version 5.01.00114. Since update my vehicle does not wait at the start point to load. Instead, it drives over near the silo. Was puzzled by this until I read a recent update where courseplay will attemtpt to center trailer under farm silo for loading... I then realized my vehicle ignored the start point at the field and drove course until trailer was centered on start point. Maybe I drove too close to farm silo when recording course?? Playing on pine cove farm by Stevie. Planning to test on other maps.

**Comment by pops64** [comment] 2017-04-13 02:42
? What are you trying to do. And what is courseplay doing. Which mode are using. Picture would help because I see no bug

**Comment by bubbatron04** [comment] 2017-04-13 02:50
Apologies I should have described more clearly. I am trying to move grain
from field into farm silo using mode 1. The very first run after I record
the course my vehicle stops at course start point waiting to be loaded.
Once full it runs course, unloads and returns but does not stop at start
point to load. It continues (at turning speed) to point where tipper
trailer is centered next to farm silo (not actually under farm silo).

**Comment by pops64** [comment] 2017-04-13 02:58
Make sure your second waitpoint is before the silo fill trigger. If CP doesn't detect a silo fill trigger while moving from the first to second waitpoint it will behave as normal if it does it will center the trailer under the fill trigger

**Comment by bubbatron04** [comment] 2017-04-13 10:51
Courseplay drove to the 50th waypoint before stopping. It seemed to
continue driving until it found a silo fill point.

**Comment by pops64** [comment] 2017-04-14 02:31
That has no bearing on where it stops. Unless it reaches max number of runs then it will tell CP to stop when it reaches the last waypoint. Are you only having issues with just this one course?

**Comment by bubbatron04** [comment] 2017-04-14 02:40
I tried a couple different courses. Each course I recorded (starting in different fields) stopped the vehicle somewhere in the vicinity of the screenshot I attached. Originally, I had recorded the course with an earlier version of CP (without silage leveling mode) and they worked perfectly. Once I updated to this version I started having this issue. I re-recorded courses using this version of CP to test as well...

**Comment by pops64** [comment] 2017-04-14 03:12
Hmmmm. Could we get a picture of the beginning of the course. As well as a log with debug channel for loading tippers. I think it is channel 2. As well as the raycast/tip trigger channel. This is channel 1 I believe. I am on vacation till tomorrow so I am not sure of the channel numbers

**Comment by bubbatron04** [comment] 2017-04-15 15:01
[log.txt](https://github.com/Courseplay/courseplay/files/923680/log.txt)
![first run](https://cloud.githubusercontent.com/assets/27390322/25064567/aa233ca8-21ca-11e7-8f4c-5d4b47e2841f.png)
![second run](https://cloud.githubusercontent.com/assets/27390322/25064568/aa2b6ea0-21ca-11e7-9a41-0ef5980bb073.png)

With Debug 1 and 2 active the truck stopped where it should have. However, it did not fully unload the trailer at the farm silo.....

**Comment by pops64** [comment] 2017-04-15 15:49
Have you tried this with other trailers/trucks? Cause that is the only thing I could think that might be a problem as well. Could we get a link to your trailer and is that the default giants truck? Thanks

**Comment by Satissis** [comment] 2017-04-15 16:07
@bubbatron04 have you checked that the farm silo if not full ?
If that's the case, then it will continue the route, until it either finds a new tip trigger or when at the start point again.

**Comment by bubbatron04** [comment] 2017-04-15 16:19
I have not checked if farm silo full.  I pulled the grain out of farm silo
into grain cart so I'm thinking it isn't. Truck is default giants. I can
swap to a default giants trailer and try again with and without debug
active.

**Comment by bubbatron04** [comment] 2017-04-16 13:01
Farm silo wasn't full however changing to a different tipper seems to have resolved all issues. Normally I would try that first, but this tipper had been working until I updated CP. The pics are of the Dakota Spread Axel 42'x 102" version 1.0. Thank you all for your help!

**Comment by pops64** [comment] 2017-04-16 15:39
Do you have a link to where it is at? I going to reopen this has it may be possible to fix. Now we know that is an issue with a mod.

**Comment by 37cee** [comment] 2017-06-17 18:51
I actually ran into a similar Problem. The hard part is it just happened but i cant really replicate it.
There were no - or at least not always mods used. I ran into the issue firt on a moded map, but i ran into it again later on Sosnovska (with basic MAN + Trailer). The sosvska game is used to replicate errors with mods thats i use, its basic game + the mod i need to test.

I'm currently trying (when im in the mood) to figure out what leads to the faulty behaviour. The odd part is in 90% of the time (or more) the truck + trailer combination works fine (regardles of mod or map).

Intended usage:
Combine or Augur Wagon is used to unload into a the MAN + Krampe trailer. The trailer is unloaded at a Silo trigger. (load/fill at starting point)
or
MAN + Krampe is used to fill at a trigger and sell at another. (again load/fill at starting point)
Error:
At some point of time the truck will not stop at the "Start" point but at the "End" point, sometime an information is displayed that the silo is empty. 

At the same time other vehicles (even the same types) can work without any issues on the same course. 

Im almost certain this happens only i used the option that the (then bugged) vehicle should run a certain amount of passes of a course, so at the last pass it stops at the "end" point, but the reset to 1-10 or inivite numbers of passes will somehow not help.

When the trailer and truck are both reset they will function as intended. If i run into this error again ill try to find out if the error is tied to the truck or the trailer by using another machine.

**Comment by pops64** [comment] 2017-06-18 16:41
Yea this is a known but unproven issue. We will eventually push debug code into CP because the possible cause of this behavior currently has no debug code in it.

**Comment by Blackmankot** [comment] 2017-08-05 02:25
@pops64  I suggest also close it for cleaning.

**Comment by bubbatron04** [comment] 2017-08-05 02:33
I experienced this issue again. However, if I had a auger wagon over the
truck when I started the course it would work properly in subsequent
attempts without the auger cart present. Made me think it was trying to
center the trailer underneath a loading point and would drive to find a
loading point (unless an auger wagon was there at course start)

**Comment by Blackmankot** [comment] 2017-08-05 03:22
@bubbatron04  Can you record a video about your problem?

**Comment by pops64** [comment] 2017-08-12 20:10
Moving this to #2051. Same problem.

**Closed by pops64** 2017-08-12 20:10 UTC
Labels: Mod Issue

**Comment by pops64** [comment] 2018-06-19 19:46
Please post this in #2051 has that is the main thread for this issuse. I am assuming it is still a problem then? This shouldn't be vehicle dependent, tho it is CP deceting a trigger but isn't clearing out even tho it is not relevant

**Comment by Natasmi** [comment] 2018-06-20 04:57
when the problem happens all vehicles running that course get affected but as soon as i reset the vehicle it works again and the others dont untill i reset them also. i have posted my fix in other thread.

**Comment by douk-a** [comment] 2018-09-08 23:28
i'm having the same issue 😭😭😭😭

**Comment by pops64** [comment] 2018-09-09 02:48
Are you running 5.3 release or latest Dev version? This was fixed in 5.3.07 I think. Please see my earlier comment and post in the correct thread if updateing doesn't work
