### ISSUE TITLE
mode 2: not saving which combine was assigned manually

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1001] opened 2015-01-25 18:13 UTC
When a combine is assigned manually and then saving and quitting courses and modes are saved, but the driver loses the assignment of the combine.

 next time loading the savegame again you have to assign the combine.

**Comment by eddiem54** [comment] 2015-01-25 18:40
I'm sure that has always been the case.

**Comment by AndyK70** [comment] 2015-01-25 18:41
that's why I wasn't referring to a version.

Don't you think it should be saved?

**Comment by eddiem54** [comment] 2015-01-25 19:19
It would certainly help as I keep forgetting about it.

**Comment by AndyK70** [comment] 2015-01-25 19:20
me2 and then wondering why the combine isn't unloaded... :smile:

**Comment by Raints** [comment] 2015-01-25 19:35
Why you just not making route to inside the field, then autodetect working.

**Comment by JakobTischler** [comment] 2015-01-25 19:51
Duplicate of https://github.com/Courseplay/courseplay/issues/478.

**Closed by JakobTischler** 2015-01-25 19:51 UTC

**Comment by AndyK70** [comment] 2015-01-25 20:16
@JakobTischler thanks, didn't found that one. Sad it is not possible.

@Raints because I haven't yet found out how to have the drivers not get into traffic with the combines. Maybe it's a good thing on big fields, where you can have drivers stand on the field without getting into traffic with the combine, but on those small fields like at Björnholm I'd prefer the drivers to wait outside the fields.

**Comment by Raints** [comment] 2015-01-25 21:16
Here how i do it. Im using autocombine for harvester and allways cut a 1 headland first. Then i send driver off from farm and he have free space on the field. Never had problems to make some room first for the driver.

**Comment by AndyK70** [comment] 2015-01-25 21:32
I'm using autocombine just for testing purposes right now, but that case seems to be closed so I will remove this mod from my installation (again).
It's a very nice mod, but does not work the way as I like it. So it's no solution for me.
thanks anyway, for making proposals.
