### ISSUE TITLE
Multiple Tools Use on Sowers

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2495] opened 2017-12-04 22:23 UTC
![20171204172106_1](https://user-images.githubusercontent.com/24764870/33579522-22abd2a2-d918-11e7-9360-fbb155fc4267.jpg)
I've used the combine convoy and it works well, but I think I am missing something with the multiple tools. Using 2 sowers on a field and they are staying in their own lanes, but they do each lane twice thus defeating the purpose of using 2 sowers at once.  The attached shows one sower going over the lane it just finished and my settings.

**Comment by pops64** [comment] 2017-12-05 06:24
Can't tell you what you are doing wrong from that one picture, I need all waypoints on and both tractor settings for the lane offset and the course gen settings used. You should definitely being using copy course with the new course generator for multi tools

**Comment by lcc1211** [comment] 2017-12-06 21:44
I generated the course with one tractor and the courseplay generated width of 8.8 meters. I copied it to the tractor further up the field.  So I am sure the width selected is fine.  The tractors are not offset as I didn't think I needed to do that, but even without an offset why would they move down the lane, turn around and go back over the exact place they just covered except in the opposite direction  Can I give you a log so you can see the settings?  Or how would I get them to you?

**Comment by pops64** [comment] 2017-12-06 23:22
I need to see the pic of the other tractors settings. But it sounds like it is working as intended. On the new course generator. The lane width and the first and last lane is not has a wide of the course workwidth. This is because on those to lanes the rough edge of the circle needs to be overlapped and or the work width does not divide into a integer number of lanes. With the old one only the last condition can be true and is usually true.

**Comment by lcc1211** [comment] 2017-12-07 01:59
OK.  I'll get back to that field in the morning.  It has a crop growing now, so once I harvest that I'll set up the sowers the same way I did before.  By the way, I ran 2 cultivators and two sprayers on that same field without this happening.  I may have set up the sowers a bit different, but I'll give it a go and see what happens.

**Comment by lcc1211** [comment] 2017-12-08 02:46
I don't know if it was updating to the latest dev version of CP or if I made a mistake in creating the course, but today I am unable to duplicate the error.

**Comment by pops64** [comment] 2017-12-08 17:09
Alright. I'll close this if you can reproduce this please post here. And we will reopen this

**Comment by lcc1211** [comment] 2017-12-10 16:30
I was able to reproduce the issue again by accident.  This time several lanes over and on multiple lanes.
![20171210112413_1](https://user-images.githubusercontent.com/24764870/33806954-87ac10ac-dd9d-11e7-9ef6-be462d986931.jpg)
![20171210112418_1](https://user-images.githubusercontent.com/24764870/33806955-87ba9ece-dd9d-11e7-93b1-ebbdbace65af.jpg)
![20171210112427_1](https://user-images.githubusercontent.com/24764870/33806956-87c849ca-dd9d-11e7-9703-d80013c83b85.jpg)
![20171210112644_1](https://user-images.githubusercontent.com/24764870/33806957-87d8a1d0-dd9d-11e7-8cfa-b4c09b0379b4.jpg)
![20171210112658_1](https://user-images.githubusercontent.com/24764870/33806958-87e86778-dd9d-11e7-91f1-dd849d579027.jpg)

**Comment by pops64** [comment] 2017-12-10 16:45
You missed the important page. I need to see the offest settings.  For both tractors. Perferably before and after the turn for the tractor driving over it's last bit

**Comment by lcc1211** [comment] 2017-12-10 17:23
Do you mean the page where it says which tractor is left or right?

**Comment by pops64** [comment] 2017-12-10 19:20
Yea but from your original picture doesn't look possible

**Comment by lcc1211** [comment] 2017-12-10 20:31
Best I can do with the current field as they have finished it now.  This does only seem to happen when sowing.  I have used this type of course for cultivating, ploughing and fertilizing and they seem fine, so I have to wonder if this feature was intended.  If it was intended then why does it happen randomly and with both tractors.

**Comment by JDTiger** [comment] 2017-12-10 20:34
maybe you sometimes switch the symmetric lane change option? without noticing it/ forgetting to do the same on both tractors?

**Comment by lcc1211** [comment] 2017-12-10 20:44
I've only done this course 3 times.  I can't say for sure about the first one, but I haven't set symmetric lane change.  These screen shots are from my 3rd attempt.

**Comment by lcc1211** [comment] 2017-12-18 21:55
I have not been able to reproduce the error again. Perhaps an update has changed the behavior.

**Closed** 2017-12-25 04:18 UTC
Labels: waitingForUserAnswer
