### ISSUE TITLE
Feature request: GPS-alike function / Lane Assist

### ISSUE THREAD

**Issue by AlexStephenLytton** [Courseplay/courseplay#2923] opened 2019-01-04 14:26 UTC
Hey Devs of CP out there :)

What about a feature to hold lane in desired direction just like the FS17 GPS mod? In FS17 i used GPS to stay in lane on longer straight roads / ways... Would love to see such a function integrated in the new version of CP for LS19. Don't know if that is completely away from the nature of the scripts in CP right now but i guess the system still includes the basic functions to hold a lane...

**Comment by bgo1973** [comment] 2019-01-04 14:39
Maybe the mod KeyboardSteer by Mogli12 will help you out. Pressing right shift + w snaps the current direction. You will find it right here on github. 😉

**Comment by Tensuko** [comment] 2019-01-04 16:00
If CP is out... well after it was out for FS17 I put away my GPS Mod, tho I would love to use it in FS19 now.

**Comment by AlexStephenLytton** [comment] 2019-01-04 18:56
> I guess they should get it working before implementing new functions. Maybe the mod KeyboardSteer by Mogli12 will help you out. 

Thanks for the hint but i'm still using that mod ;) But i know myself - if I wouldn't have posted that suggestion, I would have forgotten it when the time for it has come ;)

**Comment by bgo1973** [comment] 2019-01-04 22:07
Ah okay. You're welcome. :) I never used that until now.
A function wich will automatically follow the road at all would be nice. That would make recording track much easier.

**Comment by Kokolores11** [comment] 2019-01-07 06:40
I used the GPS mod in FS17 a lot. Especially for recording courseplay-courses which are not on fields e.g. mowing at the side of the road.
Whopster Modding is working on a new GPS mod. He will post the progress on his fb page.

**Comment by SirAlbertL** [comment] 2019-01-07 07:17
Not sure how this would work if it could at all....
Let me try to describe my idea that I tried to do in fs17.

For Silage Harvest and Leveling
I would like to add a silage shield to the front of my transport truck or tractor in order to level out my last load of chaff. This will be able to smooths out the load so that the next will not get stuck driving up into the silo with the next load. 
Now the problem is to combine both leveling mode with transport mode. This way as you drive into the silo, it lowers the silage shield, and dumps the next load at the same time... 

Again, not sure if possible or not...Just something I thought would be cool.....

Thank you ALL for the hard work you all do converting this every versions and keeping it updated.
Being a editor of mods myself, I truly understand the dedication, and hours it takes to do the work...
God Bless and happy FS19 to you all.

**Comment by bgo1973** [comment] 2019-01-07 07:41
The function for that is already implemented. Just let a second tractor do the leveling. That's how it"s done in reallife.

**Comment by bgo1973** [comment] 2019-01-07 07:49
@Kokolores11, just use the course of the combine or even the baler with a suitable offset. Works fine.

**Comment by Kokolores11** [comment] 2019-01-07 12:33
@bgo1973 that is true for square bales, but I always had problems with the round ones rolling down hill.

I'm looking forward to the first release. FS without courseplay is just halve the fun.
Thank you, for your hard work!

**Comment by Kokolores11** [comment] 2019-01-07 12:51
> A function wich will automatically follow the road at all would be nice. That would make recording tracks much easier.
Do you know Stephan-S/AutoDrive for FS17?
It would be awesome if this would be included in courseplay. I really like the approach to setup a network and automatically determine the best path. I don't know if someone works on a version for FS19 though.

**Comment by bgo1973** [comment] 2019-01-07 18:36
That's the reason why every farmer would use squarebales on steep terrain. 😘

**Comment by BurrrY** [comment] 2019-01-08 08:52
i also thought of a more automated GPS-Function, where i can select like "drive to destination X", and its starts driving automatically.

As a first step, its maybe possible to create a separate tool.
There you can:
- Draw all Roads
- mark all destinations
- let it automatically generate all X-to-Y CP-Courses, and export them so you can use them in game (manually).

In a second Step, its maybe possible to port the pathfinding algorithm to LUA/CP and CP can select the path by itself. (Network of roads still predefined)

A third step could may be an automatic ingame Road-detection.

i've played around a bit at step one, C#-App to load map, place markers and stuff, but still a very buggy "works for me"-state.

**Comment by bgo1973** [comment] 2019-01-08 09:39
I guess there was a tool called courseplay drawer during fs 15. There it was possibile to draw courses using the pda map. Maybe it is possible to use something similar die fs19.

**Comment by Kokolores11** [comment] 2019-01-08 09:46
@BurrrY The First step you describe is exactly what AutoDrive by Stephan-S does. You can find it on GitHub. So converting it shouldn't be a problem. You can define and edit the paths in game.
For narrow roads you can even define paths where the tractor waits for oncoming traffic to pass, before continuing.
But I think it did not work in MP...

**Comment by BurrrY** [comment] 2019-01-08 09:50
@Kokolores11 sounds good, i'll have a look at it
@bgo1973 Yes, i've seen that, and planned to do it similar. (But with C#, not VBasic ;))

**Comment by TinyCrocodile** [comment] 2019-01-08 21:08
@bgo1973
@burrry

The actual version for FS17 is here

https://github.com/TinyCrocodile/Coursedrawer

I also was thinking about porting to c# as both is based on .net it should not be hard to do for a learned programmer. 

I planned to do a fs 19 version but not shure if i will because of different reasons i did not make a lot of work for fs 17 as well. 

If you do one for fs19 i am verry interested.

**Comment by 37cee** [comment] 2019-01-10 10:35
I don't see why GPS like functions have anything to do with CP. Don't get me wrong, i liked the GPS mod in FS17 and it would be useful in FS 19, but it should remain a different mod.
I know that Wopster (he worked on mods like the hose system for fs17) has been working on a Lane assist mod for FS19.  His latest update on his facebook page was like a day ago... so i assume it will be released at some point. 

[https://www.facebook.com/WopsterModding/](url)

**Comment by BurrrY** [comment] 2019-01-10 11:42
i think there are two version of GPS mods.
- Straight lines on Field
- Driving on roads.

I want the second one.
CP hast most functions link "drive from point to point", course-mamangement, "find next point" and all that stuff, which i do not have to reinvent. Of course, officially implement it or publishing it is some other topic.

**Comment by jvalst** [comment] 2019-01-18 12:02
Maybe something like CP integration in the roadsets is an option. So that the roadsections build into the maps have some "cp dots" available already (2 sides of the road offcourse). And that CP is able to connect those roadpoints into a route (checking the angle of curves and correct side of the road offcourse). Maybe then you can say, drive towards there, and the whole roadnetwork is connected to CP.

**Comment by duffstone** [comment] 2019-01-21 04:35
for the record,  I'd just like a working product to start with... I'm patient and hope to look into being a beta tester.    However,  if requests are able to be made, is there anyway we could just get circular AI / courses without manually recording them?   all this back and forth action is novel, but most of us here in the bread-basket hardly ever farm that way.   Going in circles is the most efficient way to farm, Odd that Giants doesn't recognize that with the AI...  anyway,  circular motion options or auto-course builds would be a nice *nod* to us farmers here in the bread basket.   

-Thanks!

**Comment by pvajko** [comment] 2019-01-21 06:18
@duffstone you can now set up to 40 headlands in CP so you can always generate something like this:
![capture](https://user-images.githubusercontent.com/2379521/51455999-53abd180-1d4c-11e9-8770-1edc5d005b95.PNG)
(There'll most likely be a bit of back and forth in the middle)

Where's that 'bread basket' you are farming? As the developer of the new course generator I'm always interested making it more realistic.

**Comment by jvalst** [comment] 2019-01-21 06:37
Damn, @pvajko the new interface is looking smooth! Keep up the good work guys! We're here for the testing part! Just take your time guys.

**Comment by knoxville73** [comment] 2019-01-21 18:57
@pvajko This is an other path used by the farmers with some tools (mower, tedder, rake by example).
After 2 or 3 headlands, the farmer works in band and goes trough the headland to join the next one in fast speed (without working).  If a field, even rectangular, the farmer divides in 2 or 3 the width to shorten the path between the bands.

![field_path](https://user-images.githubusercontent.com/23388102/51493783-b043d680-1db6-11e9-85c0-d5d56597df66.jpg)

**Comment by knoxville73** [comment] 2019-01-21 18:58
It's just for your information and why not to use for the future ...

**Comment by pvajko** [comment] 2019-01-21 20:11
@knoxville73 thanks, that's great info, I'll may implement that. Can you give a name to this pattern I could use?

Also, are you aware of the 'skip row' setting right? There you can skip 1,2... rows so your turns are fast, I guess IRL this works with GPS only (I saw it in tractor GPS user manuals).

**Comment by knoxville73** [comment] 2019-01-21 20:20
@pvajko I don't know a name for this method.  This is an old method, before the GPS.  The 'skip row' method is only possible since the existence of GPS.  (Sorry for my english, I'm belgian, I speak normally french).

**Comment by yumi-modding** [comment] 2019-01-21 20:38
@pvajko Hello, from my experience, this method described by @knoxville73 is also used when harvesting to avoid making U-turn and losing time by stopping the combine and going backward, especially if you have relatively small header. On the picture you can see only 2 U-turn between 7 & 8 and 16 & 17.
I always harvest this way when playing FS.
By the way, thanks for your great work on courseplay !

**Comment by pvajko** [comment] 2019-01-21 20:52
@yumi-modding we already have something similar called 'narrow field' mode although it works with one headland only and does not split the field into 2 or 3 pieces.

**Comment by bgo1973** [comment] 2019-01-21 21:01
For the combines the following example  would be nice : (I guess that's what yumi-modding means)
Relating to knoxville73' image,
1&2 = headland 
3 = 3 (middle of the field)
4 = 4
5 = 9
6 = 6
7 = 11......aso.
Depending on the cutter width maybe it's needed to choose more headland to make u-turns possible. The smaller the width, the more headlands you'll need.

**Comment by bgo1973** [comment] 2019-01-21 21:09
What's the meaning of "multiple tools"? Is it the ammount of mounted implements? If yes it would be nice to choose cutter, front, rear, front & rear. Or would that make no sense because CP will recognize it by itself?

**Comment by kylemeyer13** [comment] 2019-01-21 22:08
In real life we will use the method that I think knoxville73 was trying to describe. When we are harvesting, usually with 2 or 3 combines on long rows, we will do all of our endrows and then cut through the field and then go around and around that cut so our augers always face the harvested part of the field. It is the most efficient way to harvest if you can make it all the way across the field without dumping.

**Comment by delawarehunter** [comment] 2019-01-21 23:46
> @knoxville73 thanks, that's great info, I'll may implement that. Can you give a name to this pattern I could use?
> 
> Also, are you aware of the 'skip row' setting right? There you can skip 1,2... rows so your turns are fast, I guess IRL this works with GPS only (I saw it in tractor GPS user manuals).

@pvajko In the U.S. we call this "working in lands".  So, a farmer will work in a land.  For us, the main reason we do this is two-fold.  First, it cuts down on the 180 degree turn, lessening stress on the tractor and implement even though it's out of the ground and reducing the rutting that is caused by turning the wheels too sharp.  Second, it reduces the width of the head land/head row/turn row when that is needed.  For us we use it almost exclusively when harvesting and planning on planting without tilling (otherwise call no-till planting), when mowing/bailing hay/grass, or when doing a light tillage practice like vertical tillage since it's less destructive on the ground.  

Hope that helps?

-Billy

**Comment by pauloluz72** [comment] 2019-01-22 00:46
for when a download version

**Comment by bgo1973** [comment] 2019-01-22 08:17
Maybe this could help a little
https://efarmer.mobi/features/

**Comment by pvajko** [comment] 2019-01-27 18:01
@bgo1973 @knoxville73 the current dev beta version includes an experimental implementation of both versions (called circular and spiral as had no better idea)

**Comment by duffstone** [comment] 2019-01-27 19:39
@pvajko just noticed the beta only has 20 headlands, not 40.  easy change I could make myself, or something planned to update in the future?

**Comment by knoxville73** [comment] 2019-01-27 20:31
Dear Peter @pvajko ,

I'm sorry, I use de lastest version (00005) but I don't find your proposal !

**Comment by pvajko** [comment] 2019-01-27 20:41
@knoxville73 @duffstone 
![image](https://user-images.githubusercontent.com/2379521/51806612-7ef95980-2241-11e9-81d7-75d9bb7a65bf.png)
Also, pushed the increased headlands.

**Comment by duffstone** [comment] 2019-01-27 20:55
thanks man!

**Comment by 206airmail** [comment] 2019-01-27 21:38
> @knoxville73 thanks, that's great info, I'll may implement that. Can you give a name to this pattern I could use?
> 
> Also, are you aware of the 'skip row' setting right? There you can skip 1,2... rows so your turns are fast, I guess IRL this works with GPS only (I saw it in tractor GPS user manuals).

@pvajko I've always heard that method refered to as the "racetrack" method since it kinda looks like your going around a Nascar Oval.
First heard it called that by a cropduster I worked for (it's one of their primary way of spraying a field as it gives them room to be able to get turned around) and then it was also referred to that on the farm I worked at later on.

**Comment by kylemeyer13** [comment] 2019-01-28 21:30
![fsscreen_2019_01_28_15_18_51](https://user-images.githubusercontent.com/26012725/51867259-b125bc80-2310-11e9-90be-59fbd07b6c36.png)

I created a path for the function we were talking about earlier. Someone suggested calling it working lands. Instead of going around and around the entire field it would separated into a few smaller chunks where you start in the middle of chunk and work your way out. If you guys need further clarification let me know and i can make a more detailed path to help explain what i mean.

**Comment by knoxville73** [comment] 2019-01-30 18:00
Dear Peter,

I like your job, it's a good translation of my suggestion (mode spiral).  I'm in test for this, my first wish would be an increase in speed when the tool is not working.

An other wish is the possibility to choose a number of division for the field (1 to 3 or 4 max).

I think it's not currently the priority, stay cool !

Many thanks at your team, you are the best ...

If you come to Belgium one day, contact me, we have the best beers in the world ...

**Comment by bgo1973** [comment] 2019-01-30 22:43
Adjustable headland speed would be nice. Thumbs up.

**Comment by pvajko** [comment] 2019-02-05 23:53
![image](https://user-images.githubusercontent.com/2379521/52312092-ef555880-296e-11e9-9356-3c0bb4c3763b.png)

**Comment by jvalst** [comment] 2019-02-06 06:41
And the harvester needs to drive the other way around? So that the harvester can always unload? Then the pathfinding of the tractors needs to drive around the crops. This is awesome! Keep up the good work guys!

**Comment by pvajko** [comment] 2019-02-06 16:29
@jvalst correct me if I'm wrong but in this pattern on one leg the fruit will always be on the wrong side. Must unload on the other leg.

**Comment by jvalst** [comment] 2019-02-07 06:49
No, I'm wrong, excuses. Thought the harvester would always take parts of the field and have the unloading on the outer side.

**Comment by yumi-modding** [comment] 2019-02-07 07:07
@jvalst I think also it's better to turn clockwise so nearly all the time the pipe is on already harvested part and combine can be unload.

**Comment by ChrisASnyder** [comment] 2019-02-07 16:54
Clockwise works better because the pipe is on the outside of the turn. This prevents the harvester from turning into the chaser. 

The problem is the header direction and the spiral/circular direction are opposite. A clockwise header will be a counter clockwise lane. Probably an option to specify the lane directions as clockwise or counter clockwise.

The ideal pattern is to center cut the field and do a counter clockwise spiral out from the center. This would keep the pipe always in the center of the field out of the fruit. I think there is already a ticket open for this request.

**Comment by KenStumich** [comment] 2019-02-23 19:06
so this is what bgo1973 suggest

> For the combines the following example would be nice : (I guess that's what yumi-modding means)
> Relating to knoxville73' image,
> 1st&2nd = headland
> 3rd = 3 (middle of the field)
> 4th = 4
> 5th = 9
> 6th = 6
> 7th = 11......aso.
> The distance between the single rows is always the same.
> Depending on the cutter width maybe it's needed to choose more headland to make u-turns possible. The smaller the width, the more headlands you'll need.

so this is what it looks like . using with a normal havester with a pipe on the left side brings nothing to the table. 
but this will work with a forage harvester with a turnig pipe ( e.g. krone BigX)

![center_mode_circular](https://user-images.githubusercontent.com/28400454/53290544-cbcf4200-37a5-11e9-8bac-d531042a81df.png)

beginnig with lane 4 , there is always a line beside the cutter free to drive on. 
suggesting the chasing tractor is behind the cutter you can travel on the free rows beside the cutting row.

**Comment by Tensuko** [comment] 2019-02-23 20:21
I don't get the advantage of those 2 new strategies.
Both got left out parts on the field, cause of sharp edges and not having those 'turn manuvers'.
Someone might explain that to me ?

Got those weird turns in all screenshots, and for Combines, the Lifting at those 'turn' are also weird.
I know work in progress for sure, but I don't see the advantage. I wrote about a CW/CCW Problem here too #3246 
if you could control, that pipe is always outside (CW for both, mid and preturn section) its rly nice, but somehow it does a direction turn (can see in screenshots).

**Comment by pvaiko** [comment] 2019-02-24 01:58
The advantage is that there are no slow turn maneuvers. It is much faster and economical. At the moment it makes only sense for relatively narrow fields as it divides the field into two parts only but I'm working on that. 

Also, it was suggested by folks who actually have seen real life farming...

**Comment by SteelRodent** [comment] 2019-11-13 17:07
In regards to the OP post in this thread:
Wopster's GPS steering mod actually works pretty well. https://github.com/stijnwop/guidanceSteering

It's a bit different from UpSideDown's mod for FS17 and not as feature rich, but it behaves more like a real farming GPS. Just make sure to read the instructions.

Personally I think stuff like this is way outside what CP is meant to do.

**Closed** 2020-01-08 12:44 UTC
Labels: suggestion
