### ISSUE TITLE
Course not generating - headland.lua:191: attempt to index a nil value 

### ISSUE THREAD

**Issue by neonlazer** [Courseplay/courseplay#3824] opened 2019-05-22 01:01 UTC
I updated to the latest github files today(00217) and I have noticed that they largest field I have on Midwest Horizon seems to now cause an error when I attempt to add a headland. 

This did not happen previously(I have the files but tried to revert and error still came up, not sure why), although it did limit me to 1 headland even if i put 2 or more.

My log file with the headland error twice at the end due to me attempting to generate the course twice.
[log.txt](https://github.com/Courseplay/courseplay/files/3205096/log.txt)
This is the course successfully generated without a headland.
![20190521194124_1](https://user-images.githubusercontent.com/50254800/58139992-eda05f80-7c02-11e9-9f93-af8a6d923315.jpg)
This is the headland settings when I attempt to generate a course, old course stays on map due to error.
![20190521194140_1](https://user-images.githubusercontent.com/50254800/58140033-0741a700-7c03-11e9-81b7-b8a5313de379.jpg)

**Comment by Tensuko** [comment] 2019-05-22 05:06
The Field looks weird.
I guess @pvaiko would need Fielddata or something.
A logfile with debugchannel for Coursegeneration could be helpful too.

Beside that. This is not your full logfile, but still see a lot Errors:
2019-05-21 19:51 Error: Vehicle type 'BrentV800' has unknown specialization 'FS19_BrentV800.fillable'!
2019-05-21 19:51 Error: Vehicle type 'BrentV800' has unknown specialization 'FS19_BrentV800.overloading'!
2019-05-21 19:51 Error: Vehicle type 'BrentV800' has unknown specialization 'FS19_BrentV800.crawler'!

+ a List that is too long...

https://github.com/Courseplay/courseplay/wiki

**Comment by pvaiko** [comment] 2019-05-22 11:11
Post your field definitions as described in https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions

**Comment by neonlazer** [comment] 2019-05-22 14:53
@Tensuko I actually removed The V800 after I saw some of the errors. I did not think about mods causing conflicts, which it actually seems to be. I realized I had never used JHHG's NL345 lime spreader until yesterday on 62 and I tried a stock game one and it generated fine. I am unsure how to get the debugchannel to work on the log, I looked around but found nothing to make it log everything.

Here is the cpFields in case it's useful.
[cpFields.txt](https://github.com/Courseplay/courseplay/files/3207931/cpFields.txt)

**Comment by Tensuko** [comment] 2019-05-22 15:36
CP HUD Settings Menu, there are the Channels, for Coursegeneration it is Channel 7, if you got that one on and then generate a course, it should be all written in the log.txt wich you can then drag and drop here as you did, but pls post the full log and not a part. (It starts with system infos and Version and List of Mods etc...)

**Comment by neonlazer** [comment] 2019-05-22 22:11
Did not realize the first log file didn't contain everything. I cleaned it out and assumed it had it all. This one looks to have it all plus a some extra channel 7 stuff.

[log.txt](https://github.com/Courseplay/courseplay/files/3209493/log.txt)

**Comment by pvaiko** [comment] 2019-05-22 22:25
I don't think that this ever worked with that 30 m work width. The problem is that little nook on the southwest corner which just too narrow to fit headlands in there.

**Comment by neonlazer** [comment] 2019-05-22 23:33
> 
> 
> I don't think that this ever worked with that 30 m work width. The problem is that little nook on the southwest corner which just too narrow to fit headlands in there.

That would make sense since when I tried to do 2 headlands with a smaller plow, it reset it to only 1 headland pass. I thought maybe it would try to calculate it and look a bit funky. Thank you for the help, glad to know how to use the channels for debugging for the future.

**Comment by pvaiko** [comment] 2019-05-23 00:14
@neonlazer the lines telling you the truth is:
2019-05-22 17:08 :33 [dbg7 lp3292] Generated headland track #1, area -359202, clockwise = true
2019-05-22 17:08 :33 [dbg7 lp3292] Can't fit more headlands in field, using 0

The negative area means the the headlands passes most likely overlap. Closing this now.

**Closed by pvaiko** 2019-05-23 00:14 UTC
Labels: waiting for logfile
