### ISSUE TITLE
Estancia Lapacho field 29 headland turn issue with big implements (Video replay link)

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3324] opened 2019-03-01 00:28 UTC
New Video link upload and new Gist as per "How to", help by @Messy71
Here is the new video link and the new GIST link to Estancia Lapacho Headlands / Turn issue on field 29

* Yes I realize in the video i had generated the course with 3 headlands passes then switched it to  2 without regenerating the course [plot. But that would make no difference as it does exactly the same thing at the exact same position ( If I hadn't made that Boo-Boo ...lol)

https://gist.github.com/Hubcap-1/2ece41234a39e670c87487e46402feb6

https://www.youtube.com/watch?v=xJpsVnYoLBg 

Let me know if my efforts are of value or helpful so I know I'm not wasting my efforts. If I need to change resolutions or anything else you would like me to do....let me know in a reply.
@ messy described this issue and asked me to test earlier today.

**Comment by Hubcap-1** [comment] 2019-03-01 01:36
Hubcap_ Headlands / turn issue on Estancia/ Lapacho @ Messy

**Comment by Hubcap-1** [comment] 2019-03-01 01:37
Above is the GIST title..I'm new to this I don't know if that is the link or not.

**Comment by pops64** [comment] 2019-03-01 03:18
The opposite direction setting never got implemented into headland turns. They would need to see debug channel 12 and 14 on. Does this occur with up/down headlands? Imo I wouldn't use the turn setting for headlands instead round or smooth when pulling trailered tools. Has there is some error checking that has never been included that avoids tools that can't reverse properly(This is assuming the same occurs on up/down). Also there as certain corners when the headlands doesn't generate correctly for those. But  they would need 12 and 14 on to see what CP is trying to do for that corner

**Comment by Hubcap-1** [comment] 2019-03-01 03:24
@pops64  I get that but we are testing a branch with headlands and turns near fixed...not the normal current master CP

**Comment by Hubcap-1** [comment] 2019-03-01 03:29
@pops64
https://github.com/Courseplay/courseplay/tree/headlandturns

**Comment by pvaiko** [comment] 2019-03-01 12:09
Branch merged to master with some additional fixes.

**Comment by Hubcap-1** [comment] 2019-03-02 00:37
Feedback  *New Video Link and GIST 
Okay updated CP to the new master. Ran Estancia Lapacho field 29 again. Seems to work just fine now. Same equipment, same start point / 2 headlands passes.
Debug info starts just before the first turn . I let the video run until it was well established past the last transition from headlands into up / down.
I noticed someone picked up on my point of the irregular way the course was plotted to transition from headlands to up/ down and applied a new plotting solution..bravo !

https://gist.github.com/Hubcap-1/a902eea5bef6d6c365beb9d56446ac26
https://youtu.be/lF1eStiTTwE

**Comment by pvaiko** [comment] 2019-03-02 12:24
@Hubcap-1 Listen, I don't know how you even have the permission to unassign but I'd like to ask you to stop doing that. I assign myself for a reason. You overriding that and changing in my repository is rude.

**Comment by Messy71** [comment] 2019-03-03 11:41
@pvaiko This ( reoccurs ) is still a problem with version v6°01°00110 {[Revert "v6.01.00109 Fixes #3254, what it breaks we don't know"](https://github.com/Courseplay/courseplay/commit/3aa8c7016e172126d4e51923c8ab176f71634104)}
Here's the [log](https://gist.github.com/Messy71/09845db50dc90c664abe0eaa098ca9c7) and some photos [All settings are on auto working width changed from 24.4 to 22.4]:
![fsscreen_2019_03_03_12_20_05](https://user-images.githubusercontent.com/47163914/53694590-4f45f000-3db1-11e9-96ab-b386a9e93527.png)
![fsscreen_2019_03_03_12_20_20](https://user-images.githubusercontent.com/47163914/53694591-4f45f000-3db1-11e9-8910-a8f1ed15a248.png)
![fsscreen_2019_03_03_12_20_21](https://user-images.githubusercontent.com/47163914/53694592-4fde8680-3db1-11e9-8a73-9d3ea2d44bad.png)
![fsscreen_2019_03_03_12_20_27](https://user-images.githubusercontent.com/47163914/53694593-4fde8680-3db1-11e9-9168-09feb91705d0.png)

**Comment by Hubcap-1** [comment] 2019-03-03 19:42
> @Hubcap-1 Listen, I don't know how you even have the permission to unassign but I'd like to ask you to stop doing that. I assign myself for a reason. You overriding that and changing in my repository is rude.

I am not doing that..Github is. I noticed it happening too....automatically. I have no Idea why

**Comment by Hubcap-1** [comment] 2019-03-03 19:43
It just did it again every time I enter a comment.it's happening on it's own.

**Comment by pvaiko** [comment] 2019-03-04 00:55
@Messy71 savegame?

**Comment by Messy71** [comment] 2019-03-04 01:36
@pvaiko Here it is [savegame+course id 3](https://github.com/Messy71/Files/raw/master/savegame%2B%20course.zip).

**Comment by pvaiko** [comment] 2019-03-04 02:14
id 3 is not for the field in your screenshots. The first course looks similar to what you have in your screenshot but it does not have any issues here.

**Comment by Messy71** [comment] 2019-03-04 06:27
@pvaiko i’m sorry sir it was late i was tired but it should be easy to reproduce
All settings to auto , working width 22,4m.
Course starts with 2 headlands in turn mode  and the starting point it’s in the next corner after the ine in the photo, to the right of the road that coomes from the shop.

**Comment by pvaiko** [comment] 2019-03-04 12:22
Sorry, I have not time experimenting, with this savegame and course I was not able to reproduce it.

**Comment by Messy71** [comment] 2019-03-04 13:10
I understand , no problem . I’ll be home in 1,5 hours and recreatee it set it up just to hit drive course and upload it again.

**Comment by Messy71** [comment] 2019-03-04 16:35
@pvaiko Here it is with version 6°01°00112 - [Course+Save+LOG](https://github.com/Messy71/Files/raw/master/Course%2BSave%2BLOG.zip).

**Closed** 2019-03-06 00:43 UTC
