### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by rayrizal** [Courseplay/courseplay#2037] opened 2017-05-04 14:29 UTC
I'm using the latest version of courseplay for my farming simulator 17, but the game freezes when running multiple harvester with courseplay, so i have to force quit the game reload again.

**Comment by pops64** [comment] 2017-05-04 19:11
https://github.com/Courseplay/courseplay/wiki

**Comment by rayrizal** [comment] 2017-05-05 07:17
[gistfile1.txt](https://github.com/Courseplay/courseplay/files/978291/gistfile1.txt)

Here' my log file, i'm using courseplay 5.01.00131


![mod](https://cloud.githubusercontent.com/assets/28395955/25736639/669c0fc2-319d-11e7-9c24-5719629b3bd0.jpg)

This is my mod list

This problem happen in westbridge hills and goldcrest valley map

**Comment by rayrizal** [comment] 2017-05-05 08:17
I just update to courseplay 5.01.00133, try to running multiple vehicle with courseplay, and in the middle of the game it freeze again and got same error message

![screen shot 2017-05-05 at 15 12 17](https://cloud.githubusercontent.com/assets/28395955/25738177/e0300e76-31a5-11e7-9f9b-b0827b6df748.png)

**Comment by pops64** [comment] 2017-05-05 19:06
How many AI do you have running I believe the maximum with out a use of another mode is 10. We probably could put something in that won't let CP start if the you have more than 10(Or what ever the max number is if modded to a different value)

**Comment by Lupo36** [comment] 2017-05-07 00:28
I can confirm the error.
[log.txt](https://github.com/Courseplay/courseplay/files/981257/log.txt)

**Comment by pops64** [comment] 2017-05-07 04:38
We need steps to reproduce. Have you tried running CP with out any mods?

**Comment by rayrizal** [comment] 2017-05-07 06:43
Yes i do try to run the game without any mods except courseplay and it still freezes in the middle of the game.

**Comment by Lupo36** [comment] 2017-05-07 19:34
Mode 7, mod only CP. Harvester is CaseIH 9230.
With Version 089 it still worked.

**Comment by rayrizal** [comment] 2017-05-08 13:05
Ok now i'm revert to version 089 and running without any issue with all mods enable, just missing few new function in latest CP version like save fuel option and plough over the edge of field, hopefully the next CP version will fix the problem

**Comment by rayrizal** [comment] 2017-05-11 15:02
I just try the new version 136 and the same error message srill appears. Looks like I'm gonna stuck in version 089 which is mot compatible with big bud dlc : (

**Comment by pops64** [comment] 2017-05-11 19:15
Try with version 137 or higher.

**Comment by Lupo36** [comment] 2017-05-11 21:18
With version 0136 is the same error. Here again the log with debug channel 11. The error occurs with 5 combine harvesters simultaneously.
[log.txt](https://github.com/Courseplay/courseplay/files/994478/log.txt)

**Comment by pops64** [comment] 2017-05-11 21:47
Has I said earlier 

> Try with version 137 or higher

...

**Comment by Lupo36** [comment] 2017-05-12 00:12
Thank you for version 137. It all works perfectly.

**Comment by rayrizal** [comment] 2017-05-12 16:03
Yes 137 works smoothly so far, but still need a little bit adjustment for big bud dlc, because when i use great plains sowing machine YP-2425A, the driver unable to reverse correctly and also unable to put the tools in right position to start sowing the next row, but overall i love version 137 and running without sny issue

**Comment by pops64** [comment] 2017-05-12 16:49
Yea. The big bud for what ever reason needs alot of fine tuning because the auto calculations for that dlc aren't working that well for that equipment. I will close this out then. If it pops up again post here and I will reopen it.

**Closed by pops64** 2017-05-12 16:49 UTC
Labels: bug, waitingForUserAnswer
