### ISSUE TITLE
Refilling seeders/spreaders speed 10km/h after refill.

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#6925] opened 2021-02-28 00:39 UTC
[log.txt](https://github.com/Courseplay/courseplay/files/6056011/log.txt)

Hello guys,
I'm on v 0045, having tractors with seeders working on a field with refilling course for seeds/fert all works fine but after refill they are travelling back to field & work only in fixed 10km/h speed. Same happened to me with fertilizer/lime spreader.  All machines are stock/Kuhn pack. They are refilled from auger trailers not from any silo or refill point.

**Comment by TobiHH78** [comment] 2021-02-28 12:38
I noticed this twice in mode 7 (bale collect). After unloading of the bales at the sellpoint, the tractor only drove with 10 km/h from there. After I once set the cruise control back to max speed again (without discharge of the tractor) it worked fine.

**Comment by lcc1211** [comment] 2021-02-28 13:40
I can confirm this as well. I sometimes have to manually increase the cruise control speed as it leaves the fuel point, silo etc.

**Comment by Bobster82** [comment] 2021-03-01 13:11
I can confirm those too, on multiple modes where CP uses max speed from the cruise control setting.

**Comment by RayzerSharpe** [comment] 2021-03-30 21:11
I can kinda replicate the issue and its happening to me all over the place. I cannot replicate it so that it stay on forever but this might provide some pointers. 

PIc 1 taken right before hitting 10 mph limit
Pic 2 taken right after 10 mph limit set
Pic 3 taken further along the route and associated to the second part of log shown below where its still stuck at 10mph

![Image1](https://user-images.githubusercontent.com/25461795/113057317-cb83ab00-91a4-11eb-80c9-8fa4c3c518db.png)
![Image2](https://user-images.githubusercontent.com/25461795/113057333-d1798c00-91a4-11eb-9233-b88458ef9045.png)

Have a look at the log part below. I'm not an expert but the line "has 4 colliding object(s)" seems to change things down to 10mph 

2021-03-30 21:50 :09 [dbg4 lp964621] 7618 Dyna-6 (#2): onWaypointPassed 170
2021-03-30 21:50 :09 [dbg17 lp964630] 7618 Dyna-6 (#2): updating collision boxes at waypoint 170, have 20 positions, invalid: false
2021-03-30 21:50 :09 [dbg15 lp964655] 7618 Dyna-6 (#2): PPC: two intersection points, ix=170, q1=4.8, q2=5.3, la=4.8, cte=-0.0
2021-03-30 21:50 :09 [dbg15 lp964659] 7618 Dyna-6 (#2): PPC: common case, ix=171, q1=4.7, q2=15.0 la=4.8
2021-03-30 21:50 :09 [dbg15 lp964659] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-currentWpNode waypoint index 172
2021-03-30 21:50 :09 [dbg4 lp964659] 7618 Dyna-6 (#2): onWaypointChange 172, connecting: nil, temp: false
2021-03-30 21:50 :10 [dbg17 lp964690] 7618 Dyna-6 (#2): updating collision boxes at waypoint 170, have 20 positions, invalid: false
2021-03-30 21:50 :10 [dbg15 lp964691] 7618 Dyna-6 (#2): PPC: waypoint 171 passed, dz: 0.0  
2021-03-30 21:50 :10 [dbg15 lp964691] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-relevantWpNode waypoint index 171
2021-03-30 21:50 :10 [dbg15 lp964691] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-nextWpNode waypoint index 172
2021-03-30 21:50 :10 [dbg15 lp964691] 7618 Dyna-6 (#2): PPC: relevant waypoint: 171, crosstrack error: -0.0
2021-03-30 21:50 :10 [dbg4 lp964691] 7618 Dyna-6 (#2): onWaypointPassed 171
2021-03-30 21:50 :10 [dbg4 lp964700] 7618 Dyna-6 (#2): Speed = 51.0, gx=0.0 gz=4.8 l=4.8 ax=0.0 az=4.8 allowed=true fwd=true
2021-03-30 21:50 :10 [dbg17 lp964700] 7618 Dyna-6 (#2): has 4 colliding object(s)
2021-03-30 21:50 :10 [dbg15 lp964723] 7618 Dyna-6 (#2): PPC: two intersection points, ix=171, q1=4.8, q2=5.5, la=4.8, cte=-0.0
2021-03-30 21:50 :10 [dbg15 lp964729] 7618 Dyna-6 (#2): PPC: common case, ix=172, q1=4.8, q2=15.0 la=4.8
2021-03-30 21:50 :10 [dbg15 lp964729] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-currentWpNode waypoint index 173
2021-03-30 21:50 :10 [dbg4 lp964729] 7618 Dyna-6 (#2): onWaypointChange 173, connecting: nil, temp: false
2021-03-30 21:50 :11 [dbg17 lp964750] 7618 Dyna-6 (#2): updating collision boxes at waypoint 171, have 20 positions, invalid: false
2021-03-30 21:50 :12 [dbg4 lp964800] 7618 Dyna-6 (#2): Speed = 10.0, gx=0.0 gz=4.8 l=4.8 ax=0.0 az=4.8 allowed=true fwd=true
2021-03-30 21:50 :12 [dbg17 lp964800] 7618 Dyna-6 (#2): has 4 colliding object(s)
2021-03-30 21:50 :12 [dbg15 lp964803] 7618 Dyna-6 (#2): PPC: waypoint 172 passed, dz: 0.0  
2021-03-30 21:50 :12 [dbg15 lp964803] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-relevantWpNode waypoint index 172
2021-03-30 21:50 :12 [dbg15 lp964803] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-nextWpNode waypoint index 173
2021-03-30 21:50 :12 [dbg15 lp964803] 7618 Dyna-6 (#2): PPC: relevant waypoint: 172, crosstrack error: -0.0
2021-03-30 21:50 :12 [dbg4 lp964803] 7618 Dyna-6 (#2): onWaypointPassed 172
2021-03-30 21:50 :12 [dbg17 lp964810] 7618 Dyna-6 (#2): updating collision boxes at waypoint 172, have 20 positions, invalid: false
2021-03-30 21:50 :12 [dbg16 lp964835] Maestro 12 SW: unloadingTriggerCallback close Cover
2021-03-30 21:50 :13 [dbg16 lp964853] Maestro 12 SW: unloadingTriggerCallback close Cover
2021-03-30 21:50 :13 [dbg17 lp964870] 7618 Dyna-6 (#2): updating collision boxes at waypoint 172, have 20 positions, invalid: false
2021-03-30 21:50 :13 [dbg4 lp964900] 7618 Dyna-6 (#2): Speed = 10.0, gx=0.0 gz=4.8 l=4.8 ax=0.0 az=4.8 allowed=true fwd=true
2021-03-30 21:50 :13 [dbg17 lp964900] 7618 Dyna-6 (#2): has 4 colliding object(s)
2021-03-30 21:50 :13 [dbg15 lp964906] 7618 Dyna-6 (#2): PPC: two intersection points, ix=172, q1=4.8, q2=5.4, la=4.8, cte=-0.0
__________________________________________________________________________________________________________________________________

This is a portion of the log files as the same tractor has moved further along the line and has refilled (i paused the games and was typing this up which explains the 5 minute difference in time and it still has "has 4 colliding object(s)"

2021-03-30 22:00 :14 [dbg4 lp999889] 7618 Dyna-6 (#2): onWaypointPassed 271
2021-03-30 22:00 :15 [dbg4 lp999900] 7618 Dyna-6 (#2): Speed = 10.0, gx=-0.2 gz=4.9 l=4.9 ax=-0.2 az=4.9 allowed=true fwd=true
2021-03-30 22:00 :15 [dbg17 lp999900] 7618 Dyna-6 (#2): has 4 colliding object(s)
2021-03-30 22:00 :15 [dbg15 lp999901] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-currentWpNode waypoint index 273
2021-03-30 22:00 :15 [dbg4 lp999901] 7618 Dyna-6 (#2): onWaypointChange 273, connecting: nil, temp: false
2021-03-30 22:00 :15 [dbg17 lp999924] 7618 Dyna-6 (#2): updating collision boxes at waypoint 271, have 20 positions, invalid: false
2021-03-30 22:00 :16 [dbg17 lp999971] 7618 Dyna-6 (#2): updating collision boxes at waypoint 271, have 20 positions, invalid: false
2021-03-30 22:00 :16 [dbg15 lp999986] 7618 Dyna-6 (#2): PPC: waypoint 272 passed, dz: 0.0  
2021-03-30 22:00 :16 [dbg15 lp999986] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-relevantWpNode waypoint index 272
2021-03-30 22:00 :16 [dbg15 lp999986] 7618 Dyna-6 (#2): PPC: 7618 Dyna-6 (#2)-nextWpNode waypoint index 273
2021-03-30 22:00 :16 [dbg15 lp999986] 7618 Dyna-6 (#2): PPC: relevant waypoint: 272, crosstrack error: 0.0
2021-03-30 22:00 :16 [dbg4 lp999986] 7618 Dyna-6 (#2): onWaypointPassed 272
2021-03-30 22:00 :17 [dbg4 lp1000000] 7618 Dyna-6 (#2): Speed = 10.0, gx=-0.0 gz=4.8 l=4.8 ax=-0.0 az=4.8 allowed=true fwd=true
2021-03-30 22:00 :17 [dbg17 lp1000000] 7618 Dyna-6 (#2): has 4 colliding object(s)
2021-03-30 22:00 :17 [dbg17 lp1000025] 7618 Dyna-6 (#2): updating collision boxes at waypoint 272, have 20 positions, invalid: false

![Image3](https://user-images.githubusercontent.com/25461795/113057356-d6d6d680-91a4-11eb-9b5b-c7c63c060e72.png)
________________________________________________________________________________________________________________________________
As an aside i ran this several times and it kept hitting the 10mph limit.. I then moved the trailers & implements in the pic in further and i did not not hit he 10mph limit. I moved them back out and on the rerun i hit the 10mph again..

Hope this helps

**Comment by Tensuko** [comment] 2021-04-01 20:17
Well, thanks for the rply, but throw on all debugchannels doesn't help much...

**Comment by Misamangame** [comment] 2021-04-09 06:56
Just an update what I experienced. When I have fertilizer function OFF on seeder and refilling only seeds, tractors continue in normal speed. Same is for liquid fertilizer had no issue with it at all. Haven't tested slurry or manure but looks only lime and solid fertilizer causing slowing down.

**Comment by RayzerSharpe** [comment] 2021-04-26 19:52
In AIDriver.lue Line 468/469 I changed the code back to the commented out code and it works fine now for me

	if self:getIsInFilltrigger() or self:hasTipTrigger() then-- or isInTrigger then
	--if isInTrigger then

It looks like the isInTrigger is not enough on its own.

**Comment by Tensuko** [comment] 2021-05-13 12:50
If you have a way to reproduce this, can you give it a try with version 00060 ? I am not sure if the fixes we did for the speed + the switch to AD and back may cause things like that.

**Comment by RayzerSharpe** [comment] 2021-05-17 20:10
Tensuko, Yes initial check seems that the issue is gone.. I will keep an eye on it but for me the issue does not happen any more. Nice job :)

**Comment by Tensuko** [comment] 2021-05-29 14:15
Oh damn I am late in notice the feedback.

Well that sounds good!
I will close this then, in case there is something happening still, reopen or better make a new Issue and assign this one. :)

**Closed by Tensuko** 2021-05-29 14:15 UTC
Labels: bug

**Comment by Babalookan** [comment] 2021-07-24 23:27
I'm experiencing this right now. I'm filling using big bags the equipment drives over fills up fine and then never gets above 6mph.  is there something simple for me to fix, CP gets stuck in isInTrigger:True i see this issue has happened before. i am running version 6.4.0.4
