### ISSUE TITLE
No turning after the first row

### ISSUE THREAD

**Issue by Hasilein** [Courseplay/courseplay#1553] opened 2016-12-25 16:17 UTC
The tractor is still heading forward instead of turning for the next row:
CP.0037
Map: GoldCrest Valley (standard)
tractor: MF 7700 with Cayron 200 (standard)
Field: 12

[log.txt](https://github.com/Courseplay/courseplay/files/672258/log.txt)

**Comment by SunkenL** [comment] 2016-12-26 16:50
Can confirm this with combine CR.10.90 on Hobbs farm. The combine just goes straight forward instead of turning after the field..

**Comment by sootysax** [comment] 2016-12-26 16:58
also happening with mowers.. after any row, not just first

**Comment by gec100** [comment] 2016-12-26 17:34
also it can happen randomly. I've had sower done the field with no problem till the last lane when tractor just continued forward before turning to the last lane.

**Comment by BenB78** [comment] 2016-12-27 08:51
It's happening for me too. It was working fine until I updated. The tractor goes right off the end of the sowing row as if the turning point isn't there, and keeps driving forward until stopped.

**Comment by gec100** [comment] 2016-12-27 10:56
it's a clean game with no mods other than CP on a standard Goldcrest Valely map.

**Comment by BenB78** [comment] 2016-12-27 10:59
Goldcrest Valley map here too.

**Comment by mereman** [comment] 2016-12-27 16:30
Same problem while ploughing using a ingame Valtra and lemken on a moded Sosnovka. When I swapped back to dev .0035 it worked as expected.

**Comment by Retsamikit** [comment] 2016-12-27 16:51
Same here with 0.37 Tractor goes straight ahaed after the first row. I tried a new game without any mods and I have the same Problem in GoldCrest and Sovnovka. I also tried different rows - there was no turn.
With turn on field everything worked. Went back to 0.36.

**Comment by sootysax** [comment] 2016-12-27 18:04
for me these are courses with headlands..  i have not tried with non-headland courses..  going back to .036 also seems to fix this

**Comment by SunkenL** [comment] 2016-12-28 11:59
Have tried to get around this problem with headlands, activated/inactivated turn on field, creating several different courses and nothing works. The combines(Holmer and CR10.90) does the same thing. Just goes straight forward instead of making a turn every time. Not only the first.. Have the devs knowlegde of this? 
Dev. 0037

**Comment by Satissis** [comment] 2016-12-28 13:22
> Have the devs knowlegde of this?

I have read about it, but since it's Christmas Holidays, I'm not at my PC and won't be until the next year I believe, so nothing I can really do atm, thou allot of this sounds really wierd, since I tested every single turn types, but with the same tool thou.

Anyway, I'll first be able to look into it when I get home again

**Comment by frm274** [comment] 2016-12-31 16:26
I think the problem is, when a turn-course is generated, it is set behind the vehicle.

<a href="http://www.pic-upload.de/view-32394337/cpissue.jpg.html"><img src="http://www2.pic-upload.de/thumb/32394337/cpissue.jpg" alt="Bild hochladen" /></a>

Had this issue in a former version with a fertilizer spreader, but this works fine now in the newest version...

**Comment by Satissis** [comment] 2017-01-01 14:33
> I think the problem is, when a turn-course is generated, it is set behind the vehicle

Yes that's normally the case.

**Comment by Retsamikit** [comment] 2017-01-04 21:19
still no turn with 5.01.00009 - fresh game, no mods but courseplay, Goldcrest. At the End of a row it goes straight ahead....

**Comment by Zibbl** [comment] 2017-01-04 21:53
Unfortunately yes

**Comment by pops64** [comment] 2017-01-04 23:23
Add fertilizer Excata EL 700 back to the list. With turn on field disabled. The turn around maneuver is behind the tractor and no reverse course is generated. v0.10

**Comment by jonnyyorks** [comment] 2017-01-07 10:34
I get the same issue also.  It happens with the default mowers, Exacta and mid sized tedder so far

**Comment by AgroWillem** [comment] 2017-01-07 13:53
Still happens with V 5.x19. After 2nd row it runs straight ahead.
GV Field25
Mowers: Lely Splendimo 320FC+900FC

[log](https://gist.github.com/AgroWillem/31f9db1b9b27e17e445097e6a6bdbad4)

**Comment by Satissis** [comment] 2017-01-08 11:30
@AgroWillem could you take an screenshot with debug 12 and 14 active, just when it starts turning.
Also post the log after that, since it have prints in it from debug 12 and 14 in it when they are active :)

**Comment by Raints** [comment] 2017-01-08 12:01
@AgroWillem Maybe you also try without DriveControl, had some weird issues with it.

**Comment by Hasilein** [comment] 2017-01-08 12:26
**@Satissis** 
![1](https://cloud.githubusercontent.com/assets/24765277/21749755/eebf8932-d5a5-11e6-9655-f0b185a1b07a.png)
![2](https://cloud.githubusercontent.com/assets/24765277/21749756/f606ccdc-d5a5-11e6-8c47-abb4fecda98c.png)
![3](https://cloud.githubusercontent.com/assets/24765277/21749757/f8e67074-d5a5-11e6-9056-3dd6a7c5f241.png)
![4](https://cloud.githubusercontent.com/assets/24765277/21749758/fa8226e4-d5a5-11e6-8e07-0108519c6b5f.png)
![5](https://cloud.githubusercontent.com/assets/24765277/21749759/fc0436d8-d5a5-11e6-8ee7-3db0da94cd5a.png)
[log.txt](https://github.com/Courseplay/courseplay/files/692082/log.txt)

**Comment by AgroWillem** [comment] 2017-01-08 14:23
@Raints
I already tried without any mods and it still happened.
With an old version of CP (i believe 5.0x028) it didn't occure with all the mods active.

**Comment by AgroWillem** [comment] 2017-01-08 15:16
@Satissis 
I started a new level with no other mods then CP.
It still occurs.
Field 25 GV
I let the tractor first make 3 roundings and on the first straight line it goes wrong.

[log](https://gist.github.com/AgroWillem/0848970dda8fc05d493f44451760f7bf)
![fsscreen_2017_01_08_16_05_27](https://cloud.githubusercontent.com/assets/23076511/21750858/8fa123da-d5bd-11e6-9e82-46000e58b359.png)
![fsscreen_2017_01_08_16_05_32](https://cloud.githubusercontent.com/assets/23076511/21750859/8fa16282-d5bd-11e6-8a91-712747dab22a.png)
![fsscreen_2017_01_08_16_05_44](https://cloud.githubusercontent.com/assets/23076511/21750860/8fa31a0a-d5bd-11e6-8de3-044d4964bb11.png)
![fsscreen_2017_01_08_16_05_52](https://cloud.githubusercontent.com/assets/23076511/21750861/8fa66278-d5bd-11e6-812e-441008b0443c.png)

**Comment by ralf001** [comment] 2017-01-08 15:58
It also happens to me with no mod map and no mod vehicles, but only with larger work width. 
If i increase the turning circle (Wendekreis) the vehicle will turn.
e.g. the couse was generated with a workwidth of 12m and the turning circle was 10m it will turn, but if the work width is 13m it won't turn. If i increase it it turns.

**Comment by pops64** [comment] 2017-01-08 17:55
I think its any tool that has no wheels that causes this issue including the great plains seeder. Cause harvesters work fine. [Log](http://pastebin.com/TGCapMnD)
![farming simulator 17 1_8_2017 12_50_01 pm](https://cloud.githubusercontent.com/assets/10678220/21752112/164942d6-d5a1-11e6-85c3-7b6958b0b61d.png)

**Comment by Raints** [comment] 2017-01-08 18:26
I'll definitely do something wrong, because I will not be able to experience the same error. Did same test in GV field 25. Made 3 headland and here is the video.https://www.youtube.com/watch?v=b6ya8R4qvEE

What am I doing differently?

**Comment by Satissis** [comment] 2017-01-08 18:36
@Raints that turn is not the 3 point turn, so that's why you are not experience the same problem.
@pops64 yeah something is wrong in the wide turn. I'll look if I can replicate it and fix it once I'm done with the forward 3 point turn. The reverse 3 point turn works fine.

I make a commit in a min or so, with an update for the 3 point turns, so stay tuned :P

**Comment by Satissis** [comment] 2017-01-08 18:40
Try again with v01.0022 or later and report back

**Comment by AgroWillem** [comment] 2017-01-08 19:54
Yep, here it's working now fine. Great job! :D

**Comment by Satissis** [comment] 2017-01-08 22:59
@pops64 Try 01.0023
it's working on my end now

**Comment by frm274** [comment] 2017-01-09 08:08
<a href="http://www.pic-upload.de/view-32454751/issue3.jpg.html"><img src="http://www2.pic-upload.de/thumb/32454751/issue3.jpg" alt="Bild hochladen" /></a>

**Comment by Satissis** [comment] 2017-01-09 15:24
@frm274 could you make an new issue about that, since you are using an self made course. Something I have not tested at all yet.

**Comment by Retsamikit** [comment] 2017-01-09 17:53
Made a short test with a new game in goldcrest with no other mods. Took the first Tractor and it seems to work now.  Thankyou.  000023

**Comment by pops64** [comment] 2017-01-09 18:18
Works for me thanks for updated :D

**Comment by Satissis** [comment] 2017-01-09 18:28
Alright, I'm going to close this then. We can reopen it if needed to :)
@frm274 I think it's related to #1561 post https://github.com/Courseplay/courseplay/issues/1561#issuecomment-270597246 as well and might be the chopper that's the problem. I'll have an look into it.

**Closed by Satissis** 2017-01-09 18:28 UTC
Labels: bug, waitingForUserAnswer

**Comment by Michael9220** [comment] 2017-06-04 00:46
Hmm is this still an issue? I'm having this problem when using the New Holland 10.90 combine and the Case 9230 combine. I haven't experienced it with any other vehicles. It seems like it's only happening with the 45 ft headers?

**Comment by pops64** [comment] 2017-06-04 06:12
Headers shouldn't have any impact in the turn maneuvers. It sounds like your courses probably is setup differently for theses harvesters. Check out the many other issues with regarding turn manuvers. If they don't match make a new issue following https://github.com/Courseplay/courseplay/wiki debug channel 12 and 14
