### ISSUE TITLE
level and compacting

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2174] opened 2017-07-10 16:28 UTC
im using the latest version of CP and i recorded the course the same as always and when i save it and click drive the tractor just stays there and the game becomes very laggy , this hasnt happend before and im using the same mods as i always use 

[log.txt](https://github.com/Courseplay/courseplay/files/1136358/log.txt)

**Comment by pops64** [comment] 2017-07-10 17:19
I would start by cleaning out mods that are throwing out errors. Has you have a ton of non CP related errors on load. I would also suspect that this is the cause of your call stack error

**Comment by willie2016** [comment] 2017-07-10 19:40
iv always used them mods though and never had this problem with cp

**Comment by pops64** [comment] 2017-07-10 22:02
Well, you must have updated or you installed a new mod or started using a new mod(aka just bought a new tractor) Ethier way please test with no mods on but CP and report back. As I think you have a mod that is missing something that CP needs and there is no avoiding this.

**Comment by bigjoker76** [comment] 2017-07-11 13:54
I had the same once with the AIVehicleExtension Mod from Mogli...

**Comment by pops64** [comment] 2017-07-11 22:14
This is separate from the AIVE mod problem. Which now fixed since version 134 or so. So could be so many things just based on the amount errors other mods are spitting out.

**Comment by pops64** [comment] 2017-07-16 13:12
What is the status of this? Have you tried running without mods. As I believe this is something we can't fix

**Comment by bigjoker76** [comment] 2017-07-17 16:46
Until now, no further problems...with or without AIVE

**Comment by pops64** [comment] 2017-07-28 12:34
Closed due to inactivity and something we can't fix.

**Closed by pops64** 2017-07-28 12:34 UTC
Labels: Mod Conflict
