### ISSUE TITLE
Claas Lexion 8900 unload - to less backup from fruit

### ISSUE THREAD

**Issue by aszechlicki** [Courseplay/courseplay#4463] opened 2019-10-28 19:00 UTC
Harvesting with Lexion 8900 with Stop during unload set to true
When combine gets full with pipe on the crop side, the combine moves away from crop to make space for the unloading vehicle
It works great, except in the case of Claas Lexion 8900 - it has a long pipe, that forces driver to go to the very edge of the crop to unload, without any room for error

It would be nice if the combine could move a bit further away from crop

**Comment by pvaiko** [comment] 2019-10-28 19:51
Duplicate of #3987

**Closed by pvaiko** 2019-10-28 19:51 UTC
