### ISSUE TITLE
Turn maneuvers with seeders from the Big Bud DLC

### ISSUE THREAD

**Issue by xDeterminatorx** [Courseplay/courseplay#2864] opened 2018-09-13 21:06 UTC
When using the GREAT PLAINS YP-2425A, it turns to the wrong side while reversing. It would be the right side, if the seeder was not a trailer, so maybe courseplay is not taking this into account? On the other hand, judging from the red-box/line, courseplay seems to detect work area shifted way to the front. So maybe there is something wrong with the detection of the wheels/pivot point to.

The same problem appears if I use the Terminator TH18 or XL Toolbar 84ft without a seed tank (switching the helper to autobuy seeds and fertilizer). On the Terminator, the work area is also shifted but way to the back.

All these seeder have a lot of wheels, especially steered wheels, but nonetheless behave like an unsteered trailer. Accordingly, I tend to a misplaced pivot point.

For completeness: I am using CP 5.3.0.0 and the problem occurs even if I deactivate all mods except for CP, Drive Control and the the DLC of course.

**Comment by pops64** [comment] 2018-09-13 22:55
Try it with the seed cart. I don't think I ever tested the big bud dlc without the seed cart. Also the red box line has nothing to do with work area just width. Try it with a non pivoting tractor. Has these have never really played nice with the reversing turn manuvers

**Comment by pvajko** [comment] 2018-09-13 23:18
Duplicate of #2396

**Closed by pvajko** 2018-09-13 23:18 UTC
