### ISSUE TITLE
Grain Transport - Adding Message when Silo is empty or full

### ISSUE THREAD

**Issue by ninjayx02** [Courseplay/courseplay#3513] opened 2019-04-01 19:43 UTC
it appears that if there is not enough grain to fill the trailer, it waits at the fill point for manual intervention,  but no message

**Comment by sootysax** [comment] 2019-04-02 12:13
@ninjayx02 as it has always done..  not a bug

**Comment by ninjayx02** [comment] 2019-04-02 12:56
in 17,  there was a message that the silo was empty

**Comment by Tensuko** [comment] 2019-04-02 13:42
When got a bit grain, it wills up till empty and then drive its round.
When silo is empty, it gives out a message.
Thats what I remember from my NF_Marsch Straw Compost loop with silo and compost_master.

**Comment by Tensuko** [comment] 2020-09-06 12:21
should be done already, still tweaking the new Triggers a bit. Closing anyway.

**Closed by Tensuko** 2020-09-06 12:21 UTC
Labels: postponed, suggestion
