### ISSUE TITLE
Sites promoting this mod with fake download

### ISSUE THREAD

**Issue by ProCal94** [Courseplay/courseplay#2925] opened 2019-01-08 22:46 UTC
There are a few sites out there promoting this mod with a fake download link. Just posting here in case people think its the actual mod. Plus these downloads are usually very risky because they can contain malware.

This is some of them:
https://www.fsmod.net/fs19-mods/fs19-courseplay-v1/
https://www.simulatorgamemods.com/fs19-courseplay-v1/
https://www.farmingsimulator19.com/farming-simulator-19-mods/fs19-courseplay-v1-0/

**Comment by erksartori** [comment] 2019-01-09 01:18
Thanks for the information, thank God I just get out of here. And I am anxious to put and leave playing.

**Comment by Tensuko** [comment] 2019-01-09 08:16
Thos kind of 'farmingsimulator19mods' and other similar adresses are simply full of trash and stolen mods!
Even Modhoster starts to accept all kind of mods and trash.... Hard to find the good and worth one.

**Comment by derJan2001** [comment] 2019-01-09 15:16
Modhoster is not the fastes way to get the mod you prefer. that´s the reason why the other ones are so popular.
http://www.uploadmods.com is my favorite ... quick, fast and easy :-*

**Comment by bgo1973** [comment] 2019-01-09 23:06
Das Problem ist nur, und das würde ich mal fast als eine Frechheit bezeichnen, dass dort dann nicht der Originallink benutzt wird. Selbst die Fahrzeuge, etc. vom Modhub werden dort über einen eigenen Link angeboten. Somit wird sämtliche Monetarisierung vernichtet. Ich gönne das den Moddern und werde auch in Zukunft keine Mods von solchen Seiten beziehen.

**Comment by bgo1973** [comment] 2019-01-09 23:08
The problem is, and I would almost call this a cheekiness, that the original link is not used there. Even the vehicles, etc. from the Modhub, are offered there via their own link. This destroys all monetization. I treat this to the modders and will not receive mods from such sites in the future

**Comment by ProCal94** [comment] 2019-01-11 14:40
> 
> 
> If you're dumb enough to think that Courseplay was completed in the first week of FS19 being released, you kind of deserve malware.

@sootysax I think we should all help each other to make the internet a better place. It doesn't just benefit the person that doesn't click the link and avoids the malware, it also benefits everyone in a way. Maybe that person goes on and helps someone else accomplish the same. All I'm saying is one random act of kindness at a time can go a long way. Let's all help each other and make the internet a great place to chill :P

**Comment by ThomasGaertner** [comment] 2019-01-27 10:12
I will close this to keep the area clean, Thanks for the hints ..

**Closed by ThomasGaertner** 2019-01-27 10:12 UTC
