### ISSUE TITLE
Unable to activate editor

### ISSUE THREAD

**Issue by gentfarmer** [Courseplay/courseplay#4751] opened 2020-01-01 05:52 UTC
"e", "E", or CTRL+e do not activate Russ's editor, all they do is exit the vehicle.
Am I missing something?
v 6.01.00355

**Comment by russbeuker** [comment] 2020-01-01 05:56
The course editor by default has hotkeys already assigned, such as LCTRL-e to toggle the editor.  But these won't work if the e has already been assigned to a different action.   

Best to load your savegame and go into the to hotkeys and scroll to the bottom of the list where the courseplay and course editor hotkeys are listed.  Then set them to whatever you prefer.  There is a courseplay modifier that may already be set to LCTRL, so for the editor toggle hotkey, you could just enter 'e' or whatever.  I'll post a vid in the next day or so showing more info and  how to set it all up.

**Comment by gentfarmer** [comment] 2020-01-01 06:05
A light bulb moment Russ :-)
Looking at the list of controls nothing was set for Courseplay editor, when I assigned LCTRL+e the editor was activated.
Many thanks for this much needed Courseplay addon.

Now to have a play

**Comment by game455** [comment] 2020-01-01 19:07
I assigned LCTRL+LSHIFT+e to the editor. That works. Many thanks for that addon

**Comment by bojanh66** [comment] 2020-01-01 19:24
Does anyone else have a problem when you want to load course, before it was instantly, now it takes 5-10 seconds ?

**Comment by Tensuko** [comment] 2020-01-02 01:33
Check your advanced setting if load course on start is on or off.

**Comment by bojanh66** [comment] 2020-01-02 07:37
Wow, it fixed it, tnx.
With deactivated, its again like before, less than a second, with activated, game freezes for 10 seconds.
Now, could you please explain shortly, what was the cause of it?
In 354 and lower versions, i had always activated Load course on start, because if i savegame in a middle of harvesting and load game, i hate to load courses on each vehicle again, so thats why i had activated that option, so i could continue my work without searching for courses.

But it seems this option is activated now even if it says Deactivated ?
I tried to load some courses on my tractors, turned off Load courses on start, saved game, loaded game and courses were still loaded on my tractors?

It seems its because of CP editor, does it somehow conflict with Load course on start if its activated?

**Comment by Tensuko** [comment] 2020-01-02 09:04
That option load all course when load savegame or only load them when you open them in the HUD. That got nothing to do with course stays loaded at your tractor or not.

**Comment by pvaiko** [comment] 2020-01-05 16:17
@Tensuko why isn't this closed?

**Comment by Tensuko** [comment] 2020-01-05 16:33
@pvaiko As Information Issue... but nevermind I close this and wait for the next one to be opened.

**Closed by Tensuko** 2020-01-05 16:33 UTC
