### ISSUE TITLE
Question: Field work max amount of unload triggers. 

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#2035] opened 2017-05-03 19:25 UTC
The case is the following:
I'm picking up hay with a loading wagon and unloading it into hay stacks - the placeable standard ones. 
I have tried it with 2 haystack and it's working perfectly, unloading at the first until it's full and then unloading at the second. 

Now I have added a few more haystacks and made a new course for them and the worker is unloading at the fourth, even through number 1-3 are empty. 
So I was wondering if there is a highest amount of triggers to add to the field work course.

**Comment by pops64** [comment] 2017-05-03 21:52
If the mod you are is using a standard giants tip tiggers. I don't think there is a maximum has CP is always looking for tip triggers when off the field. So if it is skipping the first 3 then I think CP isn't even detecting those tip triggers an issue debug channel 1 well help figure out. If your using unload points and using giants tip anywhere feature that is a different story and something Thomas probably could answer for you.

**Comment by TheRealRolandDeschain** [comment] 2017-05-04 19:25
I think CP did recognises the triggers (it writes it into the mod window). 
Anyhow, I will try to make a new course and post a video over the weekend. 

Maybe the triggers are just too close to each other....

**Comment by pops64** [comment] 2017-05-04 19:39
I am not sure about mode6. but I know if two triggers next to each other. The tractor will unload in the first one because that is the one it sees And since it has seen a trigger it stops looking for one until it unloads. If the tractor is near the edge of the 2nd trigger when it has finished unloading it won't see this second. Not 100% sure on that because mode4 and 8 acts completely differently theses two modes if CP doesn't see the trigger but the work tool happens to cross into a trigger CP will try unloading into that trigger. This is why you can put seed and fertilizer pallets next to each other and it works. But yea a video would be great. If debug channel 1 is recongize the trigger than trying running the channel for load and unload tippers(2 I believe) I know mode6 unloading has gotten a little funny in the conversion to 17.

**Comment by TheRealRolandDeschain** [comment] 2017-05-07 16:33
OK, so as Promised here is the video and log:
https://youtu.be/ryZwSfjBPJA

[log.txt](https://github.com/Courseplay/courseplay/files/981733/log.txt)

The driving around the haystacks is to avoid two triggers beeing too close to each other, however my first guess is, that this still is the problem.

**Comment by pops64** [comment] 2017-05-07 19:50
Only one of the CP developers speaks German. So reports should always be in English.  Could we get your save game file as well as all your courses. I have a feeling that I know what the problem is.

**Comment by TheRealRolandDeschain** [comment] 2017-05-07 21:25
So I kept playing, so there is no save game at the moment ;)

I will make another save game where everything is ready to test for you and upload it.

**Comment by TheRealRolandDeschain** [comment] 2017-05-08 21:53
OK, here you will find all the files:
https://app.box.com/s/k1l4bay98laynx8zfpdh6bfw4ic7bumm

The savegame should be ready, so you just have to start the course.

**Comment by pops64** [comment] 2017-05-10 19:14
So to give you an update. The problem is the turn through the fill trigger. If you went straight through it instead of having a turn at the exit it would dump. That is why the last one works. I am working on a solution while trying to keep the tip point in the center.

**Comment by TheRealRolandDeschain** [comment] 2017-05-10 19:19
Thanks a lot!

**Comment by pops64** [comment] 2017-05-11 01:51
Try with version 136 or higher and report back. Thanks

**Comment by TheRealRolandDeschain** [comment] 2017-05-15 16:55
Hey, sorry for the long wait, can't play much atm. 
Will report asap if the fix works!

**Comment by TheRealRolandDeschain** [comment] 2017-05-22 16:37
Finally tested it with the current version and it works fine!

**Comment by pops64** [comment] 2017-05-22 18:07
Thanks will close this out

**Closed** 2017-05-24 06:21 UTC
Labels: bug, waitingForUserAnswer
