### ISSUE TITLE
Problem with Gemeinde Rade 2k19

### ISSUE THREAD

**Issue by nismof15** [Courseplay/courseplay#4704] opened 2019-12-26 11:45 UTC
[log.txt](https://github.com/Courseplay/courseplay/files/4002400/log.txt)
Hello everyone. I have experienced a problem on the new map that i would like to play. The problem did not occured on any other map, i have the latest version of courseplay. The problem is that when i record some path, or generate one from course generator it can not start moving tractor. The tractor is staying at one place and i can see an arrow in the courseplay HUD. Thet error occurs that says the trigger.lua Table is nil and some fault with mouse control event. Is that problem on the side of faulty map or courseplay needs to be adjusted? Sorry if there was a question like this, im new to Github. Anyway keep that great work of development, you guys are the best. Best regards.

**Comment by Tensuko** [comment] 2019-12-26 14:39
Map Issue.
Duplicate of #4185
Closed.

**Closed by Tensuko** 2019-12-26 14:39 UTC
