### ISSUE TITLE
Cannot fill trailer at any station??

### ISSUE THREAD

**Issue by Lykkehoj** [Courseplay/courseplay#1082] opened 2015-02-28 22:31 UTC
Hi

I'm using CP4.01 and is trying to setup a standard sell route from my silo til flour mill. Standard tractor, standard ITC trailer. Go to the point where fill pops up in F1 menu, push record, fill my trailer and drive the route to the flour mil and back and line up, then press stop. 
Then i press drive course, and the tractor blasts through the fill point and runs the course plottet, if i stop it and fill the trailer manual, it tips off allright, but it will not fill any grain type, sugar beets og potatoes.. i don't get it. I have watched a lot of youtube and run through a lot of webpages, but i can not see where i'm doing it wrong

**Comment by PTAzores** [comment] 2015-02-28 23:33
Hello try here, maybe some solution!!
https://github.com/Courseplay/courseplay/issues/866

**Comment by Mopar** [comment] 2015-03-01 05:49
I am using dev version 86 and so far no issues with grain transport from silos.

1. Are you using a modded map or one of the default maps?
2. Are you sure you have CP in mode 1? (Grain transport mode)
3. Is the start of the course under the silo fill pipe? (It should give you the option to fill manually before you start recording the course)

**Comment by Lykkehoj** [comment] 2015-03-01 10:01
Default map, CP in mode one, start point at fill.
I will try and start a new game, empty mods except cp and try again

**Comment by Lykkehoj** [comment] 2015-03-01 12:37
New game loaded, starting tractor with tipper, only CP and GPS mod. everytihning works like a charm.. loads and unloads whatever i want. will install mods one by one till i find the one that ruins it. Tanks for your help, CP works, my mods don't ;-)

**Comment by Lykkehoj** [comment] 2015-03-01 13:39
Forgot to mention.
Tried to install all my mods again, stiil no fails, but found the fault.
IT runner trailer and container will NOT fill on auto, all my other "normal" tippers works like a charm..

**Comment by ThomasGaertner** [comment] 2015-03-01 13:51
maybe @Satissis  will have a look on it by chance

**Comment by Satissis** [comment] 2015-03-01 16:57
I know what the problem is :P 
You need to update to the latest developing version, since support for the ITRunner package was not added in the release version, which is the one I'm guessing you are using when you say you use the CP4.01 :)
I fixed that problem right after our first release, so it should be fixed in the developing version.
How to install the developing version..... well search youtube and you will find some tutorials on it ;)

**Comment by Lykkehoj** [comment] 2015-03-01 19:02
Dev version installed, ITRunner works like a charm, everything works like a charm. THANKS.
Quite new here at GITHUB, so don't know if it's me who should close it, or one of you? can see i have the option.

**Closed** 2015-03-02 08:25 UTC
Labels: waitingForUserAnswer

**Comment by Satissis** [comment] 2015-03-03 01:17
yeah you just close it your self if you think it needs to :)
