### ISSUE TITLE
Error: Running LUA method 'update' - Plow.lua(680) : attempt to compare number with nil

### ISSUE THREAD

**Issue by westgate911** [Courseplay/courseplay#4315] opened 2019-10-01 00:33 UTC
2019-09-30 19:29 data/shared/ai/trafficCollision.i3d (0.34 ms)
2019-09-30 19:31 Error: Running LUA method 'update'.
2019-09-30 19:31 dataS/scripts/vehicles/specializations/Plow.lua(680) : attempt to compare number with nil
2019-09-30 19:31 Error: Running LUA method 'update'.
2019-09-30 19:31 dataS/scripts/vehicles/specializations/Plow.lua(680) : attempt to compare number with nil
2019-09-30 19:31 Error: Running LUA method 'update'.

Every Time any tractor gets at the end of the row to turn to the next pass camera freezes up and then tractor keeps going straight.

**Comment by Tensuko** [comment] 2019-10-01 05:02
full logfile...
what tractor, what tool, screenshot ?

**Comment by Tensuko** [comment] 2019-10-01 15:39
Error: Invalid mod name '72x150_redshed_wlights'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Error: Failed to open xml file 'C:/Users/Anthony/Documents/My Games/FarmingSimulator2019/mods/FS19_flieglDPW180SB_BD/modDesc.xml'.
Load mod: FS19_flieglDPW180SB_BD (Hash: f3b834e03a74fd016d5c1bf9520fb0c9)
Error: Missing descVersion attribute in mod FS19_flieglDPW180SB_BD

Error: Invalid mod name 'FS19_guidanceSteering-maste'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit 
(why not get the ModHub Version ?)

Callstack from Seasons:
LUA call stack:
2019-10-01 09:58   dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
2019-10-01 09:58   dataS/scripts/i3d/I3DUtil.lua (88) : checkChildIndex
2019-10-01 09:58   dataS/scripts/objects/AnimatedObject.lua (82) : indexToObject
2019-10-01 09:58   dataS/scripts/placeables/Placeable.lua (582) : load
2019-10-01 09:58   =C:/Users/Anthony/Documents/My Games/FarmingSimulator2019/mods/FS19_RM_Seasons/src/misc/SeasonsMask.lua (241) : superFunc
2019-10-01 09:58   =C:/Users/Anthony/Documents/My Games/FarmingSimulator2019/mods/FS19_RM_Seasons/src/placeables/PlaceableAdmirers.lua (67) : superFunc
2019-10-01 09:58   dataS/scripts/placeables/Workshop.lua (25) : load
2019-10-01 09:58   dataS/scripts/placeables/Placeable.lua (967) : load
2019-10-01 09:58   =C:/Users/Anthony/Documents/My Games/FarmingSimulator2019/mods/FS19_RM_Seasons/src/economy/SeasonsEconomy.lua (260) : superFunc
2019-10-01 09:58   dataS/scripts/missions/mission00.lua (671) : loadFromXMLFile
2019-10-01 09:58   dataS/scripts/misc/AsyncManager.lua (42) : lambda
2019-10-01 09:58   dataS/scripts/misc/AsyncManager.lua (119) : runLambda
2019-10-01 09:58   dataS/scripts/misc/DeferredLoadingManager.lua (39) : runTopTask
2019-10-01 09:58   dataS/scripts/main.lua (1839) : update
2019-10-01 09:58   Error: Index not found: 5|18|7
2019-10-01 09:58   Error: Failed to find child 0 from node Trigger74, only 0 childs given

CP Error:
2019-10-01 10:00 Error: Running LUA method 'update'.
2019-10-01 10:00 dataS/scripts/vehicles/specializations/Plow.lua(680) : attempt to compare number with nil

AI Turn in Advanced Settings on or off ? Vanilla Tools ? Wich one is it ?

**Comment by pvaiko** [comment] 2019-10-01 15:57
Duplicate of #4240, come on people, use the search before posting an issue.

**Closed by pvaiko** 2019-10-01 15:57 UTC
Labels: More Information Required
