### ISSUE TITLE
Tractor not unloading at grain silo

### ISSUE THREAD

**Issue by kbrandwijk** [Courseplay/courseplay#4327] opened 2019-10-04 02:14 UTC
I just started using Courseplay, so maybe I'm doing something wrong. I set up a simple tractor route in combine mode. Everything works correctly, it empties the combine, it drives the route, and at the unloading point, it starts unloading.

The problem is, it doesn't actually unload. I see it tipping to the side, I see the corn streaming out, but it doesn't empty. I have to rapidly click 'stop unloading' and 'unload' to _actually_ unload.

It doesn't matter where I put the unloading point. It pretends to unload, but doesn't do it until I toggle unloading off/on.

**Comment by Tensuko** [comment] 2019-10-04 06:31
duplicate of #3953
Can you post your logfile there with debugchannel 1 and 2 active and what silo you used ? Maybe a Screenshot too.

Closed.

**Closed by Tensuko** 2019-10-04 06:31 UTC

**Comment by Merrlin** [comment] 2019-10-04 12:30
Small Addition: if you unload on a Grainsilo you have not to put there an Unload Point, it recognizes by self... Unloadpoint is just needed if you want to tip on Ground where is no trigger.
