### ISSUE TITLE
LevelCompactAIDriver.lua:208: attempt to index a nil value

### ISSUE THREAD

**Issue by MADxHAWK** [Courseplay/courseplay#4207] opened 2019-09-07 02:16 UTC
I ran in this error while i had a tractor compacting a silo when another vehicle arrived to unload. 
The compactor vehicle drove to its wating position and didnt start again after the other vehicle have unloaded. 
CP Version: v6.01.00294
I had some logs running buy surprise and thats what i got:

2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):updateCollisionVehicle:
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):  checking CollisionIgnoreList for 262735
2019-09-07 03:50 :37 [dbg3 lp317934]   is on local list ->ignore
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):  checking CollisionIgnoreList for 262864
2019-09-07 03:50 :37 [dbg3 lp317934]   is not on CollisionIgnoreList
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):  checking CollisionIgnoreList for 4139924
2019-09-07 03:50 :37 [dbg3 lp317934]   is not on CollisionIgnoreList
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):  checking CollisionIgnoreList for 4139925
2019-09-07 03:50 :37 [dbg3 lp317934]   is not on CollisionIgnoreList
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):  checking CollisionIgnoreList for 4139923
2019-09-07 03:50 :37 [dbg3 lp317934]   is not on CollisionIgnoreList
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3):  checking CollisionIgnoreList for 4139926
2019-09-07 03:50 :37 [dbg3 lp317934]   is not on CollisionIgnoreList
2019-09-07 03:50 :37 [dbg3 lp317934] S374 (#3): updateCollisionVehicle: vehicle.cp.collidingVehicleId is nil
2019-09-07 03:51 Error: Running LUA method 'update'.
2019-09-07 03:51 C:/Users/**********/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/LevelCompactAIDriver.lua:208: attempt to index a nil value

**Comment by Tensuko** [comment] 2019-09-07 05:19
duplicate of #4198
Closed.

**Closed by Tensuko** 2019-09-07 05:19 UTC
