### ISSUE TITLE
"The work tool needs to be refilled" even when the tool is full (spraying herbicide with Deltis 1302 and PF 1500)

### ISSUE THREAD

**Issue by jgbijlsma** [Courseplay/courseplay#5109] opened 2020-03-25 14:47 UTC
Issue found with the seasons mod on the map Oakfield Farm. Have not tested on vanilla FS and on other maps.

**Comment by Tensuko** [comment] 2020-03-25 14:48
And no logfile...

**Comment by polosubtil** [comment] 2020-03-26 19:17
Hi @Tensuko ,
I play with the same map and something strange is happening now with version v6.01.00397
I just saw that with the lime spreader but it might happen with other tools too.
At the lime station, the spreader fills up but get "stuck" at the end of the filling. It's like the tarp is closing/opening very quickly
![fsScreen_2020_03_26_20_11_56](https://user-images.githubusercontent.com/60451845/77687397-9dbac380-6f9e-11ea-8851-a7ad98dd387b.png)
My log file but I guess I should do it again with some channels on, please advise !!!
[log.txt](https://github.com/Courseplay/courseplay/files/4389454/log.txt)

**Comment by Tensuko** [comment] 2020-03-26 19:24
I see a lot of Silos there, so also a lot of Triggers.
A Video could help more and also a Screenshot with show Triggers (press F5 once on the keyboard).

**Comment by Friendlyx** [comment] 2020-03-27 09:45
I have the problem also that cp says it needs to be refilled for example with the unimog from FBM when it has a Fillvolume configured. If I have the Bale platform installed. there is no problem. So maybe the problem is if you have any fillable things on your tractor it might conflict with cp.

**Comment by polosubtil** [comment] 2020-03-29 18:50
Hi @Tensuko 
You were right, this course is a new refill course through the farm and it was probably is a little bit too far away from the lime station and probably creates confusion with the other fill stations
So I changed a little bit the course on the left hand side and it works fine again. Sorry about that

I don't understand what you asked with F5, it doesn't trigger anything on my screen.

**Comment by Tensuko** [comment] 2020-03-31 04:55
Normaly it should show Triggers and Collissions but when its solved for you its fine. :)

**Comment by Tensuko** [comment] 2020-03-31 04:56
Ok but the actual Issue is not solved... thats why it is better to make extra Issues...

Still wait for a logfile...

**Comment by Tensuko** [comment] 2020-04-05 17:06
Closed due to inactivity.

**Closed by Tensuko** 2020-04-05 17:06 UTC
Labels: waiting for logfile
