### ISSUE TITLE
Grain Transport not loading from Silo automatically

### ISSUE THREAD

**Issue by juninholiveira** [Courseplay/courseplay#4920] opened 2020-02-11 01:02 UTC
I made a route from my silo to Restaurant (the selling point of grain). But my tractor don't load from the silo, it just stops under the output of Silo and waits for the user to manually click R and choose what to load. Then it follow the route as expected and unloads in the selling point normally. But it returns to the Silo and again stops forever under the output waiting for user Input.

Edit: I'm having the problem in Multiplayer. Didn't test in Single Player.

![Untitled-1](https://user-images.githubusercontent.com/10757100/74204193-ec133d80-4c50-11ea-80bb-cb2371ab42e0.jpg)

**Comment by Tensuko** [comment] 2020-02-11 06:23
Duplicate of #4778

Closed.

**Closed by Tensuko** 2020-02-11 06:23 UTC
