### ISSUE TITLE
Input bindings mode9 crash

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#2867] opened 2018-09-18 18:56 UTC
Hello,
Could you help me with this problem? (see my log)
I removed all the mods because I thought it came from there, but I still have the problem, even without the mods. The game crashes and I have to force the stop.
Thanks.

attached, my log:
https://pastebin.com/EN8qRfAg

**Comment by AndyK70** [comment] 2018-09-19 12:31
Does this happen, if you use a Giants standard map?
The first errors appear loading the map Clover Creek.

**Comment by KITT3000** [comment] 2018-09-19 14:28
@AndyK70 Some of the errors are caused by this #2729, there are no keys added to modDesc, which were entered in lines **800-810** in the `base.lua`

**Comment by pops64** [comment] 2018-09-19 17:51
That is what I would assume to be the problem is the push for mod 9 hot keys has no default keybinding. And has no nil handling. So if we could fix that and push. I will look it over. I will be back by tomorrow afternoon EDT.

To OP has stated beforehand please post log in gist or pastebin which I have gone ahead done for you. It makes it easier and cleaner to read the issue thread. Has for fixing you issue in the short term please add key bindings to the missing CP keybindings and that should fix the issue

**Comment by Crinouche** [comment] 2018-09-20 06:54
Hello,
Thank you for your answers.

AndyK70:  I don't know if the problem is the same on a map Giants. I have not played on it for a long time. Knowing I've been playing Clover Creek for a long time and I did not have that problem before.

pops64: what do you mean by: "Has for fixing you issue in the short term please add key bindings to the missing CP keybindings and that should fix the issue"
What do I have to do exactly?

Sorry for my bad English
thank you in advance

**Comment by AndyK70** [comment] 2018-09-20 09:18
> 
> 
> @AndyK70 Some of the errors are caused by this #2729, there are no keys added to modDesc, which were entered in lines **800-810** in the `base.lua`

Right, the bindings are added as option without defining default keys. That's done because keybindings are a rare good in LS and not everyone uses this functionality. So if one wants to use shovel positioning by keys he/she has to add the keys by oneself in the options.

One thing @pops64 is right, there's no nil handling, which I assume can lead to errors if no binding is set. I'll have a look at this.

@Crinouche  I think pops64 is confusing _has_ and _as_, he likes to say "As this is so and so, ..." but swaps _as_ erroneously with _has_. So he is saying you should assign keybindings to the CP shovel positioning commands in the options.

**Comment by pops64** [comment] 2018-09-20 13:49
:P yes I do tend to just say as instead has. Has I can't really remember which one to use when. What you need to do is look through your keybindings in the settings page and scroll down to the CP section. And ensure each one has a key binding the blank ones are the ones mostly likely causeing your error

**Comment by pops64** [comment] 2018-09-20 18:17
Should be fixed in version 17 or higher

**Comment by pops64** [comment] 2018-09-23 13:52
From other issue https://pastebin.com/embed_js/5HszYkLA

**Closed** 2018-09-23 14:02 UTC
Labels: bug
