### ISSUE TITLE
Pathfinding to forage harvester keeps failing

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#6915] opened 2021-02-26 16:16 UTC
My tractors have troubles finding a path to the forage harvester, at first I thought it was only on the headlands, but now it's happening even when the harvester is close to the tractor and there is no crop in between. like in the following screenshot
![20210226171242_1](https://user-images.githubusercontent.com/21219044/109325301-0ddc6400-7856-11eb-9325-b2cb83b21ad4.jpg)
After I send both tractors of it started working again for 1 tractor, but the other one can't find a path
log:
[log.txt](https://github.com/Courseplay/courseplay/files/6050907/log.txt)

**Comment by Tensuko** [comment] 2021-02-26 16:36
We need a logfile with debugchannel 4, 7, 12 and 14 active, let it run for a while and attach that logfile.

**Comment by Quintto** [comment] 2021-02-26 16:46
here you go, I already tried switching tractors around the 718 is on the green trailer thats having trouble now, the xerion is doing just fine : [log.txt](https://github.com/Courseplay/courseplay/files/6051092/log.txt)

**Comment by pvaiko** [comment] 2021-02-26 19:31
Likely a duplicate of #6832, that modded trailer's size is too big.

You can check the size with the console command gsVehicleDebugAttributes and then pressing F5 twice.

Reopen if that's not the problem.

**Comment by pvaiko** [comment] 2021-02-27 12:04
It isn't a duplicate, the trailer is fine.

**Comment by pvaiko** [comment] 2021-02-27 12:10
> here you go, I already tried switching tractors around the 718 is on the green trailer thats having trouble now, the xerion is doing just fine : 

Can you explain please, what this means with the 'green trailer'? Is there a specific trailer you are having problems with? If yes which one (link to a non-malware site)?

**Comment by Quintto** [comment] 2021-02-27 19:43
the green trailer I'm using is the one in the screenshot, the Reisch RTWK 200 AS 700  https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=185869&title=fs2019 

just to rule the size out I did look at the gsVehicleDebugAttributes and that looks fine, it's a little bigger but not as bad as the upfit in #6832 
![20210227203909_1](https://user-images.githubusercontent.com/21219044/109398266-27f07200-793c-11eb-8050-e493b25c5ae1.jpg)

**Comment by pvaiko** [comment] 2021-03-27 22:55
Should be fixed by 6.03.00052

**Closed by pvaiko** 2021-03-27 22:55 UTC
Labels: Mode2/Mode3
