### ISSUE TITLE
Cannot generate course

### ISSUE THREAD

**Issue by realm174** [Courseplay/courseplay#5760] opened 2020-07-19 18:36 UTC
Courseplay 5.02.00040
Map: MVP19

Firstly, it seems that some fields are not scanned. For example, field 15, player owned, does not get automatically scanned.  It can be added manually with the "Calculate currentl field's edge path" option however... 

Secondly, when attempting to generate a field, I come across the following issues:  When adding headlands, regardless the the number of headlands I select, after drawing the headlands (up to a maximum of 7) I get a message saying "Course generated successfully but due to the current direction settings it may cause issues when driving".

If I select no headlands at all, I get the same message, however, no waypoints were added to the course.

So what it seems to be here is that I can only generate headlands, but no up and down are generated.

Note that the fields on this map are quite large.  Am I possibly hitting the maximum number of waypoints maybe? This is what the field looks like. So not a square field, and big.

![image](https://user-images.githubusercontent.com/7480440/87882161-65ab1680-c9bb-11ea-813f-0494ead7e547.png)

And here are the generator settings:

![image](https://user-images.githubusercontent.com/7480440/87882127-41e7d080-c9bb-11ea-8756-101fadfb9dd2.png)

And this is after generating the course:

![image](https://user-images.githubusercontent.com/7480440/87882285-4fea2100-c9bc-11ea-9e97-f9136908019d.png)

Total waypoints: 8856.  So I know I am not reaching a maximum as I have other fields that got many more waypoints than that (17k+).

Any idea what might be happening?

**Comment by Tensuko** [comment] 2020-07-19 21:00
There must be something wrong with your Fieldborder, at least it looks like that.
Post Fielddefinitions and create the course with logfile 7 active and post that logfiel.
For Fielddefinitions, take a look at this:
https://github.com/Courseplay/courseplay/wiki

**Comment by realm174** [comment] 2020-07-19 21:33
Had to zip the cpFields so i could upload it here.
[cpFields.zip](https://github.com/Courseplay/courseplay/files/4944700/cpFields.zip)

[Log file](https://pastebin.com/wxW4MZJ8)

**Comment by pvaiko** [comment] 2020-07-21 20:24
1. if not all fields are scanned that is almost certainly an issue with the map, usually caused by not enough gap between the adjacent fields.
2. CP will stop adding headlands when they start to overlap, like the NW corner of your field.
3. looks like the generation without bypass island was successful.
4. I hate to say but our course generator has problems with such an irregular (and, what's even worse, concave) field with so many islands and nooks. Even without island  bypass, we had to split the field into 17 blocks and use the genetic algorithm to find the best sequence working on them. With the island bypass it is 41 blocks and we just give up. If you can you can play with this limit in https://github.com/Courseplay/courseplay/blob/df01d55707b9a0711eef2a2da89677e7b4b22690/course-generator/center.lua#L279 (it is currently set at 30), and set it to 50 and see what happens. You can also experiment with manual directions. 

So no, we won't fix this any time soon.

**Closed by pvaiko** 2020-07-21 20:24 UTC
