### ISSUE TITLE
Tractor doing circles when turn speed too high

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4370] opened 2019-10-14 07:46 UTC
Pathfinding turned off.
Turn on field turned off.
Auto turn radius.
With default ingame tractor its even worse, it will do 2-3 circles then continue forward to the fence.

I can reproduce it always if you need some logs to fix it ?
https://youtu.be/ueUDvCs1k3s

**Comment by Tensuko** [comment] 2019-10-14 10:59
AI Turn active ? See advanced Settings.
Also logfile with debugchannel 9 12 and 14 active.

**Comment by bojanh66** [comment] 2019-10-14 11:32
[log.txt](https://github.com/Courseplay/courseplay/files/3724190/log.txt)
https://youtu.be/rX232iuKMWA
Yes, AI Turn is active.

Auto turn is 10m, if i increase it to 14-15m its a little better, but i would like to keep auto turn radius, because of other implements.
Only way to fix this is to create course with 2 headlands or experiment with different up/down rows position.

**Comment by pvaiko** [comment] 2019-10-14 12:26
And try slowing down in that turn, 15 km/h is way too fast. I'm pretty sure this is because of the fix for #4308 as now the Giants speed adjustment does not kick in anymore. I think I'll force the turn speed to 10 km/h or less...

**Comment by pvaiko** [comment] 2019-10-14 12:28
@bojanh66 yeah, case pretty clear. Slow down.

**Comment by bojanh66** [comment] 2019-10-14 12:44
Wow, yes, turn speed 10km/h instead of 15km/h fixed this turn.
But in 99% courses and turns, i can use 15km/h, even higher speed without any problems.
Only on sharp turns like this its required to use 10km/h.
Some implements like mowers or balers have working speed of 20-25km/h and it feels very slow when tractor aproaches turn corner and lower the speed from 20-25 to 10km/h so i tried to keep it as high as possible, while still able to maintain the turn without issue.
Is it possible for Courseplay to calculate speed for sharp turns like this and lower the speed to 10km or less, while keeping 15km/h for normal rounded turns ?
Ty for your help.

**Comment by Woife1** [comment] 2019-10-14 16:27
The Holmer Roder didn't get the waypoints by driving backwards and try it in circles to get it

**Comment by pvaiko** [comment] 2019-10-21 01:15
Duplicate of  #4370, #4407, #4409

**Closed by pvaiko** 2019-10-21 01:15 UTC
