### ISSUE TITLE
Driver get stuck in traffic without traffic

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3187] opened 2019-02-10 10:00 UTC
Using cp version .00055, RAVENPORT, no mods, FENDT 1050 and trailer JOSKIN. 

Started course mode 1, cp calls "cp driver stucks in traffic. But there is no traffic. 

![bildschirmfoto 2019-02-10 um 10 53 57](https://user-images.githubusercontent.com/24283753/52532313-f8557980-2d22-11e9-9bb2-e067c1875aa6.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2848722/log.txt)

I got a bit creasy: 
Testing JOHN DEERE and KRAMPE the same course worked: 
![bildschirmfoto 2019-02-10 um 11 06 46](https://user-images.githubusercontent.com/24283753/52532368-43bc5780-2d24-11e9-91b1-6110495d865d.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2848731/log.txt)

**Comment by Karlshoj** [comment] 2019-02-10 10:19
I switched back to v54 for the same reason

**Comment by tjBerlin** [comment] 2019-02-10 10:25
Where can I finde a copy of v54? Didn't save mine...

**Comment by Karlshoj** [comment] 2019-02-10 10:33
Here you are
[Courseplay.zip](https://github.com/Courseplay/courseplay/files/2848743/Courseplay.zip)

**Comment by Karlshoj** [comment] 2019-02-10 10:36
Got it?

**Comment by tjBerlin** [comment] 2019-02-10 10:50
Yes! Thanx!

**Comment by pvajko** [comment] 2019-02-10 12:27
Wish I could reproduce this. Do you have a savegame for me?

**Comment by pvajko** [comment] 2019-02-10 12:50
And the course, of course....

**Comment by tjBerlin** [comment] 2019-02-10 12:56
Yes:

[savegame4.zip](https://github.com/Courseplay/courseplay/files/2848872/savegame4.zip)

It should be course #10 
[MapUS.zip](https://github.com/Courseplay/courseplay/files/2848874/MapUS.zip)

**Comment by Messy71** [comment] 2019-02-10 13:00
i think it get’s the front of the parked car in that corner of the bga. same happened to me but i was driving straight to it and also had traffic off.

**Comment by alpha117** [comment] 2019-02-10 13:30
Same issue here. Planter get empty, then I get this
![image](https://user-images.githubusercontent.com/30005040/52534305-d31f3600-2d37-11e9-827b-078819cbed6f.png)
I have a refill course also appended, not sure if that is the issue?
[log.zip](https://github.com/Courseplay/courseplay/files/2848906/log.zip)

**Comment by pvajko** [comment] 2019-02-10 14:05
@tjBerlin ok, I see what the problem is. In the meantime, you can work around this by selecting a different mode (transfer for example) and then mode 1 again, then it'll start.

**Comment by tjBerlin** [comment] 2019-02-10 14:11
Thanks!

Von meinem iPad gesendet

**Comment by pvajko** [comment] 2019-02-10 15:32
Try with 57.

**Comment by alpha117** [comment] 2019-02-10 15:59
#57 in my field situation, still get 'stuck in traffic'

**Comment by pvajko** [comment] 2019-02-10 16:02
@alpha117 get me a log with debug channels 12 and 14.

**Comment by Martinnygaard** [comment] 2019-02-10 16:05
I have the same problem. Case IH Optum with Horsch Pronto 9 gets "stuck on trafic" on refill route.
Changing mode does to transport (or any other) and back to seeding does not help me.
<blockquote class="imgur-embed-pub" lang="en" data-id="a/NzJq5zk"><a href="//imgur.com/NzJq5zk"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Martinnygaard** [comment] 2019-02-10 16:06
Picture: https://imgur.com/a/NzJq5zk

**Comment by pvajko** [comment] 2019-02-10 16:08
@Martinnygaard as I said, version 57. You are running 56.

**Comment by alpha117** [comment] 2019-02-10 16:19
debug channels 12 and 14
![image](https://user-images.githubusercontent.com/30005040/52536201-4aac8f80-2d4f-11e9-8328-7db36a53439e.png)
[log.zip](https://github.com/Courseplay/courseplay/files/2849095/log.zip)

**Comment by tjBerlin** [comment] 2019-02-10 16:21
Tested the same course with .00057 and it worked perfectly! Thanks for that. 

But I found a new one, I will open a new issue! 

BTW: Great work! I love cp.

**Comment by tjBerlin** [comment] 2019-02-10 17:41
Hit the wrong Button, didn‘t want TI close this. Sorry @alpha117

**Comment by Messy71** [comment] 2019-02-10 17:51
@alpha117 / @pvajko i think it reacts different when you have two combined modes
same for @Mannelig83 in issue #3196 / @tjBerlin in issue #3193

**Comment by pvajko** [comment] 2019-02-10 18:01
The original issue is solved, so closing this and reopening the other one.

**Closed by pvajko** 2019-02-10 18:01 UTC
Labels: waitingForUserAnswer
