### ISSUE TITLE
Working with harvesters

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#7169] opened 2021-05-03 05:42 UTC
Possibly this is a problem of the combine and the truck itself, but it is still a problem.

The truck sometimes chooses the wrong trajectory when approaching a load, which leads to a collision.
[log.txt](https://github.com/Courseplay/courseplay/files/6412992/log.txt)
![1](https://user-images.githubusercontent.com/65189100/116844328-7dbaf200-abeb-11eb-9cdc-f52f70045c39.jpg)
![3](https://user-images.githubusercontent.com/65189100/116844330-7eec1f00-abeb-11eb-9723-e0380e95b02f.jpg)

**Comment by Tensuko** [comment] 2021-05-03 06:07
Increase turn radius might help.

**Comment by Tocik** [comment] 2021-05-06 20:09
I tried a wide turning radius, different harvesters and cars, but sooner or later I come to this result.


![1](https://user-images.githubusercontent.com/65189100/117359389-02459300-aec0-11eb-8e32-4c8ae4d7ac13.jpg)

**Comment by Tensuko** [comment] 2021-05-07 09:25
I will do some tests on this.

**Comment by Tensuko** [comment] 2021-05-07 10:52
This is a bit tricky, we will see if there is something we can do about this.

**Comment by Tensuko** [comment] 2021-05-12 05:03
Try Version 6.03.00059 or higher and report.

**Comment by Marisolaa** [comment] 2021-05-15 12:22
I just wanted to add to the chorus. My issue seems primarily with the ManTipper, a tractor/semi with trailer at least gets banged out of the way just enough. Turning radius doesn't change it. It's especially angry (as in almost each time, approx 95%), handily reproducible) when at the end of a field and the combine calls for unloading. Avoid fruit and/or turn on field enabled or disabled - same result. It appears to my dumb blonde brain that this is some sort of boundary issue between the combine calling and what/when trailers show up. It's identical to OPs pathing and issue. I updated Courseplay 12 hours ago, the problem is actually worse for my play as it's happening each pass within 2 rows of a border (or the width of two rows after making the uuee).

**Comment by Tensuko** [comment] 2021-05-15 15:47
when at the end of a field and the combine calls for unloading

end of field or end of the course ?!

**Comment by Marisolaa** [comment] 2021-05-15 16:47
End of each row on the field - any borders to the plot at all where the combine calls for emptying.

Going to load up and look at percent versus call versus the border. It occurred to me a few minutes ago, that it may be calling for emptying and then the combine goes from row 1 to row 2. Since it's off the plot, the trailer goes wonky? I'll report back when I get done.

**Comment by Tensuko** [comment] 2021-05-15 17:31
Don't have this happen, when we go to the next row we chack if pipe will be in the fruit so we don't even try to unload.
Avoid Fruit active on both, combine and unloader.

**Comment by Marisolaa** [comment] 2021-05-16 14:29
Okay, so, I can reproduce this in the following manner on two different maps:

Any combine, any single harvest fruit. (In other words - canola, wheat, etc. have NOT tested on any convoys or other fruits).
Any trailer, "one piece", semi with tipper or tractor with large trailer.

When the combine is between 51 and 53% as it comes to the end of the row, it keeps moving. It causes any mod or vanilla trailer/tractor combo I have to bug out IF it is called when the combine is on the end of the row and the trailer arrives AFTER it has already straightened out and began moving on the next row. In modded trailers like the ManTipper or my modded semi with trailer, it causes a full lag out and stutter until it gets stuck and gives the warning or the combine pushes it out of the way. It more often than not does NOT trip a warning. When it doesn't trip a warning, the stutter gets worse and worse until it goes into the fruit and you have to click stop driver to end the stutter.

Here are two screens from the exact same time on two different fields. One has tripped the stuck warning, the other has not. The modded ManTipper is giving the warning in this case, the vanilla isn't.
![FSCS2](https://user-images.githubusercontent.com/51178939/118400786-1d876f80-b631-11eb-8890-c013b6d55883.png)

![FSCS1](https://user-images.githubusercontent.com/51178939/118400783-1c564280-b631-11eb-9782-0d381d0b1190.png)

**Comment by Marisolaa** [comment] 2021-05-16 16:46
Another possible piece, unsure if it's related but almost seems like it should be since the other issues are at the same time in pathing, in this SS, you can see though avoid fruit is on, the combine is confused as to what to do. It made the turn, the trailer came very late, it made the turn but didn't want to get out of the fruit, it drove over it then sat. No messages other than it needs to be unloaded.

![fscs3](https://user-images.githubusercontent.com/51178939/118405170-7dd3dc80-b644-11eb-81ea-c2b99e720604.png)

**Comment by Tensuko** [comment] 2021-05-17 04:27
You have avoid fruit off and what did I say ? Avoid fruit = on!

The not continue harvest is mostly when there is a peace of wrong fruit on the way.

**Comment by Marisolaa** [comment] 2021-05-17 06:03
What did I say? It happens whether it's **on OR off**. It pushes the trailers into the fruit after it moves to the next row, in the last photo, you can see the start of the row it tried to avoid and gave up. With avoid fruit on, it steered the tractor into fruit then stopped moving altogether.

I don't know any other way to phrase it. On, off, on either the combine OR the trailer, this happens at the end of rows when the trigger percent is reached.

**Comment by Tensuko** [comment] 2021-05-17 10:36
I just cutting down a complete field with avoid fruit on, on **both**, combine **and** unlaoder and have no issue at all!

Do it again with needed debugchannels active (channel 2 and 11).

**Comment by Marisolaa** [comment] 2021-05-18 05:52
I moved on with the field since we were hung up disagreeing on the fruit, I can do it again, but I wanted to share this part. It maybe not the combine at all. When I was tearing things down and replacing the fields for buildings, I was harvesting and leaving it. Despite having my seeder drop early and rise late, it didn't read the borders of the field correctly.  It escaped my attention that the fields with the problem were the same fields until trying to reproduce it and make it very specific. Because I never changed the fruit type and my seeder stays within a few rows of my harvester, I never noticed it. This is the maps pregenerated field, not one user generated/rewrote.

This map is modded, but I've played it for ages and until the CP revamp, never had issues with field reading. Vanilla game hiring doesn't leave this behind.

Because the combine/unloading acted the same as OP with identical pathing, I thought it went here. Now I'm unsure if it's related. It may have been the combine was only reacting to a border bug so it was a symptom, not the cause.

I'll work it some more with debugs on a new save.

![fscp5](https://user-images.githubusercontent.com/51178939/118597231-6991fb80-b77a-11eb-8aa5-101e2af3dfac.png)

**Comment by Tensuko** [comment] 2021-05-18 08:34
Since you don't give any valuable infos, what can I answer here ?
Not even how your course looked like.
I do all my fields without any Issue.

Try use 'raise implement later and lower early' in the adv. settings menu.

Also this got nothing to do with the original Issue. Will close this now.

**Closed by Tensuko** 2021-05-18 08:34 UTC
Labels: waitingForUserAnswer

**Comment by Marisolaa** [comment] 2021-05-18 11:16
I don't know if it's part of the original issue. I was passing along a second possible source for the collision issues. I posted the traces of fruits (which I'm unaware of any other settings to highlight them further for you), not looking for advice.  As I noted in my response - like I had many times when you followed up with telling me to do what I'd already posted I'd done, I HAD those settings and it still isn't reading the fruit right.

**_"Despite having my seeder drop early and rise late, it didn't read the borders of the field correctly. "_**

You keep telling me to try things I've said I already tried.  Now that I know what you needed I could help since I'd read your response as I was posting additional problems on those fields, I had intended on the debug you asked for.  I wanted to give back to fixing something I've enjoyed for some time.

I wasn't looking for an answer, trying to help fix a major CoursePlay breaking bug but since you won't bother with reading what I'm writing, you do you. Close it out and I'll shut it up. Clearly, you wouldn't even bother reading or looking at my debugs either so... enjoy. Good day sir.
