### ISSUE TITLE
HybridAStar.lua error

### ISSUE THREAD

**Issue by SledgeHammer75** [Courseplay/courseplay#4838] opened 2020-01-17 22:30 UTC
still getting this error with 371 while fertilizing/spraying at end of field row:
2020-01-17 23:22 Error: Running LUA method 'update'.
2020-01-17 23:22 C:/Users/Christian/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/course-generator/HybridAStar.lua:613: attempt to index field 'nextEdge' (a nil value)

log with debug 7 and 14, warning 11mb
[log.txt](https://github.com/Courseplay/courseplay/files/4079381/log.txt)

**Comment by bojanh66** [comment] 2020-01-18 09:37
Can confirm, i got this error too, but i have combine mode6, tractor mode6 baling and tractor mode2 overloading at the same time.
2020-01-18 10:26 Error: Running LUA method 'update'.
2020-01-18 10:26 C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00371/course-generator/HybridAStar.lua:613: attempt to index field 'nextEdge' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4080202/log.txt)

**Comment by pvaiko** [comment] 2020-01-18 12:40
duplicate of #4836

**Closed** 2020-01-18 15:48 UTC
Labels: duplicate
