### ISSUE TITLE
Error: Running LUA method 'update'. - AIVehicle.lua(384) : attempt to perform arithmetic on local 'distanceToStop' (a nil value) + Callstack + 'Burn' Money

### ISSUE THREAD

**Issue by Merrlin** [Courseplay/courseplay#4171] opened 2019-08-28 21:45 UTC
Hi together

I had a strange bug right now. I had 2 cultivators (bednar swifter 5M )(vanilla game) in convoy mode running. After setting them on a new field (#10 on NF Marsch ohne Gräben) and starting them quite close together they drove to the first waypoint and the second one starts literally to burn my money. The money burn rate was approximately around 4k€ per second. Because I don't know the right Debug Channel i've created a log with quete all of them. The log is shortened, that means i've cut out the dozens of the repeating error message.

Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AIVehicle.lua(384) : attempt to perform arithmetic on local 'distanceToStop' (a nil value)
Hope that helps.

[log.txt](https://github.com/Courseplay/courseplay/files/3553004/log.txt)

**Comment by Merrlin** [comment] 2019-10-07 20:20
Wasserstandsmeldung meinerseits: Konnte da wegen Zeitmangel noch nicht weitertesten.
ModConflict kann es aber eigentlich nicht sein, weil bis auf die Karte und CP waren ja nur Vannila Geräte beteiligt.

**Comment by pvaiko** [comment] 2020-01-08 12:51
Looks like this can't be reproduced, lua error comes from Giants code, there has been fixes for the wages, closing.

**Closed by pvaiko** 2020-01-08 12:51 UTC
Labels: try to reproduce
