### ISSUE TITLE
rescanning  islands at startup

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2810] opened 2018-07-30 00:53 UTC
hello   i have a problem with a field with island. (on lone oak farm map , with version 5.03.00012)
when i generate course  with an harrow (13 m) work  fine
but when i try to generate with a plow (5,5 m) , coursplay can not create the course when  island detection is active , with different startup position .
i try generate course for multiple (3) plow , i have no error but a waypath bug ( crossing water on  picture).
![fsscreen_2018_07_30_01_32_52](https://user-images.githubusercontent.com/32802279/43372107-6d462872-939d-11e8-9013-421f01a82318.png)

i try  to modify the shape of island  for make it more regular,  but after reloading game for scan field , coursplay don't see  the modification . (i  had very  increase the island's border  for sample on picture).
![fsscreen_2018_07_30_01_56_46](https://user-images.githubusercontent.com/32802279/43372176-462ba400-939e-11e8-8e66-77f5e24e75ca.png).

finally  the only way i have found it's to destroy island with a way to ouside field :
![fsscreen_2018_07_30_02_45_37](https://user-images.githubusercontent.com/32802279/43372661-67a1e52c-93a3-11e8-95f9-a60cf9a898ca.png)
but is not lovely.

it is possible to enable the island modification detection at startup ?

regards

``

.

**Comment by pvajko** [comment] 2018-07-30 01:53
Could you set debug channel 7, try to generate with the 5.5m plow and post the log (see https://github.com/Courseplay/courseplay/wiki)

**Comment by pvajko** [comment] 2018-07-30 02:13
Also, on the first screenshot, did you generate that with the 'Simple' or 'Circle' island avoidance settings? Looks like Simple to me. Have you tried Circle?

**Comment by pops64** [comment] 2018-07-30 09:19
Also the field scanning tool does not detect island, island detection is done when the course is created so you would see no change in island shape till course is created

**Comment by pvajko** [comment] 2018-07-30 16:02
Next time please use Gist or Pastebin as described in the wiki to upload content.

Anyway, this is the same issue as #2767. With three fields merged, three islands and all those little nooks, the generator needs to split the field at least into 12 blocks which is over the (rather arbitrary) limit of 10. You can try the solution I suggested there to see if it helps, just delete this line:
https://github.com/Courseplay/courseplay/blob/ac536b5e2ea7aaa72965d85015de261676dc2c82/course-generator/center.lua#L198

Let me know if that works, I may then increase that limit of 10 a bit.

**Comment by magicmana** [comment] 2018-07-30 18:59
hello.
after change,  now  i can  create a course with a single plow , with no error during the creation.

but  i  have the same problem  on the west of the island.


![fsscreen_2018_07_30_19_27_51](https://user-images.githubusercontent.com/32802279/43414282-a0b73fa8-9432-11e8-8432-a162a2d04b61.png)

![fsscreen_2018_07_30_19_21_12](https://user-images.githubusercontent.com/32802279/43414307-b2248d5e-9432-11e8-926f-d025030a9ef7.png)


finally  i  try to split in 2 field 

![fsscreen_2018_07_30_20_56_33](https://user-images.githubusercontent.com/32802279/43417439-46c52150-943b-11e8-9ef3-75be11cfca78.png)

and a create a custom field with only the long island 
it s not working i can  not create a custom field with the island
the only way to create  it 's to make a way to outside like this


![fsscreen_2018_07_30_20_48_06](https://user-images.githubusercontent.com/32802279/43417447-4d7f8332-943b-11e8-8129-3250adbd621a.png)

**Comment by pvajko** [comment] 2018-07-30 21:17
Not sure how you modified the map but the problem is caused by this little piece of island sticking out (marked in red):

![2810](https://user-images.githubusercontent.com/2379521/43423907-4859395c-9413-11e8-851b-121d8a91c49c.png)

If you can remove that or smooth it out a bit or make that bay also into an island, it'll work. 

I'm not sure yet if I can really call this a bug in the course generator, this little bulge definitely confuses the algorithm which constructs the perimeter of the island.

**Comment by pops64** [comment] 2018-07-30 23:35
I think it is cause what defines the field to the function(That layer or what ever gets deleted when you remove the field) is bigger than the field by 1/4 of a meter or so. I tried shortening field 36 cause of the gate and I was to lazy to close it and I still had a bulge I just kept running back and forth till it was gone

**Comment by magicmana** [comment] 2018-08-02 08:29
i had  try but  don't work .   i  will stay with the way to  outside .  i dont want  restart map at startup only for this ;-)

**Comment by pops64** [comment] 2018-08-02 14:34
Alright close this out has nothing we can do to fix it. Thanks

**Closed by pops64** 2018-08-02 14:34 UTC
