### ISSUE TITLE
Vaderstad 600  - work tool needs to be refilled

### ISSUE THREAD

**Issue by bullfarmer** [Courseplay/courseplay#3866] opened 2019-06-04 07:31 UTC
hi there,

It comes up when i go to drill that the vaderstad 600 is empty. I have the lastest courseplay. 

Thanks
![fsScreen_2019_06_04_19_22_55](https://user-images.githubusercontent.com/51358240/58859987-30802e00-86ff-11e9-8343-bc7d4acdeff8.png)

**Comment by Tensuko** [comment] 2019-06-04 11:11
https://github.com/Courseplay/courseplay/wiki
logfile needed.

**Comment by ashmills158** [comment] 2019-07-01 21:03
[log.txt](https://github.com/Courseplay/courseplay/files/3347318/log.txt)

I have exactly the same issue. Also with any fertiliser

**Comment by pvaiko** [comment] 2019-07-03 05:07
@ashmills158 this log file has no debug channel activated. We need channel 14.

**Comment by ashmills158** [comment] 2019-07-06 17:13
Please see attached log file with channel 14 debugging activated. 
[log.txt](https://github.com/Courseplay/courseplay/files/3364876/log.txt)

**Comment by pvaiko** [comment] 2019-07-07 18:20
@ashmills158 your issue seems to be related to that Claas Axion tractor which reports no DEF (AdBlue) and no air. Can you reproduce this with a standard tractor?

**Comment by ashmills158** [comment] 2019-07-08 12:28
@pvaiko thank you, using a standard tractor seems to have resolved the issue. I'll have to enable the DEF mod and try refilling the Axion to see if that resolves it for that tractor in particular. Thanks again!

**Comment by Tensuko** [comment] 2019-07-18 10:09
Anything still unclear, or can we close thise one ?

**Comment by ashmills158** [comment] 2019-07-18 11:17
@Tensuko just one thing, what do you mean by "no air"? I also have the Stara self-propelled sprayer (the one that comes with the game) with the same issue, DEF is at 100% too but still says the implement needs refilling?

**Comment by pvaiko** [comment] 2019-07-19 17:54
Open a new one for the Stara.

**Closed by pvaiko** 2019-07-19 17:54 UTC
Labels: waitingForUserAnswer
