### ISSUE TITLE
Game freezes with fertilizer sprayer

### ISSUE THREAD

**Issue by Zibbl** [Courseplay/courseplay#1397] opened 2016-12-01 14:22 UTC
First of all... a big big thank you for courseplay. You guys are awesome and I appreciate your work.
I didnt need to go to work this morning and I just wanted to look at some news here and what did my sleepy eyes see?! CP beta is out, awww yeah ;-) 
Destiny!

Next step in my savegame, grubbern (not plowing (didnt find a translation into english))
Worked very well. After that I wanted to fertilize all fields. I generated a 24 meter course, drove to the end of it, saved it as "A", deleted it, started a new course to my modhub fertilizer and seed tanks, drove back to the start of "A" course and stopped recording the course, saved it as "B". After that I combined course A and B and got my brand new fertilizer course. But when I clicked start the game freezes, cant look around with mouse and controller. Then I stopped the CP helper again, started the fertilizer machine and it worked. But at the end of the course the helper drove into the wilderness somewhere and a tree stopped him.
I fertilized the rest of the fields by my self.

After that, seeding time and I feared the same would happen again, but no, I generated the course as I wrote before, same steps, same route to my modhub fertilizer and seed tanks and voila, worked well.

Does anyone know if I did something wrong with my fertilizer course?

MfG Chris

**Comment by tjBerlin** [comment] 2016-12-01 15:43
I guess "grubbern" means "to cultivator". Maybe?

**Comment by Satissis** [comment] 2016-12-01 17:49
@Zibbl an log would be nice to have, since it normally gives hints to what the problem is.

**Comment by Zibbl** [comment] 2016-12-01 18:26
Yes please, sorry I'm kinda noob in this. By the way, it is field number 12 on vanilla map.

[log.txt](https://github.com/Courseplay/courseplay/files/625457/log.txt)

**Comment by Satissis** [comment] 2016-12-01 18:41
@Zibbl update to 007 and try again. I should have fixed this in the last commit I did. At least for the ridge markers.

There is also an call stack error but I believe that's when you have 3-4 CP drivers active and then closes the game. if that's the reason, I know of it, but it's one of those bugs that's not easy to fine directly, so that one will take some time to find ;)

**Comment by Zibbl** [comment] 2016-12-01 19:21
Now, I've downloaded CP again and copy/pasted it. Not only mode4 007, is it correct?
Still same problem, cp driver doesnt want to start and freezes. Cant move mouse, but right click works and I can fire the driver. Then I can stop the course and mouse works again.

[log.txt](https://github.com/Courseplay/courseplay/files/625552/log.txt)

I dont have 3-4 active drivers, just that fertilizing one and I dont close the game before stopping all workers.

Should I delete any CP folder to test again?

LG Zibbl

**Comment by valdimellen** [comment] 2016-12-01 20:45
Same problem when i try to use i slurry spreader
Log:
https://www.dropbox.com/s/rojfnm1npf6zzh0/log.txt?dl=0

**Comment by Satissis** [comment] 2016-12-01 21:55
@Zibbl you log still says you are using version 004 and not the latest 007
@valdimellen your log says it's using version 006 and not the latest 007

So both of you need to be sure to update it ;)
you can see the version number in the log like this: ### Courseplay: initialized 38/38 files (v5.00.00004)
the 00004 is 004 :)

**Comment by Zibbl** [comment] 2016-12-01 23:31
[log.txt](https://github.com/Courseplay/courseplay/files/625986/log.txt)

Works fine now, thanks for helping me out. But one thing I dont understand...
Why the heck did I need 10-13 tries to get the 010 version?

Vielen lieben herzlichen Dank! So, nun lasse ich Euch erstmal in Ruhe ;-)

**Comment by Satissis** [comment] 2016-12-01 23:38
question regarding your latest log.
how many CP drivers did you have active when quitting the game? or is all those callstack errors from another mod ?

**Comment by Zibbl** [comment] 2016-12-01 23:45
No one was working. I stopped all tasks and closed the game clean.

**Comment by Satissis** [comment] 2016-12-01 23:53
okay. might not be from CpursePlay then.

Regarding the 10-13 tries.... I have no idea why that happened. could be an de-synchronization on github

can we close this now then ?

**Comment by Zibbl** [comment] 2016-12-02 07:15
Yes, problem solved. Thank you!

**Closed** 2016-12-02 12:11 UTC
Labels: waitingForUserAnswer
