### ISSUE TITLE
Fine tuning : 2 multiple tools on the same field - start of each lines

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/courseplay#6210] opened 2020-10-12 09:36 UTC
Context : 
When using 2 tractors equiped with the [LIZARD Untergrundlockerer 6M](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=135840) on the same field thanks to multiple tools option.
One tractor goes left of the course line , the other goes right.

What happened : 
It works really great except at the start of each line when the tractor is heading to the next line, it is aimed at the center of the line (first point of the line) and only after crossing the first point, it is aimed correctly right or left.
This causes small parts of the field not being processed at all.

**Comment by Tensuko** [comment] 2020-10-12 11:46
Screenshot of the course and the problem.
Video would be even better and a logfile pls (channel 14)

**Comment by ruth6t6** [comment] 2020-10-12 17:03
Hi, is english better or german
I had same problem yesterday with plows, different tractors. Generatet course for 2 vehicles, the headlands work fine, one left, one right, but when it comes to the rowas, the drivers drive ecactly to the generated centerline, drive a few meters, and then one turns to the left side of the centrline, the other to the right side. I am not sure since what release it happens.
You want the logfile. I am here the first time.
Can i delete it and it generates a new one, only with the actual problems? When you say channel 14, you mean i have to pull on the button debug channel 14 in courseplay HUD and then after finishing the gamesession i send you the file?

**Comment by ruth6t6** [comment] 2020-10-12 17:33
The logfile attached hopefully, the images show the right driver. The problem exactly occurs not on the very first row, thats still fine, when it turns to the second and so on row, there is the probem, same for the left driver, always upon the end, and from then on all rows that problem.
[log.txt](https://github.com/Courseplay/courseplay/files/5366624/log.txt)
![calculated course](https://user-images.githubusercontent.com/72757592/95774743-46bdd700-0cc1-11eb-8214-31af688f9e4a.png)
![right driver headland start](https://user-images.githubusercontent.com/72757592/95774764-53dac600-0cc1-11eb-86d8-457acad3f1a0.png)
![right driver on first headland](https://user-images.githubusercontent.com/72757592/95774791-648b3c00-0cc1-11eb-9a8d-065f08c527bd.png)
![right driver goes to second headland](https://user-images.githubusercontent.com/72757592/95774815-6fde6780-0cc1-11eb-8fb9-521ddd9565f2.png)
![right driver initial first row works](https://user-images.githubusercontent.com/72757592/95774888-96040780-0cc1-11eb-9582-28fae3277ba7.png)
![right driver starts turning onto ssecond row](https://user-images.githubusercontent.com/72757592/95774902-9f8d6f80-0cc1-11eb-9453-a6005511bafd.png)
![right driver starts second row in the middle](https://user-images.githubusercontent.com/72757592/95774917-a61be700-0cc1-11eb-8417-ff11ba3f77f1.png)
![right driver after a few meters on second row goes right](https://user-images.githubusercontent.com/72757592/95774947-b338d600-0cc1-11eb-9c04-a6721d535440.png)
![right driver finally on correct position on second row](https://user-images.githubusercontent.com/72757592/95774968-be8c0180-0cc1-11eb-9bb6-96b889096a84.png)

**Comment by Lactic68** [comment] 2020-10-12 17:59
Logfile : [HERE](https://gist.github.com/Lactic68/55f7e45cf6f945062c939aa1b6a12886)
Video : [HERE ](https://www.dropbox.com/s/58aui0p6iroy8gv/2020-10-12%2019-47-19.mp4?dl=0)

Issue confirmed on all raws except the very first one which is fine
[log.txt](https://github.com/Courseplay/courseplay/files/5366794/log.txt)

**Comment by ruth6t6** [comment] 2020-10-17 03:31
For Information. I went back to Version .050, ther it works fine.

**Comment by ruth6t6** [comment] 2020-10-17 04:26
Sorry my last comment is incorrect.
The Problem is Mode 4 sowing works, but mode 6 field work (plowing) thats the Problem mentioned above.
At this time, i am not sure if this is the exact Problem in Version 066. I will check again Version 066, if there is also the difference between Mode 4 and Mode 6.

**Comment by Tensuko** [comment] 2020-10-19 05:52
There is a difference between any Tools and a Plow and your tool abouve is handled like a plow becouse the Modder said it is a plow (wich it is actually not...)

**Comment by ruth6t6** [comment] 2020-10-19 14:38
So Do You think i shall try the same situation with an original plow?
When You Are right a course with to combines should work? Field work. Shall i try it? And tell you how it was?

**Comment by Tensuko** [comment] 2020-10-19 15:00
Try a vanilla plow, yes.

**Comment by Lactic68** [comment] 2020-10-19 17:09
Hi,
Same issue with a vanilla plow. Very first row is ok but very start of next rows have some misalignement.
Video : [here](https://www.dropbox.com/s/ki83pe4a5efs7rt/2020-10-19%2019-03-59.mp4?dl=0)
Log : [here](https://www.dropbox.com/s/7qqkk3dy0yshb7f/log.txt?dl=0)

**Comment by ruth6t6** [comment] 2020-10-19 18:20
I tried it not with a plow.i dont know the english word it is something like a plow, in german Tiefenlockerer, also mode 6, and that worked ok.

**Comment by ruth6t6** [comment] 2020-10-19 18:24
[log.txt](https://github.com/Courseplay/courseplay/files/5403922/log.txt)
![fsScreen_2020_10_19_19_43_34](https://user-images.githubusercontent.com/72757592/96496018-f9091780-1248-11eb-9ac7-2e5a3b6e40e8.png)
![fsScreen_2020_10_19_20_13_19](https://user-images.githubusercontent.com/72757592/96496027-fc9c9e80-1248-11eb-8d9e-11e43667edfd.png)
![fsScreen_2020_10_19_20_13_25](https://user-images.githubusercontent.com/72757592/96496050-058d7000-1249-11eb-86fd-904b04330f3b.png)
![fsScreen_2020_10_19_20_15_28](https://user-images.githubusercontent.com/72757592/96496065-0c1be780-1249-11eb-82d4-33fc8d947ed2.png)
![fsScreen_2020_10_19_20_16_09](https://user-images.githubusercontent.com/72757592/96496089-14742280-1249-11eb-898d-94d1b87ba2f2.png)

**Comment by Tensuko** [comment] 2020-10-19 19:02
Das ist auch kein Wunder.
Ein Tiefenlockerer wird wir alle anderen Tools benutzt die symetrisch sind. Ein richtiger Pflug hat eine Eigenbehandlung was die Wendekanöver usw an geht.

**Comment by Wrang22** [comment] 2020-11-02 06:39
I also have this issue.  What is the fix for this?  I use https://www.modhoster.de/mods/horsch-cruiser-12xl-oy#description.
From what I can work out we can only use tools that are real plows or this will never work correctly.
What changed and when?

**Comment by Tensuko** [comment] 2020-11-25 10:39
Is this even still valid with actual version ?

**Comment by Lactic68** [comment] 2020-11-25 15:52
@Tensuko Issue is fixed for me, thank you for your actual build (6.03.00001).

**Closed** 2020-11-25 16:02 UTC
Labels: waitingForUserAnswer

**Comment by ruth6t6** [comment] 2020-11-26 16:35
For me the Problem is not sollen. I work with a modded plow, kind a grubber, and still not working. I know the differenz about real plow and modded plow. Will it work anytime with these modded things or neuer?

**Comment by ruth6t6** [comment] 2020-11-26 16:35
Never

**Comment by Tensuko** [comment] 2020-11-26 17:20
The way that one is modded, nope, we won't add some special handling for a single plow
