### ISSUE TITLE
Problem with ai traffic and lateral distance

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/courseplay#3118] opened 2019-02-04 04:01 UTC
I downloaded the version 6.01.00037, which was released on 04.02.2019, and I noticed two things:

1. The lateral distance is not calculated correctly. The pipeis located just on the left wall of the trailer. It must be set more 1 meter laterally distance
2. It seems that the tractor drives without problems to the unloading point, but when driving back to the field messes up the AI traffic.
It is known that the helper brings the AI traffic to a halt when the AI traffic passes the field to be processed.
The same thing happens, however, when the tractor, which runs courseplay, returns from the unloading point. Even the AI traffic in front of him stops and the courseplay tractor blocks itself

translated with google translate

**Comment by pvajko** [comment] 2019-02-04 14:49
1 is duplicate of #3002. 2 is duplicate of #3015. 

Before opening an issue please check if there's one open already.

Also do not mix two completely different problems in one issue.

**Closed by pvajko** 2019-02-04 14:49 UTC
