### ISSUE TITLE
fieldwork turning broken in 030

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1492] opened 2016-12-11 14:55 UTC
windrower and balers instead of making the turn, drives straight and off into the wild yonder forever..

https://gist.github.com/sootysax/b9a5c8233fa2f7ae624dae4655bb77f7

https://dl.dropboxusercontent.com/u/36294746/2016-12-11_100143209.mp4

**Comment by gec100** [comment] 2016-12-11 15:01
i can confirm that

**Comment by Satissis** [comment] 2016-12-11 15:04
hmmm I'll have an look into that

**Comment by Satissis** [comment] 2016-12-11 15:33
I just had an look at it, to see if I could reproduce it, but I cant.

Could you try detach the implements, clear the course, reattach again and load the course again and try again ? (That have some times cleared the problem when I have mad an change)

**Comment by sootysax** [comment] 2016-12-11 16:16
it's been happening on the second turn for me

**Comment by Satissis** [comment] 2016-12-11 17:14
Still not able to reproduce it. I have even let it run for several turns, both with the baler and a windrower.
I have also tested in both N<->S and E<->W direction setup

**Comment by mereman** [comment] 2016-12-11 18:26
I had a similar problem with a seeder using CP v029. It was the end of a row almost empty of seed. This happened twice if I put it on the same row, I moved it to the start of the next row and it's been fine since.

**Comment by sootysax** [comment] 2016-12-11 18:35
it seems to be due to my manual setting of 6m turning radius (which was giving me perfect little turns in the past).  it seems to not even try the 6m turn and just go straight.

**Comment by Satissis** [comment] 2016-12-11 18:58
alright. I'll look into that tomorrow.
I'm taking the rest of the evening off, just to get a bit of free time as well :) also it's workday tomorrow ;)

**Comment by pops64** [comment] 2016-12-12 03:08
I seem to be getting this issue as  I thought it was a problem with version 31. I just ran into this issue.  I have turn on field enabled. 1 Headland,  First turn maneuver it just kept driving off field. Update later with log and video. Had premium integral II slurry tank.

**Comment by gec100** [comment] 2016-12-12 05:26
here's what i've tested: 
- still have the problem with CP v031.
- if i roll back CP to version 028, problem is gone.
- if i create a new game with CP v031 problem is also gone.
...

will do some more testing

**Comment by pops64** [comment] 2016-12-12 07:57
I don't know how starting a new game fixed this. I tried it as well did not work. @Satissis I messed around with the code a bit and it seems `turnInfo.zOffset = abs(turnInfo.zOffset);` Is still important to something in the wide turn maneuver. I moved it from 235 to 191. And it made it work for turn on field and turn off. I undid this and changed  Line 540 to `if (abs(turnInfo.zOffset) + turnInfo.turnRadius + turnInfo.halfVehicleWidth) < turnInfo.headlandHeight then` And this made turn on the field enabled work like intended. I hope this help, as it is late for me and I can only get it half working. Thanks for reading

Before: 
![farming simulator 17 12_12_2016 2_01_06 am](https://cloud.githubusercontent.com/assets/10678220/21090991/5437b172-c011-11e6-8985-63297fd171fd.png)

After:
![farming simulator 17 12_12_2016 1_35_33 am](https://cloud.githubusercontent.com/assets/10678220/21090999/62fc7706-c011-11e6-8811-31f4ce41d5dd.png)

Line 540 fix
![farming simulator 17 12_12_2016 2_26_31 am](https://cloud.githubusercontent.com/assets/10678220/21091381/c721016e-c013-11e6-8c41-84b2ad3ccb81.png)

**Comment by gec100** [comment] 2016-12-12 10:20
the new game i started was clean with only CP. So could be some other mod conflicting. That's why i need to check more

**Comment by gec100** [comment] 2016-12-12 16:32
OK, I can reproduce this on a clean new game also.

NH 8340 with Bredal F2WS 4000 on field 25. 
- If i generate the course with a Headland, after finishing the headland and first lane it does not make a turn. 
![fsscreen_2016_12_12_17_21_22](https://cloud.githubusercontent.com/assets/8178773/21107109/dfbb2f06-c090-11e6-8c2a-f2cb600c67b7.jpg)

- on a course without headland worked normally 
![fsscreen_2016_12_12_17_19_10](https://cloud.githubusercontent.com/assets/8178773/21107116/e7f503a4-c090-11e6-9dbb-b4794138986f.jpg)

**Comment by Satissis** [comment] 2016-12-12 16:44
arh so it's related to headlands then :) one of the things I haven't tested at all on the wide turns.

**Comment by anderzxb** [comment] 2016-12-12 18:20
yeah same for me if i use headland then my tractor will drive 1 mile from the field if no tree is in the way :P

**Comment by pops64** [comment] 2016-12-12 20:47
Also, with the hurliman H488 and the exacta el 700 fertilezer spreader with a weight on front, completes the turn maneuver but does not update to the next way point so it just does doughnuts [Log](http://pastebin.com/zZ4CtQTC) with 12 and 14.  [Video](https://www.dropbox.com/s/xy626jftfcs4wqy/Farming%20Simulator%2017%2012_12_2016%203_38_28%20PM.mp4?dl=0) Hope this helps thanks for reading. And as always keep up the great work

**Comment by Satissis** [comment] 2016-12-13 21:10
Try v.034 or later and report back

**Comment by pops64** [comment] 2016-12-13 22:56
Works great for me, thanks for the updated

**Comment by gec100** [comment] 2016-12-17 17:19
works good here too! thx!

**Comment by AgroWillem** [comment] 2016-12-17 20:29
I have still the same problem in v.036
When i use v.033 it's working fine.
AF-9230 on field 31, Goldcrest Valley.

**Comment by pops64** [comment] 2016-12-17 21:55
What is it doing, log?

**Comment by AgroWillem** [comment] 2016-12-18 09:26
Mmm.. when i reinstall v.036 the problem is gone. Strange. I'll keep it posted and next time i add the log too.

**Comment by Satissis** [comment] 2016-12-18 13:54
Alright. Since I haven't seen any that could not get it to work after the update I did, I'll close this issue.
If you find anything related to this, either make an new one or reopen this if you can.

**Closed by Satissis** 2016-12-18 13:54 UTC
Labels: bug, waitingForUserAnswer
