### ISSUE TITLE
Bunker silo

### ISSUE THREAD

**Issue by Ragworm** [Courseplay/courseplay#3504] opened 2019-03-31 11:01 UTC
Trailor needs to reverse about another meter to be able to completly empty

**Comment by Tensuko** [comment] 2019-03-31 11:24
You Drive through the Bunker in Mode 2 ?
If so, will take a while, as Mode2 is under rework.

#3492

**Comment by Ragworm** [comment] 2019-03-31 13:32
If you drive through the tractor speeds up and you end up with chaff in a half mile row :)

**Comment by Tensuko** [comment] 2019-03-31 13:43
You use Mode2 for that ?

**Comment by Ragworm** [comment] 2019-04-01 14:42
i have always ysed mode 2 for filling bunker silo

**Comment by Tensuko** [comment] 2019-04-01 15:45
Got to wait for Mode2 to be reworked, before implementing the Calculation.
If you use mower or collector with Mode6 it works fine.

I close this couse it is duplicate of #3492 
Closed.

**Closed by Tensuko** 2019-04-01 15:45 UTC
Labels: duplicate
