### ISSUE TITLE
Plow

### ISSUE THREAD

**Issue by seeske123** [Courseplay/courseplay#3750] opened 2019-05-07 17:55 UTC
If you are plowing with a 5 blade or more plow the plow is always on the wrong side.After the first row the tractor is always with one side in the latest plow rode.Then th eplow has to be on the opposite side. So left side og the tractor in between the plowed and the main field the plow has to be to the right. This is not working with mods and not with the FS19 equipment.Do not ask for a log file .You can generate this easy. Thanks for your good work Hans

**Comment by Tensuko** [comment] 2019-05-07 19:36
If we need a logfile, we will ask for that!
Duplicate of #3535 
Closed.

**Closed by Tensuko** 2019-05-07 19:36 UTC
