### ISSUE TITLE
Beta use

### ISSUE THREAD

**Issue by tobiasw83** [Courseplay/courseplay#2919] opened 2018-12-13 14:05 UTC
How can I use  the Beta ?

**Comment by Paul2510** [comment] 2018-12-13 14:16
i Think no! We must waiting!!

**Comment by leokuhn** [comment] 2018-12-13 15:18
Anyone knows how to become a beta tester ?

**Comment by fmhweb** [comment] 2018-12-13 15:56
You will Beta test when they are ready and push a working copy on this github repository:) We are all waiting and programming on this level is a huge deal and extremly complicated. It will take month of fs lua experience for an outsider to even be considered as an asset for this project. It took me a week of reverse engineering to move the hud from the bottom to the top of the screen for LS17;) A moveable HUB would be awesome, since it kinda blocks the machines. How cares about the sky;)

**Comment by knoxville73** [comment] 2018-12-13 17:50
Hello everybody,

I think the best way to get a beta version is to let people work !

Best regards

**Comment by Bas950** [comment] 2018-12-13 18:34
Will it also work in Multiplayer?

**Comment by PvtHaggard** [comment] 2018-12-14 07:14
@fmhweb Ahaha, that is some really good [/r/iamverysmart](https://www.reddit.com/r/iamverysmart/) material. 
Took me 10 minutes to move the HUD to the top of the screen and most of that was reloading the save to dial the right number in. I only had to change one variable in a config file to do it. Given I did it in a fraction of the time does that male me a Lua god?

**Comment by BurrrY** [comment] 2018-12-14 07:54
I would also really appreciate it, if the development would be public again. Just in sense of open source.
Generally saying 'you don't get it anyway' / 'you can't program good enough' isn't really a nice way.

i mean... even NASA publishes stuff, which i would say is waaaaay more rocket science than this ;)

**Comment by pvajko** [comment] 2018-12-14 12:40
Development will be public again once we have a status we can comfortably call beta. 

The main reason we are using a private repository at the moment is that some of the developers made bad experience during previous updates with shady mod sites publishing a Courseplay version which wasn't by any standards ready for it.

When we are ready, we'll move the development back here, including all the commits we made in the meantime and Courseplay will again be accepting contributions from the community in form of pull requests @BurrrY, not that it had been so many in the last few years....

**Comment by Justice-Molton** [comment] 2018-12-14 13:56
Hey Guys, we want to offer you our dedicated root server. If you need to test MP things. 
And no worries we never share mods in public. 
Just to let you know in case something like this is needed. 
Thx for ypur efforts and awesome work! 

Justice

**Comment by pvajko** [comment] 2018-12-14 14:56
@Justice-Molton thanks for the offer, we may need it at some point but as of now, our priority it to make single player work at all. Also, Giants seem to have changed the MP even more than the rest of the (still undocumented) API.

What we really need is time...

**Comment by Justice-Molton** [comment] 2018-12-14 15:10
@pvajko youre welcome. Just shoot me a message when it is time for this.

**Comment by HungryCow212** [comment] 2018-12-14 15:39
@pvajko Just in case you didn't know, the [FS19 LUADOC](https://gdn.giants-software.com/documentation_scripting_fs19.php) is now available on the GDN.  I look forward to CP in FS19!  Take your time.  I'd rather have a good mod than a rushed one.  :)

**Comment by pvajko** [comment] 2018-12-14 15:41
Wow! I'd swear I checked last night and it wasn't there.

**Comment by foxweik** [comment] 2018-12-14 15:45
it was uploaded about 1-2 hours ago i believe

**Comment by ice81rm** [comment] 2018-12-14 17:18
> @ pvajko Nel caso in cui non lo sapessi, il [LUADOC di FS19](https://gdn.giants-software.com/documentation_scripting_fs19.php) è ora disponibile sulla [Rete Display di Google](https://gdn.giants-software.com/documentation_scripting_fs19.php) . Attendo con ansia CP in FS19! Prenditi il ​​tuo tempo. Preferirei avere una buona mod rispetto a quella frettolosa. :)

Good evening to all ...
Should this help?

**Comment by pmckeen** [comment] 2018-12-15 16:37
> > @ pvajko Nel caso in cui non lo sapessi, il [LUADOC di FS19](https://gdn.giants-software.com/documentation_scripting_fs19.php) è ora disponibile sulla [Rete Display di Google](https://gdn.giants-software.com/documentation_scripting_fs19.php) . Attendo con ansia CP in FS19! Prenditi il ​​tuo tempo. Preferirei avere una buona mod rispetto a quella frettolosa. :)
> 
> Good evening to all ...
> Should this help?

Short version: Yes. Documentation on API is good not only because it tells you how to use what's there, but because it's typically limited to those things that are expected to last for a little while. (Some parts of the API may have been accidental exposure, experimental, or 'internal use only' if you're exploring it with things like for i, j in pairs( obj ).

Source: I'm a LUA enthusiast. I teach classes in it at a local school.

**Comment by Grayeagle54** [comment] 2018-12-17 02:41
pvajko 

When you all get ready to test just give a holler I do closed to the pubic testing for quite a few companies and am willing to donate my time to aid you gentlemen in your endeavor. All you have to do is ask.

**Comment by James31283** [comment] 2018-12-18 17:39
Very interested in being included as a Beta tester. I work as an IT consultant and would really appreciate providing feedback and help. Also I'm loosing interest in FS 19 without courseplay.

**Comment by AlexStephenLytton** [comment] 2018-12-18 19:31
I'm also interested in testing Courseplay for you. In FS17 it was the most important mod for me and it will be in FS19 too. Looking forward to help to get CP running in FS19!

**Comment by pvajko** [comment] 2018-12-18 20:04
Thanks for the offers for beta testing, we'll certainly need that.

Currently we are fighting with an issue probably caused by a conflict between CP and the Giants AI and they did not publish that part of the code in the Luadoc. Our very helpful contacts at Giants are on their Christmas vacation already so don't hold your breath...

**Comment by Russ645** [comment] 2018-12-18 20:41
I am also available for Beta testing.  1500 Hours on V5

**Comment by ole22143** [comment] 2018-12-19 13:30
Best thing to do for us is to develop content befor the courseplay issnt ready. To make the game great when courseplay comes out.  I work 8h a day on my 4x Map (Flusstal XXL V2) to get it ready when Coursplay comes for Fs 19. 

By the way, you guys make my dreams come true i posted in 2009 or 2010 i think in the Giants Forum the idea exactly that what coursplay is they say it to complicated but here we are. If i could help u in some point i will do that. But i think to deliver content for Courseplay is the best way to do that. 

Wish you nice Christmas days from germany :)

**Comment by killallaround** [comment] 2018-12-20 07:16
if you are looking for more beta tester I would love to help you out I think it should be in the base game

**Comment by psoppa** [comment] 2018-12-20 09:48
Hello everybody.
I think you should just give the developers time for the Ls17 it took quite a long time until CP was out and constantly asking it does not make it any better. I'm assuming that the CP beta is given back on codes out so that you can download the CP Master just like the LS 17th For my part, I can only say I'm looking forward to a huge CP and wish you much success in the switch to LS 19.

**Comment by VitaliyYa** [comment] 2018-12-21 11:04
Hi to all!
Testers, what do you think, invent and create test case suite for testing Courseplay v6.0 FS19?

**Comment by p4r4d0xs** [comment] 2018-12-21 11:31
Hello devs, 

i play since FS13 with Courseplay, so meanwhile i can manage and coordinate everything with Courseplay in FS.  If you need some help with tests in FS let me know it! :) I also have two MP servers with 16 slots but i think MP is not important for now.

**Comment by fudoido** [comment] 2018-12-23 04:47
would love to test it when 1st beta is released and help find bugs and whatnot.
but due the incoming season, let the devs have their xmas and new year with all the fun they can get, and lets wait till January for some more progress :)

and to all of you waiting for courseplay, do the same I recommended to devs, enjoy your holydays with family, have a blast during xmas and new years eve, and next month drop by for more news about the courseplay status, because now it will all slow down due season.

Merry Xmas and happy 2019 to all.

**Comment by SirAlbertL** [comment] 2018-12-23 14:46
> 
> 
> Will it also work in Multiplayer?

The first beta might not, but that is how they find, discover hidden issues is by releasing a beta, test version that they fix as issues get reported. Just l like it has been done for the last three versions of Farming Sim.

**Comment by Justice-Molton** [comment] 2018-12-23 14:48
How retarded are you guys? Are you able to read? Holy ghost. They will release something if its ready to release....

**Comment by yaitsbilly** [comment] 2018-12-24 01:50
I'm also open to help beta test.

**Comment by XPiRiJenZ** [comment] 2018-12-25 21:38
just take your time and merry xmas to all of you :)

**Comment by killallaround** [comment] 2018-12-26 20:16
that's fine I am here when you need me just let me know :-)

**Comment by rwkeeton** [comment] 2018-12-27 23:31
Looking forward to testing phase.  Best wishes

**Comment by Grayeagle54** [comment] 2018-12-28 01:47
@ThomasGaertner
Thanks for the update! We all love being kept in step. When you guys talk to giants maybe to get them to move quicker let them know some of us are going back to FS17 so we can play with Courseplay. For me the game is broken without it probably cause I want to a lot more than one field at a time LOL Keep up the great work. We all are very grateful thanks!

**Comment by DJGoo** [comment] 2019-01-02 22:58
I just wanted to thank the devs for being patient with us, we are all anxious to use this mod we all know and love, but not all developers respond so well to users looking for an update. If mod developers don't have any communication with the public over upcoming updates we don't know if we want to update our games or not, sometimes one awesome mod makes a game.
So thanks and keep up the good work.

**Comment by bgo1973** [comment] 2019-01-03 12:32
Thanks to all of you for the great work you're doing over and over again during the past years. 
I hope you just could fix some of the issues in the meanwhile.
A short update of the ongoing process in between would be very nice.
I'm looking forward to beta-test soon.

**Comment by omegaMV6** [comment] 2019-01-03 22:11
First a "Happy New Year" to all here !
At the moment i´ve playing FS17 with CP because it´s not funny to play the new FS without courseplay.
I would thank you that we can hope to became CP for FS19. Like @bgo1973 says: FS is not FS without CP So i looking every day on this site hoping to find a first beta-version to test it in game and give you feedback.
Thanks to all for your work on this mod !  

Sorry for my bad english, i´m from Germany ;)

**Comment by ProCal94** [comment] 2019-01-04 06:38
Source: I'm a LUA enthusiast. I teach classes in it at a local school.

Hey, I'm actually very interested in learning to code, in basically any language at this point. What do you recommend I do in order to start? Would you maybe be able to teach me or guide me?

**Comment by pvajko** [comment] 2019-01-08 20:08
Thanks for all the offers for testing. 

If you are seriously willing to help us with it please contact me at github@vajko.name.

Peter

Deutsch ist auch kein Problem.

**Comment by 37cee** [comment] 2019-01-10 10:40
I read your post in the Information post about the incremental release and i'm really happy when you will (hopefully) release CP at some point at the future. It has been years since i first used the mod and CP has been the most important mod that improves my expirience of the game.

**Comment by pvajko** [comment] 2019-01-10 12:18
Thank you all who contacted me to volunteer for testing. Looks like we have plenty of beta testers for now. 

If you do not receive an invitation in the next few days then expect not to be included in this round of testing.

**Comment by psoppa** [comment] 2019-01-10 12:41
I'm glad that you've progressed with CP. and annoying me just about myself that I have sent just such a short email for the beta test. Well no matter if it does not work, there is still the anticipation of the Relese. 😊

**Comment by ice81rm** [comment] 2019-01-10 13:43
Thanks for the reply ..... But an Italian friend will serve you
right? :)) I'm joking, of course, if I'm on the list I'll be happy Good
job guys Fabio

Il 10.01.2019 13:18 Peter Vajko ha scritto: 

> Thank
you all who contacted me to volunteer for testing. Looks like we have
plenty of beta testers for now. 
> 
> If you do not receive an
invitation in the next few days then expect not to be included in this
round of testing. 
> 
> --
> You are receiving this because you
commented.
> Reply to this email directly, view it on GitHub [1], or
mute the thread [2].
  


Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio e 6 mesi di INFINTY! http://tisca.li/myopen

**Comment by marcospms** [comment] 2019-01-10 15:50
I'd like to take part in the tests. I use the courseplay for a long time, and I come here every day to find out how your development is going. My email is marcospms@gmail.com

**Comment by tobiasw83** [comment] 2019-01-11 13:49
Würde mich zum Testen etc ebenfalls anbieten. wuerfel@htp-tel.de

**Comment by sootysax** [comment] 2019-01-11 14:21
y'all are so thirsty :)

**Comment by ProCal94** [comment] 2019-01-11 14:44
Courseplay is life but the devs also need a life. Not fair to expect out of the devs what you would not do yourself. Plus the more you guys post here the more they have to check, thus they get less work done. Be PATIENT! Wait for devs to post. Also, I'm pretty sure at this point they aren't accepting any more beta testers so posting it here does not help you at all really, just wait for the next beta test.

**Comment by Sythos** [comment] 2019-01-11 18:21
> Thanks for the offers for beta testing, we'll certainly need that.
> 
> Currently we are fighting with an issue probably caused by a conflict between CP and the Giants AI and they did not publish that part of the code in the Luadoc. Our very helpful contacts at Giants are on their Christmas vacation already so don't hold your breath...

Please, add me in betatest wishlist/waitinglist :D

**Comment by marcospms** [comment] 2019-01-11 18:34
What a beauty. A lot of people posting, because a lot of people like it, that's wonderful. No doubt, it is wonderful. I am also a developer and would be happy to see so many people interested in my projects. There is nothing wrong with this, but it is worth saying that it is good to have patience and wait

**Comment by p4r4d0xs** [comment] 2019-01-12 17:33
courseplay should be implemented in FS21. 
can we somewhere vote for it? :P

**Comment by spectrum69** [comment] 2019-01-12 22:54
tester french if you would my help (tester for map 16x australie et usa )

**Comment by felixhinze** [comment] 2019-01-14 10:06
> 
> 
> courseplay should be implemented in FS21.
> can we somewhere vote for it? :P

Totally Agree. FS is not FS without Course Play. Has GIANTs SOFTWARE not made these developers an offer yet? I cannot understand how something as valuable as course play is not yet part of the base game. If it's not going to be included in the next version of Farming Simulator, I will not buy it until Course Play becomes available for it. Without CP, FS is really a waste of time!

Thank you guys for taking the time to keep on developing course play over and over again. And tell the guys at GIANT's, I Say "Hi " :-) - they should really take a look at some of these posts and take note.

**Comment by Schmittez** [comment] 2019-01-14 10:21
> > courseplay should be implemented in FS21.
> > can we somewhere vote for it? :P
> 
> Totally Agree. FS is not FS without Course Play. Has GIANTs SOFTWARE not made these developers an offer yet? I cannot understand how something as valuable as course play is not yet part of the base game. If it's not going to be included in the next version of Farming Simulator, I will not buy it until Course Play becomes available for it. Without CP, FS is really a waste of time!
> 
> Thank you guys for taking the time to keep on developing course play over and over again. And tell the guys at GIANT's, I Say "Hi " :-) - they should really take a look at some of these posts and take note.

I HIGHLY doubt Giants will ever implement it in to the base game. They want to keep all platforms equal and it would be almost impossible to implement it on consoles.

**Comment by kylebown1** [comment] 2019-01-14 11:23
When is this going to be released the tracker has not been updated for sometime now since Nov 19, 2018

**Comment by Satissis** [comment] 2019-01-14 16:20
@kylebown1 I can assure you that the tracker have been updated since that date, but you might only see the finished jobs on the list and we have quite some that are marked as finished but are waiting for one of the other devs to retest it if they can give an thumbs up before accepting it.

We also have a closed beta test group with our private issue tracker in so you won't be able to see that either.
And no, we are currently closed for further beta testers as it would make too much work load on the guys actually working on fixing bugs atm.

All in all, what I'm saying is: Have patient and yes we are working on it in the background ;)

**Comment by Satissis** [comment] 2019-01-14 17:33
To be perfectly honest, I could not say.
There is still stuff we are trying to figure out and then we have beta bugs to deal with as well so there could still be a good while before we will be ready.

**Comment by KCHARRO** [comment] 2019-01-14 17:44
Guys, you are wonderful, your work excellent and has changed the way many of us play for the better. FS without CP, MR and Seassons is not FS, it's like missing the most important part.

Thank you for staying for all these years, I will be patient because you never stop and CP will be ready, I am sure.

Sorry for my bad English, I live in Cuba.

**Comment by limoman39** [comment] 2019-01-14 19:20
Love your work guys, I'm sure you'll release it when you can.  If there is anything I can do to help send me a message.   I have a life outside of FS just like you, but don't mind sharing the load.  

Thanks again

**Comment by marcospms** [comment] 2019-01-14 20:59
Friends, the guys are working a lot. Let's be patient and wait. If there was any good developer to help great. I'm from Brazil and all of us here also play many with courseplay. Sorry the English.

**Comment by doblonk** [comment] 2019-01-15 00:42
I'm from Indonesia, and I check progress everyday :)

**Comment by marcospms** [comment] 2019-01-20 15:20
I think so. You already have video on youtube working with the new coursePlay. The guy is gaining views by playing the new courseplay :)

**Comment by knoxville73** [comment] 2019-01-20 18:36
@ThomasGaertner , many thanks for the information about your job.  Thanks a lot at the complete team, great job.  You are the most important development team for this game.

**Comment by shadow250** [comment] 2019-01-23 15:22
if there is a beta test i would also like to be a part of it.

**Comment by Satissis** [comment] 2019-01-23 16:53
@shadow250 There is a closed beta test atm.
People was asked a while back to send Peter an email regarding the close beta test and one what they can help with.
We are not looking for more atm though.

**Comment by leokuhn** [comment] 2019-01-23 16:55
How about someone testing it on the Mac (me) ?

**Comment by terrorbaff** [comment] 2019-01-23 17:02
I sent an email after I was told that there is a set of beta testing. Do
you already have Russian beta testers in your list?

ср, 23 янв. 2019 г. в 18:55, leokuhn <notifications@github.com>:

**Comment by Satissis** [comment] 2019-01-23 17:27
As I said before, we are currently not looking for more.

@terrorbaff if you didn't get an invite, then you are one of the people that didn't get into the closed beta test. Properly due to not explaining in details what you can do for us as a beta tester or telling about your self.
But can't say though, since it was Peter that handled the invites.

**Comment by marcospms** [comment] 2019-01-24 15:15
There is a person who has the courseplay but does not take a test, only gets videos on youtube snubbing the players, saying that he is privileged with the courseplay. For me, I do not see how he is collaborating with tests. I am a developer and I do computer science, could contribute 1000 times more than this citizen. Sorry the English.

**Comment by ice81rm** [comment] 2019-01-24 17:12
@marcospms 
you refer to this:

https://youtu.be/ETlxY0zh8Hw

**Comment by Rated-Mature** [comment] 2019-01-24 21:05
Look guys I love what you do and course play is the best. Please send me a link that I can use to donate to help you guys a little.

Thanks

**Comment by limoman39** [comment] 2019-01-24 21:08
I would like to do the same...


-----Original Message-----

**Comment by psoppa** [comment] 2019-01-24 21:18
guys are you totally turning off here now? my teeth let people work in peace. courseplay will come out soon enough. always these ungodly 🤪

**Comment by ProCal94** [comment] 2019-01-24 21:33
> 
> 
> Damn me for offering to help them financially the best I can. Why don’t you just worry about yourself obviously I wasn’t asking you what you thought. Why don’t you help them out financially? I don’t intend to rush them just think that if your going to spend a bunch of time to help the community with a product that they enjoy the least people can do is try to compensate you for your time.

I would agree. This does not seem to me like it would bother the devs, plus this is also technically a suggestion for the future as you say. What I'm saying is I don't see why he is wrong in wanting to donate to devs who put so much time and effort into something we love to use and benefit from. It would only be right to want to contribute back in some sort of way.

**Comment by duffstone** [comment] 2019-01-25 04:33
Taking donations can be a bit tricky when done publicly...   Plus I don't even know if these guys are US, International, or both...   Think taxes, tarrifs, copyrights, etc...   once you add $$$ to the mix, you start having to follow different rules.    If they get all that figured out and put a donation button up,  then I'll contribute, no problem.  but be warned that it's not something thats always easy to do.

**Comment by Rated-Mature** [comment] 2019-01-25 04:56
I hear you but I remember them having one for Course Play for FS 17. It is easy to show you spent it on paper, ink, computer equipment etc in order to provide a product that your not pocketing the money as income just expenses. I just hate to use a product some killed theirselves to get out to everyone for free and not st least offer to pay what I think is right as way to offset their time and equipment used. Example they may have to pay for a dedicated server to test their multiplayer abilities. Something they shouldn’t have to foot the bill on themselves. But thanks for your insight.

**Comment by pvajko** [comment] 2019-01-25 05:05
https://courseplay.github.io/courseplay/en/index.html

Look for that button with 'Donate' on it...

**Comment by Rated-Mature** [comment] 2019-01-25 05:20
Damn sorry me asking sounds like I’m trying to rush the development. Only place I’ve seen where doing what you can is ridiculed. 

Sorry I don’t have a computer science degree and write code for a living. Maybe in my next life.

I just donate more to St Jude

Thanks

**Comment by Rated-Mature** [comment] 2019-01-25 05:30
Explain how I can help or exactly what is needed and I will definitely help in anyway I can. I never intended to rush anyone or try to get any special favor for donating. I can definitely donate time to. I just need some idea of what would help that I can do and I’ll do it. Writing is something I can do.

**Comment by Rated-Mature** [comment] 2019-01-25 05:34
Explain how I can help or exactly what is needed and I will definitely help in anyway I can. I never intended to rush anyone or try to get any special favor for donating. I can definitely donate time to. I just need some idea of what would help that I can do and I’ll do it. Writing is something I can do.

**Comment by pvajko** [comment] 2019-01-25 07:54
As I said, there's the Courseplay manual which has not really been update for years. The course generator section is out of date, I think there's nothing in there about multi tools and convoys, etc.

**Comment by psoppa** [comment] 2019-01-25 08:38
> guys are you totally turning off here now? my teeth let people work in peace. courseplay will come out soon enough. always these ungodly 🤪

To put something right I have nothing against donations for the CP developers. This is even a good thing to support the work they do in their free time. One should not forget that the developers all have a job and family. What bothers me is this rumjammer because CP is not out or you are not in the first beta tests here.

If you are interested in your manual, I would like to make tutorial videos as soon as CP goes outside and send them to the developers.

**Comment by pvajko** [comment] 2019-01-27 00:31
Dear Courseplay Users,

we decided to move back to GitHub as with the valuable help of our beta testers and some of the Giants developers we think we now reached an acceptable level of functionality and stability which allows for a wider audience to enjoy the benefits of Courseplay.

Remember, only modes 1, 2, 4, 5 and 6 are functional and there are many known bugs (as the Courseplay console message says "the Courseplay team will not take any responsibility for crop destroyed, savegames deleted or baby pandas killed"), because yes, this is still beta software.  We will be enabling functionality step by step so probably your favorite Courseplay feature may still be missing. Be patient. What you have now is better than nothing.

If you see problems, please post an issue, see our [Wiki](https://github.com/Courseplay/courseplay/wiki) on how to create a useful bug report.

Again, be patient, we have a life, family and job. For days or weeks we may not even look at the issues you post. We may defer fixing some of the issues or not fix them at all. 

If you can't wait for an issue to be resolved you are more than welcome to fix it yourself and open a Pull Request.

Your Courseplay Dev Team

**Comment by marcospms** [comment] 2019-01-27 01:37
Friends, where are a link for download?

**Comment by marcospms** [comment] 2019-01-27 02:52
courseplay is not harvesting, is failing at harvest

**Comment by wilbertlandry** [comment] 2019-01-27 03:07
What is the name for the new mod zip file?

**Closed** 2019-01-27 10:06 UTC
