### ISSUE TITLE
Mode 3, V6.02.00078 

### ISSUE THREAD

**Issue by justushickey** [Courseplay/courseplay#6332] opened 2020-11-17 17:41 UTC
Tractor and cart will unload combine correctly, navigate to truck correctly, but once the cart is empty, the tractor just stays beside the truck.  I have tried redoing the course several times with no success.  I am going to revert to an older version of courseplay where this exact course worked well.

![fsScreen_2020_11_17_12_36_36](https://user-images.githubusercontent.com/69698954/99426457-183fa700-28d2-11eb-852a-4ca3de8ddb44.png)

**Comment by Tensuko** [comment] 2020-11-17 18:08
logfile with debugchannel 4 7 12 and 14

**Comment by justushickey** [comment] 2020-11-17 18:35
I reverted back to V 6.02.00060 and it worked great.  When I saw your request, I reloaded V 6.02.00078 and ran the course.  The grain cart emptied and returned to the field.  

This is confusing, because one of the things I did when trying to solve the problem was restart the game, load the savegame without courseplay, save, exit, and load again with courseplay and it did the exact same thing.  If I can replicate the issue, I will attach the log with the correct debugchannels.

**Comment by polosubtil** [comment] 2020-11-17 21:47
Just a comment, might be completely stupid, just delete it if it is.
It looks like an issue we had with shovels in mode 9 staying stuck on top of a trailer because they were not always being fully unloaded, I remember changing the empty status to 0.1 or something like that instead of 0 to make it work. @justushickey, maybe have a look if it comes back if you still have a fruit appearing like in the photo below (even with 0%), and if it works when there is no fruit left
https://github.com/Courseplay/courseplay/blob/63e23575015f8a5bffa28b96603520f77b8bf6ed/OverloaderAIDriver.lua#L122
![image](https://user-images.githubusercontent.com/60451845/99454353-9a59bb00-2926-11eb-991f-66e912343466.png)

**Comment by justushickey** [comment] 2020-11-18 00:42
You know, now that you mention that, one thing I didn't try was resetting the cart.  I never noticed that it was doing that 0% thing.  I will keep an eye out for this.  And of course, if it happens again I will save the log.

**Comment by Tensuko** [comment] 2020-11-18 05:35
@polosubtil you might be right on this...

@schwiti6190 can you have a look ?

**Comment by schwiti6190** [comment] 2020-11-18 12:38
@Tensuko möchtest du mal "fillUnit.fillLevel > 0.1" in OverloaderAIDriver:isTrailerEmpty() testen ob sich da was ändert ?

**Comment by Tensuko** [comment] 2020-11-18 13:10
@schwiti6190 wenn das eine Sinnvolle Anpassung wäre klar kann ich machen.

**Comment by rohne83** [comment] 2020-11-18 20:41
I can remember same issue when I was playing around with the waiting time for the auger wagon (https://github.com/Courseplay/courseplay/issues/6046). Especially when waiting time was set it sometimes (not always) happened, that it was still thinking it is overloading although having been emptied completely already. Auger animations etc were still running, but of course no grain left to be overloaded.
Was a bit weird, for some auger wagons it happened quite often, for others never. Based on that, your suspicion with the fillLevel comparison seems most likely to me. Think I still have a savegame with setup where I can reproduce it quite quickly, so might be able to help testing.

**Comment by polosubtil** [comment] 2020-11-18 20:58
@rohne83 and @justushickey 
If you want to try my branch to check if this is actually the issue here
https://github.com/polosubtil/courseplay/tree/Polosubtil

**Comment by rohne83** [comment] 2020-11-23 16:47
Hi,
I just tried a bit with @polosubtil 's branch, and it seems these changes solved the issue. I was using version 1.0.0.0 of the Brent Avalanche 1596 mod. This mod always showed the issue, when setting the wait time to any value higher than 0. With this branch I could not replay the issue anymore. So from my side it looks good.

**Comment by Tensuko** [comment] 2020-11-23 17:36
Did you had anything left in the Auger Wagon after leaving ?
If all runs smooth, we will add this in.

**Comment by rohne83** [comment] 2020-11-23 17:47
No, I had an extra eye on that. Capacity of the Brent is 53000liters, so wouldn't have wondered if 50liters remained in side. But it emptied completely to 0 liters :)

**Comment by Tensuko** [comment] 2020-11-23 18:41
Well that is the Risk but can't test all mods with different emptyspeeds and capacitys :) 
Guess we will add this then.

**Comment by polosubtil** [comment] 2020-11-23 21:04
I have updated my fork with the latest version 6.03
https://github.com/polosubtil/courseplay
@rohne83, you might want to keep testing a bit with different settings to be sure ?
@Tensuko, this is a twick we already have for shovels and unload courses, tell me if you want me to do a push
https://github.com/Courseplay/courseplay/blob/64b451b183440eec0375e41f8d53ae0e0083e811/UnloadableFieldworkAIDriver.lua#L34
https://github.com/Courseplay/courseplay/blob/64b451b183440eec0375e41f8d53ae0e0083e811/ShovelModeAIDriver.lua#L353

**Comment by Tensuko** [comment] 2020-11-23 22:23
you can do a pull request like you did with the translation and we can have a look at the code.
Actually is unloading with mode6 still a big deal ? I unloaded like 60-80 times with mode2 and it went all fine.

**Comment by polosubtil** [comment] 2020-11-23 22:27
Unloading with Shovel and mode6 are working very good with this twick, they are here for quite some time now. It's just that some implements are not always fully empty (as in the picture above). I used mode 3 a few times but never saw that problem though.

**Comment by Tensuko** [comment] 2020-11-23 23:31
I unloaded arround 6M liter Silage into BGA the last days and never had a problem, thats why I am a bit confused why we need those kind of tweaks...

**Comment by rohne83** [comment] 2020-11-24 16:15
I've used my spare time to test around again with some really unrealistic settings, just to check the robustness of polosubtil's solution. But no issues found. Most extreme setting for the auger wagon was a capacity of 3.5million with an emptyspeed of just 300 - so after reaching that 0.1% fill level during unloading it still had 12 seconds to go until emptied completely. But even then the overloader perfectly finished unloading and went back on its course - with 0 grain left in its trailer. So everything good in my eyes with that approach.

**Comment by Tensuko** [comment] 2020-11-24 16:19
Awesome :)
Thanks a lot for so much testing, saved me a lot of time.
The PullRequest is already in and will be in release with the next Version.
But we will wait for new Release, as we might have some other things that we want to put in :)

Anyway, as it is on Master Branch already, I will close this Issue already.

**Closed by Tensuko** 2020-11-24 16:19 UTC
Labels: waiting for logfile
