### ISSUE TITLE
Version ending in 64 " complete failure of program". 

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3219] opened 2019-02-13 00:15 UTC
Course will not " Drive"...then weird artifacting ( when frozen in cab like I'm looking through the driver), and then you must close game from desktop as all commands are frozen.

**Comment by retiredegs** [comment] 2019-02-13 00:41
same for myself as well, same version

**Comment by Kevuk85** [comment] 2019-02-13 01:32
cannot use the programme since updating it my player just freezes inside the cab and nothing works i have to exit the game...............

**Comment by sootysax** [comment] 2019-02-13 02:33
It's not v.00064 - it's the version labelled 'Trigger Stuff' and after (.0065).

If you revert to v.00064 with commit 70cee76 - that is working normally (https://github.com/Courseplay/courseplay/tree/70cee76cf5c3bea24bf14560a58ab3a9b9adb828)

**Comment by pvajko** [comment] 2019-02-13 03:09
So many complaints but not a single log posted...

**Comment by Hubcap-1** [comment] 2019-02-13 03:11
> It's not v.00064 - it's the version labelled 'Trigger Stuff' or later (.0065).
> 
> If you revert to v.00064 with commit [70cee76](https://github.com/Courseplay/courseplay/commit/70cee76cf5c3bea24bf14560a58ab3a9b9adb828) - that is working normally (https://github.com/Courseplay/courseplay/tree/70cee76cf5c3bea24bf14560a58ab3a9b9adb828)

It most definitely was version 64

**Comment by pvajko** [comment] 2019-02-13 03:12
No, it's the trigger stuff.

**Comment by Hubcap-1** [comment] 2019-02-13 03:13
> No, it's the trigger stuff.

Well it definitely said it was version 64 in the mod list

**Comment by pvajko** [comment] 2019-02-13 03:15
Very smart but still no logs, right?

**Comment by Hubcap-1** [comment] 2019-02-13 03:15
[courseplay-master (1).zip](https://github.com/Courseplay/courseplay/files/2858655/courseplay-master.1.zip)
Here is the complete version that started this thread

**Comment by pvajko** [comment] 2019-02-13 03:16
Jesus Christ.

**Comment by Hubcap-1** [comment] 2019-02-13 03:18
I guess that you didn't like that it was version 64

**Comment by pvajko** [comment] 2019-02-13 03:22
I guess I don't like that you have no friggin idea what you are talking about. 
For those who know, it was 229322b00717a4c75f8425923ec4ed948e2142b5 causing the issue.

**Comment by Hubcap-1** [comment] 2019-02-13 03:37
> I guess I don't like that you have no friggin idea what you are talking about.
> For those who know, it was [229322b](https://github.com/Courseplay/courseplay/commit/229322b00717a4c75f8425923ec4ed948e2142b5) causing the issue.

So This would still say  it's version 64 in the mod list?

**Comment by Hubcap-1** [comment] 2019-02-13 03:38
Ps please park your profanity at the door It is not welcome or constructive here

**Comment by Hubcap-1** [comment] 2019-02-13 03:41
I guess you thinking searing at the author of thread is ok if you can just delete his comments asking you not to do so

**Comment by pvajko** [comment] 2019-02-13 11:46
duplicate of #3221

**Closed by pvajko** 2019-02-13 11:46 UTC
