### ISSUE TITLE
Late braking when reaching tip trigger in Mode2(Realistic Fill Type Mass Adjustment mod)

### ISSUE THREAD

**Issue by Nebular64** [Courseplay/courseplay#2001] opened 2017-04-22 00:49 UTC
I noted the tractors with trailer are now delaying their braking when reaching the silo tip trigger.  This causes the tractor to stop just past the trigger while trying to unload, so it just continues on its course back to the field.  The "tip trigger reached" message now shows when the tractor is much closer to the trigger, so there doesn't appear to be much time for the tractor to brake.  

I started to experience this when I updated from v.00121 to v.00126 (and now v.00127).

I thought maybe it could be one of the mods such as the Ground Response or Engine Braking, but the issue still exists after disabling such mods.  I will attempt to revert back to v.00121 to confirm, but just wanted to see if its possible for me to edit the <paraphrasing here> distance to brake before reaching tip trigger (if such a parameter).

**Comment by pops64** [comment] 2017-04-22 02:49
How big is your tip trigger? If is of standard size you shouldn't be having this issue. A while ago I moved the tip point back to center.

**Comment by Nebular64** [comment] 2017-04-22 13:31
@pops64 Thanks for the assist! The map is Grabbylatoosh`s edited version of Don Diego.  
Below are pics of the silo trigger and CP speed settings.  This pic is the approach point when the tractor hits the trigger, but hasn't started braking.
![trigger reached](https://cloud.githubusercontent.com/assets/3781477/25304815/e78ad552-273c-11e7-8bb5-e594d22702c9.jpg)
Here is the full pic of the trigger point
![silo trigger](https://cloud.githubusercontent.com/assets/3781477/25304825/2c5f64ae-273d-11e7-8799-b75c5698af86.jpg)
Current CP speeds set on this course
![cp speeds](https://cloud.githubusercontent.com/assets/3781477/25304868/f3104b18-273d-11e7-9dec-5ad6825dfffc.jpg)
I've been using CP on this map without any problems and no updates have been applied to the map.
Let me know if you need anything else and I greatly appreciate the help.

**Comment by pops64** [comment] 2017-04-22 18:27
Could you post a log with debug channel 1 active and 21 and take a picture when it says tip trigger is reached. It should say drive 836 if is setting the correct speed when it reaches the tip trigger but I have a feeling that it isn't recognizing the tip trigger until after.

**Comment by Nebular64** [comment] 2017-04-22 21:56
Log with debug channel 1 and 21 attached. 
[log.txt](https://github.com/Courseplay/courseplay/files/949297/log.txt)

 Here is the drive(836) with a refspeed of 10
![fsscreen_2017_04_22_17_32_20](https://cloud.githubusercontent.com/assets/3781477/25308517/ee253b54-2783-11e7-8235-142284547420.png)

Tractor continues driving through tip point
![fsscreen_2017_04_22_17_32_26](https://cloud.githubusercontent.com/assets/3781477/25308523/0e8d4ba2-2784-11e7-9325-3d3da0c52f70.png)

Tractor stops right at the edge of the trigger with a drive(740).  It use to stop with the trailer in the middle of the trigger, but now it's been a hit a miss with the tractor drifting past this point without finishing unloading
![fsscreen_2017_04_22_17_32_29](https://cloud.githubusercontent.com/assets/3781477/25308533/6d9ee344-2784-11e7-915b-d41b8d922fba.png)

**Comment by pops64** [comment] 2017-04-22 22:56
I would say try turning off all script based mods besides CP and what your map needs to run. Something is interfering with CP. Because CP is telling the tractor to slow down but something is overwriting CP.

**Comment by Nebular64** [comment] 2017-04-22 23:11
That's why I thought it might have been a conflict with the Engine Brake mod, but I'll start deactivating other mods and continue testing.

**Comment by pops64** [comment] 2017-04-23 07:46
Yea the refspeed = you see in channel 21 debugs is the speed in kph that CP is setting your cruise control to. But has you see in the FS GUI your cruise control is still set 22 mph or 43 kph.

**Comment by Nebular64** [comment] 2017-04-24 16:34
Ok, I can't explain why it's causing a problem now, but my issue is with the Realistic Fill Type Mass Adjustment mod.  I've been running this mod with CP for quite some time with no problems and now it looks like the culprit.  I'll tweak the .lua file in this mod to try and resolve the problem.

I'm not sure if you have this mass adjustment mod for testing purposes, but I would be curious to see if you experience the issue since I can definitely recreate it when this mod is activated.

**Comment by pops64** [comment] 2017-04-24 17:34
I don't have it. That is interesting behavior indeed. We will have a look into and maybe figure out what is going on when we have time.

**Comment by Nebular64** [comment] 2017-04-25 12:33
JWTLYK the mod I referenced basically changes the weight of all fruits to be more realistic.  This prevents you from taking a small tractor and hauling a huge load of , say fertilizer, which weighs a lot more than what Giants has set as a default.

So, my test above was with a full grain trailer hauling corn.  The real world weight is 800kg per m³ of corn, which is heavier than the in-game defaults.  I reactivated the mod and changed my tractor out with something that had better breaking power and it stops at the tip point as expected.

This, of course, doesn't resolve the symptom of why it started now, but it definitely solves the problem for me.  Not sure if a modifier can be added to CP to look for this mod and calculate DtB based on its RealMass table, but just a thought.

Again, thanks for all the support!!

**Comment by pops64** [comment] 2017-05-17 23:33
Try with version 141. And Report back. I will talk with Satis and Thomas about either making this the permanent fix for the mod or adjusting the braking parameters if the mod is enabled

**Comment by gec100** [comment] 2017-05-18 05:58
I can confirm this behavior with the Realistic Fill Type Mass Adjustment mod. Not using MR mod. Bit to realistic 4 me.

**Comment by Nebular64** [comment] 2017-05-19 21:28
I ran the same scenario as mentioned above with v.143 and, unfortunately, the braking is the same.  The tractor approaches the tip point and debug channel 21 shows CP setting the speed, but the physical load of the trailer keeps the momentum going to where it comes to a stop just outside the tipping zone.

While the Mass Adjustment mod is active, I'm not sure if more braking force could be applied and/or if CP can increase the distance of the approach, which in turn would allow the momentum to diminish enough to allow for a full stop in the tipping zone.

**Comment by Blackmankot** [comment] 2017-08-05 02:14
@pops64 And I propose to close this issue for cleaning.

**Comment by pops64** [comment] 2017-08-12 20:00
Collapsing mod issues into one thread. #2231

**Comment by pops64** [comment] 2017-09-09 03:03
This will be a can't fix. CP tells FS what speed we want to drive at by setting the cruise control. It is up to FS on how quickly we get to that speed.

**Comment by pops64** [comment] 2018-10-26 21:05
Will fix this if I can find a clean link to this mod has I need to know when it is active and the problem is it doesn't install itself into tractors

**Comment by pops64** [comment] 2018-10-26 21:11
NVM modhoster was using sharemods for this :(. Downloaded it anyways I have a reliable way of detecting this mod. Ill push it to master once I am happy with it. At the moment something is going wrong during direction changes causing the tractor not to move and I can't find the cause(maybe !% of the time)

**Comment by pops64** [comment] 2018-10-29 07:08
Version 44 or higher will work now or better than before. Still take turns easy has CP doesn't know any better than recored speed but it will now reach recored speed alot quicker than before

**Closed by pops64** 2018-10-29 07:08 UTC
Labels: Mod Issue
