### ISSUE TITLE
Courseplay HUD shortcut setting.

### ISSUE THREAD

**Issue by Shotgunface** [Courseplay/courseplay#1629] opened 2017-01-12 15:41 UTC
I'm not sure if it's by design but the HUD setting for right mouse or left ctrl+delete seems to be saved to the vehicle not a global change for the map. example: if I change it for say a Case 1455 XL I have to do it again on every other vehicle. Same goes for show waypoints.

**Comment by Satissis** [comment] 2017-01-12 16:33
That's by design, since some vehicles you might want to use the Ctrl+Delete, since they are controlled by the right mouse button and others you would just do the normal right click thingy.
So it's up to the user to set it to there likings ;)

Going to close this to keep the issues clean :)

**Closed by Satissis** 2017-01-12 16:33 UTC

**Comment by Shotgunface** [comment] 2017-01-12 17:12
Cool, thanks for the quick response, great job so far!
