### ISSUE TITLE
Issue with dumping grass into silos

### ISSUE THREAD

**Issue by iw-shawn** [Courseplay/courseplay#2024] opened 2017-04-29 18:30 UTC
Using courseplay v 1.0131  with Case Puma/ Fendt 939 with Joskin Trans-Space 8000 tippers. Northwest Texas map, confirmed on GCV

Since V 1.0122 I've been having problems dumping grass into Silos.  The trailer is dumped creating chaff as soon as it reaches the tip trigger, when it runs out of room it pulls ahead and once passing the TipCol dumps grass on the ground.  The leveller then collects the grass and can't push chaff away because the grass on the leveller doesn't turn  into chaff.

It works fine with trailers dumping chaff because the leveller can push chaff into the silo.

**Comment by iw-shawn** [comment] 2017-04-30 01:36
Here are some pictures to show whats happening.  Before the tractor would back the tipper up to the dump point giving itself some room to dump.  Now it dumps right at the leading edge of the bunker and then pulls ahead

![20170429211725_1](https://cloud.githubusercontent.com/assets/10137319/25560475/685d3508-2d23-11e7-81e8-51afd34c6f7a.jpg)
![20170429204810_1](https://cloud.githubusercontent.com/assets/10137319/25560476/6e36b0d0-2d23-11e7-8fc8-be32fae9bdd7.jpg)
![20170429204806_1](https://cloud.githubusercontent.com/assets/10137319/25560478/7151ba08-2d23-11e7-9966-f19d481d6724.jpg)

**Comment by pops64** [comment] 2017-04-30 03:51
It is hard to tell but there appears to be an unload point in the silo. There should never be any unload points in any trigger. Has this causes CP to get confused. Remove this unloadpoint and try again

**Comment by iw-shawn** [comment] 2017-04-30 13:35
I did have a dump point, but am having problems without it. 

The trailer backs to the bunker edge, starts to dump and runs out of room. It then goes into a loop of pulling ahead a few feet then reversing a few feet over and over.

**Comment by pops64** [comment] 2017-04-30 17:06
I would also try straighting out your course to leave the silo has silos now will stop unloading if the spot there unloading to is full and they are suppose to drive a bit forward and try again.

**Comment by iw-shawn** [comment] 2017-04-30 18:25
Still having the same issue with a straight course in and out of the bunker.  The trailer never enters the bunker it dumps right at the very edge, so when it pulls forward when there is no room left at the front of the bunker it can't tip anymore because of the TipCol around the bunker.

Tips at edge
![20170430141142_1](https://cloud.githubusercontent.com/assets/10137319/25566865/83631e98-2db0-11e7-865f-6316f8163bfd.jpg)

Loops into 1 foot forward and backwards movement
![20170430141203_1](https://cloud.githubusercontent.com/assets/10137319/25566877/aa48b27a-2db0-11e7-83c1-1a00c7fc1ed5.jpg)

**Comment by SweClark** [comment] 2017-05-01 15:14
I have also the same problem on a different map.. And when backing up the game start stuttering.

**Comment by SweClark** [comment] 2017-05-01 16:25
I tried Dev 096 and that one works.. And in that version i dont even get the stuttering when the Truck/tractor is backing up to the foragecombine in the field.

**Comment by E7O** [comment] 2017-05-06 19:18
Having the same issue, tractor keeps stuttering after reloading. Any tips yet? Or other versions that work?

**Comment by dkfiremann** [comment] 2017-05-06 20:50
RDAllen had a tip on how to unload the trailer a little more into the bunker/silo. 
Take a look at his youtube video: 
[https://www.youtube.com/watch?v=pHbb70uXrdQ&t=6s](https://www.youtube.com/watch?v=pHbb70uXrdQ&t=6s)

**Comment by pops64** [comment] 2017-05-27 02:52
Could we get debug channel 2 with this issue? I think this might be the case that the actual trigger shown with F5 for those who know what that is. Is larger than the BGA silo. For those who know what F5 it would be very helpful to get a picture for where the tipper is tipping inside the trigger.

**Comment by SweClark** [comment] 2017-05-27 07:56
I havent had any problems in the later DEVS.. This problem seems to be gone..

**Comment by Blackmankot** [comment] 2017-08-05 00:48
@pops64  I think that the issue has been resolved in the latest versions of the course. I suggest closing it for order.

**Comment by pops64** [comment] 2017-08-12 20:42
Not reproducible closing this out.  If steps on how to reproduce please post here and we will revisit this.

**Closed by pops64** 2017-08-12 20:42 UTC
Labels: waitingForUserAnswer
