### ISSUE TITLE
Refill seeds/fertilizer issue

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#6090] opened 2020-09-19 08:08 UTC
Hi. I'm using latest version of courseplay and i have problem with refilling seeder with two containers, for fertilizer and seeds.
When I start the course, the tractor drives to the loading point, loads the first container, and then just stands in place. In the menu I add 2 filltypes fertilizer and seeds. 
Everything works in manual mode. Previously, on version 6.01, this operation always worked.

[Video](https://www.youtube.com/watch?v=mpcCZW9DhGI)
[LOG](https://gist.github.com/Horozor/13955e57e231aed3ec3487c924e76597)

**Comment by Tensuko** [comment] 2020-09-19 09:58
Hi Horozor

> Everything works in manual mode. Previously, on version 6.01, this operation always worked.

6.01 is way to old. I think you mean a Version before the Trigger Rework. :)

**Comment by schwiti6190** [comment] 2020-09-19 09:59
Hi, 
First thanks for the video, if you could change your language to english for the next time would help a bit more :) 
I pushed a possible fix on the branch "David", if you want, you can try it out :)

David

**Comment by Horozor** [comment] 2020-09-19 11:06
@Tensuko I mean **6.01**.380 to 399 works good. **6.02**.1 to 61 has issues with refill triggers etc.
Thank you @schwiti6190 
I changed 713 line from *if not triggerHandler:isNearDischargeNode(fillableObject,fillUnitIndex,self) then*
to
*if not triggerHandler:isNearDischargeNode(fillableObject,fillUnitIndex,self) and not vehicle.cp.driver:is_a(FillableFieldworkAIDriver) then*

and that helps. BUT now refilling works good for only some seeders, not for Amazone Condor
Only if the seed tank stay first and second fertilizer, refill works for Amazone Condor, but if i add Liquid Fert, or Herbicide before seed tank, Amazone condor opened cap and closed immediately. And it stay at place. I know my english is bad, so i'm try to show you how it works in [video](https://youtu.be/m4NjtbwcCY0)
Log file clear no errors
I think it's something wrong with Amazone condor, but who knows

**Comment by Tensuko** [comment] 2020-09-19 11:38
> **6.02**.1 to 61 has issues with refill triggers etc.

Haven't touched anything about refill trigger at 6.02.00001 - 6.02.00048 ?
So I wonder a bit about that....

**Comment by schwiti6190** [comment] 2020-09-19 12:27
@Horozor I really appreciate the testing work you've done :)
Could you try the same setup with the lemken planter combo (Azurit 9 and Solitair 23), as their was a giants bug I tried to move around. This might be a similar problem with the amazone condor. Also If you could keep debug channel 2 on and send the logfile, that would be perfect :)

**Comment by Horozor** [comment] 2020-09-19 12:40
@schwiti6190 
I tryed and this works but traktor didnt stop when filling seed tank only for fertilizer
[Log](https://gist.github.com/Horozor/5e5f882af49001cb64190c37597b5526)

**Comment by schwiti6190** [comment] 2020-09-19 13:09
@Horozor two things could you try this with more space between the triggers and a link to the silos, as I've tried with a diffrent set of triggers and no problem so far :)

**Comment by Horozor** [comment] 2020-09-19 13:30
I tryed with more space between the triggers
1.Condor opened and closed cap near 2nd tank and stop
2.Horsch works good
3.Azurit 9 and Solitair 23 works good
[Video](https://youtu.be/Eo5_jS604S0)
[Log](https://gist.github.com/Horozor/231b664a2f2ef7cf7a5bc47411fd672a)

**Comment by schwiti6190** [comment] 2020-09-19 14:57
@Horozor seems like the problem is only with the condor, will probeblly wait on fixen that one. 
Thanks alot for your help and testing, if you like you can test it with the next up comming verison again, but I am not really optimistic that it will be fixed :)

**Closed** 2022-02-06 13:02 UTC
Labels: enhancement, postponed
