### ISSUE TITLE
Mode 2. The problem of transport with a combine.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2355] opened 2017-10-09 15:38 UTC
When the transport approaches the combine, the game stops for a few seconds. The same problem is with version 5.01.00207. And the technique does not always come right up to the harvester. Video.
https://yadi.sk/i/AeAyJzxN3Nby2t

**Comment by R3v0Lt-On3** [comment] 2017-10-09 16:02
Read #2314. Try my last post. :)

**Comment by Blackmankot** [comment] 2017-10-09 16:31
Alas ... But I have a different situation, the field is not large, one combine and one tractor are working on the course. ))

**Comment by pops64** [comment] 2017-10-10 16:08
Try with path finding turned off. Has I think your issue is related to #2314

**Comment by pvajko** [comment] 2017-10-10 20:12
Can you post a log with debug channels 7 and 9?

**Comment by Blackmankot** [comment] 2017-10-11 13:23
@pvajko  With pleasure!

**Comment by Blackmankot** [comment] 2017-10-11 14:01
@pvajko Can channels 7 and 9 be made active by the combine harvester or transported by a truck approaching the combine for unloading?

**Comment by pvajko** [comment] 2017-10-11 15:01
Does not matter, debug channels are global, valid for all vehicles.

**Comment by Blackmankot** [comment] 2017-10-11 15:25
@pvajko OK.

**Comment by Blackmankot** [comment] 2017-10-30 07:52
Here's the log. Stopping the game began less often and do not start right away. Also, there is often a stop of transport for no reason.
[log.txt](https://github.com/Courseplay/courseplay/files/1426344/log.txt)
![2017-10-30_14-45-14](https://user-images.githubusercontent.com/26131714/32159907-56d6a98e-bd8a-11e7-9e6e-92ad01b3d581.jpg)

**Comment by pvajko** [comment] 2017-10-31 14:14
Looks like it tries to find the path while driving in the fruit. Is that when you see the game stopping, while a tractor is driving through fruit?

**Comment by Blackmankot** [comment] 2017-10-31 14:32
No, the game stops at the beginning of the traffic to the combine. And also, on the way to the combine.

**Comment by pvajko** [comment] 2017-11-12 02:41
Can you post a savegame as described in the wiki?

**Comment by Blackmankot** [comment] 2017-11-14 08:17
Good afternoon. This problem has appeared since version 5.02.00024. If you put version 5.02.00018, then the problem disappears. If before the game stopped for 1-2 seconds, now the FPS is greatly reduced.
Link to the map - https://yadi.sk/d/kEy9BiIX3PgAkz
savegame1 - https://yadi.sk/d/fOcFsU_z3PgBSh
New video - https://yadi.sk/i/E9_BTQn63PgDuF

**Comment by Blackmankot** [comment] 2017-11-14 11:50
Here is the situation with the version 5.02.00018. As you can see, there is no problem.
New video -  https://yadi.sk/i/kFMh6hLw3Pgg7v

**Comment by pvajko** [comment] 2017-11-14 13:14
Thanks for the upload, but can't use it as:
1. the tractor you are using seems to be a mod I don't have
2. you did not upload the courses.

**Comment by Blackmankot** [comment] 2017-11-14 14:12
1. Here at this link a tractor -
https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=91708&title=fs2017
2. Courses - https://yadi.sk/d/Y8GXhmd03PgzEX

**Comment by pvajko** [comment] 2017-11-15 02:42
Ok, I tried this now with the latest 27. Can't see any problems, no frame rate drop.

**Comment by Blackmankot** [comment] 2017-11-15 05:05
Understood thanks!

**Comment by pvajko** [comment] 2017-11-15 13:22
Actually, I can see this happening on a relatively slow laptop. Did not notice anything on the fast desktop PC but on this laptop it is quite noticeable, no matter if pathfinding is on or off.

**Comment by pvajko** [comment] 2017-11-16 14:33
Don't see anything wrong or buggy in CP, this seems to be a performance issue. I only see it with my laptop unplugged in powersave mode, there's no real noticeable effect when plugged in. 

The frame rate drop is caused by the collision avoidance, more specifically by the raycasting in isTheWayToTargetFree() function. 

If this becomes a problem for many users there's probably a way to optimize this. Closing this for now.

**Closed by pvajko** 2017-11-16 14:33 UTC

**Comment by Blackmankot** [comment] 2017-11-21 16:39
@pvajko  I found out - what's the problem. When tractor starts its journey to the combine, the FPS decreases, if on the map a lot of transport is bought by the player. I have a powerful computer and there were about 100 vehicles on the map. When I sold half the vehicles, the FPS dropped exactly 50% less than the video. When I sold all the vehicles, the FPS did not go down! Conclusion - the course since version 24 reacts by reducing the FPS by the amount of transport. In your case, my game was loaded with a small amount of transport. Therefore, the decrease in FBS was visible only on a weak laptop.

**Comment by pvajko** [comment] 2017-11-21 18:38
Great, thanks. Were all those vehicles driven by Courseplay or just sitting idle when the FPS went down?

**Comment by pops64** [comment] 2017-11-22 02:09
I know there is cap on the amount of vehicles you can have i think it is around 200. Either way your really pushing your CPU for power with that many vehicles especially if most them are mods.

**Comment by Blackmankot** [comment] 2017-11-26 07:00
@pvajko All the equipment was without work.

@pops64  The technique on the map was about 100.

**Comment by pvajko** [comment] 2017-11-29 21:53
This is a duplicate of #2441
