### ISSUE TITLE
Saved courseplay courses cannot be deleted on a Dedi server!

### ISSUE THREAD

**Issue by Pieber87** [Courseplay/courseplay#5170] opened 2020-04-11 16:23 UTC
Hello!
All saved courses can no longer be deleted on a Nitrado Game Server (the garbage can is missing!)
They can be deleted on a normal multiplayer game!
All attempts: with mods, without mods, standard card with-without mods
failed

Please correct this so that you can delete the courses on a Dedi Server
THANKS
Regards
Marco

**Comment by Tensuko** [comment] 2020-04-11 18:30
Duplicate of #4840

**Closed by Tensuko** 2020-04-11 18:30 UTC
