### ISSUE TITLE
combine astray

### ISSUE THREAD

**Issue by AlvinMJ** [Courseplay/courseplay#3702] opened 2019-04-28 09:04 UTC
It was a little strange way:
https://steamcommunity.com/id/Alvinmj/screenshot/822380354965070969

**Comment by Tensuko** [comment] 2019-04-28 09:36
And how does this report help us in any way ?
https://github.com/Courseplay/courseplay/wiki
Screenshot and logfile of the course with debug channel 9 and 14 on.

**Comment by AlvinMJ** [comment] 2019-04-28 21:06
Screenshot ar on my link. Logfiles I do not know much about, but can try to find them. I can also try to repeat it on tupe.

**Comment by pvaiko** [comment] 2019-04-28 22:05
Most likely a duplicate of #3598

**Closed by pvaiko** 2019-04-28 22:05 UTC
Labels: waitingForUserAnswer

**Comment by AlvinMJ** [comment] 2019-04-28 22:08
yes

**Comment by AlvinMJ** [comment] 2019-04-29 10:51
Video: https://youtu.be/_aUn66t4z-I
[log.txt](https://github.com/Courseplay/courseplay/files/3127081/log.txt)
