### ISSUE TITLE
Tractor drive in circles infinitely

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4429] opened 2019-10-23 22:34 UTC
[log.txt](https://github.com/Courseplay/courseplay/files/3764806/log.txt)

As https://github.com/Courseplay/courseplay/issues/4372, this tractor also goes to an infinite loop:
https://youtu.be/QjFoogZcxeM

**Comment by pvaiko** [comment] 2019-10-24 00:36
Duplicate of #4372. Also, try with the PPC on (advanced settings).

**Closed by pvaiko** 2019-10-24 00:36 UTC

**Comment by rogeriodec** [comment] 2019-10-24 00:41
I don't understand, you say it's duplicated but the other issue was closed and the problem persists...
What does it mean?

**Comment by pvaiko** [comment] 2019-10-24 00:48
Have you tried with PPC on?
