### ISSUE TITLE
Using Mode6 not working on Gemeinde Rade

### ISSUE THREAD

**Issue by NSA-Quicki** [Courseplay/courseplay#4700] opened 2019-12-25 20:02 UTC
I keep getting the error: 
2019-12-25 20:52 Error: Running LUA method 'mouseEvent'.
2019-12-25 20:52 C:/Users/*/*/Dokumente/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00348/triggers.lua:648: table index is nil

Only on this map, tested with standart vehicles. 

Elsewise log is clear ..

**Comment by Tensuko** [comment] 2019-12-25 21:57
Duplicate of #4678
Map Issue.
Closed.

**Closed by Tensuko** 2019-12-25 21:57 UTC
