### ISSUE TITLE
Courseplay freezing the game when trying to send a vehicle back to the first point after finishing a course

### ISSUE THREAD

**Issue by 147loch** [Courseplay/courseplay#5297] opened 2020-05-04 20:47 UTC
Hey guys, I had a some issues while running the latest version of the mod today.

I'm running version 6.02.00004 on a multiplayer game where I was the host, everything was going fine until we started setting up a combine. My game got very laggy all of a sudden, but after about 1 min it was fine again. Then I went to a tractor and my camera got stuck in an outside view and I lost all controls of the tractor, all the inputs I was sending were getting exponentially more delayed, then I just could not do anything. Thankfully, I was able to save the progress, but then I just stopped and relaunched the game. On the second try, the same thing happened again, no inputs were working, I could only access the console.

I saw that in the console a lot of lines were errors from Courseplay being `Error: Running LUA method 'update'.` In `AIDriver.lua:1357: attempt to index local 'course' (a nil value)`.
I opened the log.txt (attached below) to see that there was around 30000 lines of the same error.

This seems to be a problem related to pathfinding causing a memory leak. I'll continue playing for a bit and if the same thing occurs again I'll send a video demonstration.

[log.txt](https://github.com/Courseplay/courseplay/files/4577310/log.txt)

**Comment by pvaiko** [comment] 2020-05-04 21:05
What exactly you mean by "started setting up a combine"?

**Comment by 147loch** [comment] 2020-05-04 21:19
We've done some testing, the lagging seems to be entirely related to pathfinding. See the capture here: https://drive.google.com/open?id=1DJjuh3f1khUiNOP55tNXnbHJ_YRfFE-z

Basically my friend drove the combine in a tree and started courseplay, that happened exactly when the game was lagging for me, as soon as he turned off courseplay for the combine the lags stopped.

**Comment by 147loch** [comment] 2020-05-04 21:47
Alright, more news: Turns out it has nothing to do with the combine. It is true that the game lags for a while if the combine has to find his way back (i.e. got stuck in a tree). But it never really got my camera stuck. See the video here: https://drive.google.com/open?id=176hbs_7m3EByKR8eaHt0LYZOc6giUJn2

After a while, the bug when the camera gets stuck happened again. See the video here: https://drive.google.com/open?id=1QV2tyXO0uXsMviyUVfdysPFH7h_O-uTE (it starts happening at the 3:34 mark)

Console says it all: 7719 returning to first point is causing the update method to fail over and over. This makes the game completely freeze on my side and here's what my friend was seeing: https://drive.google.com/file/d/1zQdCK4vkTiLkaK8eSrfpnY-tqApsw46s/view?usp=drivesdk (the point where it started happening is at 13 seconds)

Then I guess the issue should be recentered around that. It's possible that it happens only on multiplayer, but Courseplay makes the game freeze when trying to send a vehicle back to the first point after finishing a course.

My log file is available here: [log.txt](https://github.com/Courseplay/courseplay/files/4577748/log.txt)

My friend's log: https://pastebin.com/xJ37E2bA

When that started happening, I have just enough time to save my game before the game completely froze. You can see in my friend's video that he was still able to move freely (not like I was).

**Comment by pvaiko** [comment] 2020-05-04 21:48
There's no combine on that video.

**Comment by pvaiko** [comment] 2020-05-04 21:49
Seems to be a duplicate of #5280

**Comment by 147loch** [comment] 2020-05-04 21:55
First video has a combine at the very end, it was slowing the game down because of pathfinding, but this not related to this issue.

What the issue is, in the second video as soon as our seeder reached the end of the course, the game froze and my camera got stuck outside the tractor (happens at around 3:34 in that second video I sent).

It might be a duplicate, but this is a good way to reproduce it: setup a short course, enable return to first point, and let the course run. It happens as soon as the tractor tries to run back.

I'm 100% certain this is an issue happening with the vehicle once it reached the end of a course.

**Comment by pvaiko** [comment] 2020-05-04 21:56
Yeah, thanks for troubleshooting, it is a merge problem, will fix.

**Comment by Tensuko** [comment] 2020-05-05 17:08
tested with 00006, fixed.

**Closed by Tensuko** 2020-05-05 17:08 UTC
Labels: waitingForUserAnswer
