### ISSUE TITLE
Only generates headlands

### ISSUE THREAD

**Issue by lindbejb** [Courseplay/courseplay#2767] opened 2018-06-23 20:04 UTC
I have a field that is roughly 308 acres, tried generating a course for a single 8m wide implement a couple different ways and only generates the headland and nothing in middle.  When i used skip row and multiple tools it generates.  Wonder is there is a limit on data points that could be increased somewhere

**Comment by pops64** [comment] 2018-06-23 20:11
Your going to have other issuses beyond that has cp isn't designed for anything that large. I'm surprised it even correctly detected the field edge. As I belive there is a hard limit of 20km before CP stops scanning the field edge

**Comment by pvajko** [comment] 2018-06-23 21:06
https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions

and I'll take a look.

**Comment by lindbejb** [comment] 2018-06-23 22:43
[https://www.dropbox.com/s/2v0da0pceiqyazd/courseStorage0008.xml?dl=0](url)

**Comment by lindbejb** [comment] 2018-06-23 22:44
[https://www.dropbox.com/s/x2htjnbvdyd3bmc/Screenshot%202018-06-23%2018.41.22.png?dl=0](url)

**Comment by pvajko** [comment] 2018-06-23 22:49
That's not what I need. I need the cpFields.xml file and number of the field. Read the wiki carefully again.

**Comment by pvajko** [comment] 2018-06-23 22:53
Holy shit, looking at that screenshot, that's really an odd shaped field. This issue may really end up in the won't fix category.

**Comment by lindbejb** [comment] 2018-06-23 22:57
https://www.dropbox.com/s/548y03292367jna/cpFields.xml?dl=0

generates course fine when skipping a row or two or uses a second machine

**Comment by pvajko** [comment] 2018-06-24 09:30
Still don't know which filed it is...

**Comment by lindbejb** [comment] 2018-06-24 13:15
?

**Comment by pvajko** [comment] 2018-06-24 23:55
Sorry, I only saw the email notification and that did not have the field number in it.

So, the problem is the shape of that field, especially all those little nooks everywhere. Those result in a field split into at least 15 blocks and then the genetic algorithm needs to figure out the best sequence to work on those blocks. 

We have a limit of 10 blocks built in for performance reasons and I wouldn't really want to change that unless there are a significant number of users who need it. So this won't be fixed now.

(If you are interested you can read up on how this exactly works in this paper: Ibrahim A. Hameed, Dionysis Bochtis and Claus A. Sørensen: An Optimized Field Coverage Planning Approach for Navigation of Agricultural Robots in Fields Involving Obstacle Areas)

**Closed by pvajko** 2018-06-24 23:55 UTC
Labels: Mod Conflict, wontfix

**Comment by lindbejb** [comment] 2018-06-25 01:42
where would i change the 10 to 15

**Comment by pvajko** [comment] 2018-06-25 10:36
15 may not be enough, the easiest is to remove this return statement:
https://github.com/Courseplay/courseplay/blob/30f0a212eb6abf026e82a30d143bb218ffbef095/course-generator/center.lua#L196

With that return removed you may run into other issues though, but you can also play with setting the row angle manually, the automatic angle selection is not prepared for such a field.

**Comment by pvajko** [comment] 2018-06-25 14:05
If you turn on debug channel 7 you'll see in the log the number of blocks generated.

Also, you may want to use the advanced course gen GUI, just click on that small cogwheel icon (near the generation button).
