### ISSUE TITLE
hud.lua:736: attempt to index a nil value

### ISSUE THREAD

**Issue by MagnusMInuus** [Courseplay/courseplay#3573] opened 2019-04-10 13:16 UTC
HUD closed and error occures, when pressing "Fahrzeugspezifische Einstellungen"
CoursePlay (v6.01.00172)
New Game on Ravenport
Create on Field 26 a new Course and start it. Now press "Fahrzeugspezifische Einstellungen".
The HUD closed and the error occured.
![fsScreen_2019_04_10_15_06_27](https://user-images.githubusercontent.com/49484622/55881786-9f2f8800-5ba3-11e9-8493-54b24b0024d4.png)
![fsScreen_2019_04_10_15_10_47](https://user-images.githubusercontent.com/49484622/55881787-9f2f8800-5ba3-11e9-819d-baafaf716e8c.png)

**Comment by Tensuko** [comment] 2019-04-10 13:44
Duplicate of #3566
Closed.

**Closed by Tensuko** 2019-04-10 13:44 UTC
