### ISSUE TITLE
Mode 2 truck not seeing tip trigger

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#3821] opened 2019-05-21 12:03 UTC
Stock Man TGS 18.500 and Krampe trailer operating in mode 2 does not get "tip trigger" when reaching the sell point and does not empty.

The same truck and trailer empties properly in mode 1.

The same course and trailer, when pulled by a tractor/dolly instead of a truck, empties properly in mode 2.

**Comment by sootysax** [comment] 2019-05-21 12:16
duplicate #3804

**Comment by Tensuko** [comment] 2019-05-21 13:32
#3311 and duplicate of #3804 
Closed.

**Closed by Tensuko** 2019-05-21 13:32 UTC
Labels: duplicate
