### ISSUE TITLE
Reversing when hitting an obstacle

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1420] opened 2016-12-02 17:34 UTC
In FS15, when a tractor or combine hit an obstacle, say a fence when reversing on fieldwork, eventually it would change direction and continue..   this does not seem to be happening at all in FS17.

Is this still a feature?

**Comment by SquareCloud506** [comment] 2016-12-02 18:05
I noticed the same thing.

**Comment by Satissis** [comment] 2016-12-02 22:51
Hmm no I don't think that working anymore. I actually never heard that CP did that in FS15 and have never accounted it either so not really sure what to look for atm :S

**Comment by SquareCloud506** [comment] 2016-12-02 23:42
I used CP in FS15 a lot and in field work mode with a combine, or a tractor with a small seeder or cultivator (one that was lifted, not pulled), when the vehicle turned to for the next row and backed into an object, like a tree or a fence, it would give the "Vehicle is slipping" warning for a short time, then it would stop trying to reverse and would go forward again to the next row. I thought that was a planned reaction to a vehicle slipping. I came to depend on it.

So it wasn't planned? Just a happy bug? lol

**Comment by pops64** [comment] 2016-12-03 00:57
I remember reading an old issue about that. That when it reserved into an object. The time it took to go forward again was bugged. Ill edit this if can find where i read that.

**Comment by Satissis** [comment] 2016-12-03 13:20
no if it was in FS15, it should not have been an bug, I just never knew about it :)
I'll add an enhancement for now, since it's not any game breaking issue :)

**Comment by SquareCloud506** [comment] 2016-12-03 19:01
On a side note, I've noticed the new FS17 hired workers have some new logic when calculating a end of row turn, adjusting the way it makes the turn to avoid any objects near the field edge, yet in other parts of the same field it just swings wide if there is room. I wonder if it's possible, with the help of Giants, for CP to take advantage of this turn maneuver logic that avoids hitting trees and buildings. (The hired worker won't adjust for a parked vehicle in it's path, it just stops and waits) :)

**Comment by Satissis** [comment] 2016-12-03 20:06
@SquareCloud506 I have already talked with them about it and it's not that easy since theirs are fixed to there turn maneuvers.

**Comment by SquareCloud506** [comment] 2016-12-03 20:41
@Satissis Yeah, I figured if it was possible it would be something complicated to look at after beta is bug free, and didn't know if it was even possible. Also having to scan for objects before calculating a turn would probably also be complicated to work out. Not an idea for beta, just throwing it out there for maybe a later enhancement after beta is bug free. :)

**Comment by saku05** [comment] 2017-04-25 10:25
Hi Guys
Watch this video between 16 min10 sec-16 min 42sec
Thank you for your work

https://www.youtube.com/watch?v=nRzZydDAaw4

**Comment by fudoido** [comment] 2017-05-04 05:17
i remember that feature on courseplay v4, but sometimes it would take too long for the vehicle try to reverse and avoid obstacle , or simply kept slipping and never reverses to avoid obstacle (waited almost 15 minutes once to see if the feature was working as intended, got bored of waiting and cleared vehicle manually)ç
it would be nice to see the feature more enhanced in v5, also for traffic situations like on issue #1458 
after a short time slipping (no more than 5 minutes) or stuck in traffic, cp would force a reverse and new turn to avoid whatever obstacle it was retaining the vehicle path.
maybe it would be a easyer thing than elaborate a more enhanced obstacle colision detection routine..... i think.

**Comment by Blackmankot** [comment] 2017-08-05 03:12
@pops64   I suggest also close it for cleaning.

**Comment by pops64** [comment] 2018-11-07 20:07
Closed #2909

**Closed by pops64** 2018-11-07 20:07 UTC
Labels: enhancement, postponed
