### ISSUE TITLE
when setting up course for 2 tools the right one stars in a different place

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#5057] opened 2020-03-14 15:09 UTC
Not going to toutch that Maillink - Tensuko

**Comment by moose31608** [comment] 2020-03-14 15:12
should be starts

**Comment by moose31608** [comment] 2020-03-14 15:17
[log.txt](https://github.com/Courseplay/courseplay/files/4332928/log.txt)

**Comment by Tensuko** [comment] 2020-03-14 15:25
Load mod: Courseplay_6_01_00387 (Version: 6.01.00387) (Hash: 38b5a192866cd2cb5864ec5d7f373c19)
Load mod: Courseplay_6_01_00397 (Version: 6.01.00397) (Hash: c9833db90b4e0b7938aeda88b337ac97)

...

**Comment by moose31608** [comment] 2020-03-14 15:39
[log.txt](https://github.com/Courseplay/courseplay/files/4332944/log.txt)

**Comment by moose31608** [comment] 2020-03-14 15:40
![fsScreen_2020_03_14_10_53_55](https://user-images.githubusercontent.com/53488388/76685243-8f58c900-65e8-11ea-9679-2edb068500b6.png)
![fsScreen_2020_03_14_11_34_21](https://user-images.githubusercontent.com/53488388/76685244-92ec5000-65e8-11ea-863e-0ae947ad2660.png)
![fsScreen_2020_03_14_11_34_29](https://user-images.githubusercontent.com/53488388/76685246-95e74080-65e8-11ea-9d10-f52130b83539.png)
![fsScreen_2020_03_14_11_34_36](https://user-images.githubusercontent.com/53488388/76685247-98499a80-65e8-11ea-9fa8-6c7661db51be.png)

**Comment by Tensuko** [comment] 2020-03-14 16:08
What Settings when you started the Driver ? 1st Waypoint ?

**Comment by moose31608** [comment] 2020-03-14 16:36
What setting?

**Comment by moose31608** [comment] 2020-03-14 16:39
The first picture is the way I setup for both tractors. Then on the main page I go to mode specific settings and change it to left and then the 2nd tractor to the right

**Comment by moose31608** [comment] 2020-03-14 16:41
Then on the bottom I pick seed and fertilizer

**Comment by moose31608** [comment] 2020-03-14 17:07
It doesn’t do it when you are doing field work.

**Comment by moose31608** [comment] 2020-03-14 17:08
Just seeding and fertilizering

**Comment by Bobster82** [comment] 2020-03-14 17:09
> What setting?

I think he meant when u start the course... What setting is below the start? is start at 1st waypoint or at current waypoint, at next waypoint ??

**Comment by moose31608** [comment] 2020-03-14 17:15
The nearest waypoint. I never changed it

**Comment by Tensuko** [comment] 2020-03-14 17:40
Try it with 1st Waypoint if this still happens

**Comment by moose31608** [comment] 2020-03-14 17:55
Doesn’t help it just drives through the field not doing anything

**Comment by Bobster82** [comment] 2020-03-15 12:31
> Doesn’t help it just drives through the field not doing anything

Do you have a log file when u used start at 1st waypoint? 
Also a screenshot with ur generated route and all lines drawn?

**Comment by moose31608** [comment] 2020-03-15 13:01
[log.txt](https://github.com/Courseplay/courseplay/files/4334226/log.txt)
![fsScreen_2020_03_15_08_56_17](https://user-images.githubusercontent.com/53488388/76701876-9856a280-669b-11ea-982a-e3f3b2c055fb.png)
![fsScreen_2020_03_15_08_56_48](https://user-images.githubusercontent.com/53488388/76701879-9a206600-669b-11ea-8688-3a73e23eb23f.png)
![fsScreen_2020_03_15_08_57_22](https://user-images.githubusercontent.com/53488388/76701880-9b519300-669b-11ea-97f7-903bfd992bc2.png)
![fsScreen_2020_03_15_08_57_35](https://user-images.githubusercontent.com/53488388/76701882-9d1b5680-669b-11ea-80d9-43eff45e39ea.png)

**Comment by Bobster82** [comment] 2020-03-15 15:26
@moose31608 , you forgot the debug channels ;)
And btw, if u start at 1st waypoint, make sure ur vehicle is a few meters before the 1st point, not after as I see in ur pic ;)

**Comment by moose31608** [comment] 2020-03-15 15:37
What channel do I need to put? The pictures are at the start and each other picture is as it’s driving

**Comment by Bobster82** [comment] 2020-03-15 15:44
debug 7, 9, 11, 14 should be enough.
Before u press the start button, make sure ur on start 1st waypoint, then make sure ur vehicle is a few meters before startpoint (Blue arrow) if u press start, he can drive to the 1st waypoint and align correctly ;)

**Comment by moose31608** [comment] 2020-03-15 16:04
[log.txt](https://github.com/Courseplay/courseplay/files/4334460/log.txt)
![fsScreen_2020_03_15_11_51_31](https://user-images.githubusercontent.com/53488388/76705236-e2984d80-66b4-11ea-81a6-418449fa6674.png)
![fsScreen_2020_03_15_11_52_51](https://user-images.githubusercontent.com/53488388/76705240-ed52e280-66b4-11ea-94af-dfdfbd9c1ad0.png)
![fsScreen_2020_03_15_11_56_48](https://user-images.githubusercontent.com/53488388/76705248-f643b400-66b4-11ea-8bbc-7a62f964eeac.png)
![fsScreen_2020_03_15_11_42_56](https://user-images.githubusercontent.com/53488388/76705251-fd6ac200-66b4-11ea-9e81-059c5aaef018.png)

**Comment by Bobster82** [comment] 2020-03-15 16:44
@Tensuko , help me out with him if u can, Im getting stuck :P ...

Can it be the problem in the generated route? Does a route need to be saved for multiple tools? can it be the mods? the "problem" i find in his log is lots of out of mem and this strange info on creating route:
2020-03-14 10:55 :08 [dbg7 lp11805] Headland section to 1780
2020-03-14 10:55 :08 [dbg7 lp11805] Generating headland track with offset 12.75, clockwise true, inward true
2020-03-14 10:55 :19 [info lp11805] Recursion limit of 300 reached for headland generation
2020-03-14 10:55 :19 [info lp11805] Could not generate offset headland
2020-03-14 10:55 :19 [dbg7 lp11805] Get next none-headland 1781
2020-03-14 10:55 :19 [dbg7 lp11805] Up/down section to 3770

@moose31608 , can u also try it with original tractor and seeder? And I dont know if u can make a vid from the point u set up all courseplay options to genereting the track and start? So that we can see exactly what settings u use and how ur setting it up... if that can't , then i cant help any further ;)

**Comment by Tensuko** [comment] 2020-03-15 17:12
I would not create the Route at the Edge, more on the Side of the Field to get a better Start and for sure stay a few meters in front of the 1st Waypoint before start it.

Would have to try this out to find anything, but the last tests I did went all fine so....

**Comment by Tensuko** [comment] 2020-03-15 17:27
First test:
![fsScreen_2020_03_15_18_18_05](https://user-images.githubusercontent.com/27344744/76706656-679d5a00-66e9-11ea-8b47-8c0104c55d8d.png)

Position where to create Course:
![fsScreen_2020_03_15_18_19_37](https://user-images.githubusercontent.com/27344744/76706783-75071400-66ea-11ea-9785-0c388d46395d.png)

Coursecreation:
![fsScreen_2020_03_15_18_19_53](https://user-images.githubusercontent.com/27344744/76706786-79cbc800-66ea-11ea-82ea-57259ac06636.png)

Result (all good)
![fsScreen_2020_03_15_18_23_17](https://user-images.githubusercontent.com/27344744/76706794-7f291280-66ea-11ea-975b-97eb2292bcbe.png)

**Comment by moose31608** [comment] 2020-03-15 17:29
This has been a problem since after 6.01.00388. I’m still using 6.01.00387

**Comment by Tensuko** [comment] 2020-03-15 17:31
Well, there is no Problem.... What I only notice is, when use 'actual waypoint' while other does a turn, it gets wrong information...

**Comment by moose31608** [comment] 2020-03-15 17:32
I don’t  have any problems when setting up for the left side. It’s when you setup for the right side with multi tools

**Comment by Tensuko** [comment] 2020-03-15 17:37
It works for both sides as you see in my screenshots.
Stay at the Field Side, Create your course, drive a few meters in front of the 1st waypoint, then start the course with Version 397.
If it doesn't there is something wrong with your Mods or Map.

**Comment by moose31608** [comment] 2020-03-15 18:22
Well I didn’t have a problem with it until after 6.01.00388. Worked just fine in 387 and before with same map I’m using

**Comment by Tensuko** [comment] 2020-03-15 18:42
This is your Problem and this happens when you create the course at the Corner.
![fsScreen_2020_03_15_19_39_48](https://user-images.githubusercontent.com/27344744/76708139-e0ee7a00-66f4-11ea-855d-23efb8acbb69.png)

And this is how to solve it, just move a bit more into the Field and then start in front of the 1st Waypoint.
![fsScreen_2020_03_15_19_40_22](https://user-images.githubusercontent.com/27344744/76708169-15623600-66f5-11ea-9087-aa2b40a01e5d.png)


This is due to the Multitool Rework and works all fine, when you don't do what I tell you, I can't rly help you to solve your Problem.

**Comment by moose31608** [comment] 2020-03-15 19:33
How do I create a course away from the corner. The map I use that’s where it starts me at?

**Comment by moose31608** [comment] 2020-03-15 19:38
Usually I make 2 times around the field with both tools. But the second one doesn’t did it it just goes to the other end and start up and down

**Comment by moose31608** [comment] 2020-03-15 20:06
when I setup a course the startposition I usually put south/west and etc. when I do that seeding and feritzialing that's when I have a problem with it not starting at start point. Now on the field work I do it the same  way and dont have a problem

**Comment by Bobster82** [comment] 2020-03-15 22:14
I can confirm what Tensuko said... Im getting that strange behavior too when generating a course from a corner with 2 tools setup... 

Use the start location: Pick a spot on the map, then u can set a blue icon on the map to start from where u want to start, but pick a spot a bit further then the corner ;) I use that option all the time ;)

**Comment by moose31608** [comment] 2020-03-15 22:26
After I translated how he was setting up the course. The start position is current vehicle. I was trying to set it up with south/west and etc. once I figured out how he was doing it I haven’t had any problems with seeding.

**Comment by moose31608** [comment] 2020-03-15 22:29
If you look at my picture it shows how my start position was set. It he would of said use current vehicle position it would of work

**Comment by Bobster82** [comment] 2020-03-15 22:49
> After I translated how he was setting up the course. The start position is current vehicle. I was trying to set it up with south/west and etc. once I figured out how he was doing it I haven’t had any problems with seeding.

Yeah its the same as pick a spot on the map, only with that option u need to drive to that spot first before u can create the route... i create most of the routes when im not even close to the field, thats why i use the pick a spot option....

Im glad its all working now for you, have fun!

**Comment by Tensuko** [comment] 2020-03-15 23:20
I just figured out how you created this Issue, now we know whats wring and how you can make it correct. I can rly say better start more on the side of the fiel and not on the corner.

Closing this one but still can comment.

**Closed by Tensuko** 2020-03-15 23:20 UTC

**Comment by moose31608** [comment] 2020-03-15 23:51
All my courses I was setting up was that way with the start position south/west and etc. sorry if I was a ass about it

**Comment by Tensuko** [comment] 2020-03-16 09:54
It is ok, but all I can tell you is, that it works a lot better when you start more on the Side of a Field, when you use Headlands.
It does a better pattern on the Field and the Multitool Calculation will work then.

Hope it works for you now :)

**Comment by moose31608** [comment] 2020-03-16 22:28
When you set up a course do you save it and use it for both tractors

**Comment by Tensuko** [comment] 2020-03-16 22:37
Yes, but you can also copy the course from the 1st tractor.

**Comment by moose31608** [comment] 2020-03-16 23:29
Ok thanks. I was making a course for each one

**Comment by moose31608** [comment] 2020-03-17 15:25
I can remember when combining at the end of the field when the combine was unloading it stopped until it was empty is there a way we could get that put back in

**Comment by Tensuko** [comment] 2020-03-17 15:42
I did request that on my own for a long time, but doesn't seem to be to interesting to implement :)
But you can be sure, it will come back soon or later... I don't give up on that :D

**Comment by moose31608** [comment] 2020-03-17 15:52
When it came out for fs19 it was like that then it disappeared

**Comment by hellridergit** [comment] 2020-06-08 13:01
This started to happen for me today, should I open a new issue? Perhaps bad merge?
