### ISSUE TITLE
Funny moment for you guys ^^

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#3832] opened 2019-05-24 00:31 UTC
Look at this default GIANT vehicle is this is a stupid AI collider right ?
![1](https://user-images.githubusercontent.com/25174503/58294669-b5984880-7dcb-11e9-86be-44a59305608e.png)
Br

**Comment by Tensuko** [comment] 2019-05-24 05:00
Duplicate of #3239
Closed.

**Closed by Tensuko** 2019-05-24 05:00 UTC
