### ISSUE TITLE
idea: save course by reference

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1077] opened 2015-02-27 13:32 UTC
I'm recording more and more multi usable courses, with crossings to merge and so on, to save ressources and keep the courseplay.xml as small as possible.

My now upcoming problem now is I have to attach and merge (in the right order!) courses to mix them up for the final course. Sometime I'm getting up to 11 combined courses. :sob: 

My wish is: To save such a combined course by reference, as courseplay is doing it already in the vehicles.xml also in the courseplay.xml. Maybe by another button "Save by reference"?
That way only the course-IDs would be written into that type of course and not all the waypoints, which are in the courseplay.xml already. Saving a **lot**.
And when loading such a type of course, load it as you do it for the saved combined courses in the vehicles.xml. 

Possible?

**Comment by JakobTischler** [comment] 2015-03-01 13:59
Duplicate of #698

**Closed by JakobTischler** 2015-03-01 13:59 UTC
Labels: suggestion
