### ISSUE TITLE
Tractor with trailer stops when it's full next to forager (mode 2)

### ISSUE THREAD

**Issue by Senkipt** [Courseplay/courseplay#6865] opened 2021-02-20 11:46 UTC
I have updated to v.43 and now when using the mode 2, when the trailer is full, it stops next to the combine and I have either to manually press "drive now" or stop the course and start from the first waypoint.

**Comment by Tensuko** [comment] 2021-02-20 12:25
#5272 https://github.com/Courseplay/courseplay/wiki

**Comment by Senkipt** [comment] 2021-02-20 17:08
https://gist.github.com/Senkipt/fcdb765ea421125735fc0285eb19d7fc

Hope this helps @Tensuko.

**Comment by Tensuko** [comment] 2021-02-20 17:42
Screenshot would be helpful (with debugs on) as I couldn't reproduce this right now.

**Comment by Senkipt** [comment] 2021-02-20 18:25
![Sem Título](https://user-images.githubusercontent.com/77023569/108604972-f2321300-73a8-11eb-9ba8-7a9713945600.jpg)

**Comment by Senkipt** [comment] 2021-02-20 18:27
@Tensuko I have tested with the standard Claas Trailer and it works fine. Can it be an issue with the increased fill level on this specific trailer?

**Comment by Tensuko** [comment] 2021-02-20 19:11
That could be the case.
I must say 240k is way to much.... I am surprized that the Tracktor is even able to pull this.
So if the Claas Trailer is able to do this just fine, I don't take it as CP Issue and will close this one then.

**Closed by Tensuko** 2021-02-20 19:11 UTC
Labels: Mode2/Mode3
