### ISSUE TITLE
No proper instructrions to harvester pipe and truck cover in mode 2 (Multiplayer)

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#4804] opened 2020-01-10 22:08 UTC
As you can see,, courseplay in multiplayer is not doing some events like pipe extending although is unloading, and cover out of the truck.

Is giving this error in the log
2020-01-10 22:59 Error: Running LUA method 'packetReceived'.
2020-01-10 22:59 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)

![image](https://user-images.githubusercontent.com/9979168/72189771-08c41780-33fe-11ea-959a-ef629414fa20.png)

**Comment by Mannie313** [comment] 2020-01-10 23:00
Das Gleiche wie # 4693

**Comment by Tensuko** [comment] 2020-01-11 12:45
Duplicate of #4693 
Closed.

**Closed by Tensuko** 2020-01-11 12:45 UTC
