### ISSUE TITLE
Delete old courses

### ISSUE THREAD

**Issue by TadelisGaming** [Courseplay/courseplay#5009] opened 2020-03-05 11:07 UTC
Hello, are only for my that issue you can't delete saved courses? Like you complete write course and save him with name but you can't delete it. Or that issiue its only on multiplayer courseplay? Thanks for answer and have a good day.

**Comment by Tensuko** [comment] 2020-03-05 13:39
Duplicate of #4840

Closed.

**Closed by Tensuko** 2020-03-05 13:39 UTC
