### ISSUE TITLE
lime spreading, helper stops after refilling.

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3392] opened 2019-03-12 18:51 UTC
Hey guys.
Have o oroblem with a field generated course limespreading and a added refilling course.
Tractor is MFseries7, with bredal K105 lime spreader 11.000 L fillvolume configured (without cover).
I generate a fieldwork course and add a refillcourse,
The work beginns,.if the spreader 7s empty, the tractor went to the.fill8ng course, stops by the LimeSilo, fill up to 11.000L and stops.
"sofort Abfahren" oder "weiterfahren" anklicken bringt nichts. 
Only fire the worker and hire the worker seems to be work.
The worker drive.to the last spread-wp and spread the rest of the field.
Sometimes, a little few rimes it is not so,
The driver beginn filling the spreader, but he dont wait for the spreader is full, he drive along the course normal, but only with ca 4.000 -8.000 L lime in the spreader.
Any ideas?
V 6.01.00127.
Screenshots and log (wich channel) can be send.
Lg
Andreas

**Comment by SirStranger1989** [comment] 2019-03-12 18:53
I think you did not click the "+" when combining courses. 
The fieldwork/spreader cours, you load by clicking the little folder icon. Adding the refill course should be done by clicking the folder icon with the Plus (+) sign in it.

**Comment by TinMen6** [comment] 2019-03-13 13:57
> 
> 
> I think you did not click the "+" when combining courses.
> The fieldwork/spreader cours, you load by clicking the little folder icon. Adding the refill course should be done by clicking the folder icon with the Plus (+) sign in it.

I have the same problem does not mater if i click the folder icon or +. And with the latest update when i want to start to spread lime and i click to start with the first point the tractor stops after the first point (it looks like there is a wait point in the course but there isn't)

**Comment by sootysax** [comment] 2019-03-14 01:56
still no one has posted a log...

**Comment by VS-Honk** [comment] 2019-03-14 11:21
Rubicon9000 stops after refilling, too. 
Helfer entlassen und neu eunstellen hilft nicht, er bleibt trotzdem stehen. (Wird beladen 9000/9000)
Here is my log file with dbg channel 19.
[log.txt](https://github.com/Courseplay/courseplay/files/2966102/log.txt)

**Comment by pvaiko** [comment] 2019-03-14 11:26
How about a log with debug channels 12 and 14?

**Comment by VS-Honk** [comment] 2019-03-14 11:32
ok.
[log.txt](https://github.com/Courseplay/courseplay/files/2966132/log.txt)
![20190314123038_1](https://user-images.githubusercontent.com/48553778/54353818-4678d800-4655-11e9-8276-2191b2d23b60.jpg)

**Comment by pvaiko** [comment] 2019-03-14 11:36
@ThomasGaertner ?

**Comment by andreasthu** [comment] 2019-03-14 13:16
Hello pvaiko.
I am meanwile in harvesting and plowing.
When i speead lime next i will post a log with channel  12 and 14.
Lg
Andreas

**Comment by ThomasGaertner** [comment] 2019-03-14 16:53
test 135 or higher and report

**Comment by VS-Honk** [comment] 2019-03-14 17:09
it works - one time. second time go through trigger - without waiting or loading

**Comment by VS-Honk** [comment] 2019-03-14 17:09
test it two times and with tha same and different rubicon

**Comment by VS-Honk** [comment] 2019-03-15 09:44
the same as #3412

**Comment by andreasthu** [comment] 2019-03-15 15:02
Testet today with v137 and it works.
Generate a fieldcourse and add (with + ) a refill course.
Lime spreader filled up to 100% at fillpoint and then the traktor drive away.
Some new issue:
When i generate a course and add a refillcourse, and hire the cp driver at any point at the refillcourse, he drive right to the last waypoint, but then he doesnt drive to wp1. He beginn fieldwork an a random point at the fieldwork area.
Lg
Andreas

**Comment by pvaiko** [comment] 2019-03-15 15:13
@andreasthu Please don't mix different problems in one issue. Your new one is a duplicate of #3407 (already a mix :() and should have been fixed by 138.

**Comment by pvaiko** [comment] 2019-03-15 15:13
Closing as the original problem is solved.

**Closed by pvaiko** 2019-03-15 15:13 UTC
Labels: waitingForUserAnswer
