### ISSUE TITLE
Problem w/ Islands When Creating Course

### ISSUE THREAD

**Issue by hpmc13** [Courseplay/courseplay#2533] opened 2018-01-03 17:48 UTC
I am trying to generate a course on Broxton Farms. The field was originally very small, but I expanded it a great deal with a plow. I plowed around a small lake in the field. When I attempt to generate a course for any implement (sower, cultivator, harvestor) I get a "Cannot generate course, move the tractor" or something along those lines, and the console has the following error:
stack traceback:
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/cp.lua:85: in function '__index'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/geo.lua:115: in function 'applyLowPassFilter'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/headland.lua:80: in function 'calculateHeadlandTrack'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/Island.lua:179: in function 'generateHeadlands'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/track.lua:310: in function 'setupIslands'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/track.lua:104: in function <E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/track.lua:96>
	[C]: in function 'xpcall'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/course-generator/cp.lua:85: in function 'generate'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/generateCourse.lua:97: in function 'generateCourse'
	[string "setfenv(1,FS17_CoursePlay5); courseplay:generateCourse(...)"]:1: in main chunk
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/input.lua:223: in function 'executeFunction'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/input.lua:199: in function 'setCourseplayFunc'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/input.lua:185: in function 'handleMouseClick'
	E:/HGames/FS17LiveMods/FS17_CoursePlay5/input.lua:64: in function 'mouseEvent'
	[string "dataS/scripts/vehicles/Vehicle.lua"]:2239: in function 'mouseEvent'
	[string "dataS/scripts/BaseMission.lua"]:1424: in function 'mouseEvent'
	[string "dataS/scripts/FSBaseMission.lua"]:2137: in function 'mouseEvent'
	[string "dataS/scripts/missions/mission00.lua"]:333: in function 'mouseEvent'
	[string "dataS/scripts/main.lua"]:1861: in function <[string "dataS/scripts/main.lua"]:1845>

I ran cpSaveAllFields and in the cpFields.xml file there are definitions for the island.

**Comment by pvajko** [comment] 2018-01-03 17:49
I need that cpFields.xml file.

**Comment by hpmc13** [comment] 2018-01-03 17:50
Sorry about that, slipped my mind:
[cpFields.xml.txt](https://github.com/Courseplay/courseplay/files/1601212/cpFields.xml.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/1601206/log.txt)

**Comment by pvajko** [comment] 2018-01-03 18:12
Somehow you made a very small island (4x1 meters at most) which my code can't handle, it's these four nodes:

        <islandNode2181 pos="655.50 600"/>
        <islandNode2182 pos="656.50 600"/>
        <islandNode2183 pos="657.50 600"/>
        <islandNode2184 pos="658.50 600"/>

See here in the red circle:

![image](https://user-images.githubusercontent.com/2379521/34533089-ee8e7a66-f0b8-11e7-8f6d-ca2034130743.png)

I guess it is not intentional so you could plow that area over and it'll work fine until I fix my code so it won't explode.

However, that island seems to be too big anyway for the current version to handle nicely, although the circle version may be ok. I'm currently working on a more sophisticated algorithm to handle these.

**Comment by hpmc13** [comment] 2018-01-03 18:22
Thanks very much. I'm not sure where that little spot is, but I'll hunt around until I find it. Thanks again.

**Comment by hpmc13** [comment] 2018-01-04 00:03
That worked perfectly. Turns out the small island was a little patch of nonfield grass that I missed when plowing. I had cut down a tree but forgotten to grind off the stump and the plow bumped over it, leaving the patch. Once I plowed it under CP worked perfectly. The Circle option worked but Simple did not (or at least it looked as though it wouldn't have when the course generated.)
Thanks again.

**Comment by lcc1211** [comment] 2018-01-11 21:42
@pvajko What is your recommendation for the minimum and maximum Island sizes?  I would like to use this feature and would not mind using the ground mod to resize them.

**Comment by pvajko** [comment] 2018-01-11 23:49
The maximum size for the 'simple' bypass mode is 6 times the work width, otherwise it won't work. There is no maximum for the circle mode but you'll waste a lot of time because every track intersecting the island will go around it. I have a 'big island' feature in the works for those cases but that'll take a couple of weeks to finish.

As for the minimum size, especially in circle mode it depends on the vehicle and the implement geometry, with wider implements you can handle smaller radius islands, otherwise the vehicle's turn radius is the limiting factor. I'd say 5 meter diameter is a safe minimum.

I haven't merged the fix for this issue to the master branch yet, but it was caused by an island consisting of 4 nodes in a row, meaning it was smaller than 4x1 meters.

**Closed** 2018-01-20 19:05 UTC
