### ISSUE TITLE
planting poplars

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5481] opened 2020-05-26 09:07 UTC
I tried to use the original Damcon to plant poplars but I found that, after planting the pallet that I had manually loaded, the machine continues to go on not planting anything anymore (no longer having seedlings to load). I had brought a trailer loaded with pallets of poplars to check that it went automatically once unloaded but nothing. I used version 6.02.00020 of the CP

The log:[log.txt](https://github.com/Courseplay/courseplay/files/4681073/log.txt)

**Comment by Tensuko** [comment] 2020-05-26 10:39
Duplicate of  #3967

**Closed by Tensuko** 2020-05-26 10:39 UTC
