### ISSUE TITLE
No longer Reversing Properly

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2427] opened 2017-11-03 01:03 UTC
I'm having difficulties on every single map I try with any tractor mod or vanilla with just about every large plow like the Titan 11 or the sowers like Lemkin Solitair 12. The tractor can no longer reverse straight back and ends up jackknifing. Started with the last several version of the dev version of CP.

**Comment by pvajko** [comment] 2017-11-03 02:23
Would help if you could be more specific, especially which turn maneuvers are we talking about here. Or a video. Or something.

**Comment by pops64** [comment] 2017-11-03 13:29
Did you update your game to 1.5.1(this is a yes for steam users) if so this is untested with CP

**Comment by lcc1211** [comment] 2017-11-03 18:38
I don't know how much more specific I can be. When the tractor goes in reverse - regardless of what maneuver it is following - ends up with the implement and the tractor in the shape of a V.  This isn't happening with small cultivators and sowers, but anything over 6 meters that is trailed. I can't do a screen recording anymore.

**Comment by pvajko** [comment] 2017-11-03 23:24
This is a duplicate of #2396

**Closed by pvajko** 2017-11-03 23:24 UTC
Labels: More Information Required, waitingForUserAnswer
