### ISSUE TITLE
mode10 is online, please test and report

### ISSUE THREAD

**Issue by ThomasGaertner** [Courseplay/courseplay#4101] opened 2019-08-17 15:09 UTC
Leveling and Compacting Mode is online. 
It has now 3 modes : filling up,  leveling and compacting
For all of them : create a course with the first point in the silo, move to a save position and set a wait point there, reverse back to the silo. The last point has to be outside the silo. 
You have to be able to reach every point in the silo from this position !!! 
The shovel / compacter must be attached to the rear !
- filling up: attach a leveler to the tractor , and tip into the first quarter of the silo. The tractor will push it to the rear of the silo and fill it up
- leveling: attach a leveler to the tractor , and tip into the first quarter of the silo. The tractor will calculate the height and level through the whole silo
- compacting: attach a compacter to the tractor , and tip into silo while driving through. The tractor will compact maybe level a bit 

in case of issues: debugChannel 10 , description of the situation and eventually a screenshot

**Comment by Th301** [comment] 2019-08-17 20:47
Hey Thomas, great to see, that mode 10 is back! :)
Here are my first findings:

I set up the course like it was in ls17 version. Think that fits to your explanation?

- the tractor sets the speed to 3 km/h when starting the course. when it arrives at the silo, it drives trough the silo with 20 km/h while compacting/leveling.
- when another tractor (in my case a AD Driver) is recognized, the speed is set again to 3 km/h to drive to the safe position.
- after the AD-Driver left the area, the tractor did not start its course again.
- when I pushed on "continue driving", it drove to the last point of the course but did not continue anyway
- since that happened, I can not manage it, to make him level the chaff again. There is a message, saying that the implement is wrong for that mode. (see screenshot)
![Mode10_issue](https://user-images.githubusercontent.com/25582092/63217145-fe4c6d00-c140-11e9-9eba-7415257a14ef.png)

**Comment by ThomasGaertner** [comment] 2019-08-17 22:52
this message appears, when you try to compact with a shield , your setting is now "leveling" and "filling while driving through" . this is just (or should be) possible with a compacter attached

**Comment by ShiresFarmer** [comment] 2019-08-18 08:15
Hi
I seem to only have 2 modes not 3,
filling   or
levelling and compacting


levelling and compacting keeps saying wrong tool for that mode, when I have a blade on

**Comment by Th301** [comment] 2019-08-18 09:04
So when I understood that correctly it is like:
- "leveling and compacting" with "tipping backwards" is leveling with a shield
- "leveling and compacting" with "tipping by drivethrough" is compacting with a compactor

**Comment by ThomasGaertner** [comment] 2019-08-18 14:26
yes it is

**Comment by SledgeHammer75** [comment] 2019-08-18 17:05
Right now "leveling and compacting while driving through" is a bit "bumpy"

After ~45 min of leveling and compacting silo middle is still bumpy and there is a bigger bump at the end of the fill course left. (silo was filled at 280.000 l at that point)
![silo](https://user-images.githubusercontent.com/50592123/63227823-0e208b80-c1eb-11e9-8228-e089c428a1c1.png)

Good news: recognition of the delivery tractor was flawless, Delivery tractor stopped till compactor was gone, compactor waited at designated spot and resumed work after areas was free again.

**Comment by SledgeHammer75** [comment] 2019-08-18 17:14
When fiddling with the debug options i noticed the log entry "silo is devided in x columns and y rows", where the columns seem to determine how many different routes the worker takes through the silo. 

This calculation should 100% be included for the silo filling in mode1, so the delivery tractor takes different routes through the silo, instead of alway dumping in the middle.

**Comment by Marko230** [comment] 2019-08-18 17:42
Hallo
bei mir bleibt der Traktor beim Aufschütten immer hinten an der Silowand hängen.
er schiebt und schiebt und schiebt.. erst wenn ich auf weiterfahren drücke , fährt er zum ersten Punkt, fährt wieder zurück und schiebt und schiebt und schiebt

![Verdichten](https://user-images.githubusercontent.com/51233639/63228178-dbc55d00-c1ef-11e9-8808-6bb705ebf8fc.png)

**Comment by SteelRodent** [comment] 2019-08-20 15:16
Disclaimer: I admit I didn't read your post properly and did my first test with a mode 1 driver filling from the back of the bunker (backing all the way to the rear end and then going forward while empty) because that's how it had to be done in FS17. I will admit this may have contributed to the problems I encountered getting the mode 10 driver to do anything at all. I will redo the fill course to the new way and test again, but just in case my failed result is of any use:

Used manual overload into mode 1 drivers set to reverse into the silage bunker and fill it from the back, so all the silage was at the back of the bunker.

So far, with 100,000-150,000 liter chaff in the bunker:
- In fill mode the camera detaches from the mode 10 driver as soon as it finds the chaff and the driver pushes the chaff out of the bunker. Had to stop CP and found no way to resume. Had to restart the game.
- In level/compact mode, guess because there was no chaff at the start of the silo, the mode 10 driver decided to do donuts just inside the trigger and never found the chaff.

After 4-5 trips or so the mode 1 driver dumped the chaff in front of the bunker and struggled to find his way back to the exit path, and crashed into the bunker wall where he got stuck. When I tried to restart the mode 10 driver after that it immediately broke (detached from the camera) and crashed into the bunker.

CP no longer responded at all after that, but managed to exit the game normally.

![20190820170040_1](https://user-images.githubusercontent.com/20990941/63359729-857e2880-c36d-11e9-8be1-8f741e791c9e.jpg)

[log.txt on gist](https://gist.github.com/SteelRodent/fa82a03defab5b2592811cd12ab583ce)

**Comment by SteelRodent** [comment] 2019-08-20 16:32
**test 2:**
Redid the mode 10 course so start is further inside the bunker and stop further outside. First 2 passes on levelling worked fine, on 3rd pass the blade (barely) collided with the left wall and tractor got stuck. CP broke and failed to continue after that. Had to restart the game.

**test 3:**
Set the blade width to 5.5 m (0.5 m more than the actual width), which used to help prevent colliding with the walls in FS17. Mode 10 drove one pass on leveling all the way through the bunker and then CP broke again. 

**test 4:**
Redid the mode 1 course to go just inside the bunker, but it still dumps way in front of it. Never used mode 1 in CP6 before, so not sure what's up with that. Tried levelling with Mode 10 driver again, but when it has to do the passes along the walls it fails and collides with the wall instead. It doesn't drive far enough out of the bunker to get lined up correctly for these passes, so it ends up going across the bunker instead of doing the actual pass. But it looks like as long as the chaff level is high enough, CP doesn't break like it did before.

The collision problem is the same whether it's running on filling or levelling. Also, the point where the mode 10 driver starts to push is behind the point where the mode 1 driver unloads, so most of the pile remains outside the bunker which apparently messes the mode 1 driver up even more.

![20190820180836_1](https://user-images.githubusercontent.com/20990941/63365032-11e11900-c377-11e9-9fe9-c4afd7319861.jpg)

On filling, the driver pushes against the bunker wall just like when it's on filling, but after a while it goes forward and then pushes the same pass at a smoother angle which lets it rub the wall all the way through.

I haven't gotten to the compacting yet or tried with AD drivers, but so far both mode 1 and 10 needs some adjustment for this to work properly. And I assume the offload code from mode 1 will eventually make its way into mode 2?

[log.txt on gist](https://gist.github.com/SteelRodent/da82c6554ffadef0a4504c54eab01c48)

Sidenote: I removed the mod that had an error, even though it wasn't active on this map.

**Comment by ThomasGaertner** [comment] 2019-08-20 20:51
@Marko230 : welches Silo ist das ?

**Comment by Marko230** [comment] 2019-08-20 21:06
@ThomasGaertner 
NfMarsch 2.2fix BGA Nord von vorne gesehen das Linke, das war mit der cp version 6.01.00283.1
aber ich muß sagen mit der cp version 6.01.00283.3 hatte ich damit keine Probleme mehr. Bin aber jetzt auch nicht mehr zum Testen gekommen.

**Comment by ThomasGaertner** [comment] 2019-08-20 21:08
@SteelRodent : try to move the last way point more away from the silo. Then the angle to the outer columns is not that steep and it should work better

**Comment by SteelRodent** [comment] 2019-08-21 14:07
@ThomasGaertner move the stop point further out and with CP286 it works smooth now.

Only minor issues remain:
- Occasionally the mode 10 driver gets stuck because the blade gets stuck on the bumps.
![20190821150933_1](https://user-images.githubusercontent.com/20990941/63438158-27644a80-c42c-11e9-8b16-d37743d352c7.jpg)
I've managed to wrestle the tractor free each time by driving further onto the pile and then speed forward, but I guess it'd be difficult to get CP to figure out how to get itself out of a situation like that.

- When I had to jump in the wheel loader and push a pile into the bunker that the mode 1 driver left way outside the bunker area, the mode 10 driver detected the wheel loader correctly and moved out of the way, but when I turned the wheel loader off again the mode 10 driver didn't resume. He just sat there. Disabled the driver and restarted it, and he did 1 path down the middle of the bunker and then went on break again. This was with it set to stop for all running engines.
*Switched it to only stop for CP drivers for now to keep it running.
[log.txt on gist](https://gist.github.com/SteelRodent/40602e1dade52c76f7953b3294343110)

**Comment by Bobster82** [comment] 2019-08-21 18:24
Hi, I did some small testing, this were my findings so far:

  ?? No leveling mode, only leveling&compacting and filling up, is leveling going to be added?

* When setting up the course for the level and compact (use the compacter, not the blade tool) 
  - settings: attached tool + at least 0.5m, better +1 (when going back into the bunker it scratched the wall so you need a bit of space between)
  - Startpoint inside the bunker.
  - Waitpoint outside the bunker (on a place close by, but not in the way) 
  - Stop point at least 2 vehicle length outside the bunker but inline with the bunker (else the leveler or compacter crash into the walls)

  !! mode-10 driver doesnt unfold the tool.
  !! When the mode-10 driver is outside the bunker it wont raise his tool.
  !! Cant select the bunker speed (backspeed, frontspeed, drive to safespot speed)
  ?? When compact level is 100% wait outside for the next load? Maybe faster then when the new load of chaff/grass needs to wait till mode-10 driver is on his safespot?


* When setting up the course for the filler (use the blade tool), same as level and compact.
  !! The 5m blade that can "hold" 12000 ltr is much more when used with CP (is that number changed in CP? its almost 40000 now, looks too heavy)
  ?? You can change the speed, but I like slower back speed then forward speed ;)


* When driver (mode-10) drives and you drive with a vehicle within his search range, he pulls out of the bunker to the safe spot, when out of the search range, mode-10 driver goes back in.
  !! But when u park that vehicle in his range, the mode-10 driver keeps waiting even if you turned the engine down of the parked vehicle (needs a restart of mode-10 driver or the parked vehicle moved)


Overall this mode looks good, some small tweaks and its ok for me ;)

**Comment by SteelRodent** [comment] 2019-08-21 19:10
Some more observation after I finished off the bunker:

- In either setting,  when the mode 10 driver ran over the side passes (which turn into 60 degree slopes) of the part of the pile that's already compacted, the tractor got wedged against the bunker wall almost every time and had to be rescued. 
- With the compactor, the driver lowers the front weight as well as the roller. It doesn't do that with the blade.
- My problem with the mode 1 driver dumping outside the bunker continued, so ended up doing the last trips myself. With the "stop for all running engines" on, it worked fine this way, only the tractor I drove had to exit the BGA completely before the mode 10 driver resumed. Believe it's the same issue Bobster ran into above, and what caused me to not be able to restart him before with the wheel loader still inside the area.
-- I think my problems with the mode 1 drivers were worse because I made the course so they had to reverse a U-turn into the bunker, and when it decided to dump outside it was at the start of the U-turn so the pile was way outside the bunker and the mode 10 driver's work zone. If it was a straight path it possibly wouldn't be as problematic, but there is not enough space for that in the Lapacho BGA. I'm sure you guys know better than me why it decided to unload so far out, but there really was never any reason for it.

**Comment by Bobster82** [comment] 2019-08-21 19:55
@SteelRodent , how is ur course for mode 1 into the bunker? Maybe its not far enough inside?
I saw with the same course a diff between mode 1 and 2, mode1 could go further into the bunker as mode2 drops almost outside... I know mode2 still needs to reworked..

**Comment by SteelRodent** [comment] 2019-08-22 12:15
@Bobster82 the course is made to reverse just about a full trailer length (using the small Strautman trailers) into the bunker, but at first it looked like it wouldn't reverse in when there was chaff on the floor and then as the bunker filled up it didn't reverse in at all, but just started dumping on the edge of the trigger while pulling away - but because it's a U-turn going around the bunker most of it ended up outside the path of the leveler. I have no idea how it's coded, but it _looks_ like it checks whether there's enough space before it starts to dump. Either way it, for whatever reason, stopped going into the bunker to dump after the first 10 trips or so. 

I may try to make it go further in next time I try it, but I found that in this case it was actually faster just doing the runs myself - the BGA on Lapacho is in the middle between the two fields I used, so it's not like it's far to drive. 

Mode 2 doesn't know what a silage bunker is yet, but the guys are aware of that. It just means trying to use it for making silage is mostly pointless for the time being.

**Comment by Bobster82** [comment] 2019-08-22 12:24
@SteelRodent , I have a route back into the bunker so the trailer drops as far to the back as posible... then the tractor with blade doesnt need to push it all to the back... when filling up the bunker, the trailer drops the chaff further to the front (if chaff is in the beginning of the bunker, the trailer will drop at the beginning)

> but I found that in this case it was actually faster just doing the runs myself

Doing it yourself is always faster, but this was merely for testing ;)

**Comment by Th301** [comment] 2019-08-23 19:49
I had some tests with the Mode 10 again. From my point of view, the leveling part of the mode does not fullfill its purpose. the Are that is checked for too much material is too small. there are a lot of bumps in the middle of the silo which are not leveled. At the End of the silo there is a big amount of material, which looks more like filling mode and not like leveling. Is there any possibility to make some fine tuning?

Another thing I found is, that the radius for detecting other vehicles is projected to both vehicles? The tractor pushing the material and the tractor bringing the material. This is a very good idea, until the chaff is unloaded. After that it leads to tractors stopping in the middle of the street (outside the bga) because the pusher started to move again and was close to the street before.

**Comment by SteelRodent** [comment] 2019-08-25 11:31
@Th301 the bumpyness comes from how Giants coded the silage. I doubt CP can do much to get around that. That is, when a vehicle is on top of the chaff the game says it's compacting and the pile shrinks massively under the vehicle, which makes the vehicle sink and the blade dips into the pile as well and then you get bumps. When doing it manually I've found it virtually impossible to avoid bumps because of this behaviour. When you try to smooth out the bumps it just sinks in elsewhere and you either get new bumps or make it worse. Even when using modded spreaders you get bumps because the machines sink in like you're driving in sand.

**Comment by ThomasGaertner** [comment] 2019-08-25 18:04
guys you did a great job to describe what the matter is, but I kinda lost the focus. 
Could you give me some short hints what is to improve and what can be kept ?
sorry Thanks

**Comment by Th301** [comment] 2019-08-27 13:22
@SteelRodent you are right. It is really impossible to get a silo without bumps while using a shield. The ongoing up and down really gets onto my nerves when I try to get it smooth ^^

**Comment by Flicher** [comment] 2019-08-27 19:02
Hello there

Im trying to you coursplay for the first time in FS19 and in a long time
I have tried a couple map to see if it was the silo that was the problem.
The Problem is sometimes then i turn CP on then it drives directly into to wall, as if it want to drive into the silo next to it
Other times it drives fine but when it get close to the wall it drive straight into the wall and gets stuck, see the photo
Im using the Leveling and Compacting mode with the Ingame Stego 485
I see my coursplay settings in the photo

Hope anyone can help me

![fsScreen_2019_08_27_20_54_51](https://user-images.githubusercontent.com/8807567/63799742-fe045c80-c90c-11e9-9eb9-97d5ced58c46.png)

**Comment by Bobster82** [comment] 2019-08-27 19:17
@Flicher , set the blade width to 6m ... around 0,5m to 1m wider then the tool

**Comment by Flicher** [comment] 2019-08-28 11:11
> @Flicher , set the blade width to 6m ... around 0,5m to 1m wider then the tool

Yes that worked on the map in the photo, so i went back to Felsbrunn and tried again and this is the result 
I tried to set it to 7.0m, didn't work.

![fsScreen_2019_08_28_13_02_45](https://user-images.githubusercontent.com/8807567/63850769-25067100-c995-11e9-896e-4eac95f940d7.png)

**Comment by Bobster82** [comment] 2019-08-28 11:13
@Flicher , maybe ur waitpoint is set too close to the bunker, try it a bit further outside?

**Comment by Flicher** [comment] 2019-08-28 11:33
> @Flicher , maybe ur waitpoint is set too close to the bunker, try it a bit further outside?

I will try that

**Comment by Natervater** [comment] 2019-09-05 00:54
Hello everyone, new to the GitHub but long time CP user. I've been testing mode 10 for a few days tweaking this and that. The mode seems to work fine starting out but encounters issues as time goes on. 

First test: Tractor ran course fine, began leveling as expected. Chaff trailer arrived, leveler did not move, tractors rammed, chaos ensued. Had to disable CP on both, leveler would not start back up. He would do one cycle of leveling then go to his wait point. No amount of adjusting made a difference. Had to record a new route.

2nd test: added chaff to silo for testing, leveler is only leveling about a quarter of the way in. Everything past this magic line doesn't get touched. Made multiple new routes, no difference. Added more chaff to coax him back further and didn't do anything. 

3rd test. Not CPs fault but more an observation. If a tractor is seeding a field nearby, it will muck up the whole process. I would guess it be any tractor operating nearby, this case was a seeder tractor. I assumed the leveler would pull up to his pause point, and the seeder would continue until he left the range. That works fine but the leveler will not resume work. Had to restart game to get CP to continue for leveler.

Test 4: incoming chaff deliveries are not being detected for some reason. I have deliveries coming in at 5mph, leveler ignores and continues working. Stopped all traffic on farm and tested again, process worked this time. Tested again, and failed the same way. The leveler is not moving out of the way. It seems to me that he is stuck on his loop and has to finish the leveling before proceeding to the pause point which I understand. However, the delivery tractor is not being told to stop and wait, he just barrels on through.

Test 5: Recorded all new routes after finding an updated version. New issue has occurred. Chaff delivery came in, leveler moved as expected. When the delivery tractor backs up to the silo, he doesn't wait for the trailer to unload. He just started pulling out, dumping chaff into the ground as he follows the route back to the field. Leveler resumed work as expected.

Test 6: New routes again, moved stop further back and kept leveler in more a straight line. Seems that the leveler program can only pause 1 tractors route at a time. Example: field behind BGA is getting seeded. The seeder enters the range of the leveler. Leveler pauses seeder and begins to move out of the way as if a delivery was coming. Leveler stops on pause, and the seeder continues. Chaff delivery comes in, leveler doesn't detect it, and backs right into the chaff trailer as it's dumping. Not sure how to fix this. It seems the leveler only checks for incoming tractors every so often. Goes back to the issue I had on test 4.

I hope all this helps somewhat. Let me know if I can help out any other way. Love the work you guys do, without CP, I just wouldn't be able to enjoy Farming Simulator.

All the best
-Natervater

**Comment by Natervater** [comment] 2019-09-05 21:14
So further testing today with the newest update. So far, the tractor is not detecting incoming traffic, not sure what the issue is. Also, he is not leveling past the first quarter of the silo. 
![Test](https://user-images.githubusercontent.com/54920173/64381124-77ccd200-d000-11e9-91ac-d3fd731c148d.png)

**Comment by kleinerblauer** [comment] 2019-09-08 17:17
I tried mode 10 as filling up with recognize all with motor on. The filling up is quite good until I have unloaded one carrier. The tractor in mode 10 isn't starting again and waiting. Even if I start him manually he will do the filling up 1 time and then wait.
Also I have the same issue like SteelRodent in mode 1.

**Comment by MtBakerScum** [comment] 2019-09-11 04:31
Is filling mode, supposed to be used on a close ended silo? My tractor keeps pushing through the pile of chaff its made at the end of the silo and pushing it out of the silo until it runs into a wall.  Its also not stopping when the fresh pile of chaff at the beginning of the bunker has been pushed to the back.  
Also my carters are unloading at the very beginning of the silo and not at the wait point ive set for them farther in, is this by design?

Ive haven't had success with leveling yet, but haven't gotten a chance to properly test it.

I've had pretty good success with compacting though

**Comment by bgo1973** [comment] 2019-09-11 17:29
Vorschlag für das Silageschieben:
Wäre es möglich, dass CP am Endpunkt des Kurses das Schild komplett absenkt? So könnte man vor dem Silo abkippen und auch beim Verdichten rausgefahrenes würde dann ins Silo geschoben werden. Ab dem Startpunkt im Silo kann CP dann beginnen das Schild nach eigener Berechnung zu heben. Momentan ist es ja so, dass CP das Schild immer ein Stück weit über dem Boden führt. Dadurch verteilt sich die Silage vor dem Silo immer weiter.

**Comment by Knowen** [comment] 2019-09-18 08:25
Can someone pleae explain me how i need to setup a course for this to work? 
I searched on YouTube for some examples, but sadly didn't find any good ones.
I assume, that i made some mistakes in recording the course.

Thanks!

**Comment by bgo1973** [comment] 2019-09-18 10:03
Maybe this one will help.
https://youtu.be/rYT0Gwomm3s

**Comment by Knowen** [comment] 2019-09-18 12:14
Looks good. Gonna try it later. Thanks @bgo1973

**Comment by deeg427** [comment] 2019-12-02 19:47
this is happening to me and i cant seem to make sense out of it.


https://youtu.be/nLb30VvkZhM

**Comment by Tensuko** [comment] 2020-01-15 17:57
I will close this Info Issue for clean up.
Any Issue you still have with Mode10 will stay open or you make a new one when that Issue doesn't exist for now.
Closed.

**Closed by Tensuko** 2020-01-15 17:57 UTC
Labels: infoFromDev

**Comment by SpiderTash** [comment] 2021-06-27 02:22
Is mode 10 disabled in 6.4?  I cannot select Mode 10 at all.
