### ISSUE TITLE
AD LUA Error and Callstacks with CP

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#5305] opened 2020-05-05 19:38 UTC
Hello guys
I had a Lua error, and every AI stop working. The game it is not freeze but I can't do much about it except Alt + F4 to exit.
It began to happen with version 6.02, and I tried again after each new update.
It doesn't happen as soon as I start playing, but after several hours of playing.
In this last one, I had several workers:
4 combines working on a field, 
6 unloaders for those 4 combines,  but with AD in command
2 balers on 2 different field,
3 CP drivers collecting and unloading bales on different fields.

I have to say that before the CP LUA error, there is one AD LUA error. But everything was working fine with version 6.01.399 on the same map, with the same amount of workers. So maybe the now CP version it is not getting along with AD now.
AD version was always  the latest 1.1.0.5 RC build
The error repeated itself until I close he game, making the log file reach 35MB, so I have to edit it to upload it
Let me know if you need anything else
[log.txt](https://github.com/Courseplay/courseplay/files/4583213/log.txt)

**Comment by answermanitou** [comment] 2020-05-05 20:49
What if try again without autodrive mod? 
U can use save backup to reproduce this.

**Comment by Tensuko** [comment] 2020-05-05 21:03
I also see several AD Errors first.
Doubt it is a CP Issue...

**Comment by masneoquil** [comment] 2020-05-05 21:16
I will try without AD, and will also open an issue on AD github cause maybe with this new CP version there is some thing different when using AD as Combi mode.
I'm not saying it is a CP issue, but since I only update CP, there must be an issue when AD is waiting for CP to call for an unloader.

**Comment by masneoquil** [comment] 2020-05-05 22:30
I tried to test it without AD but the unloader wont move.
Here is some screens, and the log with 4 7 12 and 14.

[log.txt](https://github.com/Courseplay/courseplay/files/4583984/log.txt)
![Screen1](https://user-images.githubusercontent.com/53353740/81122214-d12a2f80-8f06-11ea-8385-1610e207c3a4.jpg)
![Screen2](https://user-images.githubusercontent.com/53353740/81122226-d7201080-8f06-11ea-89a0-5fb9db847201.jpg)

**Comment by pvaiko** [comment] 2020-05-06 00:14
Looks like the pathfinder can't find a path to the combines, difficult to tell from here, but it'll have a problem when there isn't enough harvested area to drive to the combine.

**Comment by masneoquil** [comment] 2020-05-06 01:08
Even with Pathfinding disabled? 
I'was just starting that field, the combines are finishing the first of two headlands

**Comment by Tensuko** [comment] 2020-05-06 03:16
Pathfinding on/off should have no impact afaik. It does only work with the new pathfinder.

**Comment by betrox007** [comment] 2020-05-06 09:00
maybe you can try to create unloader route start from inside field, at least 3 node waypoint minimum,i have this problem too at first release mode 2, but when i try create start point inside the field its working, although need more than 1 minute for cp unloader to create path to combine

**Comment by Tensuko** [comment] 2020-05-06 09:25
Start and end point should be outside of the field...

**Comment by pvaiko** [comment] 2020-05-06 12:04
@Tensuko with the new Mode 2 it does not really matter where they are. I need to check what the pathfinder is doing with when it is turned off in the HUD.

**Comment by Tensuko** [comment] 2020-10-01 05:28
Having similar Issues about Pathfinder, not going to check on AD Errors.
Also this Issue is very old, closing...

**Closed by Tensuko** 2020-10-01 05:28 UTC
