### ISSUE TITLE
MP Failed to create new object with class id 41770 in initial object array

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#6957] opened 2021-03-06 18:31 UTC
Hello...  testing release 049 as requested.  I am still seeing the client stop at Synchronizing 29% when I try to reconnect to a MP session.  I see " Failed to create new object with class id 41770 in initial object array" in the logs, but I'm not sure if this is the direct reason.

If I stop the server and remove CP, then I am able to connect.  It also seems that I am able to connect the very first time I re-add CP.   Once I get the error above, I have to remove CP, start the session without CP, save without CP, and then I can re-add CP for one successful connection.  Logs attached.

[server_log.zip](https://github.com/Courseplay/courseplay/files/6095871/server_log.zip)
[client_log.zip](https://github.com/Courseplay/courseplay/files/6095872/client_log.zip)

**Comment by Tensuko** [comment] 2021-03-06 18:34
Search function is something rly nice and we even have this on GitHub!
#6871

**Comment by jspring0811** [comment] 2021-03-06 18:44
@Tensuko @pvaiko @schwiti6190
I don't believe this is a duplicate, as the object id here is different and the CP version is different.  I also have plenty enough experience testing CP, other mods, and developing my own software to know how to use the search function -- I do it every day.  Peter specifically requested that we test the latest release 049 to see if it addressed the issues that we had been seeing in earlier releases.  If you do not want me to help test MP then I will stop.

**Comment by pvaiko** [comment] 2021-03-06 19:24
@jspring0811 thanks for the feedback, wish I knew what is causing this, we were not able to reproduce it. BTW, I'm not sure class IDs are the same across multiple game instances, they may well be assigned dynamically, depending on who knows what...

Unfortunately we don't have a good way to activate debug flags before starting the game, I'd really love to have a log with all debugs activated. If I gave you an instrumented debug.lua file with all flags active (or a CP zipped release with that file) would you be able to test it?

**Comment by jspring0811** [comment] 2021-03-06 19:50
@pvaiko Yes thanks.  I can test with a custom debug.lua.

Question for you:  The issue appears reconnecting after a session.  So, given Session A and Session B, it appears that something happens during session A (could be several hours of game activity) that then causes an error to be reported later after disconnecting and then trying to connect again (Session B).   Would it be sufficient to have the instrumented debug.lua activated only during the startup of Session B where the client can not connect, or would it also need to be active durring the longer, original Session A?

**Comment by pvaiko** [comment] 2021-03-06 23:22
@jspring0811 yes, we can start with the client using the https://github.com/Courseplay/courseplay/blob/issue-6957/debug.lua when reconnecting, see if it helps. (you can just clone the branch https://github.com/Courseplay/courseplay/tree/issue-6957 to the mods folder on the client).

Thanks for testing.

**Comment by jspring0811** [comment] 2021-03-11 01:55
@pvaiko I was finally able to capture a test for this.   I have the client log and the server log, both with full CP debug.lua startup debugging turned on...   The client reaches Synchronizing 29% and that's it (never shows the Start button).

Full debug logs:
[cp_debug_startup_client_log.zip](https://github.com/Courseplay/courseplay/files/6119900/cp_debug_startup_client_log.zip)
[cp_debug_startup_server_log.zip](https://github.com/Courseplay/courseplay/files/6119902/cp_debug_startup_server_log.zip)

**Comment by Tensuko** [comment] 2021-03-13 11:58
What about the 6.03.00050 ?
I got information that it should work again.

**Comment by jspring0811** [comment] 2021-03-17 03:47
Yes, we have been using .050 for several days with no issues connecting.

There is still one error during connection, but it does not prevent the user from connecting. These messages appear just after the Synchronizing message and before the Synchronizing x% messages. I have no idea if these are related to CP at all, and they don't appear to be causing any issue:

![image](https://user-images.githubusercontent.com/48362683/111411934-d83ad600-86b1-11eb-9434-4acc3f7d9266.png)

-- Thanks, I think the original issue can be marked as resolved in .050.

**Comment by Tensuko** [comment] 2021-03-25 08:46
@jspring0811 setPipeEvent is a long known Error but actually everything works anyway.
You May try it with v00051 and if it works fine, you can close the Issue ?

**Comment by pvaiko** [comment] 2021-03-27 23:09
#6871 is where we track this

**Closed by pvaiko** 2021-03-27 23:09 UTC
Labels: MP General
