### ISSUE TITLE
Internal turn.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2005] opened 2017-04-23 17:24 UTC
Question. The tractor always turns correctly on the field, depending on the point "Internal turn" Yes or No. The сombine harvester always leaves the field without regard to the position indicated in this paragraph. Is it possible to fix this? Thank you!
![2017-04-24_00-48-31](https://cloud.githubusercontent.com/assets/26131714/25315732/a4cde320-288c-11e7-8818-d0c5eff15d6b.jpg)
![2017-04-24_00-51-43](https://cloud.githubusercontent.com/assets/26131714/25315734/a9c778d2-288c-11e7-8556-b01faa7f4f1b.jpg)
![2017-04-24_01-08-05](https://cloud.githubusercontent.com/assets/26131714/25315735/ad069f5a-288c-11e7-8766-23b3cbce400b.jpg)
![2017-04-24_01-09-58](https://cloud.githubusercontent.com/assets/26131714/25315736/af1c0456-288c-11e7-9420-e52167c074b4.jpg)

**Comment by pops64** [comment] 2017-04-23 18:41
I would have to say, No the combine harvester calculations get all wonky when they turn inside the field so it is disabled internally but @Satissis could give you a better answer.

**Comment by Blackmankot** [comment] 2017-04-24 04:18
@pops64 Thank you!

**Comment by pops64** [comment] 2017-06-01 19:01
I am going to close this out. Harvesters are by designed to ignore that. I may in the future just hide that setting if you are in a combine.

**Closed by pops64** 2017-06-01 19:01 UTC
Labels: question

**Comment by Blackmankot** [comment] 2017-06-02 13:51
Clear.
