### ISSUE TITLE
Courseplay use Autodrive network to make courses - Issues and discussion

### ISSUE THREAD

**Issue by Emilioso007** [Courseplay/courseplay#4108] opened 2019-08-18 15:04 UTC
In the latest realease notes (283.1) you said: (You'll need AutoDrive 1.0.4.9 or later for this to work correctly)

AutoDrive 1.4.0.9 ins't avaliable yet, did you mean AutoDrive 1.0.4.8?

Otherwise, thanks for making such a great mod.

**Comment by raxtor** [comment] 2019-08-18 15:11
1.0.4.8 Courseplay_6/course_management.lua:1698: attempt to index global 'FS19_AutoDrive' (a nil value)
[log.txt](https://github.com/Courseplay/courseplay/files/3513167/log.txt)

**Comment by raxtor** [comment] 2019-08-18 15:21
CP panel died after loading AD course to vehicle...
FS19_Courseplay_6/hud.lua:418: attempt to index field 'Waypoints' (a nil value)
2019-08-18 17:19 Error: Running LUA method 'draw'.
[log.txt](https://github.com/Courseplay/courseplay/files/3513190/log.txt)

**Comment by alpha117** [comment] 2019-08-18 15:29
You need the latest version 1.4.0.8 AD, it works very well here. 

few issues, but it's a first to be honest. On a quick test the course speed from AD into CP is to fast...it was like a rocket. I like. So you can now combine an AD refill course with a CP field course..very good

Thanks to all for your hard work to get this together

**Comment by Bobster82** [comment] 2019-08-18 15:41
As comments are placed here, I will do i it too ;)

I did some small tests:
* Selecting AD destination in CP: It doesnt always get the right destination, it just stops in de middle.
* CP fieldwork + refill route: After fieldwork it used pathfinder to create a tmp route to the 1st point of the created route from ad tracks, then i drives to the refill point, then the route stops and the vehicle wants back to the field (cp doesnt creat the whole loop)
* Speed of the vehicle is way too high (always max speed, or cruise control speed)
* Vehicle doesnt stop at a end of the route (stop sign)

**Comment by alpha117** [comment] 2019-08-18 15:41
looks like the AD course are not importing correctly into CP. I'm getting more than one course being activated. Also if you drive the course at mach1 !!!!!  it does not represent the AD course

**Comment by pvaiko** [comment] 2019-08-18 16:18
@Emilioso007 @Stephan-S fixed the direction handling in AutoDrive 1.0.4.8 but has not created a new release yet.

**Comment by pvaiko** [comment] 2019-08-18 16:20
@Bobster82 so what should we use as the speed? Isn't it the street speed from CP?

**Comment by Bobster82** [comment] 2019-08-18 16:46
> @Bobster82 so what should we use as the speed? Isn't it the street speed from CP?

Street speed is ok, but the corners are also max speed... You cant define corner speed?

**Comment by raxtor** [comment] 2019-08-18 16:50
283.2 seems to be working... just is impossible set speed for course generated from AD... always set to max speed and no way change it.

**Comment by alpha117** [comment] 2019-08-18 18:23
I have an issue with 283.2, all was OK in 283.1

2019-08-18 19:19 :16 [dbg8 lp3499] 1050: Updating waypoint display for all
2019-08-18 19:19 :16 [dbg8 lp3499] 1050: Setting visibility for 0 waypoints, start/end=true all=false, xing=false
2019-08-18 19:19 :16 [dbg8 lp3499] 1050: updateCourseList(): reload courses true
2019-08-18 19:19 :16 [dbg8 lp3499] 1050: reloadVehicleCourses
2019-08-18 19:19 G:/FS19 Maps/FentonForest4X/FS19_Agribumper/agribumper.i3d (52.43 ms)
2019-08-18 19:19 data/shared/assets/lights/lizard/rearLightCircleWhite_02.i3d (1.03 ms)
2019-08-18 19:19 :16 [dbg8 lp3499] 1050: reloadCourses(..., true)
2019-08-18 19:19 :16 [dbg8 lp3499] 1050: loadCourse(..., id=10029, useRealId=true, addCourseAtEnd=false)
2019-08-18 19:19 Error: Running LUA method 'loadSharedI3DFileFinished'.
2019-08-18 19:19 G:/FS19 Maps/FentonForest4X/Courseplay_6_01_00283_2/course_management.lua:1791: attempt to index field 'spec_autodrive' (a nil value)

**Comment by pvaiko** [comment] 2019-08-18 21:04
@alpha117 and this is happening when exactly?

**Comment by pvaiko** [comment] 2019-08-18 21:12
@Bobster82 

> Vehicle doesnt stop at a end of the route (stop sign)

Do you have the 'Stop at last point' activated?

**Comment by alpha117** [comment] 2019-08-19 08:02
When selecting any AD course within CP, CP does not load the AD course., and the log says this (SEE ABOVE). Attached is the AD xml, perhaps and issue??  or file size?

Thanks

[AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip](https://github.com/Courseplay/courseplay/files/3514777/AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip)

**Comment by Tensuko** [comment] 2019-08-19 08:26
What is that Issue about now ?
The Question or a new Issue ?
Can we pls make a new Issue or rename this, when it is not about 1.0.4.8 or 1.0.4.9 couse 1.0.4.9 is out already....

**Comment by Bobster82** [comment] 2019-08-19 18:29
@pvaiko , did some more testing:
* Vehicle stops at end point when "stop at last point or trigger" is activated.
  - Finetuning-> The vehicle needs to brake some waypoints before the last point and stop exactly on the last point (vehicle overdrives and only brakes at last point)

*  Corner speed of vehicle is adjusted better. 
  - Finetuning-> Maybe brake before a corner (driving max speed into a corner is never good ;) )
                  Corner speed is still fast (can be good, but not realistic)


* Adding a destination in AD doesn't show up directly in CP (need to refresh in CP) (just a conclusion, if supposed, then leave it)

* Creating a course from AD destination doesn't always work. On my test map, I can't create any route to a piont after a certain point on the map, its just making a straight line to nothing. 
  (Driving manually behind that crossing, then create a course is doing well)
  Also when creating a course, CP doesn't always find the closest point to the vehicle (and sometimes it takes the point on the other side of the road, then the route would be way longer)
  This point needs some more work to get it to work, but the basics are good! (I'm happy to test)

     -->(speed of the vehicle on the ad course is way faster with CP driving then AD (sorry Stephan)

Going back to test some more, thanks for the update!

**Comment by pvaiko** [comment] 2019-08-19 19:03
@Bobster82 thanks for testing it, that's why it is beta, I just wanted to have some early feedback, especially if this a right direction...

> Also when creating a course, CP doesn't always find the closest point to the vehicle (and sometimes it takes the point on the other side of the road, then the route would be way longer)
This point needs some more work to get it to work,

This seems to be a common misunderstanding: CP **does not** create any courses, it just uses the course received from AD. So if you don't like the course for whatever reason, it is likely that CP can't do much about it.

**Comment by Bobster82** [comment] 2019-08-19 19:11
> @Bobster82 thanks for testing it, that's why it is beta, I just wanted to have some early feedback, especially if this a right direction...

> > Also when creating a course, CP doesn't always find the closest point to the vehicle (and sometimes it takes the point on the other side of the road, then the route would be way longer)
> > This point needs some more work to get it to work,
> 
> This seems to be a common misunderstanding: CP **does not** create any courses, it just uses the course received from AD. So if you don't like the course for whatever reason, it is likely that CP can't do much about it.

No problem, I like to test new things out.
I know it doesnt "create any waypoints" but it uses the waypoints ad had created. AD runs to all targets, but CP doesn't. I like the course AD has, but CP can't find the target for some reason. When I press start on AD, it drives to "test1" ... when i use CP, it just runs a straight line or a real strange route

**Comment by pvaiko** [comment] 2019-08-19 19:15
>  but CP can't find the target for some reason

No, again, CP does not look for targets, does not try to find a path. The entire course is delivered by AD. CP only tells AD the current position and the AD destination. Everything else is done by AD.

**Comment by Bobster82** [comment] 2019-08-19 19:23
Ok, But what i see is that CP makes a route from AD waypoints... Its adding a CP course line over AD lines. Its using CP to adjust the speed.

If CP is only a menu to select a AD target, then why when i press start on CP its not running AD, its running CP (in CP settings "use AD for refill, then when CP passes it to AD its running AD)

**Comment by pvaiko** [comment] 2019-08-19 19:28
>  CP makes a route from AD waypoints

No, AD makes the route from the AD waypoints and passes the route to CP. Which then becomes a CP route like any other CP route (generated or recorded), a series for points with two coordinates and can be driven by CP.

The 'use AD' is a completely different animal, there CP gives control of the vehicle to AD for the refill/unload course.

**Comment by Tensuko** [comment] 2019-08-19 19:32
Imagine, AD is a Street-Network, like a GPS.
Now you say, where you want to go, AD calculates the Route from your current position and creates the Route (in this case, waypoints to selected target), that information get sent over to your CP, wich is your self driving tracktor system. And then it is like a normal CP Course.

**Comment by Bobster82** [comment] 2019-08-19 19:39
Ok, I got it how u created it ;) (I thought CP only used the waypoints of AD and created its own route)
But then AD makes a fault with creating a route. You need a log or a video for what I try to describe?
Or does stephan needs to look at something?

**Comment by alpha117** [comment] 2019-08-19 19:43
Bob, what AD options have you go set?

**Comment by alpha117** [comment] 2019-08-19 19:44
I've just posted over here, which might help
https://github.com/Courseplay/courseplay/issues/3820#issuecomment-522696077

**Comment by Bobster82** [comment] 2019-08-19 19:51
> Bob, what AD options have you go set?

What you mean with options? This? : 
![ad1](https://user-images.githubusercontent.com/47780758/63294763-6c24a000-c2cb-11e9-8cc9-b350dcfb4472.JPG)
![ad2](https://user-images.githubusercontent.com/47780758/63294765-6c24a000-c2cb-11e9-8d05-793c465e623f.JPG)

**Comment by alpha117** [comment] 2019-08-19 19:56
Yep, cool

**Comment by Stephan-S** [comment] 2019-08-19 20:41
Hey guys, sorry for being so absent today. I'm on a business trip this week, so my time and answers will probably be limited in the next days.



>     * Adding a destination in AD doesn't show up directly in CP (need to refresh in CP) (just a conclusion, if supposed, then leave it)

@pvaiko If you're interested we could solve this with a simple publish/subscriber pattern, so you won't have to poll the information in intervals, if you wanna be up-to date on this info.



>     * Creating a course from AD destination doesn't always work. On my test map, I can't create any route to a piont after a certain point on the map, its just making a straight line to nothing.
>       (Driving manually behind that crossing, then create a course is doing well)

Could you explain this in more detail? I'm not sure I'm really getting the point here, sorry :(



>     * Also when creating a course, CP doesn't always find the closest point to the vehicle (and sometimes it takes the point on the other side of the road, then the route would be way longer)
>       This point needs some more work to get it to work, but the basics are good! (I'm happy to test)

From your settings pic later, I can presume, you are already on version 1.0.4.9. In this version, CP should actually get the same routes, AD would use itself when you activate it for a certain destination. So I am bit confused there. If you can 100% reproduce this, I would be really interested in a savegame I could fire up and debug what's going wrong there. But it should really be more of an AD issue here. From what I could see in the CP source, everything looks fine and even the min/max Distances are kept at AutoDrive default value.


>     * -->(speed of the vehicle on the ad course is way faster with CP driving then AD (sorry Stephan)

No offense taken :-) AD is just a more careful driver for now, like an old grandma behind the wheel. Not too fast but ususally get's where she wants to :D
I will probably add more parameters so you can tweak the speed and braking some more to your playstyle. But that's not on the priority list right now^^

**Comment by Bobster82** [comment] 2019-08-19 21:08
@Stephan-S ,thanks for the support ;)
Im just testing and writing my point of view, you coding guys are the heroes!
I just made a short video, I hope u can see what is happening. Dont mind the quality ;)
https://www.youtube.com/watch?v=UgieIvmLq14&feature=youtu.be

Also my savegame:
[savegame1.zip](https://github.com/Courseplay/courseplay/files/3517597/savegame1.zip)

**Comment by alpha117** [comment] 2019-08-20 08:28
Morning All

Just watched Bob,s video and noticed that the CP 2D display did not display correctly, like this
![image](https://user-images.githubusercontent.com/30005040/63330660-16ccab00-c32c-11e9-99cb-20f21dce8994.png)


I also had this issue previously on some routes around the AD network and likw Bob, CP failed to get to the destination. Any destination that displayed the CP 2D correctly(see above), worked OK. Currently testing ALL destinations with CP as so far cannot find one that fails with CP.

Bob, can you try this to see if you get the correct 2D display in CP when you select an AD destination


1. Rebuild network in AD (Update Ways in AD GUI)
2. Refresh CP AD destinations in CP
3. Close FS
4. Restart FS

Do you now get the correct 2D CP display like my screenshot.?

**Comment by alpha117** [comment] 2019-08-20 09:00
Bob, I've just used you AD network and using CP had no issues at all driving from/to any AD destinations

**Comment by Bobster82** [comment] 2019-08-20 10:03
> Bob, I've just used you AD network and using CP had no issues at all driving from/to any AD destinations
> 

Did you also tried it from the field1 side?
I can get to the park area from the silo side, but not the field1 side

**Comment by Stephan-S** [comment] 2019-08-20 10:29
Found a bug in the external interface of AD, which explains why your generated courses stopped in the middle of the track. I uploaded the fix but did not pack a new release yet. Can you test it again with this version? @Bobster82

**Comment by Stephan-S** [comment] 2019-08-20 10:30
What it doesn't explain is the moments in your video where the course started in the wrong direction. Is this still an issue?

**Comment by Bobster82** [comment] 2019-08-20 10:32
Im having a meeting now, will test it in about 2-3 hours. Thanks in advance

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by alpha117** [comment] 2019-08-20 11:29
OK I also found an issue, in Bob's course.  It now works just fine with this xml
[AutoDrive_Honey_Dew_Farms_XL_config.zip](https://github.com/Courseplay/courseplay/files/3520306/AutoDrive_Honey_Dew_Farms_XL_config.zip)

**Comment by alpha117** [comment] 2019-08-20 11:48
Just re-checked with the update AD and CP and using the xml from above all is good even from field 

Bob is good to go now at Honey Dew farm
![image](https://user-images.githubusercontent.com/30005040/63344609-b8fa8c00-c348-11e9-9e93-a27c1bbd1a71.png)

**Comment by Bobster82** [comment] 2019-08-20 13:06
@Stephan-S , @alpha117 ...
I just used the new code for AD. I can now reach every destination fine now. Thx stephan!

> What it doesn't explain is the moments in your video where the course started in the wrong direction. Is this still an issue?

Yes, its still an issue, but I think I found "the problem" The route is generated to the back of the vehicle. I will show it in the video:
https://www.youtube.com/watch?v=o0Tj5G2C1Ho&feature=youtu.be

**Comment by Bobster82** [comment] 2019-08-20 13:13
So what @pvaiko had created, its working almost fine now.

* Maybe a little more finetuning to the corners, braking before a corner instead of in a corner (or maybe add a setting where u can select the corner speed as well as the street speed?)
* Stopping at an end point or next trigger. Vehicle needs to brake earlier to stop exactly on the last point or trigger.
* Route generation needs an adjustment, as the route generated is facing the wrong side, as mentioned in my last post above.

**Comment by pvaiko** [comment] 2019-08-20 13:43
>  route generated is facing the wrong side,

I think that's something @Stephan-S needs to look at. I'll take care of the other two.

**Comment by Stephan-S** [comment] 2019-08-20 16:55
Yeah, I think I know why it only works half the time.
GetWorldRotation Return [0, 2*PI] wheras I was expecting [-PI, PI].
I will add a normalizaton to the values later. That should take care of it

**Comment by alpha117** [comment] 2019-08-20 17:52
https://github.com/Stephan-S/FS19_AutoDrive/issues/393

**Comment by Bobster82** [comment] 2019-08-22 10:59
> * Maybe a little more finetuning to the corners, braking before a corner instead of in a corner (or maybe add a setting where u can select the corner speed as well as the street speed?)
> * Stopping at an end point or next trigger. Vehicle needs to brake earlier to stop exactly on the last point or trigger.


* Vehicle is braking too early now, going at 15 km/h at least 4 vehicle lengths before the corner. But its working, only some finetuning (I know, I can be a bit fussy ;) ) (and I also dont know if I can adjust it myself or let u guys do the tuning)

* Stopping at the endpoint works,(you need to activate stop at endpoint, I always forget that) but also braking maybe too eary? But not a big thing.

* I dont know if this is new or allready was here, but when i had a speed limiter on 10 km/h, the vehicle drives the course at max 10 km/h.

Its getting there, thanks for your work @pvaiko 

(if needed, here's a log)
[log.txt](https://github.com/Courseplay/courseplay/files/3529741/log.txt)

**Comment by pvaiko** [comment] 2019-08-22 11:54
Thanks for testing, I know about the first 2, on the long term I'd like to have everything configurable to make everyone's life easier (here it'd be the lookahead distance like AD does it). I'm working on the framework for it and will start adding those parameters to the XML file and then to a screen later.

I haven't seen the third one, will look at it, not sure though if it is a bug or a feature.

**Comment by Bobster82** [comment] 2019-08-22 12:17
Thanks.
A configurable setting would be lovely.
CP should use max speed (as it was set in settings) not the cruisecontrol speed, in my opinion.


Maybe you are working on this too, but when I select in CP an AD destination, I can get a run from field to the silo, but not back (standing on the same point)... I had a work-around for it.

1st. Drive the vehicle one waypoint ahead of the AD field destination, then in CP select "silo"
2nd. Drive to the silo and go one waypoint ahead of the AD silo destination, then in CP select "field x"
now we have a close loop and can use for example mode2 on it ;)

Is it possible that when selecting a destination, the next destination is added after the last waypoint of the 1st destination?

**Comment by pvaiko** [comment] 2019-08-22 12:49
Yes that's next on my list, already started a discussion about it in the other issue a few days ago.

**Comment by pvaiko** [comment] 2019-08-22 12:52
BTW, does anyone have a fully loaded AD XML file for one of the standard/modhub maps? With lots of destinations?

**Comment by alpha117** [comment] 2019-08-22 12:55
I only have Fenton Forest4X I'm afraid

**Comment by Bobster82** [comment] 2019-08-22 13:01
No, but I can make one if needed ;)

**Comment by Emilioso007** [comment] 2019-08-22 13:05
Oakfield Farm

**Comment by Emilioso007** [comment] 2019-08-22 13:09
Oakfield Farm

**Comment by Tensuko** [comment] 2019-08-23 08:53
I got a working Network on Riesenbeck from LS-Modcompany. It is ModHub Map from Contest.
I will send you the Files later if I don't forget it...

**Comment by Th301** [comment] 2019-08-23 19:52
Since here is so much information now and new possibilities, I have, to be honest, a bit lost the overview, how to use these new things correctly. could anyone perhaps write a little "How-To" for perhaps collecting gras on the field and bringing it to the silo? Or how to exactly combine the field work with the virtual routes? That would be very nice! :)

**Comment by Bobster82** [comment] 2019-08-24 14:00
@Th301 ,
I tried to make a video for you about fieldwork with courseplay and autodrive:

https://www.youtube.com/watch?v=trgcyklnRQQ

**Comment by Th301** [comment] 2019-08-25 08:05
@Bobster82

Very cool, thank you!! Does it also work for Seeding/Fertilizing and Refilling with CP and virtual AD courses (like the first way in your video) ?

**Comment by Bobster82** [comment] 2019-08-25 10:54
@Th301 , yes both work pretty good! Just try the 2 out and see what u like the most... I dont know what cp and ad planning to do for how its going to work, but for now this works best

**Comment by ThisPf** [comment] 2019-08-28 08:17
I also started testing AD together with CP and read everything i can to understand how it works. I know, mode 2 is under rework. But for me, the current mode 2 works well if you know what to look for. My question: Current Mode 2 can also be combined with AD?

**Comment by Bobster82** [comment] 2019-08-28 08:31
@ThisPf , the way it can be combined is using the AD network and CP to drive it in mode2. you cant have cp to unload the combine and ad driving it to a sellpoint or silo.

Its the same as only using cp in mode2, but now u dont have to create the route urself if you have a ad network ;)
* Go to ur field waypoint, select mode2 select in courses the autodrive map, the silo route (return) or sellpoint route (return)
* select in combine options to search in field number or select a combine
*start ur course
* note! driving in mode2 is still max speed, so the corners wont go good unless u set the max speed lower ;)

**Comment by Stephan-S** [comment] 2019-08-28 08:36
@ThisPf Or you could give the AD unloader a try and see if that works for you. It's not as dynamic as CP's mode2 but at least it has collision detection and works better when the combine makes pockets.

**Comment by ThisPf** [comment] 2019-08-28 09:14
@Bobster82 , thanks for the exact description. 

@Stephan-S , das mache ich schon und funktioniert gut! Sofern ich keine Funktion übersehen habe, tankt AD aber immer im Stand ab, oder? 
Wenn ich den Drescher selbst fahre (meistens), tanke ich gerne während der Fahrt ab. Ich mache das meistens so, dass ich CP manuell rufe und wegschicke. Das bringt etwas Abwechslung rein und man muss sich während der (eigentlich ja eintönigen) Arbeit Gedanken zum geeigneten Zeitpunkt etc. machen. Zumal ich immer auf CP / AD-ungeeigneten Maps spiele und meine Herausforderung darin besteht, dass es trotzdem funktioniert. Mit der Beschreibung von Bobster82 könnte ich sogar wieder mal versuchen zu häckseln, jetzt wo CP wieder verteilen und verdichten kann.

**Comment by Tensuko** [comment] 2019-09-03 05:17
Closing this.
If there is something to discuss about CP-AD, pls use this one: #3820
Or make a new Issue if you face any trouble.

**Closed by Tensuko** 2019-09-03 05:17 UTC
Labels: waitingForUserAnswer
