### ISSUE TITLE
Headland settings not working properly

### ISSUE THREAD

**Issue by ElfVierzehn** [Courseplay/courseplay#3360] opened 2019-03-04 19:11 UTC
This is the log, description is below. Courseplay version: 6.01.00108

https://pastebin.com/embed_iframe/kxYjFp0r

I use this Mb-trac: https://www.modhoster.de/mods/mb-trac-1300-1800--2      in combination with the Horsch 9-meter seeder. (My issue also happens with standard Giants tractors).

I want to seed and fertilize the field at the same time, pre-turn set to after the fieldwork and set to 3 lanes. However, when I generate the course pre-turning is set to 1 and also the course is only generated with 1 lane at its end. Kinda weird situation.

**Comment by pvaiko** [comment] 2019-03-05 00:14
Are you using the HUD or the Advanced Course Generator screen?

**Comment by sootysax** [comment] 2019-03-05 01:07
> Are you using the HUD or the Advanced Course Generator screen?

Is there a difference, for the same course generated between the two?

**Comment by pvaiko** [comment] 2019-03-05 01:57
@sootysax not officially :) The HUD part isn't really maintained anymore and if it turns out that it works with the Course Gen screen but not with the HUD it'll go into the won't fix category.

**Comment by Tensuko** [comment] 2019-03-05 06:06
I would suggest to just turn off the normal HUD Course Gen and use the Menue as a Field Scanner (wich you do on the start/stop driver Menue).
Maybe with some advanced options like Name the new scaned Fieldborder as you want e.g. Grassland01 or anything like that. Would be awesome if that is possible! As I combine 2 fields I always wonder what number to give. If can make the name for F03+F09 for example thats makes things rly comfi.

I can put that in another issue section as suggestion if you want.

**Comment by GeorgeEarslight** [comment] 2019-03-05 06:23
> @sootysax not officially :) The HUD part isn't really maintained anymore and if it turns out that it works with the Course Gen screen but not with the HUD it'll go into the won't fix category.

If I'm not mistaken the option to "return to start" is missing from the Adv Course Gen.

**Comment by ElfVierzehn** [comment] 2019-03-05 13:27
Thanks for changing the title. I was a bit overstrained with my limited English knowledge.

> Are you using the HUD or the Advanced Course Generator screen?
I am using the HUD, never used any other menu but the one I can open up with right click/CTRL Del.

But I tried it with the menu, too after I read your answers. I made a short video and linked it below. 

https://youtu.be/l_sle_zflb4



> I always wonder what number to give.

I always use the smallest number of the fields I combine. Works quite well.

**Comment by pvaiko** [comment] 2019-03-05 13:45
Thanks for the video. I think this is a feature, not a bug. The number of headlands is reset to 1 because you can't fit more headlands into this corner:

![image](https://user-images.githubusercontent.com/2379521/53809568-9f8c9180-3f1a-11e9-9f07-18b9385a4ca8.png)

**Comment by ElfVierzehn** [comment] 2019-03-05 13:51
> Thanks for the video. I think this is a feature, not a bug. The number of headlands is reset to 1 because you can't fit more headlands into this corner:


I thought so, too.

But it did work once - also with this CP-version I am using right now. The tractor was just driving there, without actually working. He just passed the are with the tool lifted. I was quite impressed by how it worked.

I will try with other fields later today, and I will also get rid of this little corner. I am planning on building a small shed there. 

Thanks for your answer. You are probably right. I really would like to see it work with 3 lanes of headlands again - just to show it worked that way, too.

**Comment by pvaiko** [comment] 2019-03-05 13:55
Well, it depends on the work width as well, you may have had a narrower implement when it worked.

**Comment by ElfVierzehn** [comment] 2019-03-05 14:48
I could replicate it with the 9-meter implement. The only difference between the settings I made before is the used headland variant. Before I used 'sharp', now I used 'soft' if this is translated correctly. Screen attached.

https://imgur.com/AVLlWGp

**Comment by pvaiko** [comment] 2019-03-05 14:53
Yeah, I see. We have no support for those little nooks in the generator. Would be nice to have some day, but there are too many other important things to do. Will close this one for now.

**Closed by pvaiko** 2019-03-05 14:53 UTC

**Comment by ElfVierzehn** [comment] 2019-03-05 15:02
That's fine for me and fair enough for such a powerful tool. I now know the 'issue' and know how to prevent it from happening. Thanks for your support. This issue is solved.
