### ISSUE TITLE
Mex 5 turn maneuver is weird 

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1634] opened 2017-01-13 05:08 UTC
EDITED: Had typo and clarity 
Mex 5 both turn maneuvers behave weirdly. The turn on the field kinks out at the very end(Doesn't turn on the field either). And turn off the field doesn't lower until the trailer is on the field.  Also turn off field is an extreme example of what happens to most things that don't use a 3 point when it has a forward attached cutter(sugar beet, potato doesn't do it i think the turn radius for the potato is big enough to compensate) See pics below and [log](http://pastebin.com/uupyu9wj) Sorry if this is related to one of the other issues about turn maneuvers. Thanks for reading. Love the new turn maneuvers way better than 15 and default AI

Turn On Field
![farming simulator 17 1_12_2017 11_59_57 pm](https://cloud.githubusercontent.com/assets/10678220/21918848/82358f6a-d923-11e6-86da-7e7e3bb60e06.png)

Turn Off Field
![farming simulator 17 1_13_2017 12_00_50 am](https://cloud.githubusercontent.com/assets/10678220/21918849/83ebe9a8-d923-11e6-8cda-ffc80d91d293.png)

**Comment by Satissis** [comment] 2017-01-15 17:56
Sorry haven't had a chance to look into it yet. It's the next thing in my line to look into, but will just not be today.
I have been working for one of the companies I'm today, so only had time to look into small changes that was needed to fix stuff.

**Comment by pops64** [comment] 2017-01-15 19:14
It's all cool. It's still works its just isn't very pretty

**Comment by Satissis** [comment] 2017-01-18 18:21
try again v01.0036 or newer.
The ohm turn tends to leave a tiny bit at the ends, just so you are aware of it.
To fix this, the ohm turn would need to me much longer than it is now, so we have to live with that. The Q-Turn is working fine, thou it turns over the crops. I could switch to the opposite turn circle for it, but it will turn outside the fields for the first 4-8 lanes, which makes it possible to crash into stuff outside the field.
Give me your opinion on this.

**Comment by pops64** [comment] 2017-01-18 19:55
The Ohm turn is much much better than what it was. It does suck that it takes up so much room. Regarding the Q-Turn. Is it possible to know exactly how much space it needs to turn opposite? Cause maybe it is possible to easily code in that if its with in the first 4-8 lanes to turn regular and then once it has enough room to turn opposite. Sort of like the 3 point turns when it gets to the last couple of lanes.  

My other suggestion which I don't think would easily be done would be adding your collision detection into the turn maneuvers :O(Or just create a square the size of the turn maneuver plus a little and if any objects are in side to turn on the field. Sorry if this makes no sense I have no clue how your collision detection works) So if it sees that it would run into something during any portion of the turn maneuver(besides vehicles) it would turn inside the field or do a regular Q turn. This would solve both problems. 

Thanks for reading and fixing this. Now I just wish Giants would give us a bulldozer so we could make GCV more CP friendly

P.S have you had a look at my post in 1561 I know your busy just wondering

**Comment by Satissis** [comment] 2017-01-19 16:16
yeah, the opposite turn, is about the size of the turn circle you can see ingame (which was 14m on my end)

Checking if it will run into anything while calculating the turn, is not that easy to do, thou we could make an fake collition box validate the turn, but I'm not sure I want to do that...... at least not yet.

**Comment by pops64** [comment] 2017-01-19 19:21
Yea I figured collision box would be the easiest. Maybe you could create an ingame image of how much room CP(Like the fields boundary display button but includes the length and width of all turns) needs to turn so if we see it would collide into something we could add headlands and check again with out having to run debug 14.  Thanks for reading

**Comment by Satissis** [comment] 2017-01-19 19:36
well as I said before, the oposite turn maneuver is roughly a bit smaller than the turn circle that you can adjust ingame, so let's say that it 14m, then divide that with the workwith (I think it's around 2.5m) then you have 6 when you round up, so that means that you would need 6 headlands to be inside the field with that turn maneuver :)

If we take the Ohm turn, then it would be around 14m(Turn Circle) + 3m(Extra distance to align up again), which will be around 7 headlands.

An button to show the turn space needed, would be do able, but would still require some time spend into it to make it workable. I'll have to think about that one :)

**Comment by pops64** [comment] 2017-01-19 19:48
Could you apply the same code you have when you get to the last few lanes of a field. To the first few lanes. and do Q turns Then once it gets far enough over to do opposite turns? This way minimize the driving over the crops.(I personally don't have that mod turned on at the moment. That no turn issuse I posted with the fertilizer on my custom F19 on should see how much crop driving the harvester does on that same corner)

**Comment by Satissis** [comment] 2017-01-20 12:35
Yeah it should be possible to do that very easily :) I actually thinking on adding an button above the turn inside field option, where you can chose what to use, or simply say that if it's an chopper/harvester, then do it the other way around, that way it will be automatic and no one have to change any settings for it :)

What's your thought on this ? (I'll implements one of the options (depending on your answerer) together with the fertilizer fix)

**Comment by pops64** [comment] 2017-01-20 19:16
I am for the button but I only have one concern about it. How are you going to describe this function in only a few words? I was thinking crop damage mod enable/disabled and placing it under settings(or above turn on field) but that probably will bring up more issues than calling it something else. 

I was initially leaning automatic but you would eventually just make it default behavior. As you would need to include Manure, Slurry and Fertilizer spreaders and other stuff I can't think of in this behavior. And for those of us that run 4 or so Courseplayers on the same field at the same time having the automatic behavior would get really interesting.

Thanks for reading. I really appreciate getting asked my opinion on these things :D. Thanks

**Comment by Satissis** [comment] 2017-01-21 22:30
I have implemented this in v01.0042 so try it out :)

**Comment by pops64** [comment] 2017-01-22 04:54
Was trying it out with the grimme beet havester. It was all good expect. If I remeber from 15 if the tipper was running with either of the cheap beet or potato harvester it would park 3 or 4 lanes over.  It seems to be parking only 1 lane now which becomes a tug a war when it tries to reverse or go forward. I will post this in my other issue about the grimme as well. Which leads me to that if the sugar beet harvester is allowed to reverse(I think it's coded so its not suppose to) to have it park futher down the lane so it is avoided as well has moving it over
![farming simulator 17 1_21_2017 11_49_15 pm](https://cloud.githubusercontent.com/assets/10678220/22180102/44da2da2-e034-11e6-8e28-5550178b4b7b.png)
 for that matter

**Comment by Satissis** [comment] 2017-01-22 11:55
@pops64 that's another issue, so please post that in it's own issue since it have nothing to do with the turn maneuver.
If the turn work as intended, please close this issue :)

**Closed** 2017-01-22 19:04 UTC
Labels: bug, enhancement, fixed, waitingForUserAnswer
