### ISSUE TITLE
Wide turn got wrong alignment to turn end point

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#6129] opened 2020-09-24 15:54 UTC
Don't know since when it happens, but with my 30m liquid manure spreader, the turn are ridiculous as the spreader leaves big patches of unworked area, because the driver cuts the turn way to narrow, see pic attached
![grafik](https://user-images.githubusercontent.com/21023840/94169278-ec361580-fe8e-11ea-8c36-ff0de000e695.png)

**Comment by Tensuko** [comment] 2020-09-24 15:59
logfile and screenshot with debugchannel 12 and 14.

**Comment by iljarogoff** [comment] 2020-09-24 16:09
[log.txt](https://github.com/Courseplay/courseplay/files/5277543/log.txt)
![fsScreen_2020_09_24_18_07_06](https://user-images.githubusercontent.com/21023840/94170975-ff49e500-fe90-11ea-8e1e-61c50394ec98.png)
![fsScreen_2020_09_24_18_07_16](https://user-images.githubusercontent.com/21023840/94170979-007b1200-fe91-11ea-9a61-7ce660b0aee7.png)
![fsScreen_2020_09_24_18_07_24](https://user-images.githubusercontent.com/21023840/94170985-01ac3f00-fe91-11ea-85a8-f01c7f22b72c.png)
![fsScreen_2020_09_24_18_07_36](https://user-images.githubusercontent.com/21023840/94170989-02dd6c00-fe91-11ea-8121-04dd72e1be2f.png)

**Comment by Tensuko** [comment] 2020-09-24 16:47
Yea this doesn't look like how it should be.

**Comment by enderwiggin07** [comment] 2020-10-10 03:04
I don't really call it an enhancement, this is a problem since release 57.  No matter how you set turn radius, auto or manual, turn on field active or deactive, headlands yes or no, seed/spray tools are turning sharp towards the first waypoint on the next row and missing big areas and ignoring settings.  This is new since version 57.

**Comment by enderwiggin07** [comment] 2020-10-10 03:05
You can make a 60m headland and set a 30m radius with the 30m seadhawk and he will make the identical bad turn as when he is set on auto turn radius (18m)

**Comment by pvaiko** [comment] 2020-11-18 17:32
Duplicate of #6330, fixed by 51f42ed

**Closed by pvaiko** 2020-11-18 17:32 UTC
Labels: enhancement
