### ISSUE TITLE
Start Driver to far away from 1st WP, Pathfinder will generate course, but will not turn on workmode at 1st WP.

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#6214] opened 2020-10-12 15:17 UTC
Due to the quarantine, I had to stay at home and play F s19.

When working with Courseplay, I found the following drawbacks.
1) mode 5 - after cleaning the field, I send the harvester from the field to the base, the game freezes (I wrote about this earlier)
2) mode 2 - the harvester removes the field only if it is located near the start point. If the starting point is far away from him, then when he approaches it, he gets on the route and just moves along it, without doing any work.
3) mode 2 - if an old crop of another crop comes across while cleaning the field, it stops cleaning and drove around the field in vain.
4) mode 10 - during operation,the tractor always gets used to one of the sides (no matter what working width it sets), and does not reach the other side.

**Comment by Tensuko** [comment] 2020-10-12 15:31
>     1. mode 5 - after cleaning the field, I send the harvester from the field to the base, the game freezes (I wrote about this earlier)

doubt about this



>     2\. mode 2 - the harvester removes the field only if it is located near the start point. If the starting point is far away from him, then when he approaches it, he gets on the route and just moves along it, without doing any work.

got nothing to do with Mode2, it would be Mode6 Fieldwork.



>     3\. mode 2 - if an old crop of another crop comes across while cleaning the field, it stops cleaning and drove around the field in vain.

Again, not Mode2, it would be Mode6 and the Problem is GIANTS Issue we can't do anything about that.



>     4\. mode 10 - during operation,the tractor always gets used to one of the sides (no matter what working width it sets), and does not reach the other side.

No Idea what you talking about

Overall, no details, no logfile and I am sure we have related Issues for what you rly mean...

**Comment by Tocik** [comment] 2020-10-15 10:33
Yes, indeed. Incorrectly specified the name of the modes.
Instead of "mode 2", it meant "mode 6".
In the attachment screenshots and log file of the problem.
The harvester reaches the starting point, gets on the route and just passes it (if it was not standing next to the starting point). If you run it near the starting point, it starts working without any problems.

![2 (2)](https://user-images.githubusercontent.com/65189100/96111849-71d73f00-0eea-11eb-960a-c7d1be845de6.jpg)
![2 (2) — копия](https://user-images.githubusercontent.com/65189100/96111853-73086c00-0eea-11eb-9816-b7c1a60138c5.jpg)
![2 (2) — копия — копия](https://user-images.githubusercontent.com/65189100/96111855-73a10280-0eea-11eb-848e-45379d762e39.jpg)
[log2.zip](https://github.com/Courseplay/courseplay/files/5384137/log2.zip)
![2 (1)](https://user-images.githubusercontent.com/65189100/96111857-74399900-0eea-11eb-9c7b-fbac95069907.jpg)

**Comment by Tocik** [comment] 2020-10-15 10:43
Here is an example and log file of the problem from point 1.

The game just stops. All equipment is in place. You can't control something using the keyboard, it stops working. After stopping, you can press 2-3 keys, and then the game does not respond to the keyboard. However, you can switch between techniques using the course play, but the game is stopped by accident. You can't even make a savegame.
![1 — копия](https://user-images.githubusercontent.com/65189100/96113145-6422b900-0eec-11eb-92e1-404802ba116b.jpg)
[log1.zip](https://github.com/Courseplay/courseplay/files/5384217/log1.zip)
![1](https://user-images.githubusercontent.com/65189100/96113149-65ec7c80-0eec-11eb-9c29-57ac6ecabce6.jpg)

**Comment by Tensuko** [comment] 2020-10-15 15:59
Throw (Version: 1.0.0.0) FS19_HorseHelper out, it comes with GlobalCompany.

Still don't know if this does mess with CP (Version: 0.6.4.2) FS19_GameExtension

The only real Issue I see here is Mode6 not starting if start from to far away from 1st waypoint.
The other one is a Callstack and I got no Idea from where that comes, maybe Mission vehicles ?
Or any Mod ? I don't rly know, reopen anyway...

**Comment by Tocik** [comment] 2020-10-15 16:53
Horse helper is disabled in this game.

This problem usually happens with combines that belong to me. The problem was noticed both with the combines from the mod and with the original ones.

**Comment by Tensuko** [comment] 2021-01-23 14:23
Could not reproduce this on 6.03.00027
Closing for now.

**Closed by Tensuko** 2021-01-23 14:23 UTC
Labels: enhancement
