### ISSUE TITLE
IC Control

### ISSUE THREAD

**Issue by TrakisJoci** [Courseplay/courseplay#4543] opened 2019-11-09 21:11 UTC
If I use courseplay mode, IC Control does not work.

**Comment by TrakisJoci** [comment] 2019-11-09 21:17
https://ls-portal.eu/john-deere-6030-premium-3/


I only used this 1 tractor mode and courseplay. The courseplay menu on this machine is cumbersome. IC Control does not work with Courseplay!

**Comment by Tensuko** [comment] 2019-11-09 21:46
Duplicate of #4185
Closed.

**Closed by Tensuko** 2019-11-09 21:46 UTC
