### ISSUE TITLE
CP and mod-vehicles

### ISSUE THREAD

**Issue by cabmac** [Courseplay/courseplay#1497] opened 2016-12-12 16:34 UTC
hi, i wonder that it isn´t mentioned until now. Is it possible to work with CP and mod-tractors?

**Comment by Satissis** [comment] 2016-12-12 16:47
yes it should work, but we are still in the no mod phase atm.
If for some reason you cant use cp on one of the mod tractors, it might be due to the naming of the CP zip file. Apparently the code we have for handling mods loaded after Courseplay does not work as intended anymore, so you will have to ad "ZZZ_" in front of the zip name if it's not already there.

**Comment by cabmac** [comment] 2016-12-12 17:05
ah, ok,that's it....  i wondered why it doesn't had the zzz.....

**Comment by Satissis** [comment] 2016-12-13 22:14
Closing to clean up issues

**Closed by Satissis** 2016-12-13 22:14 UTC
