### ISSUE TITLE
Dual tank trailers won't fully unload at tip trigger

### ISSUE THREAD

**Issue by ErikW0147** [Courseplay/courseplay#5079] opened 2020-03-20 13:50 UTC
Courseplay won't fully unload trailers that have two tanks, like the Pacesetter, it only unloads one tank. Maybe because it has to use the "U" key (default) to change the tip point (front or back)?

**Comment by Tensuko** [comment] 2020-03-20 14:21
Duplicate of #3060

Closed.

**Closed by Tensuko** 2020-03-20 14:21 UTC
