### ISSUE TITLE
Turns do not include offset of tool in calc(3 Point)

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#6059] opened 2020-09-12 03:49 UTC
When a vehicle is doing a 3 point turn with a tool the offset is not included in the ending location of the turn this cause the tractor to steer to get back on course. I have not checked the other turn combos. [Log](https://pastebin.com/6nnZQ5Pi)
![fsScreen_2020_09_11_23_44_57](https://user-images.githubusercontent.com/10678220/92986479-1c41e980-f489-11ea-998b-3df8906e161c.png)
![fsScreen_2020_09_11_23_45_44](https://user-images.githubusercontent.com/10678220/92986480-1cda8000-f489-11ea-9f18-bec2702437ef.png)

**Comment by Tensuko** [comment] 2020-09-12 06:23
Duplicate of #5097

**Closed by Tensuko** 2020-09-12 06:23 UTC

**Comment by pops64** [comment] 2020-09-12 06:27
Sorry nothing popped up on google. Cons of having 200+ issues
