### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#2441] opened 2017-11-09 13:12 UTC
Hi I'm having a repeating issue on the cornbelt map in that whenever an overloader is called to unload a combine the game drops to around 12fps from 60. this is on field 35 with 3 CR10.90 Combines and 2 Challenger articulated tractors with Coolamon chaser bins from the modhub. Once the vehicle reaches the combine the frames rise to around normal again. I have this error in the log. Thought it might be down to having pathfinding enabled but tried without and still no better.

Validity check failed in TransformGroup_setDirection: Direction is zero 
  ..\..\..\src\engine\app\ReflectionAndScriptBinding.cpp (3625): dirLen > 0.0001f
LUA call stack:
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (1854) : printCallstack
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (1120) : setCollisionDirection
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/turn.lua (730) : setTrafficCollision
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (787)
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/base.lua (925) : drive
  dataS/scripts/vehicles/Vehicle.lua (2642) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1512) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1919) : update
dataS2/character/pedestrians/woman03.i3d (55.72) ms
Validity check failed in TransformGroup_setDirection: Direction is zero 
  ..\..\..\src\engine\app\ReflectionAndScriptBinding.cpp (3625): dirLen > 0.0001f
LUA call stack:
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (1854) : printCallstack
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (1120) : setCollisionDirection
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/turn.lua (730) : setTrafficCollision
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (787)
  =C:/Users/Richard Skelton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/base.lua (925) : drive
  dataS/scripts/vehicles/Vehicle.lua (2642) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1512) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1919) : update

**Comment by pops64** [comment] 2017-11-09 15:26
Full Log Please. And if possible savegame and courses has described here https://github.com/Courseplay/courseplay/wiki

**Comment by pvajko** [comment] 2017-11-09 15:49
Probably not needed, looks like a floating point issue, I think we just need to replace the == 0 comparisons with math.abs(  ) < 0.01

**Comment by lcc1211** [comment] 2017-11-10 00:19
Same issue for me on the Westbridge Hills map off Modhub.

**Comment by pvajko** [comment] 2017-11-10 02:11
Try with 2.00027 and report back.

**Comment by lcc1211** [comment] 2017-11-10 04:02
Is there a lower threshold than 20%.  I have 2 tractors with the "should be refueled soon" warning but they are continuing to plough.

**Comment by patch110** [comment] 2017-11-10 13:03
Try with 2.00027 and report back......

Hi tried that but the issue is still the same?

**Comment by lcc1211** [comment] 2017-11-10 13:06
I haven't seen the issue crop up for me since the 27 patch.

**Comment by patch110** [comment] 2017-11-10 13:46
Hi again this was using developer version from github. Have just switched to the versoin on modhub and it works a treat

**Comment by pvajko** [comment] 2017-11-10 14:04
@patch110 if you think you are still seeing the issue with 2.00027 then we need your complete log file.

**Comment by Roling51** [comment] 2017-11-12 08:27
Hello, I still have the same problem on the Cornbelt Map. Which debug levels should be enabled for the log.txt. CP version 2.00027
Regards Roling

**Comment by pvajko** [comment] 2017-11-12 13:38
If it is the exact same problem you should see the exact same error messages without turning on any debug channels.

If you don't see them, turn on 4, 9 and 14 for the first try. We may need to turn on 3 too but that's so verbose that it can cause lags itself.

**Comment by Roling51** [comment] 2017-11-12 16:32
I think it's the same problem even though there is no error in the log without debugchannel. At least not from me :). As soon as the tractor is on its way to the combine harvester, the frame rate is about 12 fps

Log without debug
https://gist.github.com/Roling51/dad91c98ae2283dd40eaf6c349c161ec

Log with debug
https://gist.github.com/Roling51/67490dc7fa87bb23e947b3823fc6bd01

**Comment by Roling51** [comment] 2017-11-12 18:06
Have looked back again. The problem can be reproduced from version 2.00020.

**Comment by pvajko** [comment] 2017-11-12 22:05
Thanks for tracking it down. This then goes to @ThomasGaertner, our mode 2 expert.

**Comment by SunkenL** [comment] 2017-11-21 12:45
Just updated to the .32 version here and i have exactly this problem on the broad acres map!

**Comment by MoslessNeo** [comment] 2017-11-22 02:34
I've been using version 018. It works great.
In the latest versions my fps crash when an overloaader (not in cp) unloads in a truck in grainTransport mode.
Even though I'm away the fps are low.
I do not know what was done. but something has changed. overall I have a lower performance compared to 018.
in my case I am using 14 cr1090, 8 overloaderd and 4 truck for transport.
the map is a 16x with the latest versions my fps get to 17! Normal is ~40 FPS.

**Comment by ThomasGaertner** [comment] 2017-11-22 19:26
can anyone provide me a clean download link to CornBelt Map 1.0.0.2 . I dont want do wait 4hours or support uploaded.to  :-(

**Comment by s1100** [comment] 2017-11-22 19:47
http://www.farming2015mods.com/farming-simulator-2017-mods/fs-17-maps/fs17-cornbelt-16fach-v1-0-0-2/

**Comment by ThomasGaertner** [comment] 2017-11-22 21:00
not clean , sorry

**Comment by narfviper** [comment] 2017-11-27 16:25
I have the same situation on the Map "Porta Westfalica V4.0".
With version 018 it works fine but at all later releases i have significant framedrops when an traktor start to drive in mode2 and trys to unload the combine.
When stopping the traktor in mode2 everything works fine again.

Download Link Map: https://www.modhoster.de/mods/porta-westfalica--2

**Comment by pvajko** [comment] 2017-11-27 16:34
@narfviper can you confirm that you see the lag in 019 but not in 018? What I'm trying to find out if it appeared in 019 (unlikely) or in 020.

**Comment by pvajko** [comment] 2017-11-27 16:42
I think it is dependent on the number of vehicles, not the map and may be caused by the new loop over all vehicles in the collision check.

**Comment by narfviper** [comment] 2017-11-27 19:10
I've tried 019 now (think i've skipped this version) still fine.

Since 020 this problem apears.
When the unloading Traktor starts to drive the framerate drops (traktor is pathfinding it's way to the point behind the combine) till it reaches the combine (unloader moving to pipe) then ist normal till unloading is finished.
When the unloading Traktor is moving to it's parking position the framerate drops again till it is parked, after that everything is fine again.

**Comment by pvajko** [comment] 2017-11-27 21:38
@narfviper thanks for checking. I think that confirms what I said, that it exactly the time when this collision check runs.

**Comment by pvajko** [comment] 2017-11-29 01:57
Please check with the latest version and report back. This is to confirm that the change in the collision detection is causing the lag.

**Comment by narfviper** [comment] 2017-11-29 16:23
This solved the Problem for me. Everything works as usual with the newest build (036).

**Comment by patch110** [comment] 2017-11-29 17:07
Yes problem is fixed now for too. 
Thaks

**Comment by Roling51** [comment] 2017-11-29 20:49
Yeah, works fine now. Thank you very much

**Comment by pvajko** [comment] 2017-11-29 21:54
Closing this but since this is not a real fix, just deactivating another fix, the original problem of collisions with combine headers still should be addressed.

**Closed by pvajko** 2017-11-29 21:54 UTC
