### ISSUE TITLE
Turning at end of row choppy

### ISSUE THREAD

**Issue by mpochylko** [Courseplay/courseplay#4258] opened 2019-09-17 05:10 UTC
Using the latest CP.

When equipment gets to the end of the row and turns the steering becomes choppy and stutters. In an articulating tractor (john deere 9rx from CM) the tractor makes a bit of turn the right way, then back the other way, then back again at about 1-6kms/hr. Eventually is just turns in a circle. 

Reg tractors are okay, but choppy and slow

Combines are ok but choppy and slow

Slow = less that programmed.

**Comment by Tensuko** [comment] 2019-09-17 07:23
logfile, what trctor exactly ? sounds like a mod from who ? CM, who is that ?

**Comment by cwattyeso** [comment] 2019-09-17 09:12
The John Deere 9RX Tractor and it's from Custom Modding, it should be on the ModHub or I might be confusing that and the 9RT. If it's not I know they plan to release it on the ModHub when it eventually gets through Giants testing, however PC Players can download it right now from their own website.

**Comment by GeorgeEarslight** [comment] 2019-09-17 11:22
@Tensuko Have encountered this also.
I assume it's the way the modded vehicle properties are written, not having enough information about it being articulated, so CP doesn't know how to deal with it.
OG CaseIH Quad works fine.

**Comment by Tensuko** [comment] 2019-09-17 13:38
I know there is a Modding Community who does good Models, but doesn't stick to GIANTS Standart, maybe it was CM, not sure.

**Comment by mpochylko** [comment] 2019-09-17 17:20
Custom Modding is the creator of the mod. I can try to get a log file when I get home. The 9rx is the worst for the stuttering turns. All other units do stutter but they can make the turn. 

By stutter I mean can't perform a smooth turn. The wheel jerks left and right as the turns are made. When not using CP6 the AI can negotiate a turn with no issue.

Are there any debug modes to activate during testing, and what video capture program would one recomend? I could just take 100 pictures and post to give an idea.

**Comment by mpochylko** [comment] 2019-09-18 03:27
[log.txt](https://github.com/Courseplay/courseplay/files/3624310/log.txt)

log file?

**Comment by mpochylko** [comment] 2019-09-19 02:09
Short video showing what happens. Eventually the tractor gets kind of on line, then backs up over everything and it's a real mess. 



[Farming Simulator 19 2019-09-18 20-05-14.zip](https://github.com/Courseplay/courseplay/files/3629015/Farming.Simulator.19.2019-09-18.20-05-14.zip)

**Comment by pvaiko** [comment] 2019-09-19 11:18
So let us know when this mod is on modhub and then we'll take a look.

**Comment by mpochylko** [comment] 2019-09-19 13:41
It's released for PC only, will it hit mod hub?

**Comment by Tensuko** [comment] 2019-09-19 14:02
Up to the modder and giants

**Comment by mpochylko** [comment] 2019-09-19 16:04
Okay. The john deere 8400 released on mod hub suffers the same turning issues. It can negotiate a turn but the wheel still jerks. I'm guessing that the scripting in the 9rx for its turning execution is causing the issue. I can post a video of the 8400 if you'd like?

**Comment by Trulight911** [comment] 2019-09-20 05:11
All AI vehicles while using courseplay are doing it on my end, not just a single tractor.  They didn't do it when courseplay was in an earlier beta, but now they do.

**Comment by mpochylko** [comment] 2019-09-20 05:29
Same, combines too. The only tractor that I have that can't make the turn is the 9rx.

**Comment by GeorgeEarslight** [comment] 2019-09-20 05:45
@Tensuko I think the last comments are relevant to what #4001 tried to solve.

**Comment by Tensuko** [comment] 2019-09-20 09:06
For me non of the AI Vehicles do it and I got far over 500 Mods (Error free except some .dds images missing). So hwo to find out what is causing the Issue.
Start with a Vanilla Savegame (take out all mods except CP) and try it again with different vehicles.
Add a ModMap that you like to play, the more different maps and sices the more Information we get.
Next is add Mod vehicles, or add some vehicles tools one by one like those steering and AWD Mods and stuff.
As I said I don't have it and can't reproduce that, or it is rly rly fine and hard to see, but even then I am not sure I got that Issue...

**Comment by GeorgeEarslight** [comment] 2019-09-20 10:18
Here's a fix for the JD 9RX. 
Proves that it's the vehicle mod's fault.

> Courseplay Fix

> (Updated August 19, 2019) Some players report about problems getting the tractor to work correctly with Courseplay. Thanks to Vincent, there is a fix that you could try. But I need to warn you. It involves editing the XML files, so please, make a backup of the mod before you try this solution.

> Here’s Vincent’s suggestion:

> Unzip the FS19_CM_JD_9RX .zip file.
Open the folder, and look for this file: 9RX.xml
Open it in Notepad or Notepad++.
Ok. With the XML file open, look for this section (starts at line 592):

> <ackermannSteeringConfigurations>
<ackermannSteering rotSpeed="25" rotMax="15" rotCenterWheel1="5" rotCenterWheel2="7"/>
</ackermannSteeringConfigurations>
</wheels>
<articulatedAxis componentJointIndex="1" anchorActor="0" rotSpeed="-25" rotMax="31" rotMin="-31" aiRevereserNode="aiReverserNode"/>

> Now, replace the values above, whit these ones:

<ackermannSteeringConfigurations>
<ackermannSteering rotSpeed="30" rotMax="15" rotCenter="0 -0.302"/>​
</ackermannSteeringConfigurations>​
</wheels>​​
<articulatedAxis componentJointIndex="1" anchorActor="0" rotSpeed="-30" rotMax="31" rotMin="-31" aiRevereserNode="aiReverserNode"/>

> When you’re finished, zip the file back together and give it the same name as before: FS19_CM_JD_9RX .zip.

Source: https://www.yesmods.com/fs19-mods/tractors/big-tractors/john-deere-9rx-cm/

**Comment by Trulight911** [comment] 2019-09-21 10:39
Ok i turned off all mods BUT courseplay, whenever ai goes to make any turn, it's like they are gassing, then letting off, then gassing again and letting off.  It's a courseplay issue.  When turning they go from 6mph to 3mph back and forth and back and forth.  I had put in an issue but they said it was a duplicate of this one, but it's not.

**Comment by mpochylko** [comment] 2019-09-22 06:04
@Georgeearslight 

Your solution almost works. Turn is less erratic but still overshoots the path

**Comment by Tensuko** [comment] 2019-09-26 05:14
If this happens to ModHub Mods, let us know, other we won't support.
Closed.

**Closed by Tensuko** 2019-09-26 05:14 UTC
