### ISSUE TITLE
Suggustion: Manual choice of turning behavior

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1575] opened 2016-12-31 16:51 UTC
Hey Dev's and fellow Coureplayers:
I'd like to suggest an option for the fieldworks modes, to manually chose the turningbehavior.
Choices:
Auto(Courseplay decides how to turn)
Reverse (Standart FS17 helper behavior aka tractor reverses, turns and reverses to start the next row)
Forward-Only (tractor will not reverse, taking the sharpest U-Turn needed to reach the next row)

This is especially neccessary for articulated tractors, like the Quadtrac, since those get stuck because the tool is angeled too shaply for the tractor when reversing...

Greets JD_Tiger

**Comment by Satissis** [comment] 2017-01-01 14:36
That's already in it. It's called Turn Inside Field (or something like that) in the combi settings

**Comment by piratqwert** [comment] 2017-01-01 14:47
combi settings doesn`t hawe Turn Inside Field.... and here is the problem
Turn Inside Field is only field work and seeding

**Comment by JDTiger** [comment] 2017-01-01 15:35
Yes and no, it is integrated but not how i meant it,
the problem is best seen when using a quadtrac with the Horsch 10LT, when set to turn on field, it jams up, when set to turn off the field, it either drives straight ahead without attempting to turn, or turns just like before, because there was an obstacle... setting the turningcircle manually doesn't help either...

**Comment by pops64** [comment] 2017-01-01 23:27
#1479 already discussed the problem is the reverse course is invalid

**Comment by Satissis** [comment] 2017-01-15 18:04
@piratqwert yes turn inside field is only available in fieldwork mode and seeding mode in the combi settings, since those are the only one that have the new turn maneuvers and wont effect anything else.

@JDTiger one of the modes you suggested, is using Giants turn behaviors ?
if that's the case, then that will not really be possible, not without having to do allot of rewriting and testing (If it even possible) so without that mode, the Turn on field is doing what you ask for except the giants turn ;)
It's not something I want to start looking into, since I believe that most of the bugs regarding the new turn stuff is now fixed and is working nicely, so if that's okay for you, can we close this one then ?

**Comment by JDTiger** [comment] 2017-01-15 18:53
yeah its okay...
Changed cultivator and now my machines turn properly...
Maybe you should implement a warning when trying to use CP with the Tiger 10 LT :P

**Comment by Satissis** [comment] 2017-01-21 21:52
I'll close this to cleanup the issues

**Closed by Satissis** 2017-01-21 21:52 UTC
