### ISSUE TITLE
No keyboard response

### ISSUE THREAD

**Issue by Mooniu** [Courseplay/courseplay#2182] opened 2017-07-15 12:09 UTC
Hello Guys,

i've got the problem, that LS17 freezes and no keyboard input is possible.
I cant drive a vehicle or go to the options to save the game. Only the end-Key is usable to show me the overview of the prices with is provided by the mod "CommodityPrices".

I play on the North-Frisian March Map and have about 10 vehicles running with courseplay simultaniously.

In the log-file i got many times Error: Running LUA method 'update' if the game is frozen.
CoursePlay is the newest version, and all mods are clear in the log.

I have attached my log-file.

Thanks for any help.
[log.txt](https://github.com/Courseplay/courseplay/files/1150287/log.txt)

**Comment by pvajko** [comment] 2017-07-15 12:21
I'm sorry, v1.0168 is not a fix for this issue, it was just too close to the other one :)

**Comment by pvajko** [comment] 2017-07-15 12:27
Seems to be caused by one of the vehicles (mod) not having the max turning radius.

**Comment by Mooniu** [comment] 2017-07-15 12:36
Ok. That means i have to find out, wich vehicle is the bad one :)

**Comment by pops64** [comment] 2017-07-15 12:59
Yea. CP doesn't support any mods with out this you can also find out by trying to use giants AI on all your mods. Giants also need this value.

**Comment by Biker23** [comment] 2017-07-16 07:55
I think I'm having the same issue. I had 4 combines going in circles "AIVehicleExtension" with 2 overloader tractors. In this case it was freezing to a point where I had to ALT+F4.
Reduced it down to  one combine and one tractor. It is still freezing, but just for a second every second so I am able to stop CP. It's doing it when their routes are in conflict "stuck in traffic". Also, it looks like the combine changes the way it turns and ends up doing something weird circle. The reason I think it's CP is because there is also a tiny freeze when the tractor starts it's route towards the combine. I will test today with a normal worker to see if it is still happening.
Thx

**Comment by pvajko** [comment] 2017-07-16 12:28
I think your issue is #2181, not this one. Try with 169 and report back there.

**Comment by pops64** [comment] 2017-07-16 13:08
AIVE requires two things to work correctly in CP. it requires like pvajko the most recent version and version 1.1b3 or higher of AIVE.

**Comment by Mooniu** [comment] 2017-07-16 14:40
Hello guys,
i've tried to start a new game without using the mod (Fendt 1000 Vario), which i think is the problem.
Until now i dont get the same error again but now i've got the next error of #2184. 
I will try the fix for this.

I think you can close this issue, because i think i have located the mod who causes the problem.

Thank a lot for your very fast help.
Great job with courseplay.

**Comment by pops64** [comment] 2017-07-16 15:10
Thanks. Closed to keep issues area clean

**Closed by pops64** 2017-07-16 15:10 UTC
Labels: Mod Conflict
