### ISSUE TITLE
Terra Dos T4-40 turning issue

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1727] opened 2017-02-01 21:19 UTC
I currently have a problem with the Terra Dos T4-40 turning after harvesting a field lane. Sometimes it will leave behind patches of beets and on a rare occurrence I found it may also get stuck turning in reverse. 

![20170201153545_1](https://cloud.githubusercontent.com/assets/16375855/22525878/1857a9c4-e897-11e6-8f79-5927a5527a9f.jpg)

In the picture above I captured it while it was stuck in reverse. You can also see in the picture the patches that was left behind.

My entire game session is in the log below. Near the bottom is where it got stuck turning in reverse.
[GIST](https://gist.github.com/8e0c14f44489f60bf94273709d363e46.git)

**EDIT:** Downloading latest version to see if problem(s) still occur

**EDIT2:** Upon my first minute in I encounter the problem a lot sooner that I initially expected. The Terra Dos T4-40 started to go in circles again while in reverse on the first turn at the end of the field.

![20170201163554_1](https://cloud.githubusercontent.com/assets/16375855/22527630/e347fc82-e89d-11e6-8cd5-1ba4c2b0b33e.jpg)

I was little late to capture it in the log but I'll try again and post the log.

**EDIT3:** [GIST2](https://gist.github.com/285d66146a4fff62d24d7db4fad4aa59.git)

**Comment by Satissis** [comment] 2017-02-05 18:57
I have looked a bit into this.
I vas not able to reproduce the circling backwards but it's still messed up when reversing. Somehow it does really not like reversing, which could be to the fact it's an articulated vehicle.
I have not found any solution to this so far. The only thing I can think of doing at this time is make it an none reverseable vehicle, which means it will make a bigger turn, but in my mind that is better than not being able to turn at all.

I'll wait and hear what all of you have in mind on this matter.

**Comment by DynamicXYZ** [comment] 2017-02-06 00:35
Thank you for looking into this. 

What about have it back up 4.5m then do a large hook turn that loops into the next lane?

The reasons I believe that this is happening is because it needs to go out farther in terms of line length and the radiant/degrees it stopped at before going forward/backward.

1. What I mean in line length is that the distance between where it starts to go in reverse and then where it goes forward again (Image 2). As you can see in the image (the tire tracks) it didn't fully reach the checkpoint and then be sent off in reverse. It's a little hard to see but the front cab of the Terra Dos just barely managed to reach the actual position of the point? Maybe it did go little farther.

2. When the Terra Dos stops to go in reverse it may still be in like a 15-20 degree turn state. So when it starts to back up it'll back up starting in that 15-20 degree state it stopped at. Which is most definitely one of the reasons why it goes off track a little bit and REALLY went off track in my second screenshot hence why it got stuck turning in circles in reverse. The second point Would it be possible to set it to 0 every time before it would reverse or go forward?

**Comment by lcc1211** [comment] 2017-02-06 01:16
Can't CP set it so that is steers rigid and then turn it much the way the grain combines turn?

**Comment by DynamicXYZ** [comment] 2017-02-06 19:54
How does backing up work for the Terra Dos speaking code wise? It's taking x2 amount of time on every turning angle it changes to. If you watch it closely with the reversing debug on try to make a visual picture in your head cut half the time it took for it to change turning direction and where it probably would have ended up relative to the center of the vehicle.

**Comment by Satissis** [comment] 2017-02-12 18:42
I haven't forgot about this, but are still testing and planing to see what I can do about it

**Comment by LordKena** [comment] 2017-02-16 12:27
I have exactly the same issue

**Comment by Danatru** [comment] 2017-02-22 12:28
The Terra Dos would refuse to do turns for me on automatic settings as well, just turned in circles and circles at the end of the field. Played around with the settings for awhile and I've got it working properly: turn speed 7km/h, reversing speed 4km/h, turn on field deactivated, opposite turn direction when possible, turning circle 10m,

**Comment by Satissis** [comment] 2017-02-23 21:43
Should be fixed in v01.0085.
Try it out and report back.

**Comment by Jestar342** [comment] 2017-02-24 02:34
I just came here to report this same turning issue, and I can confirm that v01.0085 fixed it. Thanks!

**Comment by DynamicXYZ** [comment] 2017-02-24 16:22
I'm waiting for beets to grow I'll report if it's also been fixed on my end.

**Comment by Satissis** [comment] 2017-02-24 16:36
@DynamicXYZ you don't need to have any beets ;) just run it on an generated fieldwork course and you should see it ;)

**Comment by DynamicXYZ** [comment] 2017-02-24 17:38
@Satissis Yes, thank you.

Could also make it so if "Turn on field" is activated it'll back up a few meters before doing the the turn maneuver?

**Comment by Satissis** [comment] 2017-02-24 19:28
The backing up a bit before making and turn..... It might be implemented later on, but since it's working right now, I really don't want to change anything else to it at the moment.
Just make a couple of headlands if you need a bit more space for the turn.
I did try change the turn to the same as normal combines do, which is taking less space, but it don't align up to the new lane that good, so stuck with the turn type it's doing right now.

The lifting of the header slightly too early, that could be the way how the automatic field edge scanning works, where it might not be 100% at the edge of the field. (My tests on the standard map didn't do that)
Again if it's a big problem, just make 1 headland before and it should also clear it up.

As regarding to this issue, the harvester now turn again, so I'll close here. If there is anything not related to this issue, please make an new issue about it ;)

**Closed by Satissis** 2017-02-24 19:28 UTC
Labels: fixed
