### ISSUE TITLE
Silos full

### ISSUE THREAD

**Issue by Peppobrasil** [Courseplay/courseplay#3984] opened 2019-07-20 08:23 UTC
I'd like a message and stop the trailer when the silo is full

**Comment by Tensuko** [comment] 2019-07-20 15:01
Isn't it already in, when the silo is full, that CP says, continue to next ?
@pvaiko ?
Unless it is Mode2....

**Comment by raxtor** [comment] 2019-08-11 15:29
When silo is full, unloader silently continues course to first waypoint. Result of this is full combine and full unloader. 1st msg which warrning you is X vehicle needs unload, than you find full unloader and than full silo. So he means if CP find full silo he should stop in trigger and display msg, "Silo is full"..

**Comment by Tensuko** [comment] 2019-08-14 19:11
Duplicate of #3513
Continue there.

**Closed by Tensuko** 2019-08-14 19:11 UTC
Labels: try to reproduce
