### ISSUE TITLE
LUA error with V6.02.00055

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#6056] opened 2020-09-11 15:47 UTC
Hi guys,

I just tried latest version and I had a bug : machines non responsive with some forced movement (like steering right all the time), not possible to switch from 1 vehicule to another, etc. Not much I could do except alt F4 to get out
I was using mode 1 to transport silage to BGA, loading with a telehandler
And I was sending a tractor to do soil preparation (mode 6 + course to the field)
[log.txt](https://github.com/Courseplay/courseplay/files/5210114/log.txt)
Just let me know if you need more info
This is SP
A few modes were used : Trailer https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=126991&title=fs2019 and cultivator https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=133969&title=fs2019

**Comment by Matt-14** [comment] 2020-09-11 15:54
I also have this issue. It happened to me as soon as I started driving. I didn't even start a courseplay driver or even open the HUD

**Comment by Tensuko** [comment] 2020-09-11 16:30
This Error is chasing us, damn it....

2020-09-11 17:41 Error: Running LUA method 'update'.
2020-09-11 17:41 C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua:57: attempt to call method 'is_a' (a nil value)

This one is new... @schwiti6190 any Idea ?

2020-09-11 17:41 Error: Running LUA method 'draw'.
2020-09-11 17:41 C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua:613: attempt to index field 'cp' (a nil value)

**Comment by pvaiko** [comment] 2020-09-11 17:33
The root cause is further up, you just missed it, it is the StrawHarvest stuff by @GeorgeEarslight:
```
2020-09-11 17:37 LUA call stack:
2020-09-11 17:37   =C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua (44) : printCallstack
2020-09-11 17:37   =C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/UnloadableFieldworkAIDriver.lua (64) : __index
2020-09-11 17:37   =[C] (4294967295)
2020-09-11 17:37   =C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua (44) : xpcall
2020-09-11 17:37   =C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua (21) : setAIDriver
2020-09-11 17:37   =C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (1412) : setCpMode
2020-09-11 17:37   =C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (584) : loadVehicleCPSettings
2020-09-11 17:37   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2020-09-11 17:37   dataS/scripts/vehicles/Vehicle.lua (659) : raiseEvent

**Comment by Tensuko** [comment] 2020-09-11 18:52
Can you try to add StrawHarvest and see if the Issue still exists ?

**Comment by polosubtil** [comment] 2020-09-11 19:00
So you want me to download and activate the mode StrawHarvest ?
Should I buy or do anything with it ? Not sure what it does, I never used it

**Comment by pvaiko** [comment] 2020-09-11 19:36
@polosubtil sorry, I thought I pushed the fix an hour ago, 56 should be in the releases now.

**Closed** 2020-09-11 19:36 UTC
Labels: bug

**Comment by polosubtil** [comment] 2020-09-11 20:50
Thanks a lot @pvaiko, works like a charm now ;)
