### ISSUE TITLE
Waiting for waiting position to be free...  forever & Combine Finder

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1904] opened 2017-03-18 10:38 UTC
https://gist.github.com/sootysax/364a14ca68caa36312c68eae73bdc162

Combine filling trailer at end of row..   tractor is 'waiting for waiting point to be free'..  shuts off engine and takes a nap.. 
When 
Also:

there are mode 2 issues.   automatic finding not working
manual finding often the tractor will not be called until the combine is at 100% regardless of setting

![2017-03-18_064148275](https://cloud.githubusercontent.com/assets/6591048/24071357/2a01d000-0ba6-11e7-9a58-62c2272d95e8.PNG)

![2017-03-18_064216167](https://cloud.githubusercontent.com/assets/6591048/24071358/2de57a0a-0ba6-11e7-9142-2fa175791e38.PNG)

**Comment by pops64** [comment] 2017-03-18 18:49
Is this only occurring when the Harvester has finished work? Or are you running the harvester on giants AI?  Log with debug channel 4 please

**Comment by sootysax** [comment] 2017-03-19 02:32
no it happens at the end of every row (when the tractor is unloading at the end of the row)

**Comment by pops64** [comment] 2017-03-19 16:06
Did you start debug 4 before starting the tipper? Are you running giants or CP AI for the harvester? Has this may be a problem of giants being block by the tipper and if I remember correctly the tipper always waits for the harvester to move out of the way even if it is giants AI.

**Comment by dkfiremann** [comment] 2017-03-19 17:28
Your log does not have any information fra the dabug channel 4. 
Did you make that log with debug 4 enabled in the tractor before you started the tractor?

**Comment by brnl** [comment] 2017-03-21 18:29
Ah, I got this problem too! I didn't notice it as a bug, because I was busy, but it did annoy me :-P
I'll see if I can reproduce this with debug 4 on. On which vehicle should it be enabled? All involved?

**Comment by brnl** [comment] 2017-03-21 22:17
Here is the log. Running with two unloaders (mode 2). The last two times it worked, though. https://gist.github.com/brnl/b8051431022601778e06efe5571a3119

Another thing that did happen twice this session was the tractor stopping in front of the combine, blocking its path:

![20170321230949_1](https://cloud.githubusercontent.com/assets/3243133/24173483/8c822f7a-0e8c-11e7-8a88-50a4d85a9268.jpg)

**Comment by pops64** [comment] 2017-03-22 03:09
The combine block the harvester is a different issue altogether.  With your log please run it again with **only** debug channel 4 running and **only** the tipper and the harvester running CP has described in https://github.com/Courseplay/courseplay/wiki

**Comment by sootysax** [comment] 2017-03-23 11:56
now its doing something different...  when the tractor is pulled up along side of the combine and unloading and reaching the end of the field, the combine and tractor just keep driving, past the end of the field and into the next field, or into the street...   the combine even did that when the tractor was stopped..  it seems to drive off the field whenever a tractor is assigned to the combine
https://gist.github.com/sootysax/622b1a0d0f4a159c95c781e893d14136

**Comment by pops64** [comment] 2017-03-23 15:03
Try again without​ aivehicle  mod enabled. Thanks

**Comment by sootysax** [comment] 2017-03-23 21:47
thats seems to have worked...

**Comment by pops64** [comment] 2017-03-23 23:04
I close this out then. If either of you still have issues just reply here and I will open it back up again. See #1701 for the status of AutoCombine/AIVehicle Extension

**Closed by pops64** 2017-03-23 23:04 UTC
Labels: waitingForUserAnswer
