### ISSUE TITLE
Combined courses with different modi

### ISSUE THREAD

**Issue by fpalmes** [Courseplay/courseplay#2147] opened 2017-06-30 09:25 UTC
Dear all, 
I have created two course.  one to collect Gras (Field mode), the other one I would like to use to bring it to the  bunker and get it off there. When I conmbine the two courses I only can select one modi which is used than for both courses, is there any chance to have a combined course with two modiies?

**Comment by Blackmankot** [comment] 2017-06-30 15:23
@fpalmes  Good afternoon. Describe the issue in more detail.

**Comment by Tensuko** [comment] 2017-07-04 05:55
This is what you are looking for: http://courseplay.github.io/courseplay/de/manual/index.html#driveMode6 just create a curse on field, then an extra curse for unloading. Load the field curse and then add (the folder with the +) the unload curse. As soon as the Tractor is full, it automatically starts to drive to the unload curse and when it drives back near the filed, it continuse on the field where he stopped last.

**Comment by Blackmankot** [comment] 2017-07-04 10:47
Here's a video of how to correctly combine courses.
https://youtu.be/DKoLerpmBso

**Comment by pops64** [comment] 2017-07-12 11:54
What is the status of this. Still have no clue what the issue is.

**Comment by Tensuko** [comment] 2017-07-12 12:37
I guess you can close it, looks like misunderstanding on how to combine field-work course with transportation course.

**Comment by pops64** [comment] 2017-07-16 13:14
Closed due to inactivity. @fpalmes  Post here if you can clarify this and I will reopen this.

**Closed by pops64** 2017-07-16 13:14 UTC
Labels: More Information Required
