### ISSUE TITLE
Corse generator getting stuck on Kandelin

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#4041] opened 2019-08-04 14:48 UTC
Hey,
I have the problem, that the Course generator is getting stuck (>45min generating time) on Fields 10&24 of the Kandelin map.

Is there anything i should improve in the settings for the generator?

![Capture101](https://user-images.githubusercontent.com/9157835/62425114-97a66880-b6d7-11e9-8b67-2bab530b6a35.PNG)
 screenshot of the PDA map and my generation settings.

Kind regards,
JDTiger

**Comment by Tensuko** [comment] 2019-08-04 15:37
You are on a Field war away for Field2 generating. Notsure if that cause the problem.
@pvaiko will need a logfile with debugchannel forcourse generation.

**Comment by JDTiger** [comment] 2019-08-04 16:04
you can just ignore the position i am at and the field selected at the moment, i jsut opened the dialog with a field selected to show the other settings (starting location,Bypass islands headland etc.)

what do i have to select to get the requiered logfile?

**Comment by Tensuko** [comment] 2019-08-04 16:06
You select the debugchannel 7 and create the course.
Then it will be printed in your logfile, that logfile you post here with drag and drop.
The Field Definitions might needed too, see here on how it works:
https://github.com/Courseplay/courseplay/wiki

**Comment by JDTiger** [comment] 2019-08-04 16:21
ok, will do that, as soon as the tractor has finished his work on the field its currently on...
for how long should i let it generate and write to the log?

**Comment by JDTiger** [comment] 2019-08-04 16:59
`2019-08-04 18:48 :44 [dbg7 lp6903] generateCourse() called for "Field 24"
2019-08-04 18:48 :44 [dbg7 lp6903] 8370 RT: hasGeneratedCourse=true, hasEnoughWaypoints=true, hasStartingCorner=true, hasStartingDirection=true, numCourses=1, fieldEdge.selectedField.fieldNum=24 ==> hasValidCourseGenerationData=true
2019-08-04 18:48 :44 [dbg7 lp6903] 8370 RT: hasGeneratedCourse=false, hasEnoughWaypoints=true, hasStartingCorner=true, hasStartingDirection=true, numCourses=0, fieldEdge.selectedField.fieldNum=24 ==> hasValidCourseGenerationData=true
2019-08-04 18:48 :45 [dbg7 lp6903] (1) SET UP CORNERS AND DIRECTIONS
2019-08-04 18:48 :45 [dbg7 lp6903] 8370 RT: Course starting location position selected on map at -269.3/-1373.3
2019-08-04 18:48 :45 [dbg7 lp6903] ####### COURSE GENERATOR START ##########################################################
2019-08-04 18:48 :45 [dbg7 lp6903] Headland mode normal, number of passes 3, center mode up/down
2019-08-04 18:48 :45 [dbg7 lp6903] Generating headland track with offset 7.80
2019-08-04 18:48 :58 [dbg7 lp6903] Generated headland track #1, area 1434717, clockwise = false
2019-08-04 18:48 :58 [dbg7 lp6903] Generating headland track with offset 14.51
2019-08-04 18:49 :39 [dbg7 lp6903] Generated headland track #2, area 1298294, clockwise = false
2019-08-04 18:49 :39 [dbg7 lp6903] Generating headland track with offset 14.51
2019-08-04 18:50 :12 [dbg7 lp6903] Generated headland track #3, area 1165768, clockwise = false
2019-08-04 18:50 :12 [dbg7 lp6903] Linked headland track 1 to next track, heading 228.5, distance 23.4, inwardAngle = 60
2019-08-04 18:50 :12 [dbg7 lp6903] Linked headland track 2 to next track, heading 227.9, distance 23.4, inwardAngle = 60
2019-08-04 18:50 :12 [dbg7 lp6903] ROW ANGLE: FINDING THE OPTIMUM ANGLE
2019-08-04 18:50 :15 [dbg7 lp6903] Best angle=116, nBlocks=18, nTracks=99, smallBlockScore=2, score=381.7
2019-08-04 18:50 :15 [dbg7 lp6903] Block 1 has 5 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 5 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 2 has 13 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 13 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 3 has 13 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 13 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 4 has 28 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 28 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 5 has 28 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 28 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 6 has 28 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 28 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 7 has 13 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 13 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 8 has 13 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 13 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 9 has 11 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 11 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 10 has 5 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Track 5 has only one waypoint, skipping.
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 4 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 11 has 5 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 5 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 12 has 5 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 5 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 13 has 7 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 7 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 14 has 7 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 7 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 15 has 6 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 6 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 16 has 4 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 4 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 17 has 4 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 4 tracks for this block
2019-08-04 18:50 :15 [dbg7 lp6903] Block 18 has 7 tracks
2019-08-04 18:50 :15 [dbg7 lp6903] Generated 7 tracks for this block
`

i have waited for 10min, no further entries...

**Comment by JDTiger** [comment] 2019-08-04 17:03
[log.txt](https://github.com/Courseplay/courseplay/files/3465106/log.txt)

I had to make a few tries with small changes in settings, only got headlands for the first couple of tries.

on the last try, starting at line 855 i waited about 15 min after the last entry, before uploading.

**Comment by pvaiko** [comment] 2019-08-04 17:29
That field must have an odd shape, CP had to split it into 18 blocks and is now trying to find out the sequence to work on them.

**Comment by JDTiger** [comment] 2019-08-04 18:10
Yes, 10&24 at least are quite oddly shaped... so at the current time, the generator is unable to process the fields, because they are too odd?

**Comment by pvaiko** [comment] 2019-08-04 23:47
@JDTiger your cpFields.xml does not have fields 10 or 24, but looking at that screenshot, those fields are a nightmare. I looked at Google maps, field 24 does not seem to have that very long line with little islands on it IRL, without that it may work. 10 is really bad too. You may want to experiment with manually setting the starting direction (or try the longest edge setting). Or, as you said, split the field into multiple ones, for 10 for example cut the western part, for 24 the southwestern part at that long line.

The problem is that these fields can't be worked on in one pass so CP splits them into blocks. Then it runs a genetic algorithm to determine the sequence in which these blocks should be worked on to minimize driving between the blocks. That algorithm runs fine with a few blocks (<10) but 18 is way too many. (If you are interested in details search for the paper "An Optimized Field Coverage Planning Approach for Navigation of Agricultural Robots in Fields Involving Obstacle Areas" by Ibrahim A. Hameed, Dionysis Bochtis and Claus A. Sørensen)

If you get me 10 and 24 I'll probably look at it and see if something can be done.

**Comment by JDTiger** [comment] 2019-08-05 15:07
ok, i'll just go and put the map in the GE and improve those fields then :D

Thanks for the help

**Comment by JDTiger** [comment] 2019-08-05 15:35
cpFields.xml with boundries for 10&24.
https://drive.google.com/open?id=1uLFv9UX927EOSn_sBLF46oGLeBwjWhM0
sorry, i thought save all fields would save all fields, niot only the ones currently owned/contracted

**Comment by pvaiko** [comment] 2019-08-05 22:54
Changed to genetic algorithm so it can deal with these huge odd shaped fields, just you have an idea what it is doing: with 24 blocks worked in a random sequence you may end up driving over 60 km on the headlands in total between the blocks, the algorithm can bring this down to 5-6 km.

**Comment by JDTiger** [comment] 2019-08-06 16:23
ok, nice, thanks

**Comment by JDTiger** [comment] 2019-08-06 18:43
I just tried, and was able to generate courses for both of the fields.

Thanks for the help, will report how practical those courses are, once i used them.

**Comment by Tensuko** [comment] 2019-08-07 11:50
Closing this, feel free to report here anyway, feedback is always good :)

**Closed by Tensuko** 2019-08-07 11:50 UTC
