### ISSUE TITLE
LUA  method 'draw - hud.lua: 592: + LUA Call stacks

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3612] opened 2019-04-13 12:08 UTC
hi.. when i use cp after a time my game have been crashing and i cant change vehicle or i cant save my game at this time keyboard dont affect anything ...only mouse active and it starts only cp or stop 
[log.txt](https://github.com/Courseplay/courseplay/files/3076152/log.txt)

**Comment by Tensuko** [comment] 2019-04-13 13:21
duplicate of #3592
Closed.

**Closed** 2019-04-17 19:56 UTC
Labels: duplicate
