### ISSUE TITLE
CoursePlay Crashing

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4836] opened 2020-01-17 16:29 UTC
CP versions 365-8 are crashing at random times. Tab through vehicles and I see a view from inside someone's mouth. Can't stop any CP vehicle and they run off the field.
[log.txt](https://github.com/Courseplay/courseplay/files/4077721/log.txt)

Lone Oak is the map. Using both vanilla and mod tools. I think the last crash was only from vanilla tools running at the time.

**Comment by Tensuko** [comment] 2020-01-17 16:48
Try 369 and report.
I wasn't able to produce any Errors so far...

**Comment by knoxville73** [comment] 2020-01-17 16:50
Same problem with 369

**Comment by Tensuko** [comment] 2020-01-17 17:05
Guys...
Version 396, Vanilla Mods only, Reproducable....
Or with Mods and tell exactly what happens when.
Anything else we can't do anything about it.
I Stressed CP369 with several Driver and different Modes with Pathcalculations, a lot of tabbing arround and actual 650 Mods in Mods Folder and I don't haven any Error in my logfile....

**Comment by knoxville73** [comment] 2020-01-17 17:27
I try again.  3 tractors in action with courseplay (fertilising and seeding).  After this, I move manually an other tractor and after some seconds, this tractor move without m assistance and the game freeze (version 369 - map Gemeinde Rade)
[log.txt](https://github.com/Courseplay/courseplay/files/4077937/log.txt)

**Comment by pvaiko** [comment] 2020-01-17 17:28
@lcc1211 
turn.lua:2738: attempt to perform arithmetic on local 'dStart' (a nil value) should be fixed in 369. 

If you can reproduce the HybridAStar.lua:612: attempt to index field 'nextEdge' (a nil value) error let us know how.

**Comment by pvaiko** [comment] 2020-01-17 17:31
@knoxville73 not sure I understand what are you doing, but that's a different error. Get us log with 7 and 14 maybe it helps.

**Comment by Tensuko** [comment] 2020-01-17 17:43
Packed GC wrong:
Error: Failed to open xml file 'L:/Documents/My Games/FarmingSimulator2019/mods/FS19_GlobalCompany_1_1_5_0/modDesc.xml'.
Load mod: FS19_GlobalCompany_1_1_5_0 (Hash: 222ebe8554fd175876c569508ddcdac3)
Error: Missing descVersion attribute in mod FS19_GlobalCompany_1_1_5_0

2nd Map:
Load mod: FS19_Oakfield (Version: 1.1.0.0)

A LUA Callstack from anywhere.

CP Related Error:
2020-01-17 18:22 Error: Running LUA method 'update'.
2020-01-17 18:22 L:/Documents/My Games/FarmingSimulator2019/mods/ZZZ_Courseplay/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value

But need to know how to reproduce this.

**Comment by knoxville73** [comment] 2020-01-17 18:29
I'm not sure, but I think the mod "RealDirtColor" is a problem ...

**Comment by knoxville73** [comment] 2020-01-17 18:52
My log with chanel debug 7 & 14 after a new crash game
[log.txt](https://github.com/Courseplay/courseplay/files/4078402/log.txt)

**Comment by skjatala** [comment] 2020-01-17 19:03
Pre-release ver: 6.01.00369
My log text with debug channels 7 and 14. may this help.
Remember "DLB19 13 Shank" is plow Mod from Farming Simulator official site, named (FS19_ROVICLEERSDLB19PACK) ,  I am using this mod with Course Play from near about"6.01.00258"
with no any its related error. 
[log.txt](https://github.com/Courseplay/courseplay/files/4078387/log.txt)

**Comment by lcc1211** [comment] 2020-01-17 19:28
> 
> 
> Try 369 and report.
> I wasn't able to produce any Errors so far...

On Lone Oak I reproduced with 369. I was using Class Axion 960 trailing the Claas Cargos 9500 on Field 41 whilst simultaneously harvesting on field 40 using the Rostelmash RSM 161 with the Steyer 6300 CVT trailing the Krampe Bandit 750. All are Giants machines. About 1/3 of the way through the harvest the game crashed.

I will try with 7 & 14 to see if I can reproduce again

**Comment by lcc1211** [comment] 2020-01-17 19:43
Didn't take too long for it to crash this time. Please see my attached log.
[log.txt](https://github.com/Courseplay/courseplay/files/4078699/log.txt)

**Comment by pvaiko** [comment] 2020-01-17 19:44
@knoxville73 would you have a screenshot of that situation, what vehicles, how the field and fruit looks like?

**Comment by pvaiko** [comment] 2020-01-17 19:45
@lcc1211 same question to you.

**Comment by lcc1211** [comment] 2020-01-17 19:47
I didn't get a screenshot, but the set up is the same as my previous reply except I added a mod sprayer to field 41. It ran off the field at the same time the harvester ran off the field. I was riding along in the harvestor both times when it crashed.

**Comment by pvaiko** [comment] 2020-01-17 19:53
Since here's pathfinding involved I won't be able to help without knowing the field layout and the fruit situation on the field.

**Comment by lcc1211** [comment] 2020-01-17 20:04
would this help?
![20200117150042_1](https://user-images.githubusercontent.com/24764870/72642542-a2c61b80-393a-11ea-87f6-efbe8f48844f.jpg)

**Comment by pvaiko** [comment] 2020-01-17 20:17
Yes, is that grass on field 41?

**Comment by lcc1211** [comment] 2020-01-17 20:24
Yes. On both crashes I was running a pick up course on that field.

**Comment by pvaiko** [comment] 2020-01-17 20:42
@lcc1211 thanks, that's great info, was it the Axion or the RSM that went off course? Was it turning, end of a row, middle of the row?

**Comment by lcc1211** [comment] 2020-01-17 20:55
RSM in 2 of the 3 crashes. Other crash it was both.

**Comment by pvaiko** [comment] 2020-01-17 20:59
In  the log I see the sprayer crashing during the turn. Were any of the other vehicles turning at that time?

**Comment by lcc1211** [comment] 2020-01-17 21:04
The RSM was not turning on either of the first 2 crashes. I don't know about the Claas tractor. Now that sprayer is odd. It completes spraying field 41, but It drove off the field when I try spraying field 28. It wound up at the map's edge over near field 31. I was able to stop it and restart it where it left off.

**Comment by pvaiko** [comment] 2020-01-17 21:11
If you have a savegame to reproduce this I'd love to have that.

**Comment by lcc1211** [comment] 2020-01-17 21:12
I will try again later this evening. I will try and set everything up exactly the same as I had before when it crashed.

**Comment by fnpgeorge** [comment] 2020-01-17 23:56
I am having the same problem on a heavily modified game using courseplay 369 and autodrive special downloaded from their repository. I'll keep monitoring this convo. Here is my log file. I have disabled as many mods as I could and still have the same. I verified my game files and courseplay information. At one time courseplay only recognized 26 of the 52 fields on this map. After I reset courseplay it recognized all 52 again. This has been happening since the early to mid 360's for me. 

[log.txt](https://github.com/Courseplay/courseplay/files/4079679/log.txt)

**Comment by resultwrap** [comment] 2020-01-18 01:53
> CP versions 365-8 are crashing at random times. Tab through vehicles and I see a view from inside someone's mouth. Can't stop any CP vehicle and they run off the field.
> [log.txt](https://github.com/Courseplay/courseplay/files/4077721/log.txt)
> 
> Lone Oak is the map. Using both vanilla and mod tools. I think the last crash was only from vanilla tools running at the time.

This is the same issue I was having, however, I was using ridiculously unrealistic mods. I was on a user made map, and the issue for me started in v6.01.00363

**Comment by pvaiko** [comment] 2020-01-18 02:13
@fnpgeorge try 371

**Comment by superkefir** [comment] 2020-01-18 04:26
Hello pvaiko!
I have a crush with error "2020-01-18 06:16 C:/Users/sup/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00371/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value"
Video in which it repeats in one place: https://www.youtube.com/watch?v=9DF82naexsY&feature=youtu.be

**Comment by lcc1211** [comment] 2020-01-18 04:48
I am able to repeat the crash with 369, but I am unable to save a game once CP crashes. When I try going to the save page I just see a view of the far zoomed out.

**Comment by superkefir** [comment] 2020-01-18 04:53
> 
> 
> I am able to repeat the crash with 369, but I am unable to save a game once CP crashes. When I try going to the save page I just see a view of the far zoomed out.

The same thing, only if i can stop current job i can do something, otherwize game can't be saved.
If COURSEPLAY_USE_AI_TURNS is ON, then there is no crash. If i stop course and start it in place before it was bugged the bug doesn't appear in the same place. If i load the game it's repeats every time in one place.

**Comment by fnpgeorge** [comment] 2020-01-18 04:59
I updated to the latest, i think it was 371, maybe 373, been  going for about an hour now without any issues. Hope that did it.

**Comment by knoxville73** [comment] 2020-01-18 10:11
The problem is always existing with the version 371

**Comment by pvaiko** [comment] 2020-01-18 12:19
@lcc1211 but can't you save it _before_ it crashes?

**Comment by pvaiko** [comment] 2020-01-18 12:40
Looks like this is due to a combination of many headlands, wide working widths and small turn radius. Which means I'll most likely be able to reproduce and fix it.

**Comment by resultwrap** [comment] 2020-01-18 13:53
I just had an issue with 371 with Claas lexion 8900 working fine with round (turn radius) headland corners, however, I setup Fendt 1050 pulling HaulMaster in combi mode, just started a 3 dot recording and hit start driver and crash.
[log.txt](https://github.com/Courseplay/courseplay/files/4080748/log.txt)

**Comment by Tensuko** [comment] 2020-01-18 13:59
Becouse this is old Mode2 and got nothing to do with this... Pls check #3311 and #4286 for this

**Comment by lcc1211** [comment] 2020-01-18 15:01
> 
> 
> @lcc1211
> turn.lua:2738: attempt to perform arithmetic on local 'dStart' (a nil value) should be fixed in 369.
> 
> If you can reproduce the HybridAStar.lua:612: attempt to index field 'nextEdge' (a nil value) error let us know how.

I think I have a save from before the latest crash. I don't know which file it is. I see a folder called savegame1 and savegame7.

**Comment by MamaKino** [comment] 2020-01-18 18:36
I'm having this same issue however 373 did not fix it. Here is a copy of my savegame, i am on the map Midwest horizons on field 73 with a Valtra T194 and Bredal K105. When my friend starts a course on the field it generates west to east and and the end of the field it shows the pink line as in the second picture and keeps driving it causing courseplay to crash and cameras to detach from vehicles. When i  (The Host) makes the course it goes north to south and the tractor stops shortly after exiting the field and the pink like switches to the correct turn around path.

[savegame7ZIP.zip](https://github.com/Courseplay/courseplay/files/4081394/savegame7ZIP.zip)
![image](https://user-images.githubusercontent.com/15466230/72668591-107f4f80-39ee-11ea-86d6-b15131380c94.png)

![image](https://user-images.githubusercontent.com/15466230/72668631-9e5b3a80-39ee-11ea-84d7-79f403c5ac71.png)

`2020-01-18 12:17 :58 [dbg14 lp318700] T194 (#1): Speed = 10.0, gx=-0.0 gz=1.8 l=1.8 ax=-0.0 az=1.8 allowed=true fwd=true
2020-01-18 12:17 :58 [dbg14 lp318701] T194 (#1): K105: shouldRaiseImplements: dz = -0.6
2020-01-18 12:17 :58 [dbg14 lp318702] T194 (#1): K105: shouldRaiseImplements: dz = -0.6
2020-01-18 12:17 :58 [dbg14 lp318703] T194 (#1): K105: shouldRaiseImplements: dz = -0.5
2020-01-18 12:17 :58 [dbg14 lp318704] T194 (#1): K105: shouldRaiseImplements: dz = -0.5
2020-01-18 12:17 :58 [dbg14 lp318705] T194 (#1): K105: shouldRaiseImplements: dz = -0.4
2020-01-18 12:17 :58 [dbg14 lp318706] T194 (#1): K105: shouldRaiseImplements: dz = -0.4
2020-01-18 12:17 :58 [dbg14 lp318707] T194 (#1): K105: shouldRaiseImplements: dz = -0.3
2020-01-18 12:17 :58 [dbg14 lp318708] T194 (#1): K105: shouldRaiseImplements: dz = -0.3
2020-01-18 12:17 :58 [dbg14 lp318709] T194 (#1): K105: shouldRaiseImplements: dz = -0.2
2020-01-18 12:17 :58 [dbg14 lp318710] T194 (#1): K105: shouldRaiseImplements: dz = -0.2
2020-01-18 12:17 :58 [dbg14 lp318711] T194 (#1): K105: shouldRaiseImplements: dz = -0.1
2020-01-18 12:17 :58 [dbg14 lp318712] T194 (#1): K105: shouldRaiseImplements: dz = -0.1
2020-01-18 12:17 :58 [dbg14 lp318713] T194 (#1): K105: shouldRaiseImplements: dz = -0.0
2020-01-18 12:17 :58 [dbg14 lp318714] T194 (#1): K105: shouldRaiseImplements: dz = 0.0
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318715] T194 (#1): K105: shouldRaiseImplements: dz = 0.1
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318716] T194 (#1): K105: shouldRaiseImplements: dz = 0.1
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318717] T194 (#1): K105: shouldRaiseImplements: dz = 0.2
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318718] T194 (#1): K105: shouldRaiseImplements: dz = 0.2
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318719] T194 (#1): K105: shouldRaiseImplements: dz = 0.3
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318720] T194 (#1): K105: shouldRaiseImplements: dz = 0.3
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318721] T194 (#1): K105: shouldRaiseImplements: dz = 0.4
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318722] T194 (#1): K105: shouldRaiseImplements: dz = 0.5
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318723] T194 (#1): K105: shouldRaiseImplements: dz = 0.5
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318724] T194 (#1): K105: shouldRaiseImplements: dz = 0.6
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318725] T194 (#1): K105: shouldRaiseImplements: dz = 0.6
2020-01-18 12:17 Error: Running LUA method 'update'.
2020-01-18 12:17 C:/Users/Zach Gow/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00373/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-18 12:17 :58 [dbg14 lp318726] T194 (#1): K105: shouldRaiseImplements: dz = 0.7
2020-01-18 12:17 Error: Running LUA method 'update'.`

**Comment by skjatala** [comment] 2020-01-18 18:42
Pre-release V: 6.01.00373 looks better than V:6.01.00371 . Not crashing game .
Play "FS19_DondiegoMap 2.1" Field -12 seeding with 2 Vehicles.
Tractor and tools= newHolland T8.435, caseIH magnum 380 CVX  and two amazone condor15001 seeder.
Only one thing is annoying FPS drops too much at the end of row when  tractor start to turning
 in third row, ( but FPS not drops too much when turning in 2nd row) 
[log.txt](https://github.com/Courseplay/courseplay/files/4081409/log.txt)

**Comment by pvaiko** [comment] 2020-01-18 22:06
@MamaKino that's multiplayer related, please report it in a separate issue if it has not been reported before.

**Comment by superkefir** [comment] 2020-01-19 21:07
The same problem with 374 
2020-01-20 00:05 C:/Users/sup/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00374/course-generator/PathfinderUtil.lua:363: attempt to perform arithmetic on a nil value

**Comment by pvaiko** [comment] 2020-01-19 23:21
Well, that's a completely different issue, but try with 375.

**Comment by pvaiko** [comment] 2020-01-19 23:23
(on a side note, that video, omg, turn speed 26, reversing speed 20?)

**Comment by superkefir** [comment] 2020-01-20 00:01
speed was increased cause save game point was too far, so i just increased by mouse roll all the speed limits. It doesn't depend on speed for me. Just checked with 375. [youtube](https://www.youtube.com/watch?v=SxPmQWzxRos&feature=youtu.be)
[log.txt](https://github.com/Courseplay/courseplay/files/4083939/log.txt)

**Comment by pvaiko** [comment] 2020-01-20 01:20
How is that field created, was it part of the map? 

Also, can you turn debug level 12 and 7 on as well?

**Comment by superkefir** [comment] 2020-01-20 01:33
This field has only grass, so the course was created driving around the field borders and then the current course was used to create a course for the grass.
The course was created before so i didn't change it from previous version.
The current log with 7 and 12 debug levels attached.
[log.txt](https://github.com/Courseplay/courseplay/files/4084088/log.txt)

**Comment by pvaiko** [comment] 2020-01-20 01:38
@superkefir thanks, yeah, the problem is CP does not recognize it as a field. I'll take a look.

**Comment by lcc1211** [comment] 2020-01-24 02:17
I think it is safe to close out this ticket. Since version .374, I have not had a single crash.

**Comment by Tensuko** [comment] 2020-01-26 11:20
Ok I will close this one.
If have new Issue with this, log with channels 7 and 12.

**Closed by Tensuko** 2020-01-26 11:20 UTC
Labels: waitingForUserAnswer
