### ISSUE TITLE
Sugestion to end of pick-up field work

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#3785] opened 2019-05-14 09:33 UTC
Currently a tractor running a pick-up route picking a swath of grass, will go to the beginning of the route and stops when it done picking up.

I would suggest that when the field is done, it will go to the drop point first and empty, and then drive back to the start-point.

**Comment by Tensuko** [comment] 2019-05-14 10:02
Later there will be an option to turn on/off the back to start option in the HUD.

Drive to the unload at the end of Fieldwork is something we got to discuss 1st.
If so, that would have to be an option to turn on/off, couse some will just continue on the next field and then it doesn't matter how much there is in the trailer. That would be the next Issue that would pop up....
We discuss that.

**Comment by pvaiko** [comment] 2019-05-14 11:34
Duplicate of #3127

**Closed by pvaiko** 2019-05-14 11:34 UTC
Labels: suggestion
