### ISSUE TITLE
ai traffic collision trigger

### ISSUE THREAD

**Issue by jefflng** [Courseplay/courseplay#3007] opened 2019-01-29 17:04 UTC
not sure if anyone has reported this yet haven't seen a log report with it, so here is my log report

2019-01-27 20:06 ## Courseplay: Favorit 511c: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:06 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:06 ## Courseplay: Favorit 515c: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:06 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:06 ## Courseplay: Favorit 511c: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:06 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:06 ## Courseplay: Favorit 515c: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:06 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:06 ## Courseplay: Favorit 511c: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:06 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 data/vehicles/fendt/fendt300/fendt300.i3d (801.37 ms)
2019-01-27 20:07 data/shared/wheels/trelleborg/TM800/R24_TM800.i3d (131.90 ms)
2019-01-27 20:07 data/shared/wheels/trelleborg/TM800/R38_TM800.i3d (53.65 ms)
2019-01-27 20:07 ## Courseplay: 310 Vario: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: 313 Vario: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: 310 Vario: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: 313 Vario: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 data/vehicles/valtra/NSeries/NSeries.i3d (977.39 ms)
2019-01-27 20:07 ## Courseplay: N134: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: N154e: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: N174: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: N134: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: N154e: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png
2019-01-27 20:07 ## Courseplay: N174: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
2019-01-27 20:07 C:/Users/jeffl/OneDrive/Documents/My Games/FarmingSimulator2019/mods/ZZZ_courseplay/img/hud.png

**Comment by jefflng** [comment] 2019-01-29 17:07
also i am running version 6.01.00001 of courseplay

**Comment by snwkill** [comment] 2019-01-29 17:40
do all of the logs reference "ZZZ_"?

seems like it should be
"C:\Users\%username%\Documents\My Games\FarmingSimulator2019\mods\FS19_CoursePlay\img\hud.png" as an example

**Comment by jefflng** [comment] 2019-01-29 18:19
they do. i unpacked the courseplay zip file and rezipped it according to the video

**Comment by sootysax** [comment] 2019-01-29 18:25
but we're up to v6.01.00014...

**Comment by BostonJohnny1226** [comment] 2019-01-29 19:55
By putting ZZZ_ at the front, it makes CP load last after all other mods load so CP can register them

**Comment by Satissis** [comment] 2019-01-30 14:07
The ZZZ_ in front haven't been needed since FS17 where it was changed to load mods as they were loaded in.

Anyway, regarding the traffic collision triggers missing, then that's because in FS19 those are handled a bit different.
They are warnings right now and CP should work fine as well, except checking for traffic in certain cases

**Comment by operinko** [comment] 2019-01-30 23:44
My experience so far has been "Does not check for traffic at all.", causing interesting issues with transports crashing with NPC traffic on the way to sell a load and getting stuck, to a tractor plowing straight into another one on an unrelated course and getting both stuck.

**Comment by CKMartens** [comment] 2019-02-01 12:21
Same here. It seems that is no collision check.

In the log you see that SP 6.01.00015 is loading, After that a error that the aiTrafficCollisionTrigger is missing comes up.

```
### Courseplay: initialized 61/61 files (v6.01.00015)
[...]
## Courseplay: T5.100: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
```

An during the game the CP driver collid with everything

**Comment by operinko** [comment] 2019-02-01 23:20
> The ZZZ_ in front haven't been needed since FS17 where it was changed to load mods as they were loaded in.
> 
> Anyway, regarding the traffic collision triggers missing, then that's because in FS19 those are handled a bit different.
> They are warnings right now and CP should work fine as well, except checking for traffic in certain cases

CP in itself is working fine for most part, but checking traffic doesn't seem to work at all right now, not just in certain cases.
Just checked with CP 6.01.00024

**Comment by Satissis** [comment] 2019-02-02 03:44
No traffic collision is not working at all atm.
I said:
> except checking for traffic in certain cases

Which means that that it's don't need the collision in every case.

It's still something that's being looked into though

**Comment by mehdinasef** [comment] 2019-02-07 18:41
I have the same issue: vehicles do not stop before they collide. They continue pushing each other especially when I set two vehicles driving the same course. when the first one gets to the stop point, it stops but when the second one arrives it collides with the first vehicles and pushes it.
Another case was when I had a forage harvester doing the headlands counterclockwise and a tractor in the left side chasing it. When the forage harvester was turning left it collided with the tractor and did not stop till it knocked it over.
I am a huge fan of Courseplay, I use it all the time and I want it to be better.
thank you for this great mod.
![collision](https://user-images.githubusercontent.com/47159754/52434504-c3bda400-2b0f-11e9-9d23-f1f287fabfc0.png)
![collision2](https://user-images.githubusercontent.com/47159754/52434601-041d2200-2b10-11e9-953e-18d378c5b835.png)

**Comment by pvaiko** [comment] 2019-02-19 23:27
Collision detection is implemented, there are open issues for some minor problems, closing this one.

**Closed by pvaiko** 2019-02-19 23:27 UTC

**Comment by omegaMV6** [comment] 2019-02-23 01:10
Only for information.

In v6.01.00088 the problem is still current.
AI-traffic only detected in mode 1. In mode 2 detection won´t work.
