### ISSUE TITLE
Maxtron/Tractors Emptying it.

### ISSUE THREAD

**Issue by Evilmutt** [Courseplay/courseplay#2736] opened 2018-05-30 15:33 UTC
Part 2 of 2
Some of the time when the Maxtron Unloads and then get to its turning the tractor emptying it gets in the way of that little part that sticks out on the left as the Maxtron as you know empties on the right. that little part is part of the harvesters Hopper and I have to go and take one of the 2 machines  off courseplay, Move it and then Re-engage Courseplay. Sadly I have not got potatoes On any of my fields so I can't recreate the effect for you. once more, sorry for no Pictures but I am sure some people Might be able to recreate this bug.

**Comment by pops64** [comment] 2018-06-11 20:11
We need to see a pic of what is going wrong otherwise we will close this out has rare bugs are hard to fix and don't impact game play to the extent of requiring exhaustive testing from us to find the cause

**Comment by Evilmutt** [comment] 2018-06-12 12:04
I will Need to plant some Potatoes and then show you with Pics and Maybe a video of it.

**Comment by pops64** [comment] 2018-07-11 13:39
Closed due to inactivity

**Closed by pops64** 2018-07-11 13:39 UTC
Labels: More Information Required, waitingForUserAnswer
