### ISSUE TITLE
New Version has a new Bug

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3380] opened 2019-03-08 13:21 UTC
I notice with the Latest version available a new bug has developed. Consistently now the course play when plotting a new field / implement it No longer " auto detects" the working width of the attached implement. Rather, it is defaulting to the last working width that was used. Now you must manually change it to the new working width of the different attached tool. ( Seeder VS Plow ETC...)

**Comment by pvaiko** [comment] 2019-03-08 14:48
https://github.com/Courseplay/courseplay/wiki

**Comment by Hubcap-1** [comment] 2019-03-08 15:11
https://gist.github.com/Hubcap-1/0e8983210a126366e48cc66d43aa43a5

No unsupported mods

**Comment by Hubcap-1** [comment] 2019-03-08 16:26
Sorry I gave an interesting link with Bugs but the wrong one. i have edited the video link to match the GIST

**Comment by pvaiko** [comment] 2019-03-08 18:03
video unavailable

**Comment by pvaiko** [comment] 2019-03-09 12:12
So what is your expectation, do you want me to spend half an hour watching that video and trying to figure out what the problem is?

**Comment by Hubcap-1** [comment] 2019-03-09 23:01
Guess the GIST will have to do. The point was for you to see the problem which was obvious. The video was a bonus but once again you are on the edge of rude.,which is why Github was unnasigning you to anything to do with me

**Comment by KenStumich** [comment] 2019-03-09 23:40
to open the hud you can set new keys in the keyboard mapping menue in FS19. and you need to set the HUD and the modifier key. normaly its Left-Ctrl and delete . testet 2 times and works like a charm.

1map per game 

FS19_Glen_Isla 
FS19_JonesDairyFarm 

btw the harvester(rostselmash) works fine with courseplay. 

on a side note for the editing. for me (german) the behavior is not rude, ist blunt to the point. no blabla no chitchat no beating the bush . strait forward. but this is my personal opinion.

**Comment by Hubcap-1** [comment] 2019-03-09 23:44
Really ?....keep using it ....unil it does what i say it did...it will. I know how how to map keys.I'm not new at this..it does not work  Perfect".every time. That harvester does not work well in course play when you finally get it to " Lock out the Hud".

**Comment by KenStumich** [comment] 2019-03-10 00:09
ok. so i cant reproduce the hud error, neither could you open the hud. 
to find the bug you describe, you need to 
open a new game 
no mods exept CP
set your keybindings to your desire and make a propper bug report if the problem still exist.

i guess its either a mod problem ( key binding double ) or a giant problem with the key binding.(personal note: FS is the only game i cant use the middle mouse button for my logitech G502. same for the giant editor. )


after that wait till the dev find the time to adress the issue.

**Comment by Hubcap-1** [comment] 2019-03-10 00:32
Actually this is a well known issue ( hud failing to display but the click is heard).

**Comment by KenStumich** [comment] 2019-03-10 01:05
im am aware of #3329 and im sure the devs are too.
but this shoudnt be a discussion between us about the already known issue. my initial posting i this thread was to clarify some of your issues .

**Comment by Hubcap-1** [comment] 2019-03-10 01:41
Okay , I was able to reproduce the Problem with this Harvester. Set open Hud to left ctrl + Del.  You must actually plot a course to harvest / start him/ close the Hud / get out / allow harvester to finish / then get back in and try to re-open the Hud .it will not open with either command....the harvester can not be stopped ( it starts again after you get in it R"Repeating" the plotted course again

**Comment by Hubcap-1** [comment] 2019-03-10 01:49
I will attempt a reproduction of the problem if someone can tell me which debug channels to activate

**Comment by KenStumich** [comment] 2019-03-10 02:48
this was not the intension i had in mind, cause the initial issue was" **auto detects" the working width of the attached implement** and the problem you describe had to go into #3329 but i will try to reproduce this for myself.
meanwhile , pls do us all a favour and close this issue by yourself, post a propper report for the auto detection  in a new report (titel e.g. auto detection working width problem) use the actual version, post the log file and  test it beforehand on e.g. ravenfield or felsbrun with no other mods. this will produce a clean logfile and a clean report to work with.
the problem at hand with the HUD-bug goes into #3329  and all is fine. 

btw the auto detect is a minor problem , nice to have but nothing the world really needs now.  nevertheless its a bug and needs to be reported.

**Comment by KenStumich** [comment] 2019-03-10 03:04
meanwhile the harvester is done. i jumped in and the harvester wants to drive to the startin point as you discribe early. 
but on my computer i was able to open the hud with ctrl-del and stop the driver.

as i mention beforhand. i suggest its a general problem with the keybindings from giants. i read about some troubles with the keybindings of other mods too. the general approach was to clear all bindings and set them all manually new. maybee its a way for you too.

its about 5 am now and im getting a little bit tired now. if i find the time tomorrow i will set up a video and post it in #3329 to show you that i can open the hud after all. 
and last but not least . info line by mouse over channel 18 says debug : HUD action . maybe this is the right channel.

**Comment by pvaiko** [comment] 2019-03-10 12:11
Closing this as @KenStumich is right.

**Closed by pvaiko** 2019-03-10 12:11 UTC
