### ISSUE TITLE
Trailer hit roof when unload at sell point. 

### ISSUE THREAD

**Issue by MrCona** [Courseplay/courseplay#3974] opened 2019-07-18 12:24 UTC
it is possible that the Trailer can lower before moving on!?

![fsScreen_2019_07_18_14_08_25](https://user-images.githubusercontent.com/53046359/61457391-8421a080-a968-11e9-9a65-87e9d55a19fa.png)
![fsScreen_2019_07_18_14_08_33](https://user-images.githubusercontent.com/53046359/61457392-8421a080-a968-11e9-941c-b7d64723d985.png)
![fsScreen_2019_07_18_14_08_37](https://user-images.githubusercontent.com/53046359/61457393-8421a080-a968-11e9-8146-ec2ffab3915a.png)
![fsScreen_2019_07_18_14_08_40](https://user-images.githubusercontent.com/53046359/61457395-8421a080-a968-11e9-998c-263904b5a774.png)
![fsScreen_2019_07_18_14_08_09](https://user-images.githubusercontent.com/53046359/61457396-8421a080-a968-11e9-91fc-deb7d6a57c72.png)

**Comment by Tensuko** [comment] 2019-07-18 13:05
Duplicate of #3863
Closed.

**Closed by Tensuko** 2019-07-18 13:05 UTC
