### ISSUE TITLE
Request: Stop course after Return to first point - Wage Issue ...

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#4472] opened 2019-10-29 22:41 UTC
So I'm really trying to do the 'right thing' and have my courseplay drivers earn a wage when running courses..   I of course walk away from the computer and come back, and the worker (or multiple workers) are sitting there, having completed all the work...  and still collecting a wage (sometimes ALOT of wage) for just sitting there because the course is still running.

Is there any way to remedy this?   Either automatically stop the course at the end, or perhaps turn off the wage payment when the course is finished.

If we are going there, I would also wouldn't mind wages stopping being paid when the worker has crashed into a wall or stuck in traffic..   but if we can at least get the 'end of the course' that'd be wonderful.

**Comment by Tensuko** [comment] 2019-10-30 06:26
Do you have AD ? if so, turn the AD Wage to 0%
I never had any Issue with Wage be takeing.

**Comment by RUGhost** [comment] 2019-10-30 08:03
My AD wage set to 0 and courseplay wage is off but courseplay driver is taking the wage. Though it does not happen all the time. You start the game and use courseplay for field work or other job, he does not earn any wage but at a certain time in the gameplay you will notice driver is earning wage.

**Comment by Tensuko** [comment] 2019-10-30 08:24
Hmm I had a long session yesterday and nothing had happened.... but actually I don't have AD in my Mods....
Can we pls try somehow, if that happens only with CP or only with CP+AD ?
If it only happens with AD in addition, then we got to look there for a Solution, that we got to find out 1st

**Comment by bojanh66** [comment] 2019-10-30 10:33
Its bug with CP, not with AD, i already posted it here, the last post, but ill paste it here
https://github.com/Courseplay/courseplay/issues/4345

Finally i found out how to reproduce this bug.
I disabled all mods, except Courseplay and Money Tool.
Bought default ingame tractor and cultivator.
Steps to reproduce bug:

    activate normal worker (keypad H)
    stop normal worker (keypad H)
    start courseplay worker (fieldwork with cultivator)
    CP will start to use wage from normal ingame worker

Can somebody test and confirm this , is it a bug in CP ?

**Comment by Thorn177** [comment] 2019-11-02 04:18
I am getting something similar happen, but on two different interactions with the AD mod. 

In the first, AD is used for refilling, while CP is doing seeding/fertilizing.  AD charges a wage as per its settings while it is in control.  After, not before, AD has run, and CP takes over again, ALL CP work from then on charges a wage at either the Giants or CP rate.  I haven't played with the CP rate to confirm if it is a 'Giants' helper, or a 'CP' helper yet.  This wage is taken in real time.  Pressing H to dismiss the worker is not stopping the wage being deducted.

In the second, CP is being used to harvest in fieldwork mode, and AD is used for unloading.  It's a bit harder to track the wage charges in this scenario, but it looks like AD is getting it correct, in real time, and either a CP or Giants helper is charging a wage in a lump sum on the in game hour.  This charge stops when the work is complete.

**Comment by pvaiko** [comment] 2019-11-02 12:36
@sootysax you know, I was just going to implement this, but isn't it fair to pay your workers as long as you don't dismiss them? :)

**Comment by bojanh66** [comment] 2019-11-03 18:05
Workers still take money even if  Pay workers is deactivated in advanced options.

**Comment by pvaiko** [comment] 2019-11-05 01:43
Should be fixed by 328 or later

**Closed by pvaiko** 2019-11-05 01:43 UTC
Labels: bug
