### ISSUE TITLE
Gaps with lime spreader extension

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5796] opened 2020-07-30 00:58 UTC
Dont know whats the problem here. 3 tools 18 m wide and there is gap as is shown in picture. Courseplay recognize this tool 30 m at first but when i change to 18m and generate course there are gaps on sides.
![1](https://user-images.githubusercontent.com/68528285/88868342-3b095b00-d210-11ea-83ae-ba5b5de9c035.jpg)
![2](https://user-images.githubusercontent.com/68528285/88868347-3d6bb500-d210-11ea-8c34-9b2b49191d55.jpg)

**Comment by Tensuko** [comment] 2020-07-30 04:45
The Problem is that the Tool tell CP is has a work width of 30m, wich is changed when use lime.
But we don't get the changed width and the course offsetcourse for left and right gets generated with 30m (not by coursegenerator, the offset course will be generated on the fly when starting the driver).
I am not sure right now, but can you adjust the work width in the HUD ? if so try it out.

**Comment by 419054** [comment] 2020-07-30 04:49
I did. Its the same. Found some mod for manure spreader, working fine with those. Dunno, but on some previous versions i didnt have this issue at all. Could start from corner and so on. Half year ago maybe a bit more.

**Comment by Tensuko** [comment] 2020-07-30 05:39
Found the Issue #5467
Closing this one as we have a duplicate one.

**Closed by Tensuko** 2020-07-30 05:39 UTC
