### ISSUE TITLE
Rain/Hail with Case AusToft sugarcane harvester crashes the game /#3325/

### ISSUE THREAD

**Issue by dexus92** [Courseplay/courseplay#3551] opened 2019-04-09 03:13 UTC
I have too this problem. What log I can give you?

_Originally posted by @dexus92 in https://github.com/Courseplay/courseplay/issues/3325#issuecomment-480818171_

Reopen?

**Comment by Tensuko** [comment] 2019-04-09 05:03
Duplicate of #3325 
Closed.

**Closed by Tensuko** 2019-04-09 05:03 UTC
