### ISSUE TITLE
[Suggestion] Reset Equipment Offset

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#5570] opened 2020-06-06 10:43 UTC
It often happens that when changing equipment, I forget to reset the offset that I set for the previous one. Because of this, there is an overrun of fertilizer or inadequate sowing. Can you add a notification that the offset is currently in effect? Or reset the offset when disconnecting the equipment. Can you suggest something else? Thank.

**Comment by pvaiko** [comment] 2020-07-03 16:34
We can reset the offset when detaching anything but that's probably not what you want. The problem is that we know what is being detached but we don't know if you set the offset because of the implement being detached (which could be a weight) or because of another implement still attached.

What would be the criteria to reset the offset when detaching something?

**Comment by Gonimy-Vetrom** [comment] 2020-07-09 17:26
And really. I use the mod manualAttach, and I cannot have an accidental disconnection of equipment. And for someone, this happens by chance. This will create a  new problem for them.

**Comment by Gonimy-Vetrom** [comment] 2020-08-16 13:21
Probably it will be correct to report that any offset is activated. For example, "red exclamation mark" next to the pictogram on which the offset is set.
![fsScreen_2020_08_16_16_13_08](https://user-images.githubusercontent.com/8200153/90335268-79f32b00-dfdc-11ea-9095-4aee3a6b5289.jpg)

**Comment by pvaiko** [comment] 2021-01-23 12:21
Is now resolved in the above release.

**Closed by pvaiko** 2021-01-23 12:21 UTC
Labels: suggestion
