### ISSUE TITLE
My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/AIDriver.lua:679: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Berner93** [Courseplay/courseplay#4257] opened 2019-09-16 20:46 UTC
Sometimes when I start a tractor on a course in mode2, all HUD disappears including cp hud.
i get this text in log file: My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/AIDriver.lua:679: attempt to index field 'course' (a nil value)
[log.txt](https://github.com/Courseplay/courseplay/files/3618139/log.txt)

**Comment by Berner93** [comment] 2019-09-16 20:54
I use v6.01.00300

**Comment by Tensuko** [comment] 2019-09-17 04:57
Duplicate of #4257
Closed.

**Closed by Tensuko** 2019-09-17 04:57 UTC

**Comment by Berner93** [comment] 2019-09-17 09:51
I know its a duplicate, but i have the log file? why not use it?
Im very sorry to annoy you

**Comment by Tensuko** [comment] 2019-09-17 10:26
When you know it is a duplicate, then why you didn't post in the referenced Issue ?
And I saw you logfile and I checked it. You got several maps in modfolder, but you only allowed to have 1 in it since few LS Versions, also a Mod Package wich needs to be unzipped.
Another thing is, that we need more Information on what you did. BTW, if you only have that in Mode2 it is #3311 anyway and getting closed too.
