### ISSUE TITLE
First Lane & Second Lane Overlap New Course Gen Causes Collisions

### ISSUE THREAD

**Issue by Randy1214** [Courseplay/courseplay#2884] opened 2018-10-12 00:23 UTC
So i have a course setup for 2 combines working together and everything goes well during the headlands. But when they go up and down the field, after the first time they turn around something happens that makes the first combine come back on the lane right next to the second combine that hasent turned around yet and they collide.

It seems like the symmetric lane change dosent work well right after the headland. To fix the problem i have to change the lane position of the first combine so it leaves the free space its suppose to.

Once thats fixed everything works well for the rest of the field.

**Comment by pops64** [comment] 2018-10-12 00:59
See #2826 about the part with the first lane after headland

**Comment by Randy1214** [comment] 2018-10-12 01:46
I also noticed that when you use multiple combines somewhere in the HUD it says 1/2 and 2/2 which tells you which is the first combine. When my probleme occurs the combine that was 1/2 is now 2/2 and the one that is in the back is now considered the first one.

When it does that, instead of changing the side of the course they follow after turning around they come back on the same side and it dosent leave the 1 free lane it needs.

Next time i run that course i will try to pinpoint exactly what they do wrong

**Comment by pops64** [comment] 2018-10-12 01:56
Read my comment about the first lane after the headland  #2826 it is about halfway down. The problem is that the first and 2nd lane in the new course gen overlap when the workwidth divided by the fieldwidth results in a remainder. This would always happen on the last 2 lanes of the old course gen. No other setting matters besides this when two lanes overlap each other the one working the right side will run into the one working the left side(or right if symmetry is on). And there is currently no solution to avoid this problem other than just starting the two with enough distance between each other

**Comment by pvajko** [comment] 2018-10-12 22:43
I can easily arrange the lanes so they are distributed evenly but then there will be an (small) overlap between the adjacent lanes. Do you think that would be better? Wouldn't you have collisions then in any lane?

**Comment by Randy1214** [comment] 2018-10-12 22:48
I think the best way would be to have nothing overlap until the end. Then at the end instead of overlaping the lane that was just worked, overlap the headland instead.

You could also make that only if there was a headland in the course generation and if not overlap the last lane.

**Comment by Randy1214** [comment] 2018-10-12 22:51
If thats too complicated then just make the overlap always at the end of the course that way if something happens the course is almost done and can be easily finished manually

**Comment by pops64** [comment] 2018-10-12 23:12
@pvajko there can't be any more over lap than the old system during the middle lanes. Haveing the remainder going to the headlands would be more beneficial. The only problem is mode2 parking location but that is a separate and ongoing improvement

**Comment by pvajko** [comment] 2018-10-13 01:11
@Randy1214 ok, I'll change it to overlap with the headland. What is better, overlap the headland at both the first and the last lane or at the first or last only? 

(Can't guarantee that it'll be the last lane, the way it is implemented now it depends on the starting location if it is the first or the last lane, Also, remember, not all fields are rectangular and may be split into multiple blocks, etc. which makes things more complicated than one would think)

**Comment by Randy1214** [comment] 2018-10-13 01:32
Preferably the last lane. The field im having problems with is on lone oak farm field 45. Starting position is south-west heading north with 2 headlands. Try your best and ill see what happens. Thank you

**Comment by Randy1214** [comment] 2018-10-13 20:37
Also ive been having problems with infinite circles, is there a way to implement that when its been turning in circles for too long that it skips that point and moves on the the next. Because it seems to be turning perfectly around the point its trying to reach and never stops

**Comment by pvajko** [comment] 2018-10-13 21:44
I've been working on that problem for a while as part of our code clean up effort. If you are familiar with git you can check it out on the purepursuit branch, there's an 'experimental mode' on the drive page which should avoid all circling.

Will merge it to master anyway in a few days.

**Comment by Randy1214** [comment] 2018-10-13 21:49
Thanks ill check that out

**Comment by Randy1214** [comment] 2018-10-13 22:01
So i see drive.lua inthe purepursuit branch but nothing about experimental drive

**Comment by pops64** [comment] 2018-10-13 22:57
It is an option in the hud when running FS17. As for the connecting track to up/down transition there are times when there is no turn start/end so it doesn't make a smooth turn into up/down or headland. I was looking at adding a align course call to the end of connecting tracks to smooth this out and eliminate this problem

**Comment by pops64** [comment] 2018-10-13 23:31
About to test something here in a bit, hopefully all goes well. Cause that missing bit is quite annoying unless @pvajko can fix this in the course generation instead

**Comment by Randy1214** [comment] 2018-10-13 23:40
And my overloader still runs off the field often when turning around, driving to the wait position and driving to the unload course

**Comment by Randy1214** [comment] 2018-10-14 02:16
Im currently using a mod to wrap square bales but courseplay dosent recognize when its wrapping and when its ready to unload to it picks up the first bail and never stops. Is that something i need to fix in specialtools or is that a problem with the mod?

**Comment by pops64** [comment] 2018-10-14 09:18
It still the same problem. I would need to know what's not working and how it supposed to work. And if CPs current code can be made to accept the mod

**Comment by Randy1214** [comment] 2018-10-14 11:54
Its the mchale 998 mod. All it needs to do is stop after the bale is loaded and unload it when its done, then continue

**Comment by pops64** [comment] 2018-10-14 18:55
@pvajko Now it appears the first and second lane are directly on top of each other
![fsscreen_2018_10_14_14_54_41](https://user-images.githubusercontent.com/10678220/46920782-2e772c80-cfc1-11e8-9e6e-38c3ab971630.png)

**Comment by Randy1214** [comment] 2018-10-14 19:01
Is it better to set you start location at the corner of the field or in the middle of an edge?

Ive noticed that when you start at the corner the connecting track runs along the entire edge and then the tractor has to do a full 180degree turn to start the up and down and that causes problemes with infinite circles. If you start somewhere on the edge, after the connecting track the tractor only has to do a 90 degree turn to start the up and down.

**Comment by Randy1214** [comment] 2018-10-14 19:47
Sometimes there is turn waypoints but the start and end are too close together

**Comment by pops64** [comment] 2018-10-14 19:55
Turn waypoints usually can handle it if there are 180 angled apart. I am pretty sure that the coruse gen doesn't place turn waypoints when this isn't the case. Also see my picture above which is a bug of version 31

**Comment by pvajko** [comment] 2018-10-14 21:04
@pops64  I appreciate your activity but none of those commits were merged into master, both are on my **private development branch** (peter). Therefore, there's no such thing as bug in version 31.

There is a reason I haven't merged them to master.

**Comment by pops64** [comment] 2018-10-14 21:19
Well the above picture was taken with version 32 and I have never seen two lanes overlap directly on top of each other and I am not running your branch. So I am not sure how that got introduced or maybe it is a very old bug never seen before

**Comment by pvajko** [comment] 2018-10-14 21:40
Haven't changed anything in 31 other than the warning dialogs.

BTW, these are not directly on top of each other, there's like 0.2-0.1 m between them, which can happen if that 10 cm is all that is missing to cover the field entirely.

**Comment by pops64** [comment] 2018-10-14 22:29
Could we set if bellow a certain amount to ignore that remainder. I think in the old system any lane under .2m was ignored

**Comment by Randy1214** [comment] 2018-10-14 23:01
If they are directly on top of each other you cant see the second one. Like the connecting track

**Comment by Randy1214** [comment] 2018-10-16 23:35
@pops64 Any chance you looked at that mod posted above?

**Comment by pops64** [comment] 2018-11-07 20:31
Closed #2909

**Closed by pops64** 2018-11-07 20:31 UTC
Labels: Fine Tuning
