### ISSUE TITLE
New Headland Generator Reversing Issues

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2478] opened 2017-11-25 04:15 UTC
The CP headland generator for ploughing has an issue when reversing with large cultivators like the Lemkin Gigant or the sower like the Amazone Condor 150001.  Upon beginning the reverse maneuver, the tractor immediately cuts the wheels to the left or right and zig zags in reverse.  It sometimes jack knives and moves forward missing chunks of the field.  I have attempted slowing down the tractor to 1 mile per hour, but it still doesn't do well.
![20171124231300_1](https://user-images.githubusercontent.com/24764870/33227254-26c1a82e-d16d-11e7-81d2-5c51fdaf9e48.jpg)
![20171124231254_1](https://user-images.githubusercontent.com/24764870/33227257-29cd9fdc-d16d-11e7-857a-4702f9c71281.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/1502808/log.txt)
Using vanilla tractor and vanilla sowers on Countyline map v1.0.  Also does this behavior on maps such at Hobbs & Westbridge Hills.

**Comment by pvajko** [comment] 2017-11-25 12:23
Duplicate of #2396 (which is, BTW still waiting for user input)

**Closed by pvajko** 2017-11-25 12:23 UTC

**Comment by lcc1211** [comment] 2017-11-25 14:13
If you say so, but 99% of #2396 seems to be referring to headland turns and not reversing.

**Comment by pvajko** [comment] 2017-11-25 15:03
#2396 is mainly about jackknifing when reversing with some big implements. It was first reported for headland turns but likely the same issue.
