### ISSUE TITLE
Unloader can't find a route to the Combine after CP v6.03.00012

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#6460] opened 2020-12-09 20:38 UTC
Hello again.

The situation es like this: Un combine harvesting wheat, and two unloaders.
I have to manually drive the unloader really close and then CP start working.
It is working perfect on version v6.03.00011.
Attached is a log with channels 4 7 14.

Thanks so much for your hard work!!
[log.txt](https://github.com/Courseplay/courseplay/files/5668536/log.txt)

**Comment by archaoncze** [comment] 2020-12-10 07:37
I had same issue with mode 3 when worker is further away from combine (i harvest pretty big filed - so always not found way to combine after unload to drive on mode 1 and sometimes even on field - in menu is unloader asigned to combine, but in debug he still saying that he waits for combine call). And sometimes in mode 4 when pathifinder should set route for turn (worker just stop and after while switch engine off and sit there until i stop him and drive to next point manually), this happens randomly - sometimes its works, sometimes not (i dont have a log)

**Comment by Tensuko** [comment] 2020-12-10 08:12
Sry guys but 'I got the same problem' or 'sometimes it work sometimes not' and that without a lot is not helpful at all.... deleting Comments to keep the Issue Clean.

**Comment by Tensuko** [comment] 2020-12-10 12:14
@masneoquil 
did you use this Trailer for your unloader ? Valzelli VI/140

**Comment by dragon1220** [comment] 2020-12-10 12:17
Hi Guys. I have to agree with the OP here, using version 00013, the harvester gets to it designated fill percentage (35% for tractor to start moving) and the unloader just stays there with the field state saying waiting for combine to call, the combine combine continues to harvest uptil it fills to 95% then stops saying needs to be unloaded yet unloader still will not path to the combine, just stating waiting for combine to call. I manually have to drive close to the combine and tell it to drive course then it will find it.

I am using SIID modding's JD 7R EU tractor and a horsch titan U34 auger wagon (which I increased the capacity)

Ive attached the log with channels 4, 7, 12 and 14
[log.txt](https://github.com/Courseplay/courseplay/files/5672575/log.txt)

thanks

G

**Comment by pvaiko** [comment] 2020-12-10 12:23
@dragon1220 and @masneoquil would you guys have screenshot of the unloader in this situation?

**Comment by pvaiko** [comment] 2020-12-10 12:32
It is certainly related to the trailer. It may be a combination of a tractor with low turning radius and a big trailer.

@masneoquil I see you are a developer, if you like, you can try increasing the 3 in this line to 5 or 6 and see if it helps:
https://github.com/Courseplay/courseplay/blob/598c6ae74d668d4d49f9962a3a4f1df505572504/course-generator/PathfinderUtil.lua#L575

**Comment by dragon1220** [comment] 2020-12-10 12:44
![fsScreen_2020_12_10_12_42_57](https://user-images.githubusercontent.com/75646825/101774051-7b91b300-3ae5-11eb-861e-966aff75c4f4.png)
![fsScreen_2020_12_10_12_43_40](https://user-images.githubusercontent.com/75646825/101774055-7cc2e000-3ae5-11eb-91e7-6626239920fb.png)
![fsScreen_2020_12_10_12_43_57](https://user-images.githubusercontent.com/75646825/101774056-7df40d00-3ae5-11eb-912b-baba591f0ace.png)

**Comment by masneoquil** [comment] 2020-12-10 12:48
@pvaiko sure, will try. But it happened too with a different tractor, trailer and combine. Smaller ones.

**Comment by masneoquil** [comment] 2020-12-10 13:17
@pvaiko I did the change and so far it is working great!!
@Tensuko Sorry, yes, is the Valzelli, but the 4x. The biggest one.

**Comment by pvaiko** [comment] 2020-12-10 13:22
@masneoquil thanks, awesome. Looks like though that's just a band aid, the root cause is a bit more complicated, but at least I now know what it is.

**Comment by Vittorio1964** [comment] 2020-12-10 18:51
Hi everyone, I have a problem with the new version, I create the path to download the combine, but he doesn't see it, I use the original tractors and always original trailers.

[log.txt](https://github.com/Courseplay/courseplay/files/5675003/log.txt)

**Comment by pvaiko** [comment] 2020-12-10 19:03
You have a very old version (v6.02.00076), we are at 6.03.00014.

**Comment by Vittorio1964** [comment] 2020-12-10 20:14
New Version but same error

[log.txt](https://github.com/Courseplay/courseplay/files/5675395/log.txt)

**Comment by SeriouZ12** [comment] 2020-12-10 21:12
HI, i also gave it a try and your fix works great on the Ravenport. 
[log Ravenport.txt](https://github.com/Courseplay/courseplay/files/5675556/log.Ravenport.txt)

But  i also tried it on the MVP2020 and it is still waiting for the Combine to call. I would love to understand which functions are used by the combine to call for the unloader but i dont even get how it working himself :D 
[log MVP.txt](https://github.com/Courseplay/courseplay/files/5675619/log.MVP.txt)

Loving your Work!

**Comment by pvaiko** [comment] 2020-12-11 00:35
@Vittorio1964 we need a log with debug channels 7, 12 and 14. And a screenshot of your unloader.

**Comment by pvaiko** [comment] 2020-12-11 00:35
@SeriouZ12 a screenshot would be great so we see what's going on there.

**Comment by Vittorio1964** [comment] 2020-12-11 10:20
Solved thanks, sorry my error i use helper on combine e not courseplay

**Comment by SeriouZ12** [comment] 2020-12-11 12:55
@pvaiko  Made some Videos to it. I thought they could be more helpful.
Scenario 1 Ravenport. Works fine. 
[log Ravenport.txt](https://github.com/Courseplay/courseplay/files/5678802/log.Ravenport.txt)
https://youtu.be/WQFbfXCbM_I

Scenario 2 MVP East Corner. Starts at first then on the second try it waits for combine? On a second attempt afterwards it did nothing. (Didn´t safe the log, my bad)
https://youtu.be/4TjHoEL8m1U

Scenario 3 MVP West Corner. Starts perfectly. But then suddenly he seems to dont find anything again.
[log MVP 2.txt](https://github.com/Courseplay/courseplay/files/5679022/log.MVP.2.txt)
https://youtu.be/HXRzfbXTAwA

Hope it helps

**Comment by pvaiko** [comment] 2020-12-12 22:24
@SeriouZ12 yes, thanks it does help a lot.

**Comment by SeriouZ12** [comment] 2020-12-14 07:49
@pvaiko I got your Fix from the Pathfinder Branch. It works absolutely great! It looks like in some Cases he is not getting the call in the headlands, when it is set to wait until the combine is full and makes a niche. Also if the combine is to far away. But i cant reproduce it consistant.

**Comment by Tensuko** [comment] 2020-12-14 08:58
Well I have a big Field on a 4x Map and he did all the calls in Headland without any Issue with the niche.
About the distance I will have a test soon or later for the biggest Field on my map, but so far it runs very good and I don't have to do to any interaction with the drivers.

**Comment by pvaiko** [comment] 2020-12-14 12:37
@SeriouZ12 awesome, thanks for testing it. Would be interesting to see a log with channels 7 and 14 when it can't find a path, it should fall back to driving through the fruit in that case.

**Comment by SeriouZ12** [comment] 2020-12-14 13:44
@pvaiko I noticed right now in my game that the Combine i want to unload did not generate a Back Marker. In the last Video above you can see that the 2nd started Case did not generate a Back Marker after the first unload. Could it be that it has problems with switching between the Combines as (i think) the Pathfinder catches the Marker? 

This was my case: 2 Combines on 1st Headland, 1 Unloader for both. First got unloaded one time, Second didnt
![2020-12-14_14h23_04](https://user-images.githubusercontent.com/63880274/102087771-515c3000-3e1a-11eb-8bfd-fcc599dcd193.png)
![2020-12-14_14h23_16](https://user-images.githubusercontent.com/63880274/102087797-58833e00-3e1a-11eb-8755-56553b6b3969.png)

Then i noticed they didnt have backmarkers as the other NH Combine on an other field:
![2020-12-14_14h21_43](https://user-images.githubusercontent.com/63880274/102087887-73ee4900-3e1a-11eb-9196-b5dbe0199940.png)

After that i stopped the Second Ideal Combine and it generated a Backmarker for the first Combine and the Unloader immediately got it:
![2020-12-14_14h26_43](https://user-images.githubusercontent.com/63880274/102087985-92544480-3e1a-11eb-8847-7a9f3dcd8b4b.png)

Sry for the long LOG i played for a while
[log - Ideal Unloader goes.txt](https://github.com/Courseplay/courseplay/files/5689107/log.-.Ideal.Unloader.goes.txt)

@Tensuko Did you use one or two combines for your tests?

**Comment by pvaiko** [comment] 2020-12-14 14:29
@SeriouZ12 unfortunately you did not have debug channel 7 activated at time the pathfinder failed.

**Comment by Tensuko** [comment] 2020-12-15 17:24
This must be a different problem then.
As the Pathfinder does a good job now.

**Comment by pvaiko** [comment] 2020-12-15 19:26
@envikowaty can you open an other issue for this, log is great but a screenshot or a video would be better, showing both the unloader and the harvester in such a situation.

**Comment by Tensuko** [comment] 2021-03-20 12:50
We got a fix for this already in the current release Version.
If there is still a Problem with this, make a new Issue.

**Closed by Tensuko** 2021-03-20 12:50 UTC
Labels: Mode2/Mode3, bug
