### ISSUE TITLE
plowing issues

### ISSUE THREAD

**Issue by adpmaverick** [Courseplay/courseplay#5149] opened 2020-04-08 01:04 UTC
first off the courseplay mod is awesome I have really loved using it. The problem that I have been having is when using the lemkin plow that is in the game. No matter how I have the plow set up it never is able to start correctly into the field and it takes time for it to eventually get the offset corrected and making the correct path down the field. The second problem that I am having with the plow is that the AI can't turn the thing to save its life and as a result misses a lot of different parts of the field. I am not sure what can be done to rectify the situation but I thought you should know. Thanks

**Comment by Tensuko** [comment] 2020-04-08 04:41
Duplicate of #5097

**Closed by Tensuko** 2020-04-08 04:41 UTC
