### ISSUE TITLE
Auto Refill Sprayer

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3932] opened 2019-06-26 20:20 UTC
**Gtranslate**
Hey. There is a problem with the automatic filling of the sprayer. I shot 2 videos. The first video on the custom map, the second on the standard, with one mod. The second video shows that the problem of sticking the sprayer in the nearby machines. In the first video, the problem is most likely due to tanks with a herbicide. I use the latest version - 234
[Log](https://gist.github.com/Horozor/6bf9666e83d5eb6bc2173e4f19db3a3f)
[1st Video](https://youtu.be/BT8FfVoyYG8) Map The Pacific Northwest
[2nd Video](https://youtu.be/Ktq25aHMsCg) New game, 2 mods. Courseplay v6.01.00234 and placeableRefillStation

**Comment by Tensuko** [comment] 2019-06-27 05:27
Did you select the right refill good ?
Thats on the 3rd (?) page... Not at home can't check and show it to you.
But for example for sugarcane, you can select sugarcane and seed as refill type.

If that is not the case, I will have a closer look to this.

**Comment by Horozor** [comment] 2019-06-27 06:50
Yes refill of goods is correct. Herbicide 
![fsScreen_2019_06_27_09_47_20](https://user-images.githubusercontent.com/37561569/60243411-d408cc80-98c0-11e9-8892-b4d29640525a.jpg)
or liquid fertilizer selected. If the sprayer does not interfere with other machines, as I showed in the second video, then it refuels correctly.

**Comment by Tensuko** [comment] 2019-06-27 16:30
What I just saw in your logfile:
Load mod: Courseplay_6_01_00194 (Version: 6.01.00194) (Hash: 307ad1cef4cb605c21d5ba31522d833b)
Load mod: Courseplay_6_01_00234 (Version: 6.01.00234) (Hash: 7221d6e3f10de8a8ff2aa783e8d05fd8)

You have to delete or if you want to keep an older version, remove it from the modfolder.

Smal Tip how I do it:
When I downloaded the newest Version, I rename the zip folder to FS19_Courseplay or FS19_Courseplay6 how you like it, so I never got a 2nd CP Version in my Modfolder.

So you have 2 LUA Errors:
2019-06-26 17:14 Error: Running LUA method 'draw'.
2019-06-26 17:14 C:/Users/Horozor/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00234/hud.lua:608: attempt to index local 'selectedField' (a nil value)

2019-06-26 16:58 Error: Running LUA method 'mouseEvent'.
2019-06-26 16:58 C:/Users/Horozor/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00234/start_stop.lua:125: attempt to index a nil value

If you remove the older CP Version, the LUA Errors should be gone.
I don't think that helps with the Issue you have, but that prevent you from haveing more trouble.
The Refill I will try to reproduce it.

**Comment by Horozor** [comment] 2019-06-27 16:37
@Tensuko 
I apologize. I will always delete old versions.

**Comment by Tensuko** [comment] 2019-06-27 16:46
No Problem :)

I watched you Video just now (was at work, had no time) and the Issue is not, that the refill doesn't work.

There is a GIANTS Problem with that Kind of Sprayer. I don't find the Issue right now, but when you are in the Sprayer, Press F5 on your Keyboard and you will see a big orange Box:
![Kolli](https://user-images.githubusercontent.com/27344744/60284332-941b0700-990b-11e9-9d78-1d73f36266ee.png)
There must be an Error in the Model, so the Collision Detection (the orange Box) is as wide as the sprayer Arms.
That is why you Sprayer stops, when a Car or Tractor is placed near the Refillstation.
Should be the same, when the Traffic passes by at your Screenshot.

**Comment by Horozor** [comment] 2019-06-27 16:52
@Tensuko 
OMG. Got it. I did not know about f5. This can be solved only by editing the model, if I understood correctly. Thanks for the help

**Comment by Tensuko** [comment] 2019-06-27 17:00
Yes, that is correct.
Sadly GIANTS did not solve this in Patch 1.4

**Comment by Tensuko** [comment] 2019-08-23 07:58
Same Issue as here: #3239
Closing this one to continue in the other one.

**Closed by Tensuko** 2019-08-23 07:58 UTC
Labels: bug
