### ISSUE TITLE
Arcusin auto stack unloading problem 

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3952] opened 2019-07-06 13:51 UTC
https://youtu.be/LdNCwITOKjw
just see the problem. After unload bale, tractor should move forward some step then start to fold the stacker. But it don't do that. And the result??? see in the above video.

**Comment by pvaiko** [comment] 2019-07-06 15:45
Duplicate of #3359

**Closed by pvaiko** 2019-07-06 15:45 UTC
