### ISSUE TITLE
AIDriver.lua:679: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Flashsolutions** [Courseplay/courseplay#4279] opened 2019-09-21 16:40 UTC
See https://youtu.be/geVYxqhb8-8 for video of reproduction of the error
This error was previously submitted but closed due to unable to reproduce.

This time I had debug 14 and 15 enabled.

I started with a brand new savegame on Eiersholt map.  Purchased new vehicles and drove them to field 32 to begin video instruction of how to use courseplay and autodrive to harvest a field of wheat.   

I got the error and closed the game and restarted it with the debug 14 and 15 enabled and did the exact same sequence of events which generated the error again.

Hopefully, you can determine why.

[error_log.txt](https://github.com/Courseplay/courseplay/files/3638875/error_log.txt)

**Comment by Flashsolutions** [comment] 2019-09-21 17:15
Duplicated the error again.   New log file and new video.
[savegame18.zip](https://github.com/Courseplay/courseplay/files/3638912/savegame18.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/3638913/log.txt)

https://youtu.be/5N48E9WzMtE

**Comment by Tensuko** [comment] 2019-09-21 17:52
Duplicate of #4217
Closed.

**Closed by Tensuko** 2019-09-21 17:52 UTC
