### ISSUE TITLE
Spiral course generating

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/courseplay#4652] opened 2019-12-14 16:23 UTC
Spiral course are fine, but one thing is bad
when you plan a headland pass clockwise, the work after that is reverse clockwise, why ?

spiral work after headland pass should follow the way (clockwise for example) for all the work, and not change after headland pass.

Thx

**Comment by pvaiko** [comment] 2019-12-14 16:50
Duplicate of #4163

**Closed by pvaiko** 2019-12-14 16:50 UTC
Labels: enhancement
