### ISSUE TITLE
External tool

### ISSUE THREAD

**Issue by Goten87** [Courseplay/courseplay#903] opened 2015-01-04 21:33 UTC
Will there be a external tool for 2015 again like the older tools so we can modify our course out of the game
I have seen some good programs in the past even the website of @JakobTischler was cool

Will we see that for fs2015 as well

**Comment by JakobTischler** [comment] 2015-01-04 21:40
The tool I wrote back then was more of a case study than anything else. I have no intentions of updating it.

**Comment by PromGames** [comment] 2015-01-04 22:03
I suppose the tool you are talking about is the courseplay path editor - CourseDrawer 
I am in the process to get that programme ready for new courseplay 4.0 FS2015

Almost is finished but we will not publish till we are sure everything is correct and the courseplay development team gives the ok to the new version. 

However, I will be very happy if you or any other member of the community wants to join to the beta tester team of this new release. Send me a message through here and I will forward you  program and credentials for logs.

We will also use this opportunity to create a good repository of old CP courses transformed to new structure and features and we can share our new courses.

The good thing for the new programme is that is capable to reconstruct the old xml to the new structure without missing any data. I think there are some issues reported because they are using the old structure.

We may advise to the players that using the old version of CourseDrawer or courseplay path editor, makes the tracks incompatible (to some extend) with the new version FS2015.

Turns, folders, parent data to relate folders, ... all this data is missed if you use the old version of CourseDrawer or courseplay path editor as was the mod name used in Fs-uk

In addition, sometimes, is dividing the speed by 100, maybe that's why we saw many issues of people going in recorded speed at 1 km/h

I am confident this new release will make people happy as they will can make fine turnings of tracks recorded.

**Comment by gui7545** [comment] 2015-01-04 22:26
I am ok if you want to test your tools.
I have also some old course from FS2013 and FS2015 with all the data (Turns, folders, parent data to relate folders, ... ) so, i can test if they are correctly convert into the new system.
I haven't see how to send you PM. So i write here

**Comment by PromGames** [comment] 2015-01-04 23:48
In think you can see my email just touching or going to my profile.Is public.

**Comment by AndyK70** [comment] 2015-01-07 00:30
@PromGames would be very cool when your editor comes public. I was searching for something like that just a couple of days ago, without any success for CP4.1 and/or LS15. :anguished:

**Comment by JakobTischler** [comment] 2015-01-09 19:05
I think I can close this now.

**Closed by JakobTischler** 2015-01-09 19:05 UTC
Labels: question

**Comment by PromGames** [comment] 2015-01-09 21:31
Hi Jakob,

As you saw in my message, the courseplay path editor is almost finished.

I think the programme is accomplishing all features, mainly the transformation of the old courses from fs2013 or FS2011 to the new xml structure, and the possibility to make fine tunning of routes, taking out wait points, etc...

The programme is also solving the issue with the speed divided by 1000 that appears in many old maps. This could be the cause why people was claiming that the vehicle goes at 1 km per hour

Would you be interested to test the app and give us your support? 
No compromise, if you say no. We understand.

You know we have recovered this tool just trying to avoid  errors in courseplay coming from a bad old file structure.

If you say yes, you can just pick up the app from our repository PromGames/CourseDrawer/bin/debug/CourseDrawer.exe

Or we can send you the file in .rename format for avoiding problems of transmission .exe files

We also would like to use some images of courseplay that you allow us to use. If you think that could be possible. 

Regards 

Alfredo

**Comment by Satissis** [comment] 2015-01-10 13:48
I had a talk with Jakob about it and while we do recognize that it's being updated, we can't make a fully recommend or support it at it current state.

Don't misunderstand, we do like to see a nice too for editing the the courses, but the reason for us not supporting it in the old days was that it's a bit to clunky to navigate around and lack of modern features that makes it user friendly.

This was also one of the reasons I started my own Courseplay Editor a while back, where Jakob and I actually talked about how we would like it to be working and all of the things we talked about, you should be able to see in the issue list I have on my repo of Courseplay Editor here on github. Some of them might be closed already, so also check the closed issues.

About the images, I have talked with Jakob about it and we would like to see how much you are going to improve it before we will be willing to send it to you ;) (referenced to the above)

Now you send me an updated version to test out, and I have only tested it a little bit. Here is 2 things I found:
1. When selecting an wp that have an turn start or turn end the check box for that setting is not checked
2. When saving the courses, it do not save some of the needed infoes. here is an example from and generated route while turning:
Old ways it was saved.
```
<waypoint67 pos="98.5497 -288.6013" angle="180" wait="0" crossing="0" rev="0" speed="0" dir="N" turn="false" turnstart="0" turnend="0" ridgemarker="2" generated="true" />
<waypoint68 pos="98.5497 -289.8669" angle="89.98" wait="0" crossing="0" rev="0" speed="0" dir="N" turn="right" turnstart="1" turnend="0" ridgemarker="0" generated="true" />
<waypoint69 pos="123.4497 -289.8562" angle="0" wait="0" crossing="0" rev="0" speed="0" dir="S" turn="false" turnstart="0" turnend="1" ridgemarker="0" generated="true" />
<waypoint70 pos="123.4497 -284.897" angle="0" wait="0" crossing="0" rev="0" speed="0" dir="S" turn="false" turnstart="0" turnend="0" ridgemarker="0" generated="true" />
<waypoint71 pos="123.4497 -279.897" angle="0" wait="0" crossing="0" rev="0" speed="0" dir="S" turn="false" turnstart="0" turnend="0" ridgemarker="1" generated="true" />
```

This is the new way it needs to be saved to minimize the file size:
```
<waypoint67 pos="98.5497 -288.6013" angle="180" dir="N" ridgemarker="2" generated="true" />
<waypoint68 pos="98.5497 -289.8669" angle="89.98" dir="N" turn="right" turnstart="1" generated="true" />
<waypoint69 pos="123.4497 -289.8562" angle="0" dir="S" turnend="1" generated="true" />
<waypoint70 pos="123.4497 -284.897" angle="0" dir="S" generated="true" />
<waypoint71 pos="123.4497 -279.897" angle="0" dir="S" ridgemarker="1" generated="true" />
```

This is how yours is saved:
```
<waypoint67 pos="98.55 -288.60" angle="180.00" speed="0" />
<waypoint68 pos="98.55 -289.87" angle="89.98" speed="0" />
<waypoint69 pos="123.45 -289.86" angle="0.00" crossing="1" speed="0" />
<waypoint70 pos="123.45 -284.90" angle="0.00" speed="0" />
<waypoint71 pos="123.45 -279.90" angle="0.00" speed="0" />
```

You will notice I have removed all the variables that is either 0 or false except for "pos", "angle" and "speed", since those is needed.

Now for the last thing before ending this long reply, then we should continue this conversation on your issue tracker, so we don't mix these 2 projects ;) If there is something you wanna ask us, just tag our names in the issue, like ```@Satissis``` and we should get updates on a reply that you have mentioned our name and we will be able to have a look ;)

**Comment by Goten87** [comment] 2015-01-10 16:46
i think he was asking if you guys wanne test it as well and then when you are ready promote it

**Comment by GNiessen** [comment] 2015-01-14 20:10
@Satissis Is there a reason the XML has the "waypoints" as waypoint1, waypoint2?  I was also working on an external tool to tweek the courses, but the waypoints are not in a neat collection and show up individually as uniquely named nodes. If they were all named waypoint with a Index=1,2,..etc. it would be better.  Also splitting pos to posX and posY seems appropriate.
