### ISSUE TITLE
Money is deducted

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4468] opened 2019-10-29 08:44 UTC
Take a look at money in this video:
https://youtu.be/d-3oEFRKCiU

I cant reproduce it always, it seems it appears randomly.
This tractor was the only worker hired at that time.
I also have installed AutoDrive and AIVehicleExtension.
Driver wage is set to 0% in AutoDrive options.
When i reload savegame, money wage works fine, it will reduce only 4$ every few seconds like it should.
I dont know what is causing this money wage bug, any idea ?

**Comment by Tensuko** [comment] 2019-10-29 09:07
Duplicate of #4345
or at least similar.
Closed.

**Closed by Tensuko** 2019-10-29 09:07 UTC
