### ISSUE TITLE
Driver doesn't start course at first waypoint

### ISSUE THREAD

**Issue by touzenesmy** [Courseplay/courseplay#5772] opened 2020-07-22 17:29 UTC
Hello everyone and thank you for that magnificent mode and that support.

This issue happened with all my vehicles and actually on all my fields, I set a course, I choose "start course at : First Waypoint", I drive a bit away, like in the middle of the field to try if he'll go back to the first point.

The driver simply ignore it and start with the nearest point and keep going.

Any help please ?

**Comment by Tensuko** [comment] 2020-07-23 05:44
logfile ?

**Comment by pvaiko** [comment] 2020-07-23 12:41
@Tensuko means a logfile with debug channels 12 and 14, otherwise it won't help...

**Comment by Tensuko** [comment] 2020-07-23 15:59
Can't reproduce, he is moving to 1st waypoint when I tell him to do it. Waiting for your logfile with channel 12 and 14, but I am sure there is some corrupted mods or anything.
![fsScreen_2020_07_23_17_55_22](https://user-images.githubusercontent.com/27344744/88309097-2c054300-cd0e-11ea-952f-228312542352.png)

**Comment by touzenesmy** [comment] 2020-07-24 13:21
Hello, thank you for your responses!

Here is the logfile and a video of the event:

https://pastebin.com/W6TMwUaL

https://youtu.be/5kPZs5N6NH0

I can also invite you to the server and let you try it on your side and reproduce the issue

**Comment by Tensuko** [comment] 2020-07-24 14:07
> I can also invite you to the server

and there we got the needed detail :)

**Comment by touzenesmy** [comment] 2020-07-24 15:34
Well, didn't know it was different I'm sorry, is there any way to solve it ?

**Comment by Tensuko** [comment] 2020-07-24 15:40
Not very soon, sry.
We are working on a lot of stuff to get CP work better in MP.
@schwiti6190 can say more about that, as he is the one working on it. Maybe it is an easy fix, maybe you got to wait.

**Comment by schwiti6190** [comment] 2020-07-24 16:43
Hi, this is a know issue that might be fix with my next update. It might take a while for the branch to go online, as I am currently working on a diffrent part of CP and this one will take a bit more time.

**Closed** 2020-08-02 11:55 UTC
Labels: MP Settings
