### ISSUE TITLE
Tractor drive in circles infinitely

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4372] opened 2019-10-14 16:17 UTC
This seems to be a recurring problem, but I didn't find a solution.
For some reason, sometimes my tractor stays doing circles, instead of following the path:

https://imgur.com/v1ScJLm

[log.txt](https://github.com/Courseplay/courseplay/files/3725383/log.txt)

**Comment by Tensuko** [comment] 2019-10-14 17:16
Maybe same as #4370 ? try out (reduce speed) and report.

**Comment by rogeriodec** [comment] 2019-10-14 17:16
Not the same, the speed is the default (10).

**Comment by pvaiko** [comment] 2019-10-14 17:57
Log and video with debug channel 12 and 14 helps a lot.

**Comment by rogeriodec** [comment] 2019-10-14 18:39
Here it is:

[log.txt](https://github.com/Courseplay/courseplay/files/3725803/log.txt)

and the video: https://i.imgur.com/YxX22Gw.mp4

**Comment by Petje81** [comment] 2019-10-17 07:13
I'd like to add to this that i experienced worse steering behaviour since v. 303 (the last version i ran before updating).
In 303 i could let the worker just run a course (sprayer, tractor, anything) on higher turning speeds than 10 kph and it would turn like it should 9/10. On v. 310 it only turns right 1/10, the rest it will just keep driving in circles instantly when turning on a headland. Lowering speed to 10 kph makes it work 3/10.

**Comment by pvaiko** [comment] 2019-10-17 11:10
Three out of 10 sounds like a really bad ratio at 10 km/h. A few examples would be great.

**Comment by pvaiko** [comment] 2019-10-17 11:13
@rogeriodec to you specific case, with that spreader and 20m or so workwidth it does not make sense at all to make turn maneuvers in the corner, use the smooth headland corner options instead.

**Comment by Petje81** [comment] 2019-10-17 12:43
> Three out of 10 sounds like a really bad ratio at 10 km/h. A few examples would be great.

For example, fertilizing with a case puma (vanilla) and the kuhn fertilizer spreader (vanilla), 2 headlands on smooth goes great but when it comes to the main stretches on average 3 out of 10 turns on the headland the tractor makes it like it should, the rest it will go in infinite circles, sometimes it gets out of it after a couple, most of the time it stays in it.
Also with the Amazone Pantera (mod from ingame modhub), due to the large working width and the articulated steering it will oversteer itself, corrects it and keeps going in circles in opposite turning direction.

Thing is... it worked great on v303, 10/10 turns went perfect with both (not counting the little oversteer on the amazone because it corrected itself right) even on a higher turn speed (20 kph).

The only thing changed was going from v303 to v310 AND (maybe this is the culprit) getting updated to patch 1.5.1..
The courses were saved courses from v303.

Btw, have the max steering angles been changed? I noticed a bunch of vehicles making a larger turn than in v303 and not making it to the next arrow/pointer.

**Comment by pvaiko** [comment] 2019-10-17 13:07
So is it the headland turns only?

Well, there was this change 454a0fc07b692bf6564f89b535281b1a4d79158b but I really did not expect to have it such a big impact. (BTW, I doubt those turns were actually performed at 20kph, I think it was much slower due to the Giants speed adjustment).

**Comment by Petje81** [comment] 2019-10-17 13:40
> So is it the headland turns only?
> 
> Well, there was this change [454a0fc](https://github.com/Courseplay/courseplay/commit/454a0fc07b692bf6564f89b535281b1a4d79158b) but I really did not expect to have it such a big impact. (BTW, I doubt those turns were actually performed at 20kph, I think it was much slower due to the Giants speed adjustment).

Yes it is, no problem during the smooth corners (it is not spot on the markers but it will go through the corner).

With the giants speed adjustment is the current speed in the bottom right the right one or is it silently changed? Because i see the speed dropping to 20, keeping that speed and it is definetely faster than 10 kph on v310.

**Comment by Petje81** [comment] 2019-10-17 13:59
Do you mean exactly 180 turns? Because the way the course is plotted out together with the working width there are hardly any 180 turns, just coupled 90 turns. I did see the combine harvesters and loading wagons do 180 turns without problems (smaller working width).

Ill check on this later, still at work.

**Comment by pvaiko** [comment] 2019-10-17 14:04
I mean turns at the row end, not on the headland, where you see a green and the red arrow.

**Comment by Petje81** [comment] 2019-10-17 17:43
> So is it the headland turns only?
> 
> Well, there was this change [454a0fc](https://github.com/Courseplay/courseplay/commit/454a0fc07b692bf6564f89b535281b1a4d79158b) but I really did not expect to have it such a big impact. (BTW, I doubt those turns were actually performed at 20kph, I think it was much slower due to the Giants speed adjustment).

You were right, i was convinced it was keeping up it's speed in the corners but it didn't...

- Amazone Pantera (ingame modhub mod with only changed workspeed to 25 kph)
- Turn speed: 15kph
- Field speed: 25 kph
- Lone Oak Field 48 on a contract
- Created a new course
- On v310 "use AI turn maneuvers" deactivated

On v303 the speed and speed limit drops to 15 kph a bit before the turns. 
When doing headlands it then drops further to an average of 9 kph (it fluctuates) for the actual cornering.
When turning at row end it drops to an average of 6 kph (it fluctuates) for the actual cornering.
The whole field is finished without problems.

On v310 the speed and speed limit also drops to 15 kph a bit before the turns.
When doing headlands it then drops further to an average of 9 kph (it fluctuates) for the actual cornering.
When turning at the first row end it drops to exactly 14 kph for the actual cornering, overshoots 90 degrees turning, corrects by turning the other way around by 180 degrees and takes off at 25 kph in the wrong direction not following any waypoints.

On v310 with the turn speed set to 10 kph at row end the speed drops exactly to 9 kph, overshoots 90 degrees turning, corrects by turning the other way, overshoots again, corrects by turning back to the first direction and then keeps endlessly going in circles in that direction.
Turn speed set to 6 kph makes it turn like it should (not a finetuned speed, just picked a number based on the v303 perception).
Turn speed set back to 10 kph with "use AI turn manouvers" activated (i just had to try, didn't know if it made a difference) and the sprayer reacts the same as the above 10 kph turn speed setting, so that didn't make a difference.

**Comment by rogeriodec** [comment] 2019-10-18 19:21
https://github.com/Courseplay/courseplay/releases/tag/6.01.00311 didn't solve the infinite loop problem:

[log.txt](https://github.com/Courseplay/courseplay/files/3745370/log.txt)
[Video](https://youtu.be/wOgSATAe_xM)

**Comment by Tensuko** [comment] 2019-10-18 19:41
Different Mode (Mode2), different Situation. Got nothing to do with this one.

@pvaiko close this or wait for more testing from other Users ?

**Comment by pvaiko** [comment] 2019-10-19 01:31
This is a completely different issue than the original one. Closing as this is getting out of control.

@Petje81 if you have a savegame and course to reproduce your problems, open a new issue please.

**Closed by pvaiko** 2019-10-19 01:31 UTC
