### ISSUE TITLE
 harvester does not stop when unloading at the end of the field

### ISSUE THREAD

**Issue by androno12** [Courseplay/courseplay#4989] opened 2020-02-28 14:24 UTC
Hello. CS 00386. A harvester can hit the tractor when turning at the end of the field. But old versions Courseplay (April 2019) work fine. (google translator)
https://youtu.be/wtXXB0-KbjM

**Comment by Zoochase** [comment] 2020-03-01 03:28
Asked already...
Combine not stopping at end of field while unloading #4702

**Comment by androno12** [comment] 2020-03-01 12:38
thanks

**Comment by Tensuko** [comment] 2020-03-03 19:05
Duplicate of #4702

Closed.

**Closed by Tensuko** 2020-03-03 19:05 UTC
