### ISSUE TITLE
Prompt Missing in Mode 1

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#1780] opened 2017-02-15 23:27 UTC
This version is no longer showing the Prompts " has reached waiting point and " in traffic". The previous versions had this option active. Has the option bee removed on purpose.  Bob.

**Comment by pops64** [comment] 2017-02-16 00:58
https://github.com/Courseplay/courseplay/wiki

**Comment by hackselgut** [comment] 2017-02-16 02:23
Okay, you changed the Title. So what about the missing Prompts. A mistake or on Purpose, What one?  Bob

**Comment by pops64** [comment] 2017-02-16 04:34
I don't know because https://github.com/Courseplay/courseplay/wiki. Which mode do you think is missing this prompt. Do you have a log because maybe there is suppose to be a prompt but it throws an error. Do you have picture of where it is occurring. It could be any number of things but we can't figure out where it is without more information. I changed the title so people know what this issue is.

**Comment by hackselgut** [comment] 2017-02-16 05:43
The Mode is "load at start" This mode has always had the Prompts ( screen left bottom ) A bar in "blue" stating vehicle has reached waiting point " and also a prompt "vehicle in Traffic" when two vehicles come behind one another. now I have gone back to my old version 5.01.00036, yous are at 5.01.00076, also I have new patch in for FS17. If you want Pictures, tell me how to Upload to you.  Bob

**Comment by pops64** [comment] 2017-02-16 05:56
Which two vehicles are causing this issue? Are they mods? Which mode are they in? Do you have pictures is it just theses two vehicles. Just drag and drop you pictures into github in the comment box it will upload them automatically. If you could run debug channel 3 when you do this as well that would be appreciated to and upload the log to pastebin or  Gist like it says in the wiki I have linked. We will look into mode 1 has that has changed recently.

**Comment by hackselgut** [comment] 2017-02-16 07:38
![fsscreen_2017_02_16_00_57_05](https://cloud.githubusercontent.com/assets/10256656/23011781/e26bd55a-f3f0-11e6-856e-cb4001e2347e.png)
![fsscreen_2017_02_16_00_59_43](https://cloud.githubusercontent.com/assets/10256656/23011782/e26cca78-f3f0-11e6-950e-4e5ff954b2df.png)
![fsscreen_2017_02_16_01_41_53](https://cloud.githubusercontent.com/assets/10256656/23011784/e26dc57c-f3f0-11e6-9173-fa2d7606efd6.png)
![fsscreen_2017_02_16_01_42_02](https://cloud.githubusercontent.com/assets/10256656/23011786/e271fa3e-f3f0-11e6-92bb-131f9c2fcc78.png)
![fsscreen_2017_02_16_02_03_46](https://cloud.githubusercontent.com/assets/10256656/23011783/e26d130c-f3f0-11e6-95c3-745eb34f5ecd.png)
![fsscreen_2017_02_16_02_04_46](https://cloud.githubusercontent.com/assets/10256656/23011785/e26de84a-f3f0-11e6-839a-0abc327b7d02.png)
![fsscreen_2017_02_16_02_04_51](https://cloud.githubusercontent.com/assets/10256656/23011788/e277c84c-f3f0-11e6-9552-a5ae4f7396cb.png)
![fsscreen_2017_02_16_02_05_37](https://cloud.githubusercontent.com/assets/10256656/23011790/e27893bc-f3f0-11e6-91a7-6df5fa388006.png)
![fsscreen_2017_02_16_02_05_56](https://cloud.githubusercontent.com/assets/10256656/23011787/e277eb42-f3f0-11e6-8783-fb3f3491db39.png)
![untitled](https://cloud.githubusercontent.com/assets/10256656/23011789/e2786a68-f3f0-11e6-9ef0-fd89f1f595ba.png)

**Comment by pops64** [comment] 2017-02-16 17:08
Ok ok I see wait you mean. I thought you were talking about the start point prompt being missing. Which it is also. Thanks for the pictures

**Comment by hackselgut** [comment] 2017-02-16 19:35
@ pops64   You state from above  ( I thought you were talking about the start point prompt being missing. Which it is also )  The Start prompt is there, The pictures refere to the Waiting points  Bob.

**Comment by Satissis** [comment] 2017-02-18 18:05
Try again with v01.0079 or higher. I think I have fixed it in that version.

**Comment by ThomasGaertner** [comment] 2017-02-19 12:31
![image](https://cloud.githubusercontent.com/assets/3279913/23102335/bcee5b86-f6a7-11e6-8de0-04ecc47cf471.png)

**Comment by ThomasGaertner** [comment] 2017-02-19 12:33
![fsscreen_2017_02_19_13_32_47](https://cloud.githubusercontent.com/assets/3279913/23102348/edc0ddd8-f6a7-11e6-8e7f-bfd90010ecbc.png)
the message appears now, when the field work / sprayer route is finished....

**Comment by hackselgut** [comment] 2017-02-21 04:29
I will D/L version 79 and try it, I will let you know it is,  Bob.

**Comment by hackselgut** [comment] 2017-02-21 05:44
Problem with Prompis looks to be Fixed in Version 80, Thanks
![fsscreen_2017_02_21_00_33_17](https://cloud.githubusercontent.com/assets/10256656/23152256/d88c69e6-f7ce-11e6-997e-d8fb96ddc9b5.png)

**Comment by Satissis** [comment] 2017-02-23 18:35
Should be fixed in v01.0084.
Try it out and report back.

This is an fix for @ThomasGaertner image.
It should now only show for mode 1

**Comment by Satissis** [comment] 2017-03-05 15:16
Works as intended to. Closing

**Closed by Satissis** 2017-03-05 15:16 UTC
Labels: bug, waitingForUserAnswer
