### ISSUE TITLE
Start course at "nearest waypoint" in front of vehicle?

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1004] opened 2015-01-25 20:10 UTC
Don't know if it is applicable or not.

When I stop a session (saving and quitting) and later on continue that session most of the times I start the vehicles with "Start course at: nearest waypoint".
Unfortunately it happens some times, that the nearest waypoint is right behind the vehicle and not the one that is in front of it.
The vehicle then tries to turn and most of it, it will crash into something.

Is there a way to let the vehicle start at the nearest waypoint in front of it, when there are 2 or more  waypoints around the vehicle? Let's say within a radius of 5m?

**Comment by JakobTischler** [comment] 2015-01-25 20:11
Duplicate of #551.

**Closed by JakobTischler** 2015-01-25 20:11 UTC
