### ISSUE TITLE
Krone X 1180 speed issues

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4132] opened 2019-08-21 16:09 UTC
Been using the Krone X 1180 on Lapacho to create chaff from corn in order to test mode 10, and let CP drive it in mode 6 while I drove the chaser tractor, but it is struggling to keep the speed. 

On the first field (field 20) during the headland, the Krone occasionally would cut the speed briefly and then continue at the normal 10 km/h, but during the main up/down part it was running fine.

Repaired machine and header before going to the second field (field 19) where it was behaving the same way on the headland, but when it got to the up/down part it was stuttering badly, unable to go any faster than 7 km/h. Jumped in the machine and the cruise control was flickering between 1 and 10 km/h.

Disabled CP and let the vanilla helper take over, and it has no problem maintaining a smooth 10 km/h.

Was on CP 283 when I started on the first field yesterday and just updated to 286 today.

**Comment by Tensuko** [comment] 2019-08-21 16:48
I think that got something to do with the better tipping into trailer.
All Cutters where already moveing, even when no chaff land in the trailer, just the pipe had to see the trailer. We had some Issue about that already. #4027 (in german tho...)
I will do some more test about it, when I got time, but so far I had no Issue at all with the speed....

**Comment by SteelRodent** [comment] 2019-08-21 18:43
The German would be why I couldn't find it ;)

**Comment by Crinouche** [comment] 2019-08-24 21:09
I have the same problem with the latest versions.
With the krone 1180, the NH 850 but also with the sugar cane harvester
The problem is the same as # 4040

**Comment by SteelRodent** [comment] 2019-11-12 18:59
Can't confirm yet, but it looks like this may have been fixed with the additional pipe changes you made for the potato harvester. At least running the forager all day yesterday, it behaved perfectly the entire time.

**Comment by Tensuko** [comment] 2019-11-12 19:08
Thx for report back!
Thats good to hear.
Since this one is old, I will close this.
If you get into a new Issu with this, you know what to do (new Issue with log and discription) :)
Closed.

**Closed by Tensuko** 2019-11-12 19:08 UTC
Labels: Fine Tuning, postponed
